# -*- coding: utf-8 -*-
"""Emit retail's activity enum -- the `ACT_*` name <-> value table -- for the runtime.

`ActivityList_RegisterSharedActivities` (`vampire.dll 0x104126e0`) makes 4,460 registrations in a
fixed order, every one a `PUSH value; PUSH "ACT_NAME"; CALL` triple: 4,431 through
`RegisterSharedActivity` (`0x1000ca0e` -> `0x104123a0`) and 29 through `RegisterGrappleActivity`
(`0x10012102` -> `0x10412590`). `docs/vtmb/activity_enum.md` is the prose over the same table.

Two steps:

  * ``--extract`` reads that function's disassembly out of the corpus listing database and writes
    ``research/tooling/data/activity_enum.json`` (value, name, grapple) -- the recovered data,
    checked in.
  * the default (and ``--check``) emits
    ``Source/ElysiumUE/Private/Substrate/ElysiumRetailActivities.cpp`` from that JSON: the table
    `ElysiumRetailActivities::NameOf` / `ValueOf` answer from, which is retail's
    `ActivityList_NameForIndex` (`0x10412550`) and `ActivityList_IndexForName` (`0x10412520`,
    case-folding -- the symbol table's comparator is `__strcmpi`).

Usage::

    uv run elysium research gen_activity_enum --extract
    uv run elysium research gen_activity_enum
    uv run elysium research gen_activity_enum --check
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
DATA = HERE / "data" / "activity_enum.json"
OUT_CPP = REPO / "Source" / "ElysiumUE" / "Private" / "Substrate" / "ElysiumRetailActivities.cpp"

REGISTRAR = "104126e0"
SHARED_CALL = "0x1000ca0e"
GRAPPLE_CALL = "0x10012102"

PUSH_IMM = re.compile(r"^\s*[0-9a-f]{8}\s+PUSH\s+(0x[0-9a-f]+|\d+)\s*$", re.I)
PUSH_STR = re.compile(r'^\s*[0-9a-f]{8}\s+PUSH\s+0x[0-9a-f]+\s+"([^"]+)"\s*$', re.I)
CALL = re.compile(r"^\s*[0-9a-f]{8}\s+CALL\s+(0x[0-9a-f]+)\s*$", re.I)


def extract() -> list[dict]:
    sys.path.insert(0, str(HERE / "ghidra" / "driver"))
    import corpus  # noqa: PLC0415 -- the corpus driver lives beside this tool

    listings = corpus._listing_connection()
    if listings is None:
        raise SystemExit("no corpus listing database; run `corpus listing` and `corpus build`")
    row = listings.execute("SELECT asm FROM listing WHERE module = ? AND addr = ?",
                           ("vampire.dll", REGISTRAR)).fetchone()
    if row is None:
        raise SystemExit(f"0x{REGISTRAR} is not in the listing database")
    rows: list[dict] = []
    value: int | None = None
    name: str | None = None
    for line in row["asm"].splitlines():
        if (m := PUSH_STR.match(line)):
            name = m.group(1)
            continue
        if (m := PUSH_IMM.match(line)):
            value = int(m.group(1), 0)
            continue
        if (m := CALL.match(line)):
            target = m.group(1).lower()
            if target not in (SHARED_CALL, GRAPPLE_CALL):
                raise SystemExit(f"unexpected call {target} in 0x{REGISTRAR}")
            if value is None or name is None:
                raise SystemExit(f"a registration call with no value/name pair near: {line}")
            rows.append({"value": value, "name": name, "grapple": target == GRAPPLE_CALL})
            value = name = None
    if len(rows) != 4460:
        raise SystemExit(f"expected 4460 registrations, read {len(rows)}")
    return rows


def emit(rows: list[dict]) -> str:
    ordered = sorted(rows, key=lambda r: (r["value"], r["name"].upper()))
    out = [
        "// GENERATED by `uv run elysium research gen_activity_enum` from",
        "// `research/tooling/data/activity_enum.json` -- do not edit by hand.",
        "//",
        "// Retail's activity enum: the 4,460 registrations `ActivityList_RegisterSharedActivities`",
        "// (`vampire.dll 0x104126e0`) makes, value-ordered. `docs/vtmb/activity_enum.md` is the prose.",
        "",
        '#include "Substrate/ElysiumRetailActivities.h"',
        "",
        "namespace",
        "{",
        "\tstruct FRetailActivityRow",
        "\t{",
        "\t\tint32 Value;",
        "\t\tconst TCHAR* Name;",
        "\t\tbool bGrapple;",
        "\t};",
        "",
        "\tconst FRetailActivityRow GRetailActivities[] = {",
    ]
    for r in ordered:
        out.append(f'\t\t{{ {r["value"]}, TEXT("{r["name"]}"), {"true" if r["grapple"] else "false"} }},')
    out += [
        "\t};",
        "}",
        "",
        "const TCHAR* ElysiumRetailActivities::NameOf(int32 Value)",
        "{",
        "\t// `ActivityList_NameForIndex` (`0x10412550`). The table is value-ordered.",
        "\tint32 Low = 0;",
        "\tint32 High = UE_ARRAY_COUNT(GRetailActivities) - 1;",
        "\twhile (Low <= High)",
        "\t{",
        "\t\tconst int32 Mid = (Low + High) / 2;",
        "\t\tconst int32 At = GRetailActivities[Mid].Value;",
        "\t\tif (At == Value)",
        "\t\t{",
        "\t\t\t// Two names can share a value; the first registered in value order answers.",
        "\t\t\tint32 First = Mid;",
        "\t\t\twhile (First > 0 && GRetailActivities[First - 1].Value == Value)",
        "\t\t\t{",
        "\t\t\t\t--First;",
        "\t\t\t}",
        "\t\t\treturn GRetailActivities[First].Name;",
        "\t\t}",
        "\t\tif (At < Value)",
        "\t\t{",
        "\t\t\tLow = Mid + 1;",
        "\t\t}",
        "\t\telse",
        "\t\t{",
        "\t\t\tHigh = Mid - 1;",
        "\t\t}",
        "\t}",
        "\treturn nullptr;",
        "}",
        "",
        "int32 ElysiumRetailActivities::ValueOf(const FString& Name)",
        "{",
        "\t// `ActivityList_IndexForName` (`0x10412520`): the symbol table folds case (`__strcmpi`).",
        "\tstatic const TMap<FString, int32> ByName = []()",
        "\t{",
        "\t\tTMap<FString, int32> Map;",
        "\t\tfor (const FRetailActivityRow& Row : GRetailActivities)",
        "\t\t{",
        "\t\t\tMap.FindOrAdd(FString(Row.Name).ToUpper(), Row.Value);",
        "\t\t}",
        "\t\treturn Map;",
        "\t}();",
        "\tconst int32* Found = ByName.Find(Name.ToUpper());",
        "\treturn Found != nullptr ? *Found : INDEX_NONE;",
        "}",
        "",
        "bool ElysiumRetailActivities::IsGrapple(int32 Value)",
        "{",
        "\t// `IsGrappleActivity` (`0x104126a0`): membership of the grapple list.",
        "\tfor (const FRetailActivityRow& Row : GRetailActivities)",
        "\t{",
        "\t\tif (Row.Value == Value && Row.bGrapple)",
        "\t\t{",
        "\t\t\treturn true;",
        "\t\t}",
        "\t}",
        "\treturn false;",
        "}",
        "",
        "int32 ElysiumRetailActivities::Num()",
        "{",
        "\treturn UE_ARRAY_COUNT(GRetailActivities);",
        "}",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--extract", action="store_true", help="re-read the table out of the corpus")
    parser.add_argument("--check", action="store_true", help="fail when the emitted file differs")
    args = parser.parse_args()
    if args.extract:
        rows = extract()
        DATA.parent.mkdir(parents=True, exist_ok=True)
        DATA.write_text("[\n" + ",\n".join(json.dumps(r) for r in rows) + "\n]\n",
                        encoding="utf-8", newline="\n")
        print(f"wrote {DATA.relative_to(REPO)}: {len(rows)} registrations")
    rows = json.loads(DATA.read_text(encoding="utf-8"))
    text = emit(rows)
    current = OUT_CPP.read_text(encoding="utf-8") if OUT_CPP.exists() else ""
    if args.check:
        if current != text:
            sys.stdout.writelines(difflib.unified_diff(current.splitlines(True), text.splitlines(True),
                                                       str(OUT_CPP), "generated", n=1))
            print(f"check: {OUT_CPP.name} is stale; run gen_activity_enum")
            return 1
        print(f"check: {OUT_CPP.name} matches {DATA.name}")
        return 0
    if current != text:
        OUT_CPP.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUT_CPP.relative_to(REPO)}")
    else:
        print(f"{OUT_CPP.name} is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
