#pragma once

#include "CoreMinimal.h"
#include "Misc/Paths.h"

// Single source of truth for the extracted-content root. Runtime code resolves every
// map/asset path through here. Dev builds read the in-repo pipeline output at tools/out
// (gitignored, generated by tools/export_all.py); relocating content to a packaged folder
// next to the executable later is a one-line change.
struct FElysiumContentPaths
{
	static FString Root() { return FPaths::ProjectDir() / TEXT("tools/out"); }

	// --- Baked content (tools/bake_map.py) ---------------------------------------------
	// The look of a map — world + sky geometry, materials, textures, props, lights, fog — is
	// offline-baked into real .uasset content under the /ElysiumBaked plugin mount, and the map
	// IS a real .umap the engine opens. These are package paths (a virtual content root), not
	// filesystem paths, so they take no FPaths::ProjectDir. The mount's Content/ is game-derived
	// and gitignored exactly like Root(); only the .uplugin descriptor is committed.
	static FString BakedMount() { return TEXT("/ElysiumBaked"); }
	static FString BakedMapDir(const FString& Map) { return BakedMount() / Map; }
	// The .umap UElysiumMapSubsystem::Travel opens for this map.
	static FString BakedLevel(const FString& Map) { return BakedMapDir(Map) / Map; }
	// One baked prop model, by the same OBJ stem the .props sidecar and `model_mesh` name. The
	// exporter already emits safe stems, so the bake's own safe_name() is a no-op on them and the
	// stem maps to the asset name verbatim. Package path is <dir>/SM_<stem>.SM_<stem>.
	static FString BakedPropMesh(const FString& Map, const FString& Stem)
	{
		const FString Asset = TEXT("SM_") + Stem;
		return BakedMapDir(Map) / TEXT("Props") / Asset + TEXT(".") + Asset;
	}
	// The map's prop skin table (UElysiumPropSkinSet) -- every alternate skin family of every
	// prop model it places, as material instances resolved at bake time. Absent for a map whose
	// models all carry a single family.
	static FString BakedPropSkins(const FString& Map)
	{
		const FString Asset = TEXT("DA_") + Map + TEXT("_PropSkins");
		return BakedMapDir(Map) / TEXT("Props") / Asset + TEXT(".") + Asset;
	}

	static FString MapDir(const FString& Map) { return Root() / Map; }
	static FString MapTexDir(const FString& Map) { return MapDir(Map) / TEXT("tex"); }
	static FString MapObj(const FString& Map) { return MapDir(Map) / (Map + TEXT(".obj")); }
	static FString MapSkyObj(const FString& Map) { return MapDir(Map) / (Map + TEXT("_sky.obj")); }
	static FString MapSpawn(const FString& Map) { return MapDir(Map) / (Map + TEXT(".spawn")); }
	static FString MapSky(const FString& Map) { return MapDir(Map) / (Map + TEXT(".sky")); }
	static FString MapEnv(const FString& Map) { return MapDir(Map) / (Map + TEXT(".env")); }
	static FString MapLights(const FString& Map) { return MapDir(Map) / (Map + TEXT(".lights")); }
	static FString MapProps(const FString& Map) { return MapDir(Map) / (Map + TEXT(".props")); }
	static FString MapPropsDir(const FString& Map) { return MapDir(Map) / TEXT("props"); }
	static FString MapEnts(const FString& Map) { return MapDir(Map) / (Map + TEXT(".ents")); }
	static FString MapHulls(const FString& Map) { return MapDir(Map) / (Map + TEXT(".hulls")); }
	static FString MapDispCol(const FString& Map) { return MapDir(Map) / (Map + TEXT(".dispcol")); }
	// Decals (7.2): one deferred-decal projector per line (material + centre + normal + s/t axes +
	// half-extents, Unreal cm), written by UE_bsp_to_scene.py. Materials ride the shared <map>.mtl.
	static FString MapDecals(const FString& Map) { return MapDir(Map) / (Map + TEXT(".decals")); }
	static FString MapRopes(const FString& Map) { return MapDir(Map) / (Map + TEXT(".ropes")); }

	// Audio (P6). WAVs are game-global (shared across maps), so they live in one mirror of
	// VtMB's `sound/` tree, not per-map. Rel is the engine-relative path under sound/ (e.g.
	// "Environmental/Fire/Fire_Roaring.wav"), matching an ambient_generic `message` value.
	static FString SoundDir() { return Root() / TEXT("sound"); }
	static FString SoundFile(const FString& Rel) { return SoundDir() / Rel; }

	// Scripting (P5). VtMB's level scripts + dialogue are game-global loose plain-text,
	// mirrored verbatim under out/scripts and out/dlg by tools/UE_extract_scripts.py. A
	// worldspawn `levelscript` value (e.g. "tutorial") names the hub module, which lives at
	// scripts/<module>/<module>.py — imported into the embedded CPython VM at map load (9.3a).
	static FString ScriptsDir() { return Root() / TEXT("scripts"); }
	static FString DlgDir() { return Root() / TEXT("dlg"); }
	static FString ScriptModuleFile(const FString& Module) { return ScriptsDir() / Module / (Module + TEXT(".py")); }
	// Console config (PL5d / 9.3b). VtMB's `cfg/*.cfg` alias + cvar tables (Valve console syntax),
	// mirrored verbatim under out/cfg by tools/UE_extract_cfg.py. The runtime console bridge
	// (FElysiumConsole) seeds its alias/cvar store from these; `user.cfg` carries the Basic/Plus
	// `patchtype` alias. Because VtMB's file-touching scripts resolve `getcwd()/moddir/...`, the
	// CPython VM points its `nt.getcwd`/`sys.moddir` at Root() so `cfg/config.cfg` resolves here.
	static FString CfgDir() { return Root() / TEXT("cfg"); }
	static FString CfgFile(const FString& File) { return CfgDir() / File; }
	// An NPC's `dialogname` keyfield already carries the `dlg/` prefix ("dlg/Main Characters/
	// jack_tutorial.dlg"), so it resolves straight under the content root. Case differs from the
	// lowercased on-disk mirror, but the Windows target's file system is case-insensitive.
	static FString DlgFromDialogname(const FString& DialogName) { return Root() / DialogName; }

	// Signs (P4.10 / PL5c). VtMB's sign+popup panels are game-global `SignData` KeyValues files,
	// mirrored flat and lowercased under out/signs by tools/UE_extract_signs.py (a `definition_file`
	// keyvalue's `vdata/Signs/` prefix and authored case are dropped). Their `BackgroundImage`
	// materials decode to out/signs/tex/, keyed by out/signs/backgrounds.json.
	static FString SignsDir() { return Root() / TEXT("signs"); }
	static FString SignFile(const FString& Leaf) { return SignsDir() / Leaf; }
	static FString SignTexDir() { return SignsDir() / TEXT("tex"); }
	static FString SignBackgrounds() { return SignsDir() / TEXT("backgrounds.json"); }

	// Fonts. The sign/popup panel's typeface set — hand-authored/game-agnostic OFL faces committed
	// under Content/Fonts (NOT the game-derived out/ mirror), mapping VtMB's authored face names
	// (ParagraphText/Newsprint/Headline/...) onto vector type. Read verbatim off disk at draw time.
	static FString FontsDir() { return FPaths::ProjectContentDir() / TEXT("Fonts"); }
	static FString FontFile(const FString& File) { return FontsDir() / File; }

	// NPCs (P8 8.2). Skeletal characters export as one standard glTF 2.0 file per model (mesh +
	// StudioBone skeleton + one animation) under out/npc, written by tools/mdl_gltf.py. The runtime
	// loads them through glTFRuntime (glTF is self-describing, so no UE_-style pre-conversion — the
	// plugin does the glTF->UE basis/scale change). Stem is the model name, e.g. "gangmember_male_2".
	static FString NpcDir() { return Root() / TEXT("npc"); }
	static FString NpcGlb(const FString& Stem) { return NpcDir() / (Stem + TEXT(".glb")); }

	// The labelled sky set (debug, sky-ambience RE-A2/B1). Six self-describing face images —
	// suffix, predicted axis, TOP banner, up arrow, tagged corners, edge neighbours — authored by
	// tools/sky_probe.py, which also installs them into the *original* game so the two ends of the
	// orientation chain are checked against one set of faces. Named `<skyname><face>.png`, unlike
	// the per-map `tex/sky_<face>.png`. `elysium.SkyProbe 1` builds the cube from these.
	static FString SkyProbeDir() { return Root() / TEXT("_skyprobe"); }

	// Light-edit sessions (debug). The Lights Cog window's Save writes one JSON per map — the
	// hand-disabled set plus every hand-set attribute, keyed by `.lights` line index — so a survey
	// done by eye in-game comes back out as data. One file per map, overwritten each save; under
	// Root(), so it is game-derived and gitignored like the rest.
	static FString LightEditsDir() { return Root() / TEXT("_lights"); }
	static FString LightEdits(const FString& Map) { return LightEditsDir() / (Map + TEXT(".json")); }
};
