"""Generate the native and Python capture layouts from the record registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
REGISTRY = ROOT / "record_schemas.json"
PYTHON_OUTPUT = ROOT.parent / "generated_record_schemas.py"
CPP_OUTPUT = ROOT.parent / "generated_record_schemas.h"

PYTHON_TYPES = {
    "char": "s",
    "uint32": "I",
    "uint64": "Q",
    "int32": "i",
    "int64": "q",
    "float32": "f",
}
CPP_TYPES = {
    "uint32": "std::uint32_t",
    "uint64": "std::uint64_t",
    "int32": "std::int32_t",
    "int64": "std::int64_t",
    "float32": "float",
}


def _expanded_records(registry: dict[str, object]) -> list[dict[str, object]]:
    by_name: dict[str, dict[str, object]] = {}
    expanded: list[dict[str, object]] = []
    for source in registry["records"]:
        record = dict(source)
        if layout_from := record.get("layout_from"):
            record["fields"] = by_name[layout_from]["fields"]
        by_name[record["name"]] = record
        expanded.append(record)
    return expanded


def _python_format(fields: list[list[object]]) -> str:
    pieces = ["<"]
    for field in fields:
        _, kind, *count = field
        amount = int(count[0]) if count else 1
        if kind == "char":
            pieces.append(f"{amount}s")
        elif amount == 1:
            pieces.append(PYTHON_TYPES[kind])
        else:
            pieces.append(f"{amount}{PYTHON_TYPES[kind]}")
    return "".join(pieces)


def render_python(registry: dict[str, object]) -> str:
    records = _expanded_records(registry)
    lines = [
        '"""Generated by contracts/generate_record_schemas.py; do not edit."""',
        "",
        "import struct",
        "",
        f"REGISTRY_VERSION = {registry['registry_version']}",
        f"BYTE_ORDER = {registry['byte_order']!r}",
        "RECORDS = {",
    ]
    for record in records:
        lines.extend(
            [
                f"    {record['name']!r}: {{",
                f"        'id': {record['id']},",
                f"        'schema_version': {record['schema_version']},",
                f"        'magic': {record['magic'].encode('ascii')!r},",
                f"        'minimum_bytes': {record['minimum_bytes']},",
                f"        'maximum_bytes': {record['maximum_bytes']},",
                f"        'struct': struct.Struct({_python_format(record['fields'])!r}),",
                "    },",
            ]
        )
    lines.extend(
        [
            "}",
            "",
        ]
    )
    for record in records:
        constant = record["name"].upper()
        lines.extend(
            [
                f"RECORD_ID_{constant} = {record['id']}",
                f"SCHEMA_VERSION_{constant} = {record['schema_version']}",
            ]
        )
    lines.extend(
        [
            "",
            "POSE_FILE_HEADER = RECORDS['pose_file_header']['struct']",
            "POSE_RECORD_HEADER = RECORDS['pose']['struct']",
            "ANIMATION_FILE_HEADER = RECORDS['animation_file_header']['struct']",
            "ANIMATION_RECORD_HEADER = RECORDS['animation_base']['struct']",
            "",
        ]
    )
    return "\n".join(lines)


def _cpp_declaration(field: list[object]) -> str:
    name, kind, *count = field
    amount = int(count[0]) if count else 1
    if kind == "char":
        return f"    char {name}[{amount}];"
    suffix = f"[{amount}]" if amount != 1 else ""
    return f"    {CPP_TYPES[kind]} {name}{suffix};"


def render_cpp(registry: dict[str, object]) -> str:
    names = {
        "pose_file_header": "FileHeader",
        "pose": "PoseRecordHeader",
        "animation_file_header": "AnimationFileHeader",
        "animation_base": "AnimationRecordHeader",
    }
    records = {
        record["name"]: record for record in _expanded_records(registry)
    }
    lines = [
        "// Generated by contracts/generate_record_schemas.py; do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        f"constexpr std::uint32_t kCaptureSchemaRegistryVersion = {registry['registry_version']}u;",
        "",
        "#pragma pack(push, 1)",
    ]
    for record_name, cpp_name in names.items():
        record = records[record_name]
        lines.append(f"struct {cpp_name} {{")
        lines.extend(_cpp_declaration(field) for field in record["fields"])
        lines.extend(
            [
                "};",
                f"constexpr std::uint32_t k{cpp_name}RecordId = {record['id']}u;",
                f"constexpr std::uint32_t k{cpp_name}SchemaVersion = {record['schema_version']}u;",
                "",
            ]
        )
    final = records["animation_final"]
    lines.extend(
        [
            f"constexpr std::uint32_t kAnimationFinalRecordId = {final['id']}u;",
            f"constexpr std::uint32_t kAnimationFinalSchemaVersion = {final['schema_version']}u;",
            "",
            "#pragma pack(pop)",
            "",
            f"static_assert(sizeof(FileHeader) == {records['pose_file_header']['minimum_bytes']}, \"capture file header changed\");",
            f"static_assert(sizeof(PoseRecordHeader) == {records['pose']['minimum_bytes']}, \"pose record header changed\");",
            f"static_assert(sizeof(AnimationFileHeader) == {records['animation_file_header']['minimum_bytes']}, \"animation capture file header changed\");",
            f"static_assert(sizeof(AnimationRecordHeader) == {records['animation_base']['minimum_bytes']}, \"animation record header changed\");",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    outputs = {
        PYTHON_OUTPUT: render_python(registry),
        CPP_OUTPUT: render_cpp(registry),
    }
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if args.check:
        if stale:
            parser.error(
                "generated record schemas are stale: "
                + ", ".join(str(path) for path in stale)
            )
        return 0
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
