"""The address index (`research/tooling/lookup/addr_index.py`) and the verbs over it, on a small
synthetic checkout.

What is pinned is what a caller sees: a query -- an address in any of its spellings, a name, a
field, an offset, `slot N` -- is answered from the ledger rows, the docs sections and the port lines
that speak of it, and from nothing that merely resembles it; a generated table is not a citation;
the index is rebuilt exactly when an input changes; and each verb (`section`, `verdict`, `cited`,
`rows`) answers the question the one-off scripts it replaces kept asking.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "research" / "tooling" / "lookup"))

import addr_index as ai  # noqa: E402

ADDR = "1028a380"
SCHEDULE = "docs/vtmb/npc-ai/schedule.md"

FILES = {
    SCHEDULE: f"""# Schedules

Prose before any address.

## `0x{ADDR}` `CAI_BaseNPC::SelectSchedule`

The base selector at `0x{ADDR}` switches on the state. It reads `m_scriptState` (`+0x5d70`).
Slot 438 holds it.

### The dead arm of CAI_BaseNPC::SelectSchedule

The death schedule is chosen here.

## Another section

Nothing of interest; `0x1028a3801` is a longer run and `0x{ADDR[:7]}` is a shorter one.
""",
    "docs/vtmb/npc-kernel/functions.md": f"""<!-- generated -->
# NPC kernel — functions

| Address | Function | Size | Depth |
|---|---|---|---|
| `0x{ADDR}` | CAI_BaseNPC::SelectSchedule | 1650 | 0 |
| `0x1028a3f0` | CAI_BaseNPC::StartTask | 100 | 1 |
| `0x10300000` | CNPC_Crow::StartTask | 50 | 1 |
| `0x10300100` | CNPC_Crow::SelectSchedule | 60 | 1 |
| `0x10300200` | CNPC_Gargoyle::SelectSchedule | 60 | 1 |
| `0x10300300` | CNPC_Rat::SelectSchedule | 60 | 1 |
| `0x10300400` | CNPC_Cop::SelectSchedule | 60 | 1 |
""",
    "docs/vtmb/npc-kernel/slots.md": f"""# slots

| Slot | Base | Troika |
|---|---|---|
| 437 | `0x1028a260` CAI_BaseNPC::PreSelectSchedule | — |
| 438 | `0x{ADDR}` CAI_BaseNPC::SelectSchedule | — |
""",
    "docs/vtmb/npc-kernel/layout.tsv": ("table\toffset\tsize\tmember\ttype\n"
                                        "CAI_BaseNPCTroika\t0x5d70\t4\tm_scriptState\tint\n"
                                        "CAI_BaseNPCTroika\t0x5cc0\t4\tm_NPCState\tint\n"),
    "docs/vtmb/npc-kernel/unported.tsv": ("# the unported rules\n"
                                          "class\tslot\taddress\tverdict\tkind\n"
                                          f"CAI_BaseNPC\t438\t0x{ADDR}\trule\tstub\n"
                                          "CNPC_Crow\t442\t0x10300000\trule\tno-override\n"
                                          "CNPC_Crow\t438\t0x10300100\tdead\tno-override\n"),
    "research/tooling/ghidra/driver/kernel_verdicts.tsv": (
        "# comment\n"
        "address\tverdict\tband\ttarget\tevidence\n"
        f"{ADDR}\trule\t19-29\tFElysiumNpc::BaseSelectSchedule\t[0019/1 obs=schedule: the ladder]\n"
        "1028a3f0\trule\t19-29\tFElysiumNpc::StartTaskSlot442\t[0019/1 obs=schedule: task arms]\n"
        "10300000\tdead\t0-4\t-\t[0019/1 dead=no instance]\n"),
    "research/tooling/ghidra/driver/names.tsv": ("module\taddr\tname\ttier\tevidence\n"
                                                 "vampire.dll\t10300500\tCNPC_Crow::Think\tdoc\tx\n"),
    "Source/ElysiumUE/Private/Substrate/Select.cpp": f"""// Select: 0x{ADDR} CAI_BaseNPC::SelectSchedule.
#include "Select.h"

int32 FElysiumNpc::SelectSchedule(int32 State)
{{
    // retail 0x{ADDR}: the ladder; also 0x1028a3f0.
    return State;
}}
""",
    "Source/ElysiumUE/Private/Substrate/Generated.cpp": (
        "// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.\n"
        f"{{ 0x{ADDR}, 0x10300000 }},\n"),
    "Source/ElysiumUE/Private/Tests/SelectTests.cpp": f"// 0x{ADDR} `SelectSchedule` test\n",
    "docs/specs/0002-x/story.md": f"# Story\n\nIt touches 0x{ADDR} and 0x{ADDR}.\n",
}


def at(rel: str, needle: str) -> int:
    """The 1-based line of `rel`'s fixture text that holds `needle`."""
    return next(number for number, line in enumerate(FILES[rel].split("\n"), 1) if needle in line)


@pytest.fixture
def repo(tmp_path, monkeypatch) -> Path:
    root = tmp_path / "repo"
    for rel, text in FILES.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")         # CRLF on Windows: the index must not care
    monkeypatch.setenv("ELYSIUM_WORK_ROOT", str(tmp_path / "work"))
    monkeypatch.setattr(ai, "REPO", root)
    monkeypatch.setattr(ai, "_CURRENT", None)
    yield root
    if ai._CURRENT is not None:
        ai._CURRENT.close()


def ask(*queries: str, rows: int = 8) -> str:
    return ai.where(list(queries), rows)


def docs_lines(out: str) -> int:
    return int(re.search(r"docs \(docs/vtmb, docs/contracts\): (\d+) line", out).group(1))


def test_an_address_finds_its_ledger_rows_docs_sections_port_lines_and_specs(repo):
    out = ask(f"0x{ADDR}")
    assert f"0x{ADDR}  CAI_BaseNPC::SelectSchedule" in out
    # The rows OF the address, per table -- and the verdict overlay carries it bare, without `0x`.
    assert f"functions.md:{at('docs/vtmb/npc-kernel/functions.md', ADDR)}  0x1028a380 | " \
           f"CAI_BaseNPC::SelectSchedule | 1650" in out
    assert f"slots.md:{at('docs/vtmb/npc-kernel/slots.md', ADDR)}  438 | 0x1028a380 " \
           f"CAI_BaseNPC::SelectSchedule" in out
    assert "kernel_verdicts.tsv:3  1028a380 | rule | 19-29" in out
    assert "unported.tsv:3  CAI_BaseNPC | 438 | 0x1028a380" in out
    # A heading that holds the address is listed first and marked; a mention names its section.
    heading = at(SCHEDULE, "## `0x")
    assert f"npc-ai/schedule.md:{heading}  [heading] `0x1028a380` `CAI_BaseNPC::SelectSchedule`" in out
    body = at(SCHEDULE, "The base selector")
    assert f"npc-ai/schedule.md:{body}  § `0x1028a380` `CAI_BaseNPC::SelectSchedule`" in out
    assert out.index(f"schedule.md:{heading}") < out.index(f"schedule.md:{body}")
    # The port: source before tests, the function a line sits in, a generated table set apart.
    assert "Private/Substrate/Select.cpp:1" in out
    assert "Private/Substrate/Select.cpp:6  in FElysiumNpc::SelectSchedule" in out
    assert out.index("Substrate/Select.cpp") < out.index("Tests/SelectTests.cpp")
    assert "plus 1 in 1 generated table(s), which are not citations" in out
    assert "specs (docs/specs): 1 line(s) in 1 file(s): 0002-x x1" in out


def test_every_spelling_of_an_address_is_the_same_query(repo):
    strip = lambda text: text.split("\n", 1)[1]            # the echoed query is the only difference
    assert strip(ask(f"0x{ADDR}")) == strip(ask(ADDR)) == strip(ask(f"FUN_{ADDR}"))


def test_a_longer_or_shorter_hex_run_is_a_different_number(repo):
    out = ask(f"0x{ADDR}")
    assert "Another section" not in out
    # The longer run is its own (raw) query, and finds only itself.
    longer = ask("0x1028a3801")
    assert "Another section" in longer and "Select.cpp" not in longer


def test_a_qualified_name_finds_its_address_and_so_the_address_only_rows(repo):
    out = ask("CAI_BaseNPC::SelectSchedule")
    assert f"0x{ADDR}  CAI_BaseNPC::SelectSchedule" in out
    assert "kernel_verdicts.tsv:3  1028a380 | rule" in out        # reached only through the address
    assert f"npc-ai/schedule.md:{at(SCHEDULE, 'The death schedule') - 2}" in out   # the name as a heading


def test_a_bare_member_name_scopes_to_few_functions_and_calls_many_ambiguous(repo):
    few = ask("PreSelectSchedule")
    assert "0x1028a260  CAI_BaseNPC::PreSelectSchedule" in few and "note:" not in few
    many = ask("SelectSchedule")
    assert "note: 5 functions are named SelectSchedule" in many
    assert "0x1028a380 CAI_BaseNPC::SelectSchedule" in many
    assert "pass an address or Class::Method to scope it" in many


def test_a_field_names_its_offset_and_an_offset_names_its_field(repo):
    field = ask("m_scriptState")
    assert "CAI_BaseNPCTroika::m_scriptState  +0x5d70  (int)" in field
    prose = at(SCHEDULE, "The base selector")
    assert f"npc-ai/schedule.md:{prose}" in field and "layout.tsv:2" in field
    offset = ask("+0x5d70")
    assert "+0x5d70  CAI_BaseNPCTroika::m_scriptState  (int)" in offset
    assert f"npc-ai/schedule.md:{prose}" in offset                  # `+0x5d70` in the prose
    assert ask("0x5d70").split("\n", 1)[1] == offset.split("\n", 1)[1]


def test_a_slot_finds_its_row_by_the_bare_number_and_the_docs_that_call_it_a_slot(repo):
    out = ask("slot 438")
    assert "vtable slot 438  base body 0x1028a380 CAI_BaseNPC::SelectSchedule" in out
    assert f"slots.md:{at('docs/vtmb/npc-kernel/slots.md', '| 438 |')}  438 | 0x1028a380" in out
    assert f"npc-ai/schedule.md:{at(SCHEDULE, 'Slot 438')}" in out  # "Slot 438 holds it."
    strip = lambda text: text.split("\n", 1)[1]
    assert strip(ask("438")) == strip(ask("#438")) == strip(ask("slot438")) == strip(out)


def test_the_index_is_rebuilt_exactly_when_an_input_changes(repo):
    first = ai.ensure_index()
    directory = first.directory
    assert ai.ensure_index() is first                    # nothing to load, nothing to build
    pickles = sorted(directory.glob("index-*.pkl"))
    assert len(pickles) == 1
    stamp = pickles[0].stat().st_mtime_ns

    ai._CURRENT.close()
    ai._CURRENT = None
    assert ai.ensure_index().key == first.key and pickles[0].stat().st_mtime_ns == stamp   # loaded

    before = docs_lines(ask(f"0x{ADDR}"))
    path = repo / SCHEDULE
    path.write_text(FILES[SCHEDULE] + f"\nA late mention of 0x{ADDR}.\n", encoding="utf-8")
    assert ai.ensure_index().key != first.key
    assert docs_lines(ask(f"0x{ADDR}")) == before + 1
    assert len(list(directory.glob("index-*.pkl"))) == 1                # the old build was removed


def test_a_deleted_file_leaves_the_rebuilt_answer_without_it(repo):
    ask(f"0x{ADDR}")
    (repo / "Source/ElysiumUE/Private/Substrate/Select.cpp").unlink()
    assert "Select.cpp" not in ask(f"0x{ADDR}")


def test_section_prints_the_section_a_heading_names_not_the_file(repo):
    out = ai.section("CAI_BaseNPC::SelectSchedule")
    assert "2 section(s) whose heading names it" in out
    deep, parent = at(SCHEDULE, "### The dead arm"), at(SCHEDULE, "## `0x")
    assert out.index(f"schedule.md:{deep}") < out.index(f"schedule.md:{parent}")  # the deeper first
    assert "### The dead arm of CAI_BaseNPC::SelectSchedule" in out and "chosen here." in out
    assert "Prose before any address." not in out and "Another section" not in out
    whole = ai.section("CAI_BaseNPC::SelectSchedule", pick=2)
    assert "switches on the state" in whole and "The dead arm" in whole
    paged = ai.section("CAI_BaseNPC::SelectSchedule", lines=2, pick=2)
    assert f"--from {parent + 2}" in paged and "switches on the state" not in paged
    assert "no docs section mentions" in ai.section("0x10300100")


def test_section_falls_back_to_the_sections_that_mention_it(repo):
    out = ai.section("m_scriptState")
    assert "no heading names it; the 1 section(s) its mentions sit in" in out
    assert "switches on the state" in out


def test_verdict_reads_one_address_a_band_or_the_standing(repo):
    one = ai.verdict([f"0x{ADDR}"])
    assert "0x1028a380  rule       band 19-29  CAI_BaseNPC::SelectSchedule" in one
    assert "target: FElysiumNpc::BaseSelectSchedule" in one and "the ladder" in one
    dead = ai.verdict([], which="dead")
    assert "10300000" in dead and "1028a380" not in dead
    count = ai.verdict([], count=True)
    assert "3 verdict row(s) of 3" in count and "19-29\t2\t0\t0\t0\t0\t2" in count
    assert "0-4\t0\t0\t0\t1\t0\t1" in count
    assert "no verdict row matches" in ai.verdict([f"0x{ADDR}"], band="0-4")


def test_cited_says_where_the_port_cites_an_address_and_never_counts_a_generated_table(repo):
    out = ai.cited([f"0x{ADDR}", "0x10300000", "0x1028a3f0"])
    assert ("0x1028a380  CAI_BaseNPC::SelectSchedule  cited 3x in 2 file(s): "
            "Select.cpp:1,6; SelectTests.cpp:1") in out
    assert "0x10300000  CNPC_Crow::StartTask  NOT CITED by the port" in out    # only a generated one has it
    assert "0x1028a3f0  CAI_BaseNPC::StartTask  cited 1x in 1 file(s): Select.cpp:6" in out
    assert "2 of 3 address(es) cited by the port" in out


def test_cited_over_a_table_lists_only_the_addresses_nothing_cites(repo):
    out = ai.cited([], table="unported.tsv", column="address")
    assert "0x10300000  CNPC_Crow::StartTask  NOT CITED" in out and "0x10300100" in out
    assert "CAI_BaseNPC::SelectSchedule  cited" not in out and "1 of 3 address(es) cited" in out
    rules = ai.cited([], table="unported.tsv", where_=["verdict=rule"], show_all=True)
    assert "0x10300100" not in rules and "0x1028a380  CAI_BaseNPC::SelectSchedule  cited" in rules
    assert "has no column 'nope'" in ai.cited([], table="unported.tsv", column="nope")


def test_rows_filters_projects_and_counts_a_table(repo):
    out = ai.rows_of("unported.tsv", ["verdict=rule"], columns="class,address")
    assert out.splitlines()[0] == "# docs/vtmb/npc-kernel/unported.tsv: 2 of 3 rows"
    assert out.splitlines()[1:] == ["class\taddress", "CAI_BaseNPC\t0x1028a380",
                                    "CNPC_Crow\t0x10300000"]
    grid = ai.rows_of("unported.tsv", [], count_by="class,verdict")
    assert "1\tCAI_BaseNPC\trule" in grid and "1\tCNPC_Crow\tdead" in grid
    start = ai.rows_of("kernel_verdicts.tsv", ["band=19-29", "target~Start"], columns="address")
    assert start.splitlines()[2:] == ["1028a3f0"]
    assert ai.rows_of("unported.tsv", ["slot>=440"], columns="slot").splitlines()[2:] == ["442"]
    with pytest.raises(SystemExit, match="is not a filter"):
        ai.rows_of("unported.tsv", ["nope=1"])
    with pytest.raises(SystemExit, match="no table named missing.tsv"):
        ai.rows_of("missing.tsv", [])


def test_an_ambiguous_table_name_lists_its_candidates(repo):
    (repo / "docs/vtmb/other").mkdir()
    (repo / "docs/vtmb/other/unported.tsv").write_text("a\tb\n", encoding="utf-8")
    with pytest.raises(SystemExit, match="ambiguous"):
        ai.resolve_table("unported.tsv")
    assert ai.resolve_table("npc-kernel/unported.tsv").parent.name == "npc-kernel"


def test_the_command_line_entry_prints_the_answer(repo, capsys):
    assert ai.run("where", [f"0x{ADDR}", "--limit", "2"]) == 0
    assert f"== 0x{ADDR}" in capsys.readouterr().out
    assert ai.run("rows", ["unported.tsv", "--count-by", "verdict"]) == 0
    assert "2\trule" in capsys.readouterr().out
    assert ai.run("where", ["--stats"]) == 0
    assert "files," in capsys.readouterr().out
