"""The rules every export_v2 GLB unit shares, in one importable place.

`docs/architecture/seam_map_unit_contract.md` owns these rules; this package is their code. A
seam depends on it for identity, source resolution, the container, cross-unit references, the
coverage vocabulary, the byte ledger and the kind-independent half of validation, and states in
its own `formats/<kind>_glb/` package only what is specific to its unit kind.
"""

from elysium_pipeline.formats.unit_contract.container import (
    BIN_CHUNK,
    GLB_MAGIC,
    JSON_CHUNK,
    GlbContainerError,
    asset_block,
    decode_glb,
    encode_glb,
    generator,
    plain,
    read_glb,
    write_glb,
)
from elysium_pipeline.formats.unit_contract.capsule import (
    CAPSULE_ALIGNMENT,
    CAPSULE_ENCODING,
    CapsuleError,
    buffer_table,
    capsule_declaration,
    declares_capsule,
    encapsulate,
    extract_source_member,
    source_capsules,
)
from elysium_pipeline.formats.unit_contract.coverage import (
    COVERAGE_KEYS,
    ROOT_KEYS,
    SEMANTIC_STATES,
    CoverageError,
    coverage_block,
    extension_name,
    extension_root,
    identity_block,
)
from elysium_pipeline.formats.unit_contract.ledger import (
    LEDGER_ROW_KEYS,
    LEDGER_STATES,
    ZERO_STATES,
    ByteLedger,
    ByteLedgerError,
    ranges_sha256,
    verify_ledger_row,
)
from elysium_pipeline.formats.unit_contract.origin import (
    LOOSE_ROOT_NAMES,
    ORIGIN_KINDS,
    SOURCE_POLICY,
    Origin,
    OriginError,
    SourceMember,
    origin_of,
    pakfile_origin,
    read_member,
    source_resolution,
)
from elysium_pipeline.formats.unit_contract.references import (
    ASSET_REFERENCE,
    DEPENDENCY_OPTIONAL_KEYS,
    DEPENDENCY_REQUIRED_KEYS,
    MATERIAL_REFERENCE,
    MODEL_REFERENCE,
    REFERENCE_EXTENSIONS,
    TEXTURE_REFERENCE,
    ReferenceError,
    asset_id,
    dependency,
    missing_sentinel,
    normalize_key,
    reference_extension,
)
from elysium_pipeline.formats.unit_contract.validate import (
    FORBIDDEN_CORE,
    INDEX_ROW_KEYS,
    SCENELESS_FORBIDDEN,
    UnitValidationError,
    completeness,
    validate_accessors,
    validate_capsules,
    validate_container,
    validate_extension_root,
    validate_index_rows,
    validate_ledgers,
    validate_sceneless,
    warnings_for,
)

__all__ = [
    "ASSET_REFERENCE",
    "BIN_CHUNK",
    "CAPSULE_ALIGNMENT",
    "CAPSULE_ENCODING",
    "COVERAGE_KEYS",
    "DEPENDENCY_OPTIONAL_KEYS",
    "DEPENDENCY_REQUIRED_KEYS",
    "FORBIDDEN_CORE",
    "INDEX_ROW_KEYS",
    "GLB_MAGIC",
    "JSON_CHUNK",
    "LEDGER_ROW_KEYS",
    "LEDGER_STATES",
    "LOOSE_ROOT_NAMES",
    "MATERIAL_REFERENCE",
    "MODEL_REFERENCE",
    "ORIGIN_KINDS",
    "REFERENCE_EXTENSIONS",
    "ROOT_KEYS",
    "SCENELESS_FORBIDDEN",
    "SEMANTIC_STATES",
    "SOURCE_POLICY",
    "TEXTURE_REFERENCE",
    "ZERO_STATES",
    "ByteLedger",
    "ByteLedgerError",
    "CapsuleError",
    "CoverageError",
    "GlbContainerError",
    "Origin",
    "OriginError",
    "ReferenceError",
    "SourceMember",
    "UnitValidationError",
    "asset_block",
    "asset_id",
    "buffer_table",
    "capsule_declaration",
    "completeness",
    "coverage_block",
    "declares_capsule",
    "dependency",
    "decode_glb",
    "encapsulate",
    "encode_glb",
    "extension_name",
    "extension_root",
    "extract_source_member",
    "generator",
    "identity_block",
    "missing_sentinel",
    "normalize_key",
    "origin_of",
    "pakfile_origin",
    "plain",
    "ranges_sha256",
    "read_glb",
    "read_member",
    "reference_extension",
    "source_capsules",
    "source_resolution",
    "validate_accessors",
    "validate_capsules",
    "validate_container",
    "validate_extension_root",
    "validate_index_rows",
    "validate_ledgers",
    "validate_sceneless",
    "verify_ledger_row",
    "warnings_for",
    "write_glb",
]
