"""Generated by `uv run elysium research gen_contents_signatures`. Do not hand-edit.

The offline half of the contents-signature table: the same four masks, the same spelling
and the same profile names the runtime's `ElysiumContentsSignature.h` carries, so the
exporter and the stage partition brushes exactly as the level and the payload will.
"""

from __future__ import annotations

#: The four masks, in signature order, with the retail sites that push them.
MASKS = (
    ('player', 'P', 0x1400b),  # does this brush block the player — 0x1011e560 CategorizePosition
    ('npc', 'N', 0x2400b),  # does this brush block an NPC — 0x10303b30 local-route ground retry
    ('sight', 'S', 0x804091),  # does this brush block sight — 0x102b4630 FVisible slot 201
    ('pedestrian', 'p', 0x2000),  # is this brush a pedestrian volume — 0x102fbbaa InitLinks' second walk test
)

#: `PNSp`, the order a signature spells its answers in.
LETTERS = 'PNSp'

#: The seven signatures the shipped maps carry; a map is refused if it needs another.
SHIPPED = ('PNS-', 'PN--', 'PN-p', '--S-', '-N-p', '-N--', '---p')

#: Retail's standable normal, borrowed from the player movement layer (0x104492d0).
STANDABLE_NORMAL_Z = 0.7

#: Step height in Source units: what every NPC walks with, and what the graph was built
#: with (CAI_TestHull, 0x102d72b0).
STEP_HEIGHT_UNITS = 18.0
GRAPH_BUILD_STEP_HEIGHT_UNITS = 40.0


def signature_of(contents: int) -> int:
    """The signature bits of a contents word."""

    bits = 0
    for index, (_key, _letter, mask) in enumerate(MASKS):
        if contents & mask:
            bits |= 1 << index
    return bits


def spell(bits: int) -> str:
    """`PNSp`, a dash where the answer is no."""

    return "".join(letter if bits & (1 << index) else "-"
                   for index, letter in enumerate(LETTERS))


def signature_str(contents: int) -> str:
    return spell(signature_of(contents))


#: The collision profile a body of each signature wears, by signature bits.
PROFILE_NAMES = {
    0: 'ElysiumSig_None',  # ---- — blocks nothing
    1: 'ElysiumSig_P',  # P--- — blocks the player
    2: 'ElysiumSig_N',  # -N-- — blocks an NPC
    3: 'ElysiumSig_PN',  # PN-- — blocks the player, an NPC
    4: 'ElysiumSig_S',  # --S- — blocks sight
    5: 'ElysiumSig_PS',  # P-S- — blocks the player, sight
    6: 'ElysiumSig_NS',  # -NS- — blocks an NPC, sight
    7: 'ElysiumSig_PNS',  # PNS- — blocks the player, an NPC, sight
    8: 'ElysiumSig_p',  # ---p — blocks nothing; a pedestrian volume
    9: 'ElysiumSig_Pp',  # P--p — blocks the player; a pedestrian volume
    10: 'ElysiumSig_Np',  # -N-p — blocks an NPC; a pedestrian volume
    11: 'ElysiumSig_PNp',  # PN-p — blocks the player, an NPC; a pedestrian volume
    12: 'ElysiumSig_Sp',  # --Sp — blocks sight; a pedestrian volume
    13: 'ElysiumSig_PSp',  # P-Sp — blocks the player, sight; a pedestrian volume
    14: 'ElysiumSig_NSp',  # -NSp — blocks an NPC, sight; a pedestrian volume
    15: 'ElysiumSig_PNSp',  # PNSp — blocks the player, an NPC, sight; a pedestrian volume
}


def profile_name(bits: int) -> str:
    return PROFILE_NAMES[bits]


def affects_navigation(bits: int) -> bool:
    """A body cuts the NavMesh exactly when it blocks an NPC."""

    return bool(bits & (1 << 1))
