"""Generated by contracts/generate_binary_profiles.py; do not edit."""

REGISTRY = {'profiles': [{'id': 'owner-unofficial-patch-vampire-6b15fae4',
               'module': 'Vampire.exe',
               'file_size': 188536,
               'sha256': '6b15fae4e5514f88e023a2f17ee84e2a3cdee35ce663d5af39b8178a58e3765a',
               'pe': {'machine': 332,
                      'timestamp': 1780555277,
                      'optional_magic': 267,
                      'preferred_image_base': 4194304,
                      'size_of_image': 262144,
                      'checksum': 0,
                      'section_count': 5,
                      'characteristics': 302},
               'targets': []},
              {'id': 'vtmb-retail-client-e88beae0',
               'module': 'client.dll',
               'source_spec': 'research/cases/animation-pose/specs/animation_pose.json',
               'file_size': 3428425,
               'sha256': 'e88beae0dd03af06493c71c5e8d87a6993b54e590cb6ad37cd3513c588582870',
               'pe': {'machine': 332,
                      'timestamp': 1102032739,
                      'optional_magic': 267,
                      'preferred_image_base': 268435456,
                      'size_of_image': 7245824,
                      'checksum': 0,
                      'section_count': 4,
                      'characteristics': 8462},
               'targets': [{'semantic_label': 'client.resolve_virtual_model_pose',
                            'source_function_label': 'resolve_virtual_model_pose',
                            'kind': 'inline',
                            'backend': 'inline_detour',
                            'rva': 616608,
                            'calling_convention': 'thiscall',
                            'expected_bytes': '83ec345355'},
                           {'semantic_label': 'client.build_transformations',
                            'source_function_label': 'c_baseanimating_build_transformations',
                            'kind': 'inline',
                            'backend': 'inline_detour',
                            'rva': 589056,
                            'calling_convention': 'thiscall',
                            'expected_bytes': 'b84c6f0000'},
                           {'semantic_label': 'client.setup_bones',
                            'source_function_label': 'c_baseanimating_setupbones',
                            'kind': 'inline',
                            'backend': 'inline_detour',
                            'rva': 596416,
                            'calling_convention': 'thiscall',
                            'expected_bytes': 'b830270000'},
                           {'semantic_label': 'client.get_studio_hdr',
                            'kind': 'symbol',
                            'backend': 'none',
                            'rva': 588032,
                            'calling_convention': 'thiscall',
                            'expected_bytes': '8b4424045685c08b'}]},
              {'id': 'vtmb-retail-engine-9d00b2c1',
               'module': 'engine.dll',
               'source_spec': 'research/cases/animation-pose/specs/animation_skinning.json',
               'file_size': 1986620,
               'sha256': '9d00b2c1e5edbad052fb0b514634ba54574666e12d1b408c46ce141d51ed2313',
               'pe': {'machine': 332,
                      'timestamp': 1102032712,
                      'optional_magic': 267,
                      'preferred_image_base': 536870912,
                      'size_of_image': 20688896,
                      'checksum': 0,
                      'section_count': 5,
                      'characteristics': 8462},
               'targets': [{'semantic_label': 'engine.model_render_draw_model',
                            'source_function_label': 'c_modelrender_drawmodel',
                            'kind': 'inline',
                            'backend': 'inline_detour',
                            'rva': 681536,
                            'calling_convention': 'thiscall',
                            'expected_bytes': '83ec248b1528331720'},
                           {'semantic_label': 'engine.model_render_draw_model_shadow',
                            'source_function_label': 'c_modelrender_drawmodelshadow',
                            'kind': 'inline',
                            'backend': 'inline_detour',
                            'rva': 682384,
                            'calling_convention': 'thiscall',
                            'expected_bytes': '8b1528331720'}]},
              {'id': 'vtmb-retail-studiorender-13d56ce9',
               'module': 'StudioRender.dll',
               'source_spec': 'research/cases/animation-pose/specs/animation_studiorender.json',
               'file_size': 561222,
               'sha256': '13d56ce90de2c5faedc0df26d36b24e90f30eded5055625f616cd97e301e124b',
               'pe': {'machine': 332,
                      'timestamp': 1097124928,
                      'optional_magic': 267,
                      'preferred_image_base': 738197504,
                      'size_of_image': 2539520,
                      'checksum': 0,
                      'section_count': 4,
                      'characteristics': 8462},
               'targets': [{'semantic_label': 'studiorender.draw_model',
                            'source_function_label': 'c_studiorender_drawmodel',
                            'kind': 'vtable',
                            'backend': 'vtable_replacement',
                            'rva': 20224,
                            'calling_convention': 'thiscall',
                            'expected_bytes': '83ec08538b1dccc0',
                            'vtable': {'object_rva': 535344,
                                       'expected_vtable_rva': 442704,
                                       'slot': 22}}]}]}
PROFILES = REGISTRY['profiles']
PROFILES_BY_ID = {profile['id']: profile for profile in PROFILES}

def profiles_for_module(module_name: str) -> list[dict[str, object]]:
    folded = module_name.casefold()
    return [
        profile
        for profile in PROFILES
        if str(profile['module']).casefold() == folded
    ]

def match_profile(
    module_name: str, file_size: int, sha256: str
) -> dict[str, object]:
    matches = [
        profile
        for profile in profiles_for_module(module_name)
        if profile['file_size'] == file_size and profile['sha256'] == sha256
    ]
    if len(matches) != 1:
        raise LookupError(
            f'no exact binary profile for {module_name} size={file_size} '
            f'sha256={sha256}'
        )
    return matches[0]

def target(
    profile: dict[str, object], semantic_label: str
) -> dict[str, object]:
    matches = [
        item
        for item in profile['targets']
        if item['semantic_label'] == semantic_label
    ]
    if len(matches) != 1:
        raise LookupError(
            f"profile {profile['id']} has no unique target {semantic_label}"
        )
    return matches[0]
