// Generated by contracts/generate_record_schemas.py; do not edit.
#pragma once

#include <cstdint>

constexpr std::uint32_t kCaptureSchemaRegistryVersion = 1u;

#pragma pack(push, 1)
struct FileHeader {
    char magic[8];
    std::uint32_t version;
    std::uint32_t headerBytes;
    std::uint64_t qpcFrequency;
    std::int64_t startQpc;
    std::uint32_t pid;
    std::uint32_t studioRenderBase;
    std::uint32_t studioObject;
    std::uint32_t studioVtable;
    std::uint32_t drawModelRva;
    char studioRenderSha256[65];
    char reserved[11];
};
constexpr std::uint32_t kFileHeaderRecordId = 1u;
constexpr std::uint32_t kFileHeaderSchemaVersion = 2u;

struct PoseRecordHeader {
    char magic[4];
    std::uint32_t recordBytes;
    std::uint64_t sequence;
    std::int64_t qpc;
    std::uint32_t threadId;
    std::uint32_t studioHdr;
    std::uint32_t clientEntity;
    std::uint32_t checksum;
    std::uint32_t boneCount;
    std::uint32_t modelInfo;
    std::uint32_t drawArguments[5];
    char modelName[64];
};
constexpr std::uint32_t kPoseRecordHeaderRecordId = 2u;
constexpr std::uint32_t kPoseRecordHeaderSchemaVersion = 2u;

struct AnimationFileHeader {
    char magic[8];
    std::uint32_t version;
    std::uint32_t headerBytes;
    std::uint64_t qpcFrequency;
    std::int64_t startQpc;
    std::uint32_t pid;
    std::uint32_t clientBase;
    std::uint32_t resolveVirtualModelPoseRva;
    std::uint32_t buildTransformationsRva;
    std::uint32_t targetChecksum;
    char clientSha256[65];
    char reserved[11];
};
constexpr std::uint32_t kAnimationFileHeaderRecordId = 3u;
constexpr std::uint32_t kAnimationFileHeaderSchemaVersion = 2u;

struct AnimationRecordHeader {
    char magic[4];
    std::uint32_t recordBytes;
    std::uint64_t sequence;
    std::int64_t qpc;
    std::uint32_t threadId;
    std::uint32_t clientEntity;
    std::uint32_t studioHdr;
    std::uint32_t checksum;
    std::uint32_t boneCount;
    std::int32_t studioSequence;
    float samplePhase;
    float entityCycle;
    std::int32_t result;
    std::uint32_t positions;
    std::uint32_t quaternions;
};
constexpr std::uint32_t kAnimationRecordHeaderRecordId = 4u;
constexpr std::uint32_t kAnimationRecordHeaderSchemaVersion = 2u;

constexpr std::uint32_t kAnimationFinalRecordId = 5u;
constexpr std::uint32_t kAnimationFinalSchemaVersion = 2u;

#pragma pack(pop)

static_assert(sizeof(FileHeader) == 128, "capture file header changed");
static_assert(sizeof(PoseRecordHeader) == 132, "pose record header changed");
static_assert(sizeof(AnimationFileHeader) == 128, "animation capture file header changed");
static_assert(sizeof(AnimationRecordHeader) == 68, "animation record header changed");
