# -*- coding: utf-8 -*-
"""The address index: from a retail address, name, field or slot to everywhere the project already
speaks about it.

Answering "what do we know about `0x1028a380`" used to be a `grep` over `docs/vtmb` (1.4 MB
`functions.md`, 0.7-0.9 MB checklists), a second over the ledger, a third over `Source/`, and a read
of whatever those turned up: 800 shell searches and some 160 one-off scripts in twelve days, each
one to three seconds of which almost none was the search. This answers it in one call:

    uv run elysium research where 0x1028a380 CAI_BaseNPC::SelectSchedule m_scriptState
    uv run elysium research where "slot 442"

and, through the corpus server, as the `vtmb_where` tool. A query gets its `docs/vtmb` sections
(file, heading, line), its rows in the `npc-kernel` ledger tables, the port source lines that cite
it, and a count of the specs that mention it. (`--verbose` is a root option: without it the CLI
withholds a tool's output; `uv run python research/tooling/lookup/where.py ...` needs neither.)

The standing verbs over the same index -- `section`, `verdict`, `cited`, `rows` -- are the questions
the one-off scripts kept asking; each is `research/tooling/lookup/<verb>.py`.

How it is built. Every input is a text file the project already owns: `docs/vtmb`, `docs/contracts`,
`docs/specs`, the ledger's `.tsv` overlays beside the corpus driver, and the port's `.h`, `.cpp` and
`.inl` under `Source/`. They are packed into one lower-cased blob with a table of line starts, so a
query is a `find` through memory-mapped bytes -- any literal, with no tokeniser to disagree about
what a name is -- and a position becomes (file, line) by bisection. What a blob cannot say is parsed
once at build: headings (the section a line sits in), the name tables the ledger holds
(`functions.md`, `names.tsv`, `layout.tsv`, `slots.md`), which let a name find its address and an
address its name, and the port's citations of every address, so asking which of 2,500 addresses the
port never cites is one pass and not 2,500 searches. The whole is keyed on the input hash (every
input's path, size and mtime, and the format version) under
`$ELYSIUM_WORK_ROOT/cache/where-index/<checkout>/`: a cold rebuild is seconds, an unchanged tree
rebuilds nothing.

A line is shown from the file on disk, not from the blob, so what is printed is the file as it is;
and a file that changed since the build changed the input hash, so the index was rebuilt before it
was asked.
"""

from __future__ import annotations

import argparse
import bisect
import hashlib
import mmap
import os
import pickle
import re
import sys
import time
from array import array
from collections import Counter, defaultdict
from itertools import accumulate
from pathlib import Path

FORMAT_VERSION = 1
DEFAULT_ROWS = 8

REPO = Path(__file__).resolve().parents[3]

# What is indexed, as (directory under the repo, extensions, kind). The kind decides how a hit is
# shown: `ledger` rows are table rows, `doc` hits are prose under a heading, `port` hits are
# source, and `spec` hits are only counted. A port file a generator wrote is `generated`: it names
# every slot body by address and is the ledger's own reflection, not a citation of it.
ROOTS = (
    ("docs/vtmb", (".md", ".tsv"), "doc"),
    ("docs/contracts", (".md",), "doc"),
    ("docs/specs", (".md", ".tsv"), "spec"),
    ("research/tooling/ghidra/driver", (".tsv",), "ledger"),
    ("Source/ElysiumUE/Private", (".h", ".cpp", ".inl"), "port"),
    ("Source/ElysiumUE/Public", (".h", ".cpp", ".inl"), "port"),
    ("Source/ElysiumUEAnimGraph", (".h", ".cpp", ".inl"), "port"),
)
LEDGER_DIR = "docs/vtmb/npc-kernel/"
SKIP_DIRS = {"__pycache__", "ThirdParty", "Intermediate", "Binaries", ".git", "node_modules"}
GENERATED = b"// generated by"                # the first line of a file a generator wrote (lowered)

FUNCTIONS_MD = LEDGER_DIR + "functions.md"
SLOTS_MD = LEDGER_DIR + "slots.md"
LAYOUT_TSV = LEDGER_DIR + "layout.tsv"
NAMES_TSV = "research/tooling/ghidra/driver/names.tsv"
VERDICTS_TSV = "research/tooling/ghidra/driver/kernel_verdicts.tsv"
NAME_TABLES = (FUNCTIONS_MD, SLOTS_MD, LAYOUT_TSV, NAMES_TSV)

# How a query is read. An address is `0x` and 6-8 hex digits, or a bare eight (a table cell, a
# `FUN_` name); a bare run of fewer is not taken, because six hex digits is also a word.
ADDRESS = re.compile(r"^(?:0x)?([0-9a-fA-F]{8})$|^0x([0-9a-fA-F]{6,7})$"
                     r"|^(?:thunk_)?(?:FUN|LAB|DAT)_([0-9a-fA-F]{8})$")
SLOT = re.compile(r"^(?:slots?\s*#?\s*|#|vfunc)(\d{1,4})$|^(\d{1,3})$", re.IGNORECASE)
OFFSET = re.compile(r"^(?:\+0x|0x)([0-9a-fA-F]{1,5})$")
IDENTIFIER = re.compile(r"^~?[A-Za-z_][A-Za-z0-9_]*(?:::~?[A-Za-z_][A-Za-z0-9_]*)*$")

# What the text says. Matched against the lower-cased blob, so lower-case classes only.
CITATION = re.compile(rb"(?<![0-9a-z])(?:0x)?([1-3][0-9a-f]{7})(?![0-9a-z])")
HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
FUNCTION_ROW = re.compile(r"^\| `0x([0-9a-f]{8})` \| ([^|]+?) \|")
SLOT_ROW = re.compile(r"^\| (\d+) \| `0x([0-9a-f]{8})` ([^|]+?) \|")
DEFINITION = re.compile(r"^[A-Za-z_][^;{}()=]*?\b([A-Za-z_]\w*(?:::~?\w+)+)\s*\(")
VERDICT_WORDS = ("rule", "mechanism", "present", "dead", "unsettled")

MAX_HITS = 50_000               # per needle; a name that common is counted, not listed
_ALNUM = frozenset(b"0123456789abcdefghijklmnopqrstuvwxyz")
_WORD = _ALNUM | {ord("_")}


def load_local_environment() -> None:
    """`.elysium.local.env`, read directly: run as a script, this has no CLI to load it."""
    if os.environ.get("ELYSIUM_WORK_ROOT"):
        return
    for parent in Path(__file__).resolve().parents:
        candidate = parent / ".elysium.local.env"
        if candidate.is_file():
            for line in candidate.read_text(encoding="utf-8-sig").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    name, _, value = line.partition("=")
                    os.environ.setdefault(name.strip(), value.strip().strip("'\""))
            return


def cache_dir(repo: Path) -> Path:
    from elysium_pipeline.paths import cache_root
    # One index per checkout: the files it describes are the checkout's own.
    key = hashlib.sha256(str(repo.resolve()).lower().encode()).hexdigest()[:10]
    return cache_root() / "where-index" / key


# ---------------------------------------------------------------------------
# Building.

# An input: (path relative to the repo, kind, size, mtime in ns).
Input = tuple[str, str, int, int]


def discover(repo: Path) -> list[Input]:
    """Every input, in a fixed order, with the size and mtime the directory scan already holds.

    `os.walk` then `stat` is two system calls per file and ~0.1 ms each on Windows -- 0.2 s to
    learn that nothing changed. `DirEntry.stat()` answers from the scan itself, so the whole
    sweep, which every query makes, is a few milliseconds.
    """
    found: list[Input] = []
    root = str(repo)
    for sub, extensions, kind in ROOTS:
        if not (repo / sub).is_dir():
            continue
        batch: list[Input] = []
        stack = [os.path.join(root, *sub.split("/"))]
        while stack:
            directory = stack.pop()
            try:
                entries = list(os.scandir(directory))
            except OSError:
                continue
            for entry in entries:
                if entry.is_dir(follow_symlinks=False):
                    if entry.name not in SKIP_DIRS:
                        stack.append(entry.path)
                elif entry.name.endswith(extensions):
                    stat = entry.stat()
                    # Plain string work: `pathlib` costs more per file than the stat it is for.
                    rel = entry.path[len(root) + 1:].replace("\\", "/")
                    batch.append((rel, "ledger" if rel.startswith(LEDGER_DIR) else kind,
                                  stat.st_size, stat.st_mtime_ns))
        found += sorted(batch)
    return found


def fingerprint(inputs: list[Input]) -> str:
    """The input hash: the format version and every input's path, size and mtime.

    Stat, not content: reading 1,700 files to learn that nothing changed would cost a hundred
    times the stat, and a file whose bytes changed with its size and mtime unchanged is not a thing
    a checkout does. A checkout that rewrites every mtime (a `git checkout`) costs one rebuild.
    """
    digest = hashlib.sha256(f"{FORMAT_VERSION}\n".encode())
    for rel, kind, size, mtime in inputs:
        digest.update(f"{rel}\t{kind}\t{size}\t{mtime}\n".encode())
    return digest.hexdigest()[:16]


class Built:
    """What a build produces before it is written: the blob and the tables beside it."""

    def __init__(self) -> None:
        self.files: list[tuple[str, str]] = []
        self.first_line: list[int] = []
        self.nlines: list[int] = []
        self.blob = bytearray()
        self.line_starts = array("I")
        self.heads: dict[int, list[tuple[int, int, str]]] = {}
        self.addr_names: dict[str, list[str]] = defaultdict(list)
        self.name_addrs: dict[str, list[str]] = defaultdict(list)
        self.member_addrs: dict[str, list[tuple[str, str]]] = defaultdict(list)
        self.fields: dict[str, list[tuple[str, int, str]]] = defaultdict(list)
        self.offsets: dict[int, list[tuple[str, str, str]]] = defaultdict(list)
        self.slots: dict[int, tuple[int, str, str]] = {}
        self.port_cites: dict[str, list[tuple[int, int]]] = defaultdict(list)


def _name(built: Built, addr: str, name: str) -> None:
    name = name.strip().strip("`")
    if not name or name in built.addr_names[addr]:
        return
    built.addr_names[addr].append(name)
    built.name_addrs[name.lower()].append(addr)
    built.member_addrs[name.rsplit("::", 1)[-1].lower()].append((name, addr))


def _headings(lines: list[str]) -> list[tuple[int, int, str]]:
    """(line, level, text) of each heading outside a fenced block."""
    found = []
    fenced = False
    for number, line in enumerate(lines, 1):
        if line.startswith("```"):
            fenced = not fenced
        elif not fenced and line.startswith("#"):
            match = HEADING.match(line)
            if match:
                found.append((number, len(match.group(1)), match.group(2)[:200]))
    return found


def _tables(built: Built, rel: str, lines: list[str]) -> None:
    """The name tables the ledger holds, parsed from the files that carry them."""
    if rel == FUNCTIONS_MD:
        for line in lines:
            match = FUNCTION_ROW.match(line)
            if match:
                _name(built, match.group(1), match.group(2))
    elif rel == SLOTS_MD:
        for number, line in enumerate(lines, 1):
            match = SLOT_ROW.match(line)
            if match:
                built.slots.setdefault(int(match.group(1)),
                                       (number, match.group(2), match.group(3).strip()))
                _name(built, match.group(2), match.group(3))
    elif rel == NAMES_TSV:
        for line in lines:
            parts = line.split("\t")
            if len(parts) >= 3 and not line.startswith("#") and re.fullmatch(r"[0-9a-f]{8}",
                                                                              parts[1]):
                _name(built, parts[1], parts[2])
    elif rel == LAYOUT_TSV:
        header: list[str] | None = None
        for line in lines:
            if not line.strip() or line.startswith("#"):
                continue
            parts = line.split("\t")
            if header is None:
                header = parts
                continue
            row = dict(zip(header, parts))
            try:
                offset = int(row.get("offset", ""), 16)
            except ValueError:
                continue
            member = row.get("member", "")
            if member:
                entry = (row.get("table", ""), offset, row.get("type", ""))
                built.fields[member.lower()].append(entry)
                built.offsets[offset].append((entry[0], member, entry[2]))


def build(repo: Path, inputs: list[Input]) -> Built:
    """Read every input once."""
    built = Built()
    offset = 0
    for rel, kind, _, _ in inputs:
        data = (repo / rel).read_bytes()
        if not data.endswith(b"\n"):
            data += b"\n"
        file_id = len(built.files)
        lowered = data.lower()
        if kind == "port" and lowered.startswith(GENERATED):
            kind = "generated"
        built.files.append((rel, kind))
        pieces = lowered.split(b"\n")
        starts = list(accumulate((len(piece) + 1 for piece in pieces[:-1]), initial=offset))
        built.first_line.append(len(built.line_starts))
        built.nlines.append(len(starts) - 1)
        built.line_starts.extend(starts[:-1])
        built.blob += lowered
        if kind in ("port", "generated"):
            # Every address the port speaks of, with the line it speaks on: `cited` asks it of a
            # whole table, which as one search per address would be a minute.
            for match in CITATION.finditer(lowered):
                line = bisect.bisect_right(starts, offset + match.start()) - 1
                built.port_cites[match.group(1).decode()].append((file_id, line + 1))
        offset = starts[-1]
        if kind in ("doc", "ledger", "spec") or rel in NAME_TABLES:
            # Split on `\n` alone, the way the blob's line table is, so a heading's number is its
            # line; a Windows checkout's `\r` is part of no cell.
            lines = [line.rstrip("\r") for line in data.decode("utf-8", "replace").split("\n")]
            if rel.endswith(".md"):
                built.heads[file_id] = _headings(lines)
            _tables(built, rel, lines)
    return built


def _write(directory: Path, key: str, built: Built) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    blob, meta = directory / f"text-{key}.bin", directory / f"index-{key}.pkl"
    pid = os.getpid()
    tables = {
        "version": FORMAT_VERSION, "key": key, "files": built.files,
        "first_line": built.first_line, "nlines": built.nlines,
        "line_starts": built.line_starts.tobytes(), "heads": built.heads,
        "addr_names": dict(built.addr_names), "name_addrs": dict(built.name_addrs),
        "member_addrs": dict(built.member_addrs), "fields": dict(built.fields),
        "offsets": dict(built.offsets), "slots": built.slots,
        "port_cites": dict(built.port_cites),
    }
    (directory / f"text-{key}.{pid}.tmp").write_bytes(bytes(built.blob))
    with (directory / f"index-{key}.{pid}.tmp").open("wb") as handle:
        pickle.dump(tables, handle, protocol=pickle.HIGHEST_PROTOCOL)
    # Data first, the pointer last. Two processes that build the same key write the same bytes, so
    # a replace that loses to a mapped copy of itself has nothing to say.
    for source, target in ((f"text-{key}.{pid}.tmp", blob), (f"index-{key}.{pid}.tmp", meta)):
        try:
            os.replace(directory / source, target)
        except PermissionError:
            (directory / source).unlink(missing_ok=True)
    for old in directory.iterdir():             # earlier builds; one still mapped stays put
        if old.name not in (blob.name, meta.name):
            try:
                old.unlink()
            except OSError:
                pass


# ---------------------------------------------------------------------------
# Loading and searching.

class Index:
    """A loaded index. `text` is the memory-mapped blob; everything else is small."""

    def __init__(self, repo: Path, directory: Path, key: str) -> None:
        with (directory / f"index-{key}.pkl").open("rb") as handle:
            tables = pickle.load(handle)
        self.repo = repo
        self.directory = directory
        self.key = key
        self.files: list[tuple[str, str]] = tables["files"]
        self.first_line: list[int] = tables["first_line"]
        self.nlines: list[int] = tables["nlines"]
        self.line_starts = array("I")
        self.line_starts.frombytes(tables["line_starts"])
        self.heads: dict[int, list[tuple[int, int, str]]] = tables["heads"]
        self.addr_names: dict[str, list[str]] = tables["addr_names"]
        self.name_addrs: dict[str, list[str]] = tables["name_addrs"]
        self.member_addrs: dict[str, list[tuple[str, str]]] = tables["member_addrs"]
        self.fields: dict[str, list[tuple[str, int, str]]] = tables["fields"]
        self.offsets: dict[int, list[tuple[str, str, str]]] = tables["offsets"]
        self.slots: dict[int, tuple[int, str, str]] = tables["slots"]
        self.port_cites: dict[str, list[tuple[int, int]]] = tables["port_cites"]
        self._file = (directory / f"text-{key}.bin").open("rb")
        self.text = mmap.mmap(self._file.fileno(), 0, access=mmap.ACCESS_READ)
        self.file_ids = {rel: number for number, (rel, _) in enumerate(self.files)}
        self._lines: dict[str, list[str]] = {}

    def close(self) -> None:
        self.text.close()
        self._file.close()

    def locate(self, position: int) -> tuple[int, int]:
        """(file id, 1-based line) of a byte offset in the blob."""
        line = bisect.bisect_right(self.line_starts, position) - 1
        file_id = bisect.bisect_right(self.first_line, line) - 1
        return file_id, line - self.first_line[file_id] + 1

    def line(self, rel: str, number: int) -> str:
        """One line as the file on disk has it."""
        if rel not in self._lines:
            try:
                # Bytes, not `read_text`: universal newlines would turn a lone `\r` into a line
                # break the blob's line table does not have, and every number after it would be off.
                text = (self.repo / rel).read_bytes().decode("utf-8", "replace")
            except OSError:
                text = ""
            self._lines[rel] = text.split("\n")
        lines = self._lines[rel]
        return lines[number - 1].rstrip("\r") if 0 < number <= len(lines) else ""

    def heading_at(self, file_id: int, line: int) -> tuple[int, int, str] | None:
        """The nearest heading at or above a line."""
        heads = self.heads.get(file_id)
        if not heads:
            return None
        index = bisect.bisect_right(heads, (line, 99, "\U0010ffff")) - 1
        return heads[index] if index >= 0 else None

    def section_end(self, file_id: int, head: tuple[int, int, str]) -> int:
        """The last line of a heading's section: the line before the next heading of its level or
        higher, or the end of the file."""
        heads = self.heads[file_id]
        position = bisect.bisect_left(heads, head)
        for line, level, _ in heads[position + 1:]:
            if level <= head[1]:
                return line - 1
        return self.nlines[file_id]

    def _bounded(self, start: int, end: int, how: str) -> bool:
        if how == "raw":
            return True
        before = self.text[start - 1] if start else 0
        after = self.text[end] if end < len(self.text) else 0
        if how == "tail":                       # `+0x5b7c`: what follows must not extend the number
            return after not in _ALNUM
        if how == "address":                    # a longer hex run is a different number
            if before == ord("x") and start >= 2 and self.text[start - 2] == ord("0"):
                before = 0                      # the `0x` of `0x1028a380` is part of the address
            return before not in _ALNUM and after not in _ALNUM
        if how == "slot":                       # a number that something calls a slot
            if after in _ALNUM:
                return False
            window = self.text[max(0, start - 8):start].decode("latin-1")
            return re.search(r"(?:slots?\s*#?\s*|#|vfunc)$", window) is not None
        return before not in _WORD and after not in _WORD       # "word": not inside a longer name

    def find(self, needle: str, how: str = "word") -> tuple[dict[int, list[int]], int, bool]:
        """Every line holding `needle`: ({file id: [lines]}, how many, whether it was cut short).

        `how` bounds the needle: "word" -- not inside a longer identifier; "address" -- not inside
        a longer run of letters and digits; "tail" -- not followed by one; "slot" -- a number
        something calls a slot (`slot 442`, `#442`, `vfunc442`); "raw" -- anywhere.
        """
        target = needle.lower().encode("utf-8")
        found: dict[int, set[int]] = defaultdict(set)
        count = 0
        position = self.text.find(target)
        while position != -1:
            if self._bounded(position, position + len(target), how):
                file_id, line = self.locate(position)
                found[file_id].add(line)
                count += 1
                if count >= MAX_HITS:
                    return {k: sorted(v) for k, v in found.items()}, count, True
            position = self.text.find(target, position + 1)
        return {k: sorted(v) for k, v in found.items()}, count, False


_CURRENT: Index | None = None


def ensure_index(repo: Path | None = None, directory: Path | None = None,
                 rebuild: bool = False) -> Index:
    """The index for this tree, built first if the input hash says it is not current."""
    global _CURRENT
    repo = repo or REPO                 # read at call time, so a test can point REPO elsewhere
    directory = directory or cache_dir(repo)
    inputs = discover(repo)
    key = fingerprint(inputs)
    if (_CURRENT is not None and _CURRENT.key == key and _CURRENT.repo == repo
            and _CURRENT.directory == directory and not rebuild):
        return _CURRENT
    ready = (directory / f"index-{key}.pkl").is_file() and (directory / f"text-{key}.bin").is_file()
    if rebuild or not ready:
        _write(directory, key, build(repo, inputs))
    if _CURRENT is not None:
        _CURRENT.close()
        _CURRENT = None
    try:
        _CURRENT = Index(repo, directory, key)
    except (OSError, ValueError, KeyError, EOFError, pickle.UnpicklingError):
        # A half-written or foreign file under the right name: build it again, once.
        _write(directory, key, build(repo, inputs))
        _CURRENT = Index(repo, directory, key)
    return _CURRENT


# ---------------------------------------------------------------------------
# Reading a query.

class Plan:
    """What a query asks: what to search for, and what the index already knows about it."""

    def __init__(self, text: str) -> None:
        self.text = text
        self.what = "text"                              # address | slot | offset | name | text
        self.needles: list[tuple[str, str]] = []      # (literal, how it must be bounded)
        self.heading: list[str] = []                  # what the tables say, before any hit
        self.notes: list[str] = []
        self.addresses: list[str] = []                # bare 8-hex addresses this query stands for
        self.pinned: list[tuple[str, int]] = []       # (file, line) the tables name outright


def plan(index: Index, text: str) -> Plan:
    """Classify a query and attach what the name tables know about it."""
    query = text.strip().strip("`'\"")
    result = Plan(query)
    address = ADDRESS.match(query)
    slot = SLOT.match(query)
    offset = OFFSET.match(query)
    if address:
        digits = next(group for group in address.groups() if group)
        value = digits.lower().rjust(8, "0")
        result.what = "address"
        result.addresses = [value]
        result.needles.append((value, "address"))
        names = index.addr_names.get(value, [])
        result.heading.append(f"0x{value}  " + (", ".join(names[:3]) if names
                                                  else "no name in the ledger or the overlay"))
    elif slot:
        number = int(slot.group(1) or slot.group(2))
        result.what = "slot"
        result.needles.append((str(number), "slot"))
        row = index.slots.get(number)
        result.heading.append(f"vtable slot {number}  " + (f"base body 0x{row[1]} {row[2]}"
                                                           if row else "not in the slots ledger"))
        if row:                       # the slots table keys its row by the bare number
            result.pinned.append((SLOTS_MD, row[0]))
    elif offset:
        value = int(offset.group(1), 16)
        result.what = "offset"
        for form in dict.fromkeys((f"+0x{value:x}", f"+0x{value:04x}")):
            result.needles.append((form, "tail"))
        for table, member, kind in index.offsets.get(value, [])[:6]:
            result.heading.append(f"+0x{value:04x}  {table}::{member}  ({kind})")
        if not index.offsets.get(value):
            result.heading.append(f"+0x{value:04x}  no field in layout.tsv")
    elif IDENTIFIER.match(query):
        result.what = "name"
        result.needles.append((query, "word"))
        key = query.lower()
        qualified = "::" in query
        candidates = (index.name_addrs.get(key, []) if qualified else
                      [addr for _, addr in index.member_addrs.get(key, [])])
        candidates = list(dict.fromkeys(candidates))
        if candidates and len(candidates) <= 4:
            result.addresses = candidates
            for addr in candidates:
                result.needles.append((addr, "address"))
                result.heading.append(f"0x{addr}  " + ", ".join(index.addr_names.get(addr, [])[:3]))
        elif candidates:
            named = [f"0x{addr} {index.addr_names.get(addr, ['?'])[0]}" for addr in candidates[:6]]
            result.notes.append(f"{len(candidates)} functions are named {query}: "
                                + "; ".join(named) + (" ..." if len(candidates) > 6 else "")
                                + " -- pass an address or Class::Method to scope it")
        for table, off, kind in index.fields.get(key, [])[:6]:
            result.heading.append(f"{table}::{query}  +0x{off:04x}  ({kind})")
        if not qualified and len(index.fields.get(key, [])) > 6:
            result.notes.append(f"{len(index.fields[key])} layout rows name {query}")
    elif len(query) >= 3:
        result.needles.append((query, "raw"))
    return result


# ---------------------------------------------------------------------------
# Showing what was found.

def _clip(text: str, width: int, near: str | None = None) -> str:
    """A line cut to `width` characters, around `near` when the line is longer."""
    text = " ".join(text.strip().split())
    if len(text) <= width:
        return text
    at = text.lower().find(near.lower()) if near else -1
    start = max(0, at - width // 3) if at > 0 else 0
    return ("… " if start else "") + text[start:start + width] + (
        " …" if start + width < len(text) else "")


def _cells(rel: str, line: str) -> list[str]:
    if rel.endswith(".tsv"):
        return [cell.strip() for cell in line.split("\t")]
    return [cell.strip().replace("`", "") for cell in line.strip().strip("|").split("|")]


def _row(index: Index, rel: str, number: int, needle: str) -> str:
    """A ledger row: its first cells, and its verdict if it is a checklist row."""
    cells = _cells(rel, index.line(rel, number))
    shown = _clip(" | ".join(cells[:6]), 150, needle)
    verdict = next((cell for cell in cells if cell in VERDICT_WORDS), None)
    return shown + (f"  [verdict {verdict}]" if verdict and verdict not in shown else "")


def _is_row(index: Index, rel: str, number: int, needles: list[str]) -> bool:
    """Whether a line is a table row OF the needle (its first cells) rather than a mention in it."""
    line = index.line(rel, number)
    if rel.endswith(".tsv"):
        head = line.split("\t")[:5]             # `layout.tsv` keys its row by the 4th column
    elif line.startswith("|"):
        head = line.split("|")[1:3]
    else:
        return False
    text = " ".join(head).lower()
    return any(needle in text for needle in needles)


def _symbol(index: Index, rel: str, number: int) -> str:
    """The function a source line sits in: the nearest definition above it, at column 0."""
    for back in range(number - 1, max(0, number - 800), -1):
        line = index.line(rel, back)
        if line[:1].isalpha() or line[:1] == "_":
            match = DEFINITION.match(line)
            if match:
                return match.group(1)
    return ""


def _group(hits: dict[int, set[int]], index: Index, kinds: tuple[str, ...]) -> dict[int, list[int]]:
    return {fid: sorted(lines) for fid, lines in hits.items() if index.files[fid][1] in kinds}


def _more(counter: Counter) -> str:
    """`a.md x5; b.md x3 ...`: what was not listed, by file."""
    ranked = counter.most_common()
    return "; ".join(f"{Path(name).name} x{n}" for name, n in ranked[:6]) + (
        f"; and {len(ranked) - 6} more file(s)" if len(ranked) > 6 else "")


LEDGER_ORDER = ("functions.md", "slots.md", "fields.md", "entries.md", "checklist", "signatures.md",
                "layout.md", "layout.tsv", "order.md", "coverage.md", "kernel_verdicts.tsv")


def _ledger_rank(rel: str) -> tuple[int, str]:
    name = Path(rel).name
    for rank, prefix in enumerate(LEDGER_ORDER):
        if name.startswith(prefix):
            return rank, rel
    return len(LEDGER_ORDER), rel


def _doc_rank(rel: str) -> tuple[int, str]:
    if rel.startswith("docs/vtmb/npc-ai/"):
        return 0, rel
    if rel.startswith("docs/vtmb/"):
        return 1, rel
    return 2, rel


def _short(rel: str) -> str:
    for prefix in ("docs/vtmb/", "Source/ElysiumUE/"):
        if rel.startswith(prefix):
            return rel[len(prefix):]
    return rel


def _ledger_lines(index: Index, hits: dict[int, list[int]], literals: list[str],
                  rows: int) -> list[str]:
    """The ledger: the rows OF the query, a table at a time, then where it is only mentioned."""
    rowed: dict[str, list[int]] = defaultdict(list)
    mentions: Counter = Counter()
    for fid, lines in hits.items():
        rel = index.files[fid][0]
        for number in lines:
            if _is_row(index, rel, number, literals):
                rowed[rel].append(number)
            else:
                mentions[rel] += 1
    out = [f"   ledger (npc-kernel tables and overlays): {sum(map(len, rowed.values()))} row(s) in "
           f"{len(rowed)} table(s), {sum(mentions.values())} mention(s)"]
    left: Counter = Counter()
    shown = 0
    for rel in sorted(rowed, key=_ledger_rank):
        # Two rows of a table say what it says; a table of call edges has hundreds.
        take = max(0, min(2, rows - shown))
        for number in rowed[rel][:take]:
            out.append(f"     {Path(rel).name}:{number}  {_row(index, rel, number, literals[0])}")
            shown += 1
        if len(rowed[rel]) > take:
            left[rel] = len(rowed[rel]) - take
    if left:
        out.append("     more rows in: " + _more(left))
    if mentions:
        out.append("     mentioned in: " + _more(mentions))
    return out


def _doc_lines(index: Index, hits: dict[int, list[int]], literals: list[str], rows: int) -> list[str]:
    """The prose: the sections whose heading holds it first, then the sections that mention it."""
    named, mentioned = [], []
    for fid, lines in hits.items():
        rel = index.files[fid][0]
        heads = {line for line, _, _ in index.heads.get(fid, [])}
        for number in lines:
            (named if number in heads else mentioned).append((_doc_rank(rel), number, fid))
    named.sort()
    mentioned.sort()
    out = [f"   docs (docs/vtmb, docs/contracts): {len(named) + len(mentioned)} line(s) in "
           f"{len(hits)} file(s)"]
    shown, per_file = [], Counter()
    for entry in named + mentioned:
        if len(shown) >= rows:
            break
        if per_file[entry[2]] < (3 if entry in named else 2):
            shown.append(entry)
            per_file[entry[2]] += 1
    for _, number, fid in shown:
        rel = index.files[fid][0]
        head = index.heading_at(fid, number)
        if head and head[0] == number:
            out.append(f"     {_short(rel)}:{number}  [heading] {_clip(head[2], 120, literals[0])}")
        else:
            label = f"  § {_clip(head[2], 60)}" if head else ""
            out.append(f"     {_short(rel)}:{number}{label}  -- "
                       f"{_clip(index.line(rel, number), 110, literals[0])}")
    rest = Counter(index.files[fid][0] for entry in named + mentioned if entry not in shown
                   for fid in (entry[2],))
    if rest:
        out.append(f"     ... {sum(rest.values())} more line(s): " + _more(rest))
    return out


def _port_lines(index: Index, hits: dict[int, list[int]], made: dict[int, list[int]],
                literals: list[str], rows: int) -> list[str]:
    """The port: where the runtime already cites it -- its source before its tests, because a test
    that cites an address is evidence of coverage, not of the port body."""
    listed = sorted(((index.files[fid][0], lines) for fid, lines in hits.items()),
                    key=lambda one: ("/Tests/" in one[0], one[0]))
    out = [f"   port (Source/): {sum(len(lines) for _, lines in listed)} line(s) in "
           f"{len(listed)} file(s)"
           + (f"; plus {sum(map(len, made.values()))} in {len(made)} generated table(s), "
              f"which are not citations" if made else "")]
    shown = 0
    rest: Counter = Counter()
    for rel, lines in listed:
        take = max(0, min(2, rows - shown))
        for number in lines[:take]:
            symbol = _symbol(index, rel, number)
            out.append(f"     {_short(rel)}:{number}" + (f"  in {symbol}" if symbol else "")
                       + f"  -- {_clip(index.line(rel, number), 100, literals[0])}")
            shown += 1
        if len(lines) > take:
            rest[rel] = len(lines) - take
    if rest:
        out.append(f"     ... {sum(rest.values())} more line(s): " + _more(rest))
    return out


def render(index: Index, wanted: Plan, rows: int = DEFAULT_ROWS) -> str:
    """One query's answer."""
    out = [f"== {wanted.text}"]
    out += [f"   {line}" for line in wanted.heading]
    out += [f"   note: {line}" for line in wanted.notes]
    if not wanted.needles:
        out.append("   nothing to search for: a query is an address, a name, a field, an offset, "
                   "`slot N`, or text of three characters or more")
        return "\n".join(out)

    hits: dict[int, set[int]] = defaultdict(set)
    cut = False
    for needle, how in wanted.needles:
        found, _, over = index.find(needle, how)
        for fid, lines in found.items():
            hits[fid].update(lines)
        cut = cut or over
    for rel, line in wanted.pinned:
        if rel in index.file_ids:
            hits[index.file_ids[rel]].add(line)
    if not hits:
        out.append("   no mention in docs/vtmb, the ledger, the port or the specs")
        return "\n".join(out)
    literals = [needle.lower() for needle, _ in wanted.needles]

    ledger = _group(hits, index, ("ledger",))
    if ledger:
        out += _ledger_lines(index, ledger, literals, rows)
    docs = _group(hits, index, ("doc",))
    if docs:
        out += _doc_lines(index, docs, literals, rows)
    port, made = _group(hits, index, ("port",)), _group(hits, index, ("generated",))
    if port or made:
        out += _port_lines(index, port, made, literals, rows)
    # The specs only say how many: they are the stories' own text.
    specs = _group(hits, index, ("spec",))
    if specs:
        by_story: Counter = Counter()
        for fid, lines in specs.items():
            by_story["/".join(index.files[fid][0].split("/")[2:3]) or "docs/specs"] += len(lines)
        out.append(f"   specs (docs/specs): {sum(map(len, specs.values()))} line(s) in "
                   f"{len(specs)} file(s): "
                   + ", ".join(f"{name} x{n}" for name, n in by_story.most_common(6)))
    if cut:
        out.append(f"   (counted to {MAX_HITS:,} hits for a search term and stopped: it is too "
                   f"common to list; ask for a longer name)")
    return "\n".join(out)


def where(queries: str | list[str], rows: int = DEFAULT_ROWS) -> str:
    """The `where` answer for one query or several, each in its own block."""
    index = ensure_index()
    texts = [queries] if isinstance(queries, str) else list(queries)
    if not texts or not any(one.strip() for one in texts):
        return "where needs an address, a name, a field or `slot N`"
    return "\n\n".join(render(index, plan(index, one), rows) for one in texts if one.strip())


# ---------------------------------------------------------------------------
# The standing verbs.

def _sections(index: Index, wanted: Plan) -> tuple[list[tuple[int, int]], bool]:
    """The sections that answer a query: [(file id, heading line)], and whether a heading names it.

    A heading that holds the needle is the best answer a doc can give -- the section is ABOUT it.
    When none does, the sections its mentions sit under are what there is.
    """
    hits: dict[int, set[int]] = defaultdict(set)
    for needle, how in wanted.needles:
        for fid, lines in index.find(needle, how)[0].items():
            hits[fid].update(lines)
    named: list[tuple[tuple[int, str], int, int]] = []
    inside: dict[tuple[int, int], tuple[int, str]] = {}
    for fid, lines in hits.items():
        rel, kind = index.files[fid]
        if not rel.endswith(".md") or kind not in ("doc", "ledger", "spec"):
            continue
        rank = (_doc_rank(rel)[0] if kind == "doc" else 3 if kind == "spec" else 4, rel)
        heads = {line for line, _, _ in index.heads.get(fid, [])}
        for number in lines:
            head = index.heading_at(fid, number)
            if head is None:
                continue
            if number in heads:
                # The deepest heading first: `### 0x1028a380 SelectSchedule` is about it; the
                # `## ... family Select19` that holds it is about the family.
                named.append(((rank[0], -head[1], rank[1]), fid, number))
            elif kind == "doc":
                inside.setdefault((fid, head[0]), rank)
    if named:
        return [(fid, line) for _, fid, line in sorted(set(named))], True
    return [key for key, _ in sorted(inside.items(), key=lambda item: (item[1], item[0]))], False


def section(text: str, lines: int = 60, pick: int = 1, start: int | None = None) -> str:
    """The section of the docs that is about `text`, without reading the file around it."""
    index = ensure_index()
    wanted = plan(index, text)
    if not wanted.needles:
        return f"section needs an address, a name, a field or `slot N`; got {text!r}"
    found, named = _sections(index, wanted)
    if not found:
        return f"no docs section mentions {text}; `where {text}` says where else it is spoken of"
    out = [f"== {text}: " + (f"{len(found)} section(s) whose heading names it" if named else
                             f"no heading names it; the {len(found)} section(s) its mentions sit in")]
    for number, (fid, line) in enumerate(found[:12], 1):
        rel = index.files[fid][0]
        head = next(one for one in index.heads[fid] if one[0] == line)
        out.append(f"   [{number}] {rel}:{line}  {_clip(head[2], 90)}  "
                   f"({index.section_end(fid, head) - line + 1} lines)")
    if len(found) > 12:
        out.append(f"   ... {len(found) - 12} more")
    if not 1 <= pick <= len(found):
        return "\n".join(out + [f"pick={pick} is outside 1-{len(found)}"])
    fid, line = found[pick - 1]
    rel = index.files[fid][0]
    head = next(one for one in index.heads[fid] if one[0] == line)
    last = index.section_end(fid, head)
    first = max(line, start or line)
    limit = min(last, first + max(1, lines) - 1)
    out.append(f"\n--- [{pick}] {rel}:{first}-{limit} of {line}-{last}")
    out += [index.line(rel, number) for number in range(first, limit + 1)]
    if limit < last:
        out.append(f"--- {last - limit} more line(s): `section {text} --pick {pick} "
                   f"--from {limit + 1}` continues, --lines sets the page")
    return "\n".join(out)


def _tsv(path: Path) -> tuple[list[str], list[list[str]]]:
    """A tab-separated table: its header, and its rows. Lines starting `#` are comments; cells are
    split on tabs and never unquoted, because the evidence column holds quotation marks."""
    header: list[str] | None = None
    rows: list[list[str]] = []
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        cells = line.split("\t")
        if header is None:
            header = cells
        else:
            rows.append(cells + [""] * (len(header) - len(cells)))
    return header or [], rows


def verdict(queries: list[str], band: str | None = None, which: str | None = None,
            target: str | None = None, count: bool = False, full: bool = False,
            rows: int = 40) -> str:
    """`kernel_verdicts.tsv`: the porting verdict of an address, or of a band, or the standing."""
    path = REPO / VERDICTS_TSV
    if not path.is_file():
        return f"no verdict overlay at {VERDICTS_TSV}"
    header, table = _tsv(path)
    column = {name: number for number, name in enumerate(header)}
    index = ensure_index()
    wanted: set[str] = set()
    for text in queries:
        planned = plan(index, text)
        if planned.addresses:
            wanted.update(planned.addresses)
        else:
            return f"verdict takes addresses or Class::Method names it can resolve; got {text!r}"
    selected = [row for row in table
                if (not wanted or row[column["address"]].lower() in wanted)
                and (band is None or row[column["band"]] == band)
                and (which is None or row[column["verdict"]] == which)
                and (target is None or target.lower() in row[column["target"]].lower())]
    out = []
    if count or not (wanted or band or which or target):
        grid: Counter = Counter((row[column["band"]], row[column["verdict"]]) for row in selected)
        bands = sorted({b for b, _ in grid}, key=lambda one: [int(n) for n in re.findall(r"\d+", one)])
        out.append(f"{len(selected)} verdict row(s) of {len(table)}")
        out.append("band\t" + "\t".join(VERDICT_WORDS) + "\ttotal")
        for one in bands:
            cells = [grid[(one, word)] for word in VERDICT_WORDS]
            out.append(f"{one}\t" + "\t".join(map(str, cells)) + f"\t{sum(cells)}")
        return "\n".join(out)
    for row in selected[:rows]:
        names = index.addr_names.get(row[column["address"]].lower(), [])
        evidence = row[column["evidence"]]
        out.append(f"0x{row[column['address']]}  {row[column['verdict']]:10} band {row[column['band']]:6}"
                   f" {names[0] if names else '?'}\n    target: {row[column['target']]}\n"
                   f"    evidence: {evidence if full else _clip(evidence, 220)}")
    if len(selected) > rows:
        out.append(f"... {len(selected) - rows} more of {len(selected)}; --limit shows more, "
                   f"--count tabulates")
    return "\n".join(out) or "no verdict row matches"


def cited(queries: list[str], table: str | None = None, column: str = "address",
          where_: list[str] | None = None, show_all: bool = False, rows: int = 40) -> str:
    """Which addresses the port cites, and where; or which of a table's addresses it never does."""
    index = ensure_index()
    port = {fid for fid, (_, kind) in enumerate(index.files) if kind == "port"}

    def citations(addr: str) -> list[tuple[int, int]]:
        return [(fid, line) for fid, line in index.port_cites.get(addr, []) if fid in port]

    addresses: list[tuple[str, str]] = []
    for text in queries:
        planned = plan(index, text)
        if not planned.addresses:
            return f"cited takes addresses or Class::Method names it can resolve; got {text!r}"
        addresses += [(addr, (index.addr_names.get(addr) or ["?"])[0]) for addr in planned.addresses]
    if table:
        path = resolve_table(table)
        header, body = _tsv(path)
        if column not in header:
            return f"{path.name} has no column {column!r}; its columns are {', '.join(header)}"
        keep = _filters(header, where_ or [])
        for cells in body:
            if all(test(cells) for test in keep):
                match = re.search(r"[0-9a-f]{8}", cells[header.index(column)].lower())
                if match:
                    addresses.append((match.group(0), (index.addr_names.get(match.group(0)) or ["?"])[0]))
    if not addresses:
        return "cited needs addresses, names, or --table"
    addresses = list(dict.fromkeys(addresses))
    out, uncited = [], 0
    for addr, name in addresses:
        found = citations(addr)
        uncited += not found
        if table and found and not show_all:
            continue
        if len(out) >= rows * 2:
            continue
        if found:
            by_file: dict[int, list[int]] = defaultdict(list)
            for fid, line in found:
                by_file[fid].append(line)
            spots = [f"{Path(index.files[fid][0]).name}:{','.join(map(str, sorted(set(lines))[:4]))}"
                     for fid, lines in sorted(by_file.items())[:4]]
            out.append(f"0x{addr}  {name}  cited {len(found)}x in {len(by_file)} file(s): "
                       + "; ".join(spots))
        else:
            out.append(f"0x{addr}  {name}  NOT CITED by the port")
    out.append(f"{len(addresses) - uncited} of {len(addresses)} address(es) cited by the port "
               f"(.h/.cpp/.inl under Source/, generated tables excluded)"
               + ("" if not table or show_all else "; only the uncited are listed, --all lists every one"))
    return "\n".join(out)


def resolve_table(name: str) -> Path:
    """A `.tsv` by path, or by file name under `docs/` and `research/tooling/`."""
    direct = Path(name)
    for candidate in (direct, REPO / name):
        if candidate.is_file():
            return candidate
    wanted = name.replace("\\", "/").lower()
    # A bare file name matches any directory's; a name with a directory in it only that one's.
    found = [path for sub in ("docs", "research/tooling") for path in (REPO / sub).rglob("*.tsv")
             if (path.as_posix().lower().endswith("/" + wanted) if "/" in wanted
                 else path.name.lower() == wanted)]
    if len(found) == 1:
        return found[0]
    if found:
        raise SystemExit(f"{name} is ambiguous: " + ", ".join(
            path.relative_to(REPO).as_posix() for path in sorted(found)))
    like = sorted({path.name for sub in ("docs", "research/tooling") for path in
                   (REPO / sub).rglob("*.tsv") if Path(name).stem.lower() in path.name.lower()})
    raise SystemExit(f"no table named {name}" + (f"; did you mean {', '.join(like[:8])}" if like else ""))


FILTER = re.compile(r"^(\w+)\s*(!=|!~|>=|<=|=|~|>|<)\s*(.*)$")


def _filters(header: list[str], clauses: list[str]):
    """`col=value`, `col!=value`, `col~substring`, `col!~substring`, `col>=number`... as tests."""
    tests = []
    for clause in clauses:
        match = FILTER.match(clause)
        if not match or match.group(1) not in header:
            raise SystemExit(f"{clause!r} is not a filter over {', '.join(header)}; write col=value, "
                             f"col!=value, col~text, col!~text or col>=number")
        number, operator, value = header.index(match.group(1)), match.group(2), match.group(3)

        def test(cells, number=number, operator=operator, value=value):
            cell = cells[number]
            if operator == "=":
                return cell.lower() == value.lower()
            if operator == "!=":
                return cell.lower() != value.lower()
            if operator == "~":
                return value.lower() in cell.lower()
            if operator == "!~":
                return value.lower() not in cell.lower()
            try:
                left, right = float(int(cell, 0) if cell.lower().startswith("0x") else cell), float(value)
            except ValueError:
                return False
            return {">": left > right, "<": left < right, ">=": left >= right,
                    "<=": left <= right}[operator]

        tests.append(test)
    return tests


def rows_of(table: str, clauses: list[str], columns: str | None = None, count_by: str | None = None,
            limit: int = 40, full: bool = False) -> str:
    """A tab-separated table, filtered, counted or projected -- the `csv.DictReader` and `Counter`
    a one-off script wrote each time."""
    path = resolve_table(table)
    header, body = _tsv(path)
    keep = _filters(header, clauses)
    selected = [cells for cells in body if all(test(cells) for test in keep)]
    name = path.relative_to(REPO).as_posix() if REPO in path.parents else str(path)
    if count_by:
        keys = [one.strip() for one in count_by.split(",")]
        missing = [one for one in keys if one not in header]
        if missing:
            raise SystemExit(f"{path.name} has no column {missing[0]!r}; its columns are "
                             f"{', '.join(header)}")
        grid = Counter(tuple(cells[header.index(one)] for one in keys) for cells in selected)
        out = [f"# {name}: {len(selected)} of {len(body)} rows, by {'/'.join(keys)}"]
        out += [f"{n}\t" + "\t".join(key) for key, n in grid.most_common(limit)]
        if len(grid) > limit:
            out.append(f"... {len(grid) - limit} more group(s); --limit shows more")
        return "\n".join(out)
    shown = [one.strip() for one in columns.split(",")] if columns else header
    missing = [one for one in shown if one not in header]
    if missing:
        raise SystemExit(f"{path.name} has no column {missing[0]!r}; its columns are "
                         f"{', '.join(header)}")
    picks = [header.index(one) for one in shown]
    out = [f"# {name}: {len(selected)} of {len(body)} rows", "\t".join(shown)]
    for cells in selected[:limit]:
        out.append("\t".join(cells[number] if full else _clip(cells[number], 80) for number in picks))
    if len(selected) > limit:
        out.append(f"... {len(selected) - limit} more row(s); --limit shows more, --count-by "
                   f"COLUMN counts them")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# The command line, shared by the five `research` entry points beside this file.

def run(verb: str, argv: list[str]) -> int:
    load_local_environment()
    # The docs are UTF-8 and so is what is quoted from them; a console that is not must not turn
    # an em dash in a heading into a traceback.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(prog=verb, description=VERBS[verb][0])
    VERBS[verb][1](parser)
    arguments = parser.parse_args(argv)
    started = time.perf_counter()
    if verb == "where":
        if arguments.rebuild or arguments.stats:
            index = ensure_index(rebuild=arguments.rebuild)
            print(f"index {index.key}: {len(index.files)} files, {len(index.line_starts):,} lines, "
                  f"{len(index.text) // 1024:,} KB, {len(index.addr_names):,} named addresses, "
                  f"{len(index.port_cites):,} cited by the port; {time.perf_counter() - started:.2f} s")
            if not arguments.queries:
                return 0
        print(where(arguments.queries, arguments.limit))
    elif verb == "section":
        print(section(arguments.query, arguments.lines, arguments.pick, arguments.start))
    elif verb == "verdict":
        print(verdict(arguments.queries, arguments.band, arguments.verdict, arguments.target,
                      arguments.count, arguments.full, arguments.limit))
    elif verb == "cited":
        print(cited(arguments.queries, arguments.table, arguments.column, arguments.where,
                    arguments.all, arguments.limit))
    else:
        print(rows_of(arguments.table, arguments.filters, arguments.cols, arguments.count_by,
                      arguments.limit, arguments.full))
    return 0


def _where_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("queries", nargs="*", help="0x1028a380, CAI_BaseNPC::SelectSchedule, "
                        "m_scriptState, +0x5cc0, 'slot 442'")
    parser.add_argument("--limit", type=int, default=DEFAULT_ROWS, help="lines per section")
    parser.add_argument("--rebuild", action="store_true", help="rebuild the index first")
    parser.add_argument("--stats", action="store_true", help="say what the index holds")


def _section_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("query", help="an address, a name, a field")
    parser.add_argument("--lines", type=int, default=60, help="page length (default 60)")
    parser.add_argument("--pick", type=int, default=1, help="which listed section to print")
    parser.add_argument("--from", dest="start", type=int, default=None,
                        help="first line of the page, to continue one")


def _verdict_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("queries", nargs="*", help="addresses or names; none = the whole table")
    parser.add_argument("--band", default=None, help="a layer band, e.g. 5-9")
    parser.add_argument("--verdict", default=None, choices=VERDICT_WORDS)
    parser.add_argument("--target", default=None, help="the target contains this")
    parser.add_argument("--count", action="store_true", help="verdicts by band")
    parser.add_argument("--full", action="store_true", help="the evidence column whole")
    parser.add_argument("--limit", type=int, default=40)


def _cited_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("queries", nargs="*", help="addresses or names")
    parser.add_argument("--table", default=None, help="a .tsv whose addresses to check")
    parser.add_argument("--column", default="address", help="its address column")
    parser.add_argument("--where", action="append", default=None, metavar="COL=VALUE",
                        help="filter the table's rows (col=v, col!=v, col~text, col>=n)")
    parser.add_argument("--all", action="store_true", help="list the cited ones too")
    parser.add_argument("--limit", type=int, default=40)


def _rows_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("table", help="a .tsv, by path or file name (unported.tsv)")
    parser.add_argument("filters", nargs="*", help="col=value  col!=value  col~text  col!~text  "
                        "col>=number")
    parser.add_argument("--cols", default=None, help="the columns to show, comma-separated")
    parser.add_argument("--count-by", default=None, help="count the rows by these columns")
    parser.add_argument("--limit", type=int, default=40)
    parser.add_argument("--full", action="store_true", help="cells uncut")


VERBS = {
    "where": ("where the project already speaks about an address, name, field or slot",
              _where_arguments),
    "section": ("the docs section that is about an address or name", _section_arguments),
    "verdict": ("the porting verdict of an address, or of a band", _verdict_arguments),
    "cited": ("which addresses the port cites, or never does", _cited_arguments),
    "rows": ("filter, count or project a .tsv table", _rows_arguments),
}


if __name__ == "__main__":
    raise SystemExit(run(sys.argv[1], sys.argv[2:]))
