#!/usr/bin/env python3
"""`uv run elysium research cited <address|name ...>`
`uv run elysium research cited --table unported.tsv --column address [--where verdict=rule]`

Which retail addresses the port cites, and where; or which of a table's addresses it never does.
The citation map is built once with the index, so a 2,500-row table is one pass, not 2,500 searches.
Generated tables (`// Generated by`) name every slot body by address and are not citations.
"""

import sys

from addr_index import run

if __name__ == "__main__":
    raise SystemExit(run("cited", sys.argv[1:]))
