"""Isolated corpus-index GLB format aggregation.

One scene-less unit per export root that lists every member of the merged install, states which
unit owns it or why nothing does, and carries the whole cross-unit reference graph.
"""

from elysium_pipeline.formats.corpus_index_glb.decode import (
    CorpusIndexDecodeError,
    CorpusIndexModel,
    build_root,
    decode_corpus_index,
    summary,
    write_inverse,
)
from elysium_pipeline.formats.corpus_index_glb.model import (
    ASSET_ID,
    CHECK_NAMES,
    CORPUS_INDEX_EXTENSION,
    COVERAGE_SECTIONS,
    DEPENDENCY_ROLE,
    DISPOSITIONS,
    EXCLUDED_LOOSE_PREFIXES,
    EXCLUDED_TREES,
    KIND,
    KIND_TITLE,
    OUTPUT_NAME,
    RESIDUE_CATEGORIES,
    SCHEMA_VERSION,
    CorpusIndexModelError,
    Member,
    MemberSource,
    Reference,
    Unit,
    identity,
    kind_of,
    output_relative_path,
)
from elysium_pipeline.formats.corpus_index_glb.walk import (
    SEAM_CLAIMS,
    InstallWalk,
    InstallWalkError,
    SeamClaim,
    build_index,
    collect,
)

__all__ = [
    "ASSET_ID",
    "CHECK_NAMES",
    "CORPUS_INDEX_EXTENSION",
    "COVERAGE_SECTIONS",
    "DEPENDENCY_ROLE",
    "DISPOSITIONS",
    "EXCLUDED_LOOSE_PREFIXES",
    "EXCLUDED_TREES",
    "KIND",
    "KIND_TITLE",
    "OUTPUT_NAME",
    "RESIDUE_CATEGORIES",
    "SCHEMA_VERSION",
    "SEAM_CLAIMS",
    "CorpusIndexDecodeError",
    "CorpusIndexModel",
    "CorpusIndexModelError",
    "InstallWalk",
    "InstallWalkError",
    "Member",
    "MemberSource",
    "Reference",
    "SeamClaim",
    "Unit",
    "build_index",
    "build_root",
    "collect",
    "decode_corpus_index",
    "identity",
    "kind_of",
    "output_relative_path",
    "summary",
    "write_inverse",
]
