// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 220 generated slot rows of `FElysiumEntity` (CBaseEntity): 220 it introduces and 0 it overrides
// with a body of its own.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// This file is included INSIDE `class FElysiumEntity` (`ElysiumEntity.h`). It is not
// a header: it has no include guard and declares nothing of its own. One declaration per
// slot, in slot order, with the retail declaration in the comment and the port's lowered
// signature in the code.
//
// Each slot is declared by the port class of the retail class that introduces it, with that
// class's own body, and overridden by every port class whose retail table holds another
// body there (story 0019/5 step 6). The stub names the retail class that owns its body.
//
// A body lands on one of these in 29c/29d/29e. Until then the definition in
// `ElysiumEntitySlots.cpp` tallies `elysium.stubs` with the retail address — except
// where the verdict overlay records that retail's whole body is one literal, which the
// generator emits, or that the body is written by hand in the substrate, in which case no
// definition is generated at all and the linker is what checks the claim.

	// slot 0 0x10027450 (walked) `void SetRefEHandle(const CBaseHandle&)`
	//   layer 0, story 29c
	virtual void SetRefEHandle(const FElysiumEntityHandle&);
	// slot 1 0x10027470 (sdk) `CBaseHandle& GetRefEHandle() const`
	//   returns `CBaseHandle&`
	//   layer 0, story 29c
	virtual void* GetRefEHandle() const;
	// slot 2 0x10027610 (walked) `ICollideable* GetCollideable()`
	//   returns `ICollideable*`
	//   layer 0, story 29c
	virtual void* GetCollideable();
	// slot 3 0x10027630 (walked) `IServerNetworkable* GetNetworkable()`
	//   returns `IServerNetworkable*`
	//   layer 0, story 29c
	virtual void* GetNetworkable();
	// slot 4 0x10027650 (walked) `CBaseEntity* GetBaseEntity()`
	//   layer 0, story 29c
	virtual FElysiumEntity* GetBaseEntity();
	// slot 5 0x1009def0 (walked) `void* ~CBaseEntity(unsigned int)`
	//   retail `~CBaseEntity` is a lifetime slot; declared by index
	//   returns `void*`
	virtual void* Slot5(uint32);
	// slot 6 0x100b11d0 (sdk) `void SetCheckUntouch(bool)`
	//   layer 0, story 29c
	virtual void SetCheckUntouch(bool);
	// slot 7 0x100b12e0 (walked) `void SetSentLastFrame(bool)`
	//   layer 0, story 29c
	virtual void SetSentLastFrame(bool);
	// slot 8 0x100b17f0 (sdk) `int GetModelIndex() const`
	//   layer 0, story 29c
	virtual int32 GetModelIndex() const;
	// slot 9 0x100b1690 (sdk) `string_t GetModelName() const`
	//   layer 0, story 29c
	virtual FName GetModelName() const;
	// slot 10 0x100b1750 (sdk) `void SetModelIndex(int)`
	//   layer 0, story 29c
	virtual void SetModelIndex(int32);
	// slot 11 0x1009ac80 (walked) `void DebugSetEntityName(const char*)`
	//   layer 0, story 29c
	virtual void DebugSetEntityName(const TCHAR*);
	// slot 12 0x1009ad70 (walked) `const char* DebugGetEntityName()`
	//   layer 0, story 29c
	virtual const TCHAR* DebugGetEntityName();
	// slot 13 0x1009ae10 (walked) `void DebugSetClassName(const char*)`
	//   layer 0, story 29c
	virtual void DebugSetClassName(const TCHAR*);
	// slot 14 0x1009af00 (walked) `const char* DebugGetClassName()`
	//   layer 0, story 29c
	virtual const TCHAR* DebugGetClassName();
	// slot 16 0x1009b030 (walked) `Vector GetAttackExtents()`
	//   layer 0, story 29c
	virtual FVector GetAttackExtents();
	// slot 17 0x1009b380 (walked) `void TraceMessage(const char*, int) const`
	//   layer 1, story 29c
	virtual void TraceMessage(const TCHAR*, int32) const;
	// slot 18 0x1009b2c0 (walked) `void TraceMessage(const char*, int)`
	//   layer 1, story 29c
	virtual void TraceMessage(const TCHAR*, int32);
	// slot 19 0x1009b5a0 (walked) `void TraceMessageBare(const char*) const`
	//   layer 1, story 29c
	virtual void TraceMessageBare(const TCHAR*) const;
	// slot 20 0x1009b500 (walked) `void TraceMessageBare(const char*)`
	//   layer 1, story 29c
	virtual void TraceMessageBare(const TCHAR*);
	// slot 21 0x10026530 (walked) `void vfunc21(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot21(FElysiumEntity*);
	// slot 22 0x10026550 (walked) `void vfunc22(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot22(FElysiumEntity*);
	// slot 23 0x10026570 (walked) `void vfunc23(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot23(FElysiumEntity*);
	// slot 24 0x10026590 (walked) `void OnVictimHitByMe(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void OnVictimHitByMe(FElysiumEntity*);
	// slot 25 0x100265b0 (walked) `void vfunc25(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot25(FElysiumEntity*);
	// slot 26 0x100265d0 (walked) `void vfunc26(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot26(FElysiumEntity*);
	// slot 27 0x100265f0 (walked) `void vfunc27(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot27(FElysiumEntity*);
	// slot 28 0x10026610 (walked) `float GetStealthVisionScalar()`
	//   layer 0, story 29c
	virtual float GetStealthVisionScalar();
	// slot 29 0x10026630 (walked) `float GetStealthVisionCone()`
	//   layer 0, story 29c
	virtual float GetStealthVisionCone();
	// slot 30 0x10026650 (walked) `float GetStealthHearingDist()`
	//   layer 0, story 29c
	virtual float GetStealthHearingDist();
	// slot 31 0x1009c980 (walked) `void Dump(int)`
	//   layer 0, story 29c
	virtual void Dump(int32);
	// slot 32 0x10026670 (walked) `bool CanBeInteractiveUsed(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool CanBeInteractiveUsed(FElysiumEntity*);
	// slot 33 0x10026690 (walked) `int vfunc33()`
	//   layer 0, story 29c
	virtual int32 Slot33();
	// slot 34 0x100266b0 (walked) `int GetHighlightMaterial(CBaseEntity*)`
	//   layer 0, story 29c
	virtual int32 GetHighlightMaterial(FElysiumEntity*);
	// slot 35 0x100266d0 (walked) `int vfunc35(CBaseEntity*)`
	//   layer 0, story 29c
	virtual int32 Slot35(FElysiumEntity*);
	// slot 36 0x100266f0 (walked) `const char* vfunc36()`
	//   layer 0, story 29c
	virtual const TCHAR* Slot36();
	// slot 37 0x10026710 (walked) `float vfunc37()`
	//   layer 0, story 29c
	virtual float Slot37();
	// slot 38 0x10026730 (walked) `CBaseEntity* vfunc38(CBaseEntity*)`
	//   layer 0, story 29c
	virtual FElysiumEntity* Slot38(FElysiumEntity*);
	// slot 39 0x100a4fe0 (walked) `void OnUseBegin(CBaseEntity*)`
	//   layer 8, story 29c
	virtual void OnUseBegin(FElysiumEntity*);
	// slot 40 0x10026750 (walked) `void vfunc40(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot40(FElysiumEntity*);
	// slot 41 0x10026770 (walked) `void vfunc41(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot41(FElysiumEntity*);
	// slot 42 0x100a5030 (walked) `void OnUseEnd(CBaseEntity*)`
	//   layer 8, story 29c
	virtual void OnUseEnd(FElysiumEntity*);
	// slot 43 0x10026790 (walked) `void vfunc43(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot43(FElysiumEntity*);
	// slot 44 0x100267b0 (walked) `bool vfunc44(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool Slot44(FElysiumEntity*);
	// slot 45 0x100a5070 (walked) `bool PassesFindEntityFOVTrace(CBaseEntity*, Vector, Vector,
	// int)`
	//   layer 0, story 29c
	virtual bool PassesFindEntityFOVTrace(FElysiumEntity*, FVector, FVector, int32);
	// slot 46 0x100267d0 (walked) `void vfunc46()`
	//   layer 0, story 29c
	virtual void Slot46();
	// slot 47 0x100267f0 (walked) `void vfunc47()`
	//   layer 0, story 29c
	virtual void Slot47();
	// slot 48 0x10026810 (walked) `float vfunc48()`
	//   layer 0, story 29c
	virtual float Slot48();
	// slot 49 0x10026830 (walked) `float vfunc49()`
	//   layer 0, story 29c
	virtual float Slot49();
	// slot 54 0x10026910 (walked) `bool vfunc54(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool Slot54(FElysiumEntity*);
	// slot 55 0x10026930 (walked) `void vfunc55(CBaseEntity*, Vector, Vector)`
	//   layer 0, story 29c
	virtual void Slot55(FElysiumEntity*, FVector, FVector);
	// slot 56 0x10026950 (walked) `void vfunc56(CBaseEntity*, Vector, Vector, const char*)`
	//   layer 0, story 29c
	virtual void Slot56(FElysiumEntity*, FVector, FVector, const TCHAR*);
	// slot 57 0x10026970 (walked) `void vfunc57(CBaseEntity*, Vector, Vector)`
	//   layer 0, story 29c
	virtual void Slot57(FElysiumEntity*, FVector, FVector);
	// slot 58 0x10026990 (walked) `void vfunc58(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot58(FElysiumEntity*);
	// slot 59 0x100269b0 (walked) `void vfunc59(CSceneEntity*)`
	//   takes `CSceneEntity*`
	//   layer 0, story 29c
	virtual void Slot59(void*);
	// slot 60 0x100269d0 (walked) `void vfunc60(CSceneEntity*)`
	//   takes `CSceneEntity*`
	//   layer 0, story 29c
	virtual void Slot60(void*);
	// slot 61 0x100269f0 (walked) `void vfunc61(CSceneEntity*)`
	//   takes `CSceneEntity*`
	//   layer 0, story 29c
	virtual void Slot61(void*);
	// slot 62 0x100b2be0 (walked) `void SetOrigin(const Vector&)`
	//   layer 0, story 29c
	virtual void SetOrigin(const FVector&);
	// slot 63 0x10026a10 (walked) `void SetOrigin(float, float, float)`
	//   layer 1, story 29c
	virtual void SetOrigin(float, float, float);
	// slot 64 0x100b2d00 (walked) `void SetAngles(const QAngle&)`
	//   layer 0, story 29c
	virtual void SetAngles(const FRotator&);
	// slot 65 0x10026a50 (walked) `void SetAngles(float, float, float)`
	//   layer 1, story 29c
	virtual void SetAngles(float, float, float);
	// slot 66 0x1009d2a0 (walked) `void Hide()`
	//   layer 0, story 29c
	virtual void Hide();
	// slot 67 0x1009d380 (walked) `void Unhide()`
	//   layer 0, story 29c
	virtual void Unhide();
	// slot 68 0x10026a90 (walked) `bool ShouldIgnoreCollision(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool ShouldIgnoreCollision(FElysiumEntity*);
	// slot 69 0x10026ab0 (walked) `bool NavIgnoreCollision(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool NavIgnoreCollision(FElysiumEntity*);
	// slot 70 0x1009d820 (walked) `bool IsMonster()`
	//   layer 0, story 29c
	virtual bool IsMonster();
	// slot 71 0x1009d460 (walked) `void PrecacheSoundTable()`
	//   layer 0, story 29c
	virtual void PrecacheSoundTable();
	// slot 72 0x10026ad0 (walked) `bool vfunc72(int)`
	//   layer 0, story 29c
	virtual bool Slot72(int32);
	// slot 73 0x10026af0 (walked) `bool CausesImpactDamage(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool CausesImpactDamage(FElysiumEntity*);
	// slot 74 0x10026b10 (walked) `bool ReceivesImpactDamage(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool ReceivesImpactDamage(FElysiumEntity*);
	// slot 75 0x100a8400 (walked) `void TakeDamageFromCollision(int, gamevcollisionevent_t*)`
	//   takes `gamevcollisionevent_t*`
	//   layer 0, story 29c
	virtual void TakeDamageFromCollision(int32, void*);
	// slot 76 0x10026b30 (walked) `void DrawDebugStatOverlays()`
	//   layer 0, story 29c
	virtual void DrawDebugStatOverlays();
	// slot 79 0x1009e100 (walked) `datamap_t* GetPredDescMap()`
	//   returns `datamap_t*`
	//   layer 0, story 29c
	virtual void* GetPredDescMap();
	// slot 80 0x1009a660 (walked) `ServerClass* GetServerClass()`
	//   returns `ServerClass*`
	//   layer 0, story 29c
	virtual void* GetServerClass();
	// slot 81 0x1009a680 (walked) `int YouForgotToImplementOrDeclareServerClass()`
	//   layer 0, story 29c
	virtual int32 YouForgotToImplementOrDeclareServerClass();
	// slot 82 0x100a2290 (walked) `datamap_t* GetDataDescMap()`
	//   returns `datamap_t*`
	virtual void* GetDataDescMap();
	// slot 83 0x100b4ef0 (walked) `int GetEFlags()`
	//   layer 0, story 29c
	virtual int32 GetEFlags();
	// slot 84 0x100b4f10 (walked) `void SetEFlags(int)`
	//   layer 0, story 29c
	virtual void SetEFlags(int32);
	// slot 85 0x100b3d10 (walked) `edict_t* GetEdict()`
	//   returns `edict_t*`
	//   layer 0, story 29c
	virtual void* GetEdict();
	// slot 86 0x100ab020 (walked) `bool ShouldTransmit(int, const edict_t*, const void*, int, int)`
	//   takes `const edict_t*`
	//   takes `const void*`
	//   layer 0, story 29c
	virtual bool ShouldTransmit(int32, void*, void*, int32, int32);
	// slot 87 0x100ab280 (walked) `void SetTransmit(CCheckTransmitInfo*)`
	//   takes `CCheckTransmitInfo*`
	//   layer 0, story 29c
	virtual void SetTransmit(void*);
	// slot 88 0x10026b50 (walked) `bool vfunc88()`
	//   layer 2, story 29c
	virtual bool Slot88();
	// slot 89 0x10026b70 (walked) `void vfunc89()`
	//   layer 1, story 29c
	virtual void Slot89();
	// slot 90 0x100aa840 (sdk) `bool IsTransparent() const`
	//   layer 0, story 29c
	virtual bool IsTransparent() const;
	// slot 91 0x100b4de0 (walked) `bool ShouldCollide(int, int) const`
	//   layer 0, story 29c
	virtual bool ShouldCollide(int32, int32) const;
	// slot 92 0x10027570 (sdk) `SolidType_t GetSolid() const`
	//   returns `SolidType_t`
	//   layer 0, story 29c
	virtual int32 GetSolid() const;
	// slot 93 0x100aad70 (sdk) `void SetMoveType(MoveType_t, MoveCollide_t)`
	//   takes `MoveType_t`
	//   takes `MoveCollide_t`
	//   layer 0, story 29c
	virtual void SetMoveType(int32, int32);
	// slot 94 0x100aac30 (sdk) `MoveType_t GetMoveType() const`
	//   returns `MoveType_t`
	//   layer 0, story 29c
	virtual int32 GetMoveType() const;
	// slot 95 0x100aacd0 (sdk) `MoveCollide_t GetMoveCollide() const`
	//   returns `MoveCollide_t`
	//   layer 0, story 29c
	virtual int32 GetMoveCollide() const;
	// slot 96 0x100a9ba0 (walked) `edict_t* GetAimEntEdict()`
	//   returns `edict_t*`
	//   layer 0, story 29c
	virtual void* GetAimEntEdict();
	// slot 98 0x100b1ac0 (sdk) `void CalcAbsolutePosition()`
	//   layer 0, story 29c
	virtual void CalcAbsolutePosition();
	// slot 99 0x100aa900 (sdk) `bool TestCollision(Ray_t&, unsignedint, trace_t&)`
	//   takes `Ray_t&`
	//   takes `unsignedint`
	//   takes `trace_t&`
	//   layer 0, story 29c
	virtual bool TestCollision(void*, int32, void*);
	// slot 100 0x100aa9a0 (sdk) `bool TestHitboxes(Ray_t&, unsignedint, trace_t&)`
	//   takes `Ray_t&`
	//   takes `unsignedint`
	//   takes `trace_t&`
	//   layer 0, story 29c
	virtual bool TestHitboxes(void*, int32, void*);
	// slot 101 0x100ab430 (walked) `void ComputeWorldSpaceSurroundingBox(Vector*, Vector*)`
	//   layer 0, story 29c
	virtual void ComputeWorldSpaceSurroundingBox(FVector*, FVector*);
	// slot 102 0x100ab450 (walked) `void Physics_TraceEntity(CBaseEntity*, const Vector&, const
	// Vector&, unsigned int, trace_t*)`
	//   takes `trace_t*`
	//   layer 3, story 29c
	virtual void Physics_TraceEntity(FElysiumEntity*, const FVector&, const FVector&, uint32, void*);
	// slot 104 0x10026b90 (sdk) `void Precache()`
	//   layer 0, story 29c
	virtual void Precache();
	// slot 105 0x100ad460 (sdk) `void SetModel(char*)`
	//   layer 0, story 29c
	virtual void SetModel(TCHAR*);
	// slot 106 0x1009e120 (sdk) `void PostConstructor(char*)`
	//   layer 0, story 29c
	virtual void PostConstructor(TCHAR*);
	// slot 107 0x1009e280 (sdk) `void ParseMapData(CEntityMapData*)`
	//   takes `CEntityMapData*`
	//   layer 0, story 29c
	virtual void ParseMapData(void*);
	// slot 110 0x1009e430 (walked) `bool KeyValue(const char*, const char*)`
	//   layer 9, story 29c
	virtual bool KeyValue(const TCHAR*, const TCHAR*);
	// slot 111 0x10026bb0 (walked) `void MemberSync()`
	//   layer 0, story 29c
	virtual void MemberSync();
	// slot 112 0x10026bd0 (walked) `void vfunc112(int, int)`
	//   layer 0, story 29c
	virtual void Slot112(int32, int32);
	// slot 114 0x100ad780 (walked) `void PostClientMessagesSent()`
	//   layer 0, story 29c
	virtual void PostClientMessagesSent();
	// slot 115 0x10026bf0 (walked) `void vfunc115(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot115(FElysiumEntity*);
	// slot 116 0x10027490 (walked) `bool IsMarkedForDeletion()`
	//   layer 0, story 29c
	virtual bool IsMarkedForDeletion();
	// slot 120 0x100ace00 (sdk) `void GetInputDispatchEffectPosition(char*, Vector&, QAngle&)`
	//   layer 0, story 29c
	virtual void GetInputDispatchEffectPosition(TCHAR*, FVector&, FRotator&);
	// slot 121 0x100acab0 (sdk) `bool ReadKeyField(char*, variant_t*)`
	//   takes `variant_t*`
	//   layer 0, story 29c
	virtual bool ReadKeyField(TCHAR*, void*);
	// slot 122 0x1009f120 (sdk) `void SetClassname(char*)`
	//   layer 0, story 29c
	virtual void SetClassname(TCHAR*);
	// slot 123 0x100a0130 (sdk) `void DrawDebugGeometryOverlays()`
	//   layer 0, story 29c
	virtual void DrawDebugGeometryOverlays();
	// slot 124 0x100a02b0 (sdk) `int DrawDebugTextOverlays()`
	//   layer 0, story 29c
	virtual int32 DrawDebugTextOverlays();
	// slot 125 0x1009faf0 (walked) `void DrawMuzzleOverlay()`
	//   layer 0, story 29c
	virtual void DrawMuzzleOverlay();
	// slot 126 0x100a9f70 (sdk) `int Save(ISave&)`
	//   takes `ISave&`
	//   layer 0, story 29c
	virtual int32 Save(void*);
	// slot 127 0x100aa140 (walked) `int Restore(IRestore&)`
	//   takes `IRestore&`
	//   layer 0, story 29c
	virtual int32 Restore(void*);
	// slot 128 0x100aa680 (sdk) `bool ShouldSavePhysics()`
	//   layer 0, story 29c
	virtual bool ShouldSavePhysics();
	// slot 129 0x100aa4e0 (walked) `void OnSave()`
	//   layer 0, story 29c
	virtual void OnSave();
	// slot 130 0x100aa5a0 (walked) `void OnRestore(bool)`
	//   layer 1, story 29c
	virtual void OnRestore(bool);
	// slot 131 0x10026c10 (walked) `int RequiredEdictIndex()`
	//   layer 0, story 29c
	virtual int32 RequiredEdictIndex();
	// slot 132 0x10026c30 (walked) `void vfunc132()`
	//   layer 0, story 29c
	virtual void Slot132();
	// slot 133 0x10026c50 (walked) `void MoveDone()`
	//   layer 0, story 29c
	virtual void MoveDone();
	// slot 135 0x10026d10 (walked) `float vfunc135(float)`
	//   layer 0, story 29c
	virtual float Slot135(float);
	// slot 136 0x10026d30 (walked) `bool vfunc136()`
	//   layer 0, story 29c
	virtual bool Slot136();
	// slot 137 0x10026d50 (walked) `CBaseAnimating* GetBaseAnimating()`
	//   layer 0, story 29c
	virtual FElysiumEntity* GetBaseAnimating();
	// slot 138 0x100a7a80 (sdk) `Class_T Classify()`
	//   returns `Class_T`
	//   layer 0, story 29c
	virtual int32 Classify();
	// slot 139 0x10026d70 (walked) `void DeathNotice(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void DeathNotice(FElysiumEntity*);
	// slot 140 0x100a7aa0 (sdk) `bool PassesDamageFilter(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 0, story 29c
	virtual bool PassesDamageFilter(void*);
	// slot 141 0x100a7de0 (walked) `void TraceAttack(const CTakeDamageInfo&, const Vector&,
	// trace_t*)`
	//   takes `const CTakeDamageInfo&`
	//   takes `trace_t*`
	//   layer 0, story 29c
	virtual void TraceAttack(void*, const FVector&, void*);
	// slot 142 0x100a0e40 (sdk) `int OnTakeDamage(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 0, story 29c
	virtual int32 OnTakeDamage(void*);
	// slot 143 0x100a0d20 (sdk) `int TakeHealth(float, int)`
	//   layer 0, story 29c
	virtual int32 TakeHealth(float, int32);
	// slot 144 0x100a1a70 (sdk) `void Event_Killed(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 0, story 29c
	virtual void Event_Killed(void*);
	// slot 145 0x10026d90 (walked) `int BloodColor()`
	//   layer 0, story 29c
	virtual int32 BloodColor();
	// slot 146 0x10268ef0 (walked) `void TraceBleed(CVDmg_t*, const Vector&, trace_t*)`
	//   takes `CVDmg_t*`
	//   takes `trace_t*`
	//   layer 4, story 29c
	virtual void TraceBleed(void*, const FVector&, void*);
	// slot 147 0x10026db0 (walked) `bool IsTriggered(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool IsTriggered(FElysiumEntity*);
	// slot 148 0x10026dd0 (walked) `void AddPoints(int, bool)`
	//   layer 0, story 29c
	virtual void AddPoints(int32, bool);
	// slot 149 0x10026df0 (walked) `void AddPointsToTeam(int, bool)`
	//   layer 0, story 29c
	virtual void AddPointsToTeam(int32, bool);
	// slot 150 0x10026e10 (walked) `bool AddPlayerItem(CBaseCombatWeapon*)`
	//   layer 0, story 29c
	virtual bool AddPlayerItem(FElysiumEntity*);
	// slot 151 0x10026e30 (walked) `bool RemovePlayerItem(CBaseCombatWeapon*)`
	//   layer 0, story 29c
	virtual bool RemovePlayerItem(FElysiumEntity*);
	// slot 152 0x10026e50 (walked) `float GetDelay()`
	//   layer 0, story 29c
	virtual float GetDelay();
	// slot 153 0x10026e70 (walked) `bool IsMoving()`
	//   layer 0, story 29c
	virtual bool IsMoving();
	// slot 154 0x100b4ea0 (walked) `int DamageDecal(int, int)`
	//   layer 0, story 29c
	virtual int32 DamageDecal(int32, int32);
	// slot 155 0x100a6c50 (walked) `void DecalTrace(trace_t*, int, bool, int, CBaseEntity*, int,
	// bool)`
	//   takes `trace_t*`
	//   layer 0, story 29c
	virtual void DecalTrace(void*, int32, bool, int32, FElysiumEntity*, int32, bool);
	// slot 156 0x10026ee0 (unsettled) `void vfunc156(int)`
	//   layer 0, story 29c
	virtual void Slot156(int32);
	// slot 157 0x10026f00 (walked) `bool OnControls(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool OnControls(FElysiumEntity*);
	// slot 158 0x100b4dc0 (walked) `bool IsAlive()`
	//   layer 0, story 29c
	virtual bool IsAlive();
	// slot 160 0x100a1b40 (sdk) `bool HasTarget(string_t)`
	//   layer 0, story 29c
	virtual bool HasTarget(FName);
	// slot 161 0x100a1c30 (walked) `bool HasLinkedDoor(string_t)`
	//   layer 0, story 29c
	virtual bool HasLinkedDoor(FName);
	// slot 162 0x10026f60 (walked) `bool IsPlayer()`
	//   layer 0, story 29c
	virtual bool IsPlayer();
	// slot 163 0x100a9800 (sdk) `bool IsViewable()`
	//   layer 0, story 29c
	virtual bool IsViewable();
	// slot 164 0x100b50a0 (walked) `bool IsStandable()`
	//   layer 1, story 29c
	virtual bool IsStandable();
	// slot 166 0x10026f80 (walked) `bool CanStandOn(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool CanStandOn(FElysiumEntity*);
	// slot 167 0x10027000 (walked) `CBaseEntity* GetEnemy() const`
	//   layer 0, story 29c
	virtual FElysiumEntity* GetEnemy() const;
	// slot 168 0x10027020 (walked) `CBaseEntity* GetEnemy()`
	//   layer 1, story 29c
	virtual FElysiumEntity* GetEnemy();
	// slot 169 0x10027040 (walked) `void ViewPunch(const QAngle&)`
	//   layer 0, story 29c
	virtual void ViewPunch(const FRotator&);
	// slot 170 0x10027060 (walked) `void VelocityPunch(const Vector&)`
	//   layer 0, story 29c
	virtual void VelocityPunch(const FVector&);
	// slot 171 0x100ad550 (walked) `void SetMovedir()`
	//   layer 0, story 29c
	virtual void SetMovedir();
	// slot 172 0x100a1d20 (sdk) `CBaseEntity* GetNextTarget()`
	//   layer 0, story 29c
	virtual FElysiumEntity* GetNextTarget();
	// slot 174 0x100a49d0 (sdk) `void StartTouch(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void StartTouch(FElysiumEntity*);
	// slot 175 0x100a4af0 (sdk) `void Touch(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Touch(FElysiumEntity*);
	// slot 176 0x100a4c20 (sdk) `void EndTouch(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void EndTouch(FElysiumEntity*);
	// slot 177 0x10027080 (sdk) `void StartBlocked(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void StartBlocked(FElysiumEntity*);
	// slot 178 0x100a4d40 (sdk) `void Blocked(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Blocked(FElysiumEntity*);
	// slot 179 0x100270a0 (walked) `void EndBlocked()`
	//   layer 0, story 29c
	virtual void EndBlocked();
	// slot 180 0x100a47d0 (sdk) `void UpdateOnRemove()`
	//   layer 0, story 29c
	virtual void UpdateOnRemove();
	// slot 181 0x100ada20 (sdk) `void Teleport(Vector*, QAngle*, Vector*)`
	//   layer 0, story 29c
	virtual void Teleport(FVector*, FRotator*, FVector*);
	// slot 182 0x100ad8f0 (unsettled) `void vfunc182(int, int, int, int)`
	//   layer 0, story 29c
	virtual void Slot182(int32, int32, int32, int32);
	// slot 183 0x100ad910 (walked) `void NotifySystemEvent(CBaseEntity*, notify_system_event_t,
	// const notify_system_event_params_t&)`
	//   takes `notify_system_event_t`
	//   takes `const notify_system_event_params_t&`
	//   layer 0, story 29c
	virtual void NotifySystemEvent(FElysiumEntity*, int32, void*);
	// slot 184 0x10267260 (walked) `void MakeTracer(const Vector&, const trace_t&, int)`
	//   takes `const trace_t&`
	//   layer 4, story 29c
	virtual void MakeTracer(const FVector&, void*, int32);
	// slot 185 0x10268900 (walked) `void FireBullets(const FireBulletsInfo_t&)`
	//   takes `const FireBulletsInfo_t&`
	//   layer 16, story 29d
	virtual void FireBullets(void*);
	// slot 186 0x100270c0 (walked) `bool vfunc186()`
	//   layer 0, story 29c
	virtual bool Slot186();
	// slot 187 0x100270e0 (walked) `CBaseEntity* Respawn()`
	//   layer 0, story 29c
	virtual FElysiumEntity* Respawn();
	// slot 188 0x10027100 (walked) `bool IsLockedByMaster()`
	//   layer 0, story 29c
	virtual bool IsLockedByMaster();
	// slot 189 0x100ad850 (sdk) `int GetDamageType() const`
	//   layer 0, story 29c
	virtual int32 GetDamageType() const;
	// slot 190 0x10027120 (walked) `float GetDamage()`
	//   layer 0, story 29c
	virtual float GetDamage();
	// slot 191 0x10027140 (walked) `void SetDamage(float)`
	//   layer 0, story 29c
	virtual void SetDamage(float);
	// slot 192 0x10027160 (walked) `Vector WorldSpaceCenter()`
	//   layer 8, story 29c
	virtual FVector WorldSpaceCenter();
	// slot 194 0x100b4bc0 (walked) `const QAngle& EyeAngles()`
	//   layer 1, story 29c
	virtual const FVector& EyeAngles();
	// slot 195 0x100b4be0 (walked) `const QAngle& LocalEyeAngles()`
	//   layer 1, story 29c
	virtual const FVector& LocalEyeAngles();
	// slot 196 0x100b4c00 (walked) `Vector EarPosition()`
	//   layer 2, story 29c
	virtual FVector EarPosition();
	// slot 197 0x1009f2c0 (walked) `Vector BodyTarget(const Vector&, bool, bool)`
	//   layer 0, story 29c
	virtual FVector BodyTarget(const FVector&, bool, bool);
	// slot 198 0x100274b0 (walked) `const Vector& GetLocalVelocity()`
	//   returns `const Vector&`
	//   layer 0, story 29c
	virtual void* GetLocalVelocity();
	// slot 199 0x100ad1a0 (sdk) `void GetVelocity(Vector*, AngularImpulse*)`
	//   takes `AngularImpulse*`
	//   layer 0, story 29c
	virtual void GetVelocity(FVector*, void*);
	// slot 200 0x100ad6e0 (walked) `int Illumination()`
	//   layer 0, story 29c
	virtual int32 Illumination();
	// slot 201 0x100a6fa0 (walked) `bool FVisible(CBaseEntity*, int, CBaseEntity**, int)`
	//   layer 0, story 29c
	virtual bool FVisible(FElysiumEntity*, int32, FElysiumEntity*, int32);
	// slot 203 0x100a1360 (walked) `float GetAttackDamageScale()`
	//   layer 0, story 29c
	virtual float GetAttackDamageScale();
	// slot 204 0x100a1470 (walked) `float GetReceivedDamageScale()`
	//   layer 0, story 29c
	virtual float GetReceivedDamageScale();
	// slot 205 0x10027330 (walked) `bool vfunc205()`
	//   layer 0, story 29c
	virtual bool Slot205();
	// slot 206 0x10027350 (unsettled) `bool vfunc206(int, int, int, int, int)`
	//   layer 0, story 29c
	virtual bool Slot206(int32, int32, int32, int32, int32);
	// slot 207 0x1003d3d0 (sdk) `bool IsCurrentlyTouching() const`
	//   layer 0, story 29c
	virtual bool IsCurrentlyTouching() const;
	// slot 208 0x100b1420 (sdk) `void SetGroundEntity(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void SetGroundEntity(FElysiumEntity*);
	// slot 209 0x100b1510 (walked) `CBaseEntity* GetGroundEntity()`
	//   layer 0, story 29c
	virtual FElysiumEntity* GetGroundEntity();
	// slot 210 0x10027370 (walked) `void GetGroundVelocityToApply(Vector&)`
	//   layer 0, story 29c
	virtual void GetGroundVelocityToApply(FVector&);
	// slot 211 0x100274d0 (sdk) `int GetSolidFlags() const`
	//   layer 0, story 29c
	virtual int32 GetSolidFlags() const;
	// slot 212 0x100b15f0 (sdk) `void SetModelName(string_t)`
	//   layer 0, story 29c
	virtual void SetModelName(FName);
	// slot 213 0x100b1890 (walked) `void SetSize(const Vector&)`
	//   layer 0, story 29c
	virtual void SetSize(const FVector&);
	// slot 214 0x100b1960 (walked) `const Vector& GetSize()`
	//   returns `const Vector&`
	//   layer 0, story 29c
	virtual void* GetSize();
	// slot 215 0x100b4c30 (walked) `const Vector& WorldSpaceCenter() const`
	//   returns `const Vector&`
	//   layer 8, story 29c
	virtual void* WorldSpaceCenter() const;
	// slot 216 0x100b2300 (sdk) `void SetAbsOrigin(Vector&)`
	//   layer 0, story 29c
	virtual void SetAbsOrigin(FVector&);
	// slot 217 0x100b31b0 (sdk) `Vector& GetAbsOrigin() const`
	//   layer 0, story 29c
	virtual const FVector& GetAbsOrigin() const;
	// slot 218 0x100b2510 (sdk) `void SetAbsAngles(QAngle&)`
	//   layer 0, story 29c
	virtual void SetAbsAngles(FRotator&);
	// slot 219 0x100b3280 (sdk) `QAngle& GetAbsAngles() const`
	//   layer 0, story 29c
	virtual const FVector& GetAbsAngles() const;
	// slot 220 0x100b3070 (walked) `const Vector& GetOrigin()`
	//   layer 0, story 29c
	virtual const FVector& GetOrigin();
	// slot 221 0x100b3110 (walked) `const QAngle& GetAngles()`
	//   layer 0, story 29c
	virtual const FVector& GetAngles();
	// slot 222 0x100a9eb0 (sdk) `Vector GetSoundEmissionOrigin() const`
	//   layer 0, story 29c
	virtual FVector GetSoundEmissionOrigin() const;
	// slot 223 0x100b5080 (walked) `bool CreateVPhysics()`
	//   layer 0, story 29c
	virtual bool CreateVPhysics();
	// slot 224 0x100273b0 (walked) `bool ForceVPhysicsCollide(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool ForceVPhysicsCollide(FElysiumEntity*);
	// slot 225 0x100b5040 (walked) `void VPhysicsDestroyObject()`
	//   layer 4, story 29c
	virtual void VPhysicsDestroyObject();
	// slot 226 0x100b4f30 (walked) `void VPhysicsUpdate(IPhysicsObject*)`
	//   takes `IPhysicsObject*`
	//   layer 1, story 29c
	virtual void VPhysicsUpdate(void*);
	// slot 227 0x100a1580 (sdk) `int VPhysicsTakeDamage(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 0, story 29c
	virtual int32 VPhysicsTakeDamage(void*);
	// slot 228 0x100a65a0 (sdk) `void VPhysicsShadowCollision(int, gamevcollisionevent_t*)`
	//   takes `gamevcollisionevent_t*`
	//   layer 0, story 29c
	virtual void VPhysicsShadowCollision(int32, void*);
	// slot 229 0x100273d0 (sdk) `void VPhysicsShadowUpdate(IPhysicsObject*)`
	//   takes `IPhysicsObject*`
	//   layer 0, story 29c
	virtual void VPhysicsShadowUpdate(void*);
	// slot 230 0x100a6640 (sdk) `void VPhysicsCollision(int, gamevcollisionevent_t*)`
	//   takes `gamevcollisionevent_t*`
	//   layer 0, story 29c
	virtual void VPhysicsCollision(int32, void*);
	// slot 231 0x100a6800 (sdk) `void VPhysicsFriction(IPhysicsObject*, float, int, int)`
	//   takes `IPhysicsObject*`
	//   layer 0, story 29c
	virtual void VPhysicsFriction(void*, float, int32, int32);
	// slot 232 0x100a69e0 (sdk) `void UpdatePhysicsShadowToCurrentPosition(float)`
	//   layer 0, story 29c
	virtual void UpdatePhysicsShadowToCurrentPosition(float);
	// slot 233 0x100a6ad0 (sdk) `int VPhysicsGetObjectList(IPhysicsObject**, int)`
	//   takes `IPhysicsObject**`
	//   layer 0, story 29c
	virtual int32 VPhysicsGetObjectList(void*, int32);
	// slot 234 0x10035780 (sdk) `void PhysicsPushEntity(Vector&, trace_t*)`
	//   takes `trace_t*`
	//   layer 0, story 29c
	virtual void PhysicsPushEntity(FVector&, void*);
	// slot 235 0x100273f0 (walked) `void OnPhysGunPickup(CBasePlayer*)`
	//   layer 0, story 29c
	virtual void OnPhysGunPickup(FElysiumEntity*);
	// slot 236 0x10027410 (walked) `void OnPhysGunDrop(CBasePlayer*, bool)`
	//   layer 0, story 29c
	virtual void OnPhysGunDrop(FElysiumEntity*, bool);
	// slot 237 0x1003e7a0 (sdk) `unsignedint PhysicsSolidMaskForEntity() const`
	//   returns `unsignedint`
	//   layer 0, story 29c
	virtual int32 PhysicsSolidMaskForEntity() const;
	// slot 238 0x10039ff0 (sdk) `void PerformCustomPhysics(Vector*, Vector*, QAngle*, QAngle*)`
	//   layer 0, story 29c
	virtual void PerformCustomPhysics(FVector*, FVector*, FRotator*, FRotator*);
	// slot 239 0x100389e0 (sdk) `CBaseEntity* PhysicsPushRotate(float)`
	//   layer 0, story 29c
	virtual FElysiumEntity* PhysicsPushRotate(float);
	// slot 240 0x10027430 (walked) `PyObject* vfunc240()`
	//   returns `PyObject*`
	//   layer 0, story 29c
	virtual void* Slot240();
