// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 22 generated slot rows of `FElysiumFlex` (CBaseFlex): 16 it introduces and 6 it overrides with a
// body of its own.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// This file is included INSIDE `class FElysiumFlex` (`ElysiumFlex.h`). It is not
// a header: it has no include guard and declares nothing of its own. One declaration per
// slot, in slot order, with the retail declaration in the comment and the port's lowered
// signature in the code.
//
// Each slot is declared by the port class of the retail class that introduces it, with that
// class's own body, and overridden by every port class whose retail table holds another
// body there (story 0019/5 step 6). The stub names the retail class that owns its body.
//
// A body lands on one of these in 29c/29d/29e. Until then the definition in
// `ElysiumFlexSlots.cpp` tallies `elysium.stubs` with the retail address — except
// where the verdict overlay records that retail's whole body is one literal, which the
// generator emits, or that the body is written by hand in the substrate, in which case no
// definition is generated at all and the linker is what checks the claim.

	// slot 5 0x100b5940 (walked) `void* ~CBaseEntity(unsigned int)`
	//   retail `~CBaseEntity` is a lifetime slot; declared by index
	//   returns `void*`
	void* Slot5(uint32) override;
	// slot 79 0x100b58b0 (walked) `datamap_t* GetPredDescMap()`
	//   returns `datamap_t*`
	void* GetPredDescMap() override;
	// slot 80 0x100b5520 (walked) `ServerClass* GetServerClass()`
	//   returns `ServerClass*`
	void* GetServerClass() override;
	// slot 81 0x100b5540 (walked) `int YouForgotToImplementOrDeclareServerClass()`
	int32 YouForgotToImplementOrDeclareServerClass() override;
	// slot 82 0x100b57b0 (walked) `datamap_t* GetDataDescMap()`
	//   returns `datamap_t*`
	void* GetDataDescMap() override;
	// slot 105 0x100b5ab0 (sdk) `void SetModel(char*)`
	//   layer 0, story 29c
	void SetModel(TCHAR*) override;
	// slot 276 0x100b5ce0 (sdk) `void Blink()`
	//   layer 0, story 29c
	virtual void Blink();
	// slot 277 0x100b5b00 (walked) `void SetViewtarget(const Vector&)`
	//   layer 0, story 29c
	virtual void SetViewtarget(const FVector&);
	// slot 278 0x100b5b40 (walked) `const Vector& GetViewtarget() const`
	//   returns `const Vector&`
	//   layer 0, story 29c
	virtual void* GetViewtarget() const;
	// slot 279 0x100b5ba0 (walked) `void SetFlexWeight(int, float)`
	//   layer 1, story 29c
	virtual void SetFlexWeight(int32, float);
	// slot 280 0x100b5b60 (walked) `void SetFlexWeight(char*, float)`
	//   layer 6, story 29c
	virtual void SetFlexWeight(TCHAR*, float);
	// slot 281 0x100b5c50 (walked) `float GetFlexWeight(int)`
	//   layer 1, story 29c
	virtual float GetFlexWeight(int32);
	// slot 282 0x100b5c20 (walked) `float GetFlexWeight(char*)`
	//   layer 6, story 29c
	virtual float GetFlexWeight(TCHAR*);
	// slot 283 0x100b6250 (walked) `void ProcessSceneEvents()`
	//   layer 9, story 29c
	virtual void ProcessSceneEvents();
	// slot 284 0x100b65b0 (walked) `void AddSceneExpressions()`
	virtual void AddSceneExpressions();
	// slot 285 0x100b5d80 (walked) `void ClearSceneEvents(CChoreoScene*)`
	//   takes `CChoreoScene*`
	//   layer 1, story 29c
	virtual void ClearSceneEvents(void*);
	// slot 286 0x100b5e60 (walked) `void AddSceneEvent(CChoreoScene*, CChoreoEvent*)`
	//   takes `CChoreoScene*`
	//   takes `CChoreoEvent*`
	//   layer 3, story 29c
	virtual void AddSceneEvent(void*, void*);
	// slot 287 0x100b6180 (walked) `void RemoveSceneEvent(CChoreoEvent*)`
	//   takes `CChoreoEvent*`
	//   layer 1, story 29c
	virtual void RemoveSceneEvent(void*);
	// slot 288 0x100b6cf0 (walked) `void AddFlexSetting(const char*, float, const
	// flexsettinghdr_t*, const flexsettinghdr_t*, bool)`
	//   takes `const flexsettinghdr_t*`
	//   takes `const flexsettinghdr_t*`
	//   layer 6, story 29c
	virtual void AddFlexSetting(const TCHAR*, float, void*, void*, bool);
	// slot 289 0x100b6960 (walked) `void AddFlexAnimation(CSceneEventInfo*)`
	//   takes `CSceneEventInfo*`
	//   layer 7, story 29c
	virtual void AddFlexAnimation(void*);
	// slot 290 0x100b70e0 (walked) `void ProcessSequenceSceneEvent(CSceneEventInfo*)`
	//   takes `CSceneEventInfo*`
	//   layer 2, story 29c
	virtual void ProcessSequenceSceneEvent(void*);
	// slot 291 0x100b7040 (walked) `void ProcessGestureSceneEvent(CSceneEventInfo*)`
	//   takes `CSceneEventInfo*`
	//   layer 3, story 29c
	virtual void ProcessGestureSceneEvent(void*);
