// Generated by `uv run elysium research gen_contents_signatures`. Do not hand-edit.
//
// A brush's SIGNATURE is its four answers to the retail trace masks, computed once at the
// seam. Nothing downstream of the bake tests a contents bit again: the payload stores a
// signature per body, the level's components wear the matching collision profile, and the
// NavMesh follows from the profile because Unreal calls a body navigation-relevant exactly
// when it blocks ECC_Pawn (UPrimitiveComponent::IsNavigationRelevant).
//
// The masks, with the retail sites that push them:
//   P  0x1400b      does this brush block the player       0x1011e560 CategorizePosition, 0x1011fb50, 0x10166cc0
//   N  0x2400b      does this brush block an NPC           0x10303b30 local-route ground retry, 0x102f3ccb CanFitAtNode, 0x102f3df1 CanFitAtNode
//   S  0x804091     does this brush block sight            0x102b4630 FVisible slot 201, 0x10301720 the cover search, 0x10302e50 the shoot node
//   p  0x2000       is this brush a pedestrian volume      0x102fbbaa InitLinks' second walk test, 0x102fe9f0 the alternate search's 5-10x edge cost
//
// Only the BRUSH bits of each mask are kept. The entity bits (MONSTER 0x2000000) select
// which entities a trace hits and are answered by those entities' own collision.

#pragma once

#include "CoreMinimal.h"

/** One answer per retail mask; a brush's signature is the OR of the answers it gives. */
enum class EElysiumContentsSignature : uint8
{
	None = 0,
	Player = 1 << 0,	// 0x1400b — does this brush block the player
	Npc = 1 << 1,	// 0x2400b — does this brush block an NPC
	Sight = 1 << 2,	// 0x804091 — does this brush block sight
	Pedestrian = 1 << 3,	// 0x2000 — is this brush a pedestrian volume
};
ENUM_CLASS_FLAGS(EElysiumContentsSignature)

namespace ElysiumContents
{
	/** The four masks, in signature order. */
	inline constexpr uint32 PlayerMask = 0x1400b;	// MASK_PLAYERSOLID_BRUSHONLY
	inline constexpr uint32 NpcMask = 0x2400b;	// MASK_NPCSOLID_BRUSHONLY
	inline constexpr uint32 SightMask = 0x804091;	// MASK_OPAQUE_AND_NPCS, brush bits
	inline constexpr uint32 PedestrianMask = 0x2000;	// VtMB

	/** Retail's standable normal, borrowed from the player movement layer: the AI's own
	    ground and stand tests read no surface normal, so a rasterised mesh has no retail
	    slope to reproduce and takes this one. */
	inline constexpr float StandableNormalZ = 0.7f;	// 0x104492d0

	/** Step height, Source units. Every NPC walks with the base; the graph was laid down
	    by CAI_TestHull, which steps 40, so a link can assert a rise no agent can climb. */
	inline constexpr float StepHeightUnits = 18.0f;	// 0x101a6b40
	inline constexpr float GraphBuildStepHeightUnits = 40.0f;	// 0x102d72b0

	/** The signature of a contents word. */
	inline EElysiumContentsSignature SignatureOf(uint32 Contents)
	{
		EElysiumContentsSignature Signature = EElysiumContentsSignature::None;
		if ((Contents & PlayerMask) != 0)
		{
			Signature |= EElysiumContentsSignature::Player;
		}
		if ((Contents & NpcMask) != 0)
		{
			Signature |= EElysiumContentsSignature::Npc;
		}
		if ((Contents & SightMask) != 0)
		{
			Signature |= EElysiumContentsSignature::Sight;
		}
		if ((Contents & PedestrianMask) != 0)
		{
			Signature |= EElysiumContentsSignature::Pedestrian;
		}
		return Signature;
	}

	/** `PNSp`, a dash where the answer is no — the spelling the census and the pins use. */
	inline FString Spell(EElysiumContentsSignature Signature)
	{
		const uint8 Bits = static_cast<uint8>(Signature);
		const TCHAR* const Letters = TEXT("PNSp");
		FString Out;
		for (int32 Index = 0; Index < 4; ++Index)
		{
			Out.AppendChar((Bits & (1 << Index)) != 0 ? Letters[Index] : TCHAR('-'));
		}
		return Out;
	}

	/** The collision profile a body of this signature wears. Only a profile NAME survives
	    a `.umap` save/load, so the level's static bodies carry these and never a set of
	    per-channel responses. */
	inline FName ProfileName(EElysiumContentsSignature Signature)
	{
		switch (static_cast<uint8>(Signature))
		{
		case 0: return FName(TEXT("ElysiumSig_None"));	// ---- — blocks nothing
		case 1: return FName(TEXT("ElysiumSig_P"));	// P--- — blocks the player
		case 2: return FName(TEXT("ElysiumSig_N"));	// -N-- — blocks an NPC
		case 3: return FName(TEXT("ElysiumSig_PN"));	// PN-- — blocks the player, an NPC
		case 4: return FName(TEXT("ElysiumSig_S"));	// --S- — blocks sight
		case 5: return FName(TEXT("ElysiumSig_PS"));	// P-S- — blocks the player, sight
		case 6: return FName(TEXT("ElysiumSig_NS"));	// -NS- — blocks an NPC, sight
		case 7: return FName(TEXT("ElysiumSig_PNS"));	// PNS- — blocks the player, an NPC, sight
		case 8: return FName(TEXT("ElysiumSig_p"));	// ---p — blocks nothing; a pedestrian volume
		case 9: return FName(TEXT("ElysiumSig_Pp"));	// P--p — blocks the player; a pedestrian volume
		case 10: return FName(TEXT("ElysiumSig_Np"));	// -N-p — blocks an NPC; a pedestrian volume
		case 11: return FName(TEXT("ElysiumSig_PNp"));	// PN-p — blocks the player, an NPC; a pedestrian volume
		case 12: return FName(TEXT("ElysiumSig_Sp"));	// --Sp — blocks sight; a pedestrian volume
		case 13: return FName(TEXT("ElysiumSig_PSp"));	// P-Sp — blocks the player, sight; a pedestrian volume
		case 14: return FName(TEXT("ElysiumSig_NSp"));	// -NSp — blocks an NPC, sight; a pedestrian volume
		case 15: return FName(TEXT("ElysiumSig_PNSp"));	// PNSp — blocks the player, an NPC, sight; a pedestrian volume
		default: return NAME_None;
		}
	}

	/** True when a body of this signature cuts the NavMesh: it blocks an NPC, and nothing
	    else in the engine's relevance test is ever set (see the Vehicle note above). */
	inline bool AffectsNavigation(EElysiumContentsSignature Signature)
	{
		return EnumHasAnyFlags(Signature, EElysiumContentsSignature::Npc);
	}
}
