// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 139 generated slot rows of `FElysiumCombatCharacter` (CBaseCombatCharacter): 106 it introduces
// and 33 it overrides with a body of its own.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// This file is included INSIDE `class FElysiumCombatCharacter` (`ElysiumPlayer.h`). It is not
// a header: it has no include guard and declares nothing of its own. One declaration per
// slot, in slot order, with the retail declaration in the comment and the port's lowered
// signature in the code.
//
// Each slot is declared by the port class of the retail class that introduces it, with that
// class's own body, and overridden by every port class whose retail table holds another
// body there (story 0019/5 step 6). The stub names the retail class that owns its body.
//
// A body lands on one of these in 29c/29d/29e. Until then the definition in
// `ElysiumCombatCharacterSlots.cpp` tallies `elysium.stubs` with the retail address — except
// where the verdict overlay records that retail's whole body is one literal, which the
// generator emits, or that the body is written by hand in the substrate, in which case no
// definition is generated at all and the linker is what checks the claim.

	// slot 5 0x103274a0 (walked) `void* ~CBaseEntity(unsigned int)`
	//   retail `~CBaseEntity` is a lifetime slot; declared by index
	//   returns `void*`
	void* Slot5(uint32) override;
	// slot 31 0x103222c0 (walked) `void Dump(int)`
	//   layer 12, story 29d
	void Dump(int32) override;
	// slot 34 0x10342800 (walked) `int GetHighlightMaterial(CBaseEntity*)`
	//   layer 2, story 29c
	int32 GetHighlightMaterial(FElysiumEntity*) override;
	// slot 68 0x10340650 (walked) `bool ShouldIgnoreCollision(CBaseEntity*)`
	//   layer 1, story 29c
	bool ShouldIgnoreCollision(FElysiumEntity*) override;
	// slot 72 0x1015dc20 (walked) `bool vfunc72(int)`
	//   layer 0, story 29c
	bool Slot72(int32) override;
	// slot 73 0x10340590 (walked) `bool CausesImpactDamage(CBaseEntity*)`
	//   layer 1, story 29c
	bool CausesImpactDamage(FElysiumEntity*) override;
	// slot 74 0x103404f0 (walked) `bool ReceivesImpactDamage(CBaseEntity*)`
	//   layer 0, story 29c
	bool ReceivesImpactDamage(FElysiumEntity*) override;
	// slot 79 0x10321670 (walked) `datamap_t* GetPredDescMap()`
	//   returns `datamap_t*`
	//   layer 0, story 29c
	void* GetPredDescMap() override;
	// slot 80 0x10321960 (walked) `ServerClass* GetServerClass()`
	//   returns `ServerClass*`
	//   layer 0, story 29c
	void* GetServerClass() override;
	// slot 81 0x10321980 (walked) `int YouForgotToImplementOrDeclareServerClass()`
	//   layer 0, story 29c
	int32 YouForgotToImplementOrDeclareServerClass() override;
	// slot 82 0x1031a5a0 (walked) `datamap_t* GetDataDescMap()`
	//   returns `datamap_t*`
	void* GetDataDescMap() override;
	// slot 86 0x103407b0 (walked) `bool ShouldTransmit(int, const edict_t*, const void*, int, int)`
	//   takes `const edict_t*`
	//   takes `const void*`
	//   layer 1, story 29c
	bool ShouldTransmit(int32, void*, void*, int32, int32) override;
	// slot 104 0x10340360 (sdk) `void Precache()`
	//   layer 12, story 29d
	void Precache() override;
	// slot 105 0x103409a0 (sdk) `void SetModel(char*)`
	//   layer 10, story 29d
	void SetModel(TCHAR*) override;
	// slot 106 0x10337d80 (sdk) `void PostConstructor(char*)`
	//   layer 14, story 29d
	void PostConstructor(TCHAR*) override;
	// slot 111 0x10337ca0 (walked) `void MemberSync()`
	//   layer 13, story 29d
	void MemberSync() override;
	// slot 124 0x1033e4a0 (sdk) `int DrawDebugTextOverlays()`
	//   layer 13, story 29d
	int32 DrawDebugTextOverlays() override;
	// slot 125 0x1033e7e0 (walked) `void DrawMuzzleOverlay()`
	//   layer 4, story 29c
	void DrawMuzzleOverlay() override;
	// slot 126 0x10348980 (sdk) `int Save(ISave&)`
	//   takes `ISave&`
	//   layer 14, story 29d
	int32 Save(void*) override;
	// slot 127 0x10348890 (walked) `int Restore(IRestore&)`
	//   takes `IRestore&`
	//   layer 8, story 29c
	int32 Restore(void*) override;
	// slot 130 0x10323b60 (walked) `void OnRestore(bool)`
	//   layer 11, story 29d
	void OnRestore(bool) override;
	// slot 142 0x1032ef60 (sdk) `int OnTakeDamage(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 23, story 29e
	int32 OnTakeDamage(void*) override;
	// slot 143 0x1032ebc0 (sdk) `int TakeHealth(float, int)`
	//   layer 1, story 29c
	int32 TakeHealth(float, int32) override;
	// slot 144 0x1032b9b0 (sdk) `void Event_Killed(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 15, story 29d
	void Event_Killed(void*) override;
	// slot 145 0x1014fa10 (walked) `int BloodColor()`
	//   layer 0, story 29c
	int32 BloodColor() override;
	// slot 180 0x10327790 (sdk) `void UpdateOnRemove()`
	//   layer 5, story 29c
	void UpdateOnRemove() override;
	// slot 228 0x10334a50 (sdk) `void VPhysicsShadowCollision(int, gamevcollisionevent_t*)`
	//   takes `gamevcollisionevent_t*`
	//   layer 1, story 29c
	void VPhysicsShadowCollision(int32, void*) override;
	// slot 240 0x1014f8b0 (walked) `PyObject* vfunc240()`
	//   returns `PyObject*`
	//   layer 0, story 29c
	void* Slot240() override;
	// slot 244 0x103408e0 (walked) `const char* GetSkeletonModelName()`
	//   layer 12, story 29d
	const TCHAR* GetSkeletonModelName() override;
	// slot 252 0x103251c0 (walked) `int SelectWeightedSequenceForStat(Activity, int, int)`
	//   layer 11, story 29d
	int32 SelectWeightedSequenceForStat(int32, int32, int32) override;
	// slot 253 0x10325440 (walked) `int SelectHeaviestSequenceForStat(Activity, int, int)`
	//   layer 11, story 29d
	int32 SelectHeaviestSequenceForStat(int32, int32, int32) override;
	// slot 254 0x10325300 (walked) `int SelectSameSequenceForStat(Activity, int, int)`
	//   layer 11, story 29d
	int32 SelectSameSequenceForStat(int32, int32, int32) override;
	// slot 284 0x10105f30 (walked) `void AddSceneExpressions()`
	//   layer 8, story 29c
	void AddSceneExpressions() override;
	// slot 292 0x103229d0 (walked) `void DamageFlinch(const CTakeDamageInfo&, const Vector&,
	// trace_t*)`
	//   takes `const CTakeDamageInfo&`
	//   takes `trace_t*`
	//   layer 7, story 29c
	virtual void DamageFlinch(void*, const FVector&, void*);
	// slot 293 0x1014f6f0 (walked) `CBaseEntity* GetFollowerBoss()`
	//   layer 0, story 29c
	virtual FElysiumEntity* GetFollowerBoss();
	// slot 295 0x103417b0 (walked) `bool CanTalk(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool CanTalk(FElysiumEntity*);
	// slot 296 0x10348ba0 (walked) `bool vfunc296(int)`
	//   layer 0, story 29c
	virtual bool Slot296(int32);
	// slot 297 0x10332ef0 (walked) `void AdjustDialogReaction(CBaseEntity*, int, const char*)`
	//   layer 15, story 29d
	virtual void AdjustDialogReaction(FElysiumEntity*, int32, const TCHAR*);
	// slot 298 0x10323c20 (walked) `int GetMaxInvenSlotsPerSection(int)`
	//   layer 0, story 29c
	virtual int32 GetMaxInvenSlotsPerSection(int32);
	// slot 299 0x10330d00 (walked) `void CreateDamageEffects(const CTakeDamageInfo&, bool*)`
	//   takes `const CTakeDamageInfo&`
	//   takes `bool*`
	//   layer 20, story 29e
	virtual void CreateDamageEffects(void*, void*);
	// slot 300 0x1032c580 (walked) `void Event_TookLife(CBaseCombatCharacter*, bool, bool)`
	//   layer 5, story 29c
	virtual void Event_TookLife(FElysiumEntity*, bool, bool);
	// slot 301 0x1032c0e0 (walked) `void CreateCorpse(const Vector&, const CTakeDamageInfo&)`
	//   takes `const CTakeDamageInfo&`
	//   layer 14, story 29d
	virtual void CreateCorpse(const FVector&, void*);
	// slot 302 0x10335f60 (walked) `bool Inventory_ShouldAllow_Autopickup(CBaseCombatWeapon*,
	// bool)`
	//   layer 0, story 29c
	virtual bool Inventory_ShouldAllow_Autopickup(FElysiumEntity*, bool);
	// slot 303 0x10336000 (walked) `bool Inventory_ShouldAllow_AutopickupAmmo(CBaseCombatWeapon*)`
	//   layer 0, story 29c
	virtual bool Inventory_ShouldAllow_AutopickupAmmo(FElysiumEntity*);
	// slot 304 0x1033dde0 (walked) `void GiveBaseFightingItems()`
	//   layer 11, story 29d
	virtual void GiveBaseFightingItems();
	// slot 305 0x1033deb0 (walked) `void RemoveBaseFightingItems()`
	//   layer 11, story 29d
	virtual void RemoveBaseFightingItems();
	// slot 306 0x1033e370 (walked) `void LookAtEntity(CBaseEntity*, bool)`
	//   layer 5, story 29c
	virtual void LookAtEntity(FElysiumEntity*, bool);
	// slot 307 0x10336cd0 (walked) `bool HasUsableMeleeWeapon()`
	//   layer 2, story 29c
	virtual bool HasUsableMeleeWeapon();
	// slot 308 0x10336d70 (walked) `bool HasUsableRangedWeapon()`
	//   layer 1, story 29c
	virtual bool HasUsableRangedWeapon();
	// slot 309 0x10337080 (walked) `CBaseCombatWeapon* GetBestRangedWeapon()`
	//   layer 1, story 29c
	virtual FElysiumEntity* GetBestRangedWeapon();
	// slot 310 0x10324430 (sdk) `void SetActivity(Activity)`
	virtual void SetActivity(int32);
	// slot 311 0x103250d0 (walked) `void ForcePreTranslatedSequenceAndActivity(Activity, Activity,
	// int)`
	virtual void ForcePreTranslatedSequenceAndActivity(int32, int32, int32);
	// slot 313 0x10322b40 (walked) `void UpdatePresenceEffect()`
	//   layer 22, story 29e
	virtual void UpdatePresenceEffect();
	// slot 314 0x10054060 (walked) `void UpdatePoseParameters(float)`
	//   layer 2, story 29c
	virtual void UpdatePoseParameters(float);
	// slot 315 0x10346cd0 (walked) `void MeleeSwingUpdate()`
	//   layer 18, story 29d
	virtual void MeleeSwingUpdate();
	// slot 316 0x1014f710 (walked) `void vfunc316(CBaseCombatCharacter*, bool, bool)`
	//   layer 0, story 29c
	virtual void Slot316(FElysiumEntity*, bool, bool);
	// slot 317 0x1014f730 (unsettled) `bool vfunc317(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool Slot317(FElysiumEntity*);
	// slot 318 0x1014f750 (walked) `bool PlayerDefenderBlockReaction(CBaseCombatCharacter*,
	// melee_dice_roll_result*, CVDmg_t*)`
	//   takes `melee_dice_roll_result*`
	//   takes `CVDmg_t*`
	//   layer 0, story 29c
	virtual bool PlayerDefenderBlockReaction(FElysiumEntity*, void*, void*);
	// slot 319 0x1014f770 (walked) `bool PlayerAttackerBlockedReaction(CBaseCombatCharacter*,
	// melee_dice_roll_result*, CVDmg_t*)`
	//   takes `melee_dice_roll_result*`
	//   takes `CVDmg_t*`
	//   layer 0, story 29c
	virtual bool PlayerAttackerBlockedReaction(FElysiumEntity*, void*, void*);
	// slot 320 0x1014f790 (walked) `bool PlayerKnockbackReaction(CBaseCombatCharacter*, Activity)`
	//   layer 0, story 29c
	virtual bool PlayerKnockbackReaction(FElysiumEntity*, int32);
	// slot 321 0x1014f7b0 (walked) `bool vfunc321(CBaseCombatCharacter*)`
	//   layer 0, story 29c
	virtual bool Slot321(FElysiumEntity*);
	// slot 322 0x1014f7d0 (walked) `void vfunc322(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot322(FElysiumEntity*);
	// slot 323 0x10344dd0 (walked) `int vfunc323(const Vector&)`
	//   layer 1, story 29c
	virtual int32 Slot323(const FVector&);
	// slot 324 0x1014f7f0 (walked) `bool vfunc324()`
	//   layer 0, story 29c
	virtual bool Slot324();
	// slot 325 0x1014f810 (walked) `bool vfunc325()`
	//   layer 0, story 29c
	virtual bool Slot325();
	// slot 326 0x103482e0 (walked) `bool vfunc326(void*, CBaseCombatCharacter*)`
	//   takes `void*`
	//   layer 13, story 29d
	virtual bool Slot326(void*, FElysiumEntity*);
	// slot 327 0x10345460 (walked) `bool vfunc327()`
	//   layer 0, story 29c
	virtual bool Slot327();
	// slot 328 0x1014f830 (walked) `bool vfunc328()`
	//   layer 0, story 29c
	virtual bool Slot328();
	// slot 329 0x1014f850 (walked) `bool vfunc329()`
	//   layer 0, story 29c
	virtual bool Slot329();
	// slot 330 0x1014f870 (walked) `void vfunc330(float, const FireBulletsInfo_t*)`
	//   takes `const FireBulletsInfo_t*`
	//   layer 0, story 29c
	virtual void Slot330(float, void*);
	// slot 331 0x10347180 (walked) `bool ChooseMeleeAttackSequence(CBaseCombatWeapon*,
	// CBaseEntity*, Activity, int*)`
	//   takes `int*`
	//   layer 11, story 29d
	virtual bool ChooseMeleeAttackSequence(FElysiumEntity*, FElysiumEntity*, int32, void*);
	// slot 332 0x1014f890 (walked) `void vfunc332(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void Slot332(FElysiumEntity*);
	// slot 333 0x10325580 (walked) `void MaintainEyeDirection(float)`
	//   layer 0, story 29c
	virtual void MaintainEyeDirection(float);
	// slot 334 0x10330020 (walked) `bool vfunc334(int, int)`
	//   layer 9, story 29c
	virtual bool Slot334(int32, int32);
	// slot 335 0x103415f0 (walked) `void NotifyChangeSizeSmall()`
	//   layer 0, story 29c
	virtual void NotifyChangeSizeSmall();
	// slot 336 0x10341680 (walked) `void NotifyChangeSizeNormal()`
	//   layer 0, story 29c
	virtual void NotifyChangeSizeNormal();
	// slot 337 0x10341710 (walked) `int GetUsedHullBits()`
	//   layer 0, story 29c
	virtual int32 GetUsedHullBits();
	// slot 338 0x1033cc30 (unsettled) `void AddPreDisciplineEffect(int, int, int)`
	//   layer 0, story 29c
	virtual void AddPreDisciplineEffect(int32, int32, int32);
	// slot 339 0x1033cd70 (unsettled) `void AddDisciplineEffect(int, int, int)`
	//   layer 0, story 29c
	virtual void AddDisciplineEffect(int32, int32, int32);
	// slot 340 0x1033ccd0 (unsettled) `void RemovePreDisciplineEffects(int, int, int)`
	//   layer 0, story 29c
	virtual void RemovePreDisciplineEffects(int32, int32, int32);
	// slot 341 0x1033cef0 (walked) `void RemoveDisciplineEffects(int, int)`
	//   layer 20, story 29e
	virtual void RemoveDisciplineEffects(int32, int32);
	// slot 342 0x10339800 (walked) `bool CanBeFedUponBy(CBaseCombatCharacter*)`
	//   layer 14, story 29d
	virtual bool CanBeFedUponBy(FElysiumEntity*);
	// slot 343 0x10053e20 (walked) `void SetShakyHands(float, float, int)`
	//   layer 0, story 29c
	virtual void SetShakyHands(float, float, int32);
	// slot 344 0x10053fa0 (walked) `float GetShakyHandsIntensity()`
	//   layer 0, story 29c
	virtual float GetShakyHandsIntensity();
	// slot 345 0x1032fb80 (walked) `float SetPoseParameter(const char*, float, bool)`
	//   layer 1, story 29c
	virtual float SetPoseParameter(const TCHAR*, float, bool);
	// slot 346 0x1032fc50 (walked) `float SetPoseParameter(int, float, bool)`
	//   layer 5, story 29c
	virtual float SetPoseParameter(int32, float, bool);
	// slot 347 0x10107120 (walked) `bool GetExpressionEventParams(int, char*, float*, float*,
	// float*, float*)`
	//   takes `float*`
	//   takes `float*`
	//   takes `float*`
	//   takes `float*`
	//   layer 0, story 29c
	virtual bool GetExpressionEventParams(int32, TCHAR*, void*, void*, void*, void*);
	// slot 348 0x1032fe60 (walked) `int HealthToPercent()`
	//   layer 11, story 29d
	virtual int32 HealthToPercent();
	// slot 349 0x103412b0 (walked) `void InputBarterBegin(inputdata_t&)`
	//   takes `inputdata_t&`
	//   layer 14, story 29d
	virtual void InputBarterBegin(void*);
	// slot 350 0x10341450 (walked) `void InputBarterEnd(inputdata_t&)`
	//   takes `inputdata_t&`
	//   layer 10, story 29d
	virtual void InputBarterEnd(void*);
	// slot 354 0x1014f8d0 (walked) `void vfunc354()`
	virtual void Slot354();
	// slot 355 0x1014f8f0 (walked) `void vfunc355()`
	virtual void Slot355();
	// slot 356 0x1033b500 (walked) `void PrayerBegin()`
	//   layer 1, story 29c
	virtual void PrayerBegin();
	// slot 357 0x1033b5f0 (walked) `void vfunc357()`
	//   layer 14, story 29d
	virtual void Slot357();
	// slot 358 0x1033b890 (walked) `void PrayerEnd()`
	//   layer 1, story 29c
	virtual void PrayerEnd();
	// slot 359 0x1014f910 (walked) `int vfunc359(CBaseEntity*)`
	//   layer 0, story 29c
	virtual int32 Slot359(FElysiumEntity*);
	// slot 360 0x1014f930 (walked) `bool vfunc360()`
	//   layer 0, story 29c
	virtual bool Slot360();
	// slot 361 0x1014f950 (walked) `bool vfunc361()`
	//   layer 0, story 29c
	virtual bool Slot361();
	// slot 362 0x10326a20 (walked) `bool FInViewCone(const Vector&)`
	//   layer 8, story 29c
	virtual bool FInViewCone(const FVector&);
	// slot 363 0x10326750 (walked) `bool FInViewCone(CBaseEntity*)`
	//   layer 7, story 29c
	virtual bool FInViewCone(FElysiumEntity*);
	// slot 364 0x10326bd0 (walked) `bool FInAimCone(const Vector&)`
	//   layer 6, story 29c
	virtual bool FInAimCone(const FVector&);
	// slot 365 0x10326ae0 (walked) `bool FInAimCone(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool FInAimCone(FElysiumEntity*);
	// slot 366 0x10326d40 (sdk) `bool HandleInteraction(int, void*, CBaseCombatCharacter*)`
	//   takes `void*`
	//   layer 0, story 29c
	virtual bool HandleInteraction(int32, void*, FElysiumEntity*);
	// slot 367 0x10331880 (sdk) `QAngle BodyAngles()`
	//   layer 1, story 29c
	virtual FRotator BodyAngles();
	// slot 369 0x10331a40 (sdk) `Vector BodyDirection3D()`
	//   layer 2, story 29c
	virtual FVector BodyDirection3D();
	// slot 370 0x10331cb0 (sdk) `Vector HeadDirection2D()`
	//   layer 4, story 29c
	virtual FVector HeadDirection2D();
	// slot 371 0x10331b30 (sdk) `Vector HeadDirection3D()`
	//   layer 3, story 29c
	virtual FVector HeadDirection3D();
	// slot 372 0x1014f970 (walked) `Vector EyeDirection2D()`
	//   layer 5, story 29c
	virtual FVector EyeDirection2D();
	// slot 373 0x1014f9a0 (walked) `Vector EyeDirection3D()`
	//   layer 4, story 29c
	virtual FVector EyeDirection3D();
	// slot 374 0x10334180 (walked) `int GiveAmmo(int, int, bool)`
	//   layer 4, story 29c
	virtual int32 GiveAmmo(int32, int32, bool);
	// slot 375 0x10328030 (walked) `Activity NPC_EarlyTranslateActivity(Activity)`
	//   layer 14, story 29d
	virtual int32 NPC_EarlyTranslateActivity(int32);
	// slot 376 0x10328110 (sdk) `Activity NPC_TranslateActivity(Activity)`
	//   layer 0, story 29c
	virtual int32 NPC_TranslateActivity(int32);
	// slot 377 0x1014f9d0 (walked) `bool vfunc377(CBaseCombatCharacter*, int)`
	//   layer 0, story 29c
	virtual bool Slot377(FElysiumEntity*, int32);
	// slot 378 0x1014f9f0 (walked) `bool vfunc378(CBaseCombatCharacter*, int)`
	//   layer 0, story 29c
	virtual bool Slot378(FElysiumEntity*, int32);
	// slot 381 0x10327ec0 (walked) `Activity Weapon_TranslateActivity(Activity)`
	//   layer 0, story 29c
	virtual int32 Weapon_TranslateActivity(int32);
	// slot 382 0x1032d9b0 (sdk) `bool Weapon_CanUse(CBaseCombatWeapon*)`
	//   layer 1, story 29c
	virtual bool Weapon_CanUse(FElysiumEntity*);
	// slot 383 0x1032d380 (walked) `void Weapon_Equip(CBaseCombatWeapon*, bool)`
	//   layer 21, story 29e
	virtual void Weapon_Equip(FElysiumEntity*, bool);
	// slot 384 0x1032d6e0 (sdk) `bool Weapon_EquipAmmoOnly(CBaseCombatWeapon*)`
	//   layer 5, story 29c
	virtual bool Weapon_EquipAmmoOnly(FElysiumEntity*);
	// slot 385 0x1032d0c0 (walked) `void Weapon_Drop(CBaseCombatWeapon*, const Vector*, bool)`
	//   layer 11, story 29d
	virtual void Weapon_Drop(FElysiumEntity*, const FVector*, bool);
	// slot 386 0x1032ce40 (walked) `void Weapon_Drop()`
	//   layer 10, story 29d
	virtual void Weapon_Drop();
	// slot 387 0x1032d2e0 (walked) `void Weapon_Drop_All()`
	//   layer 11, story 29d
	virtual void Weapon_Drop_All();
	// slot 388 0x1032dde0 (sdk) `bool Weapon_Switch(CBaseCombatWeapon*, int)`
	//   layer 22, story 29e
	virtual bool Weapon_Switch(FElysiumEntity*, int32);
	// slot 389 0x103338c0 (walked) `Vector Weapon_ShootPosition(const Vector&)`
	//   layer 1, story 29c
	virtual FVector Weapon_ShootPosition(const FVector&);
	// slot 390 0x103302e0 (walked) `int OnTakeDamage_Alive(const CTakeDamageInfo&)`
	//   takes `const CTakeDamageInfo&`
	//   layer 22, story 29e
	virtual int32 OnTakeDamage_Alive(void*);
	// slot 391 0x103315e0 (sdk) `int OnTakeDamage_Dying(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 0, story 29c
	virtual int32 OnTakeDamage_Dying(void*);
	// slot 392 0x10331680 (sdk) `int OnTakeDamage_Dead(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 1, story 29c
	virtual int32 OnTakeDamage_Dead(void*);
	// slot 393 0x10327e20 (sdk) `Activity GetDeathActivity()`
	//   layer 0, story 29c
	virtual int32 GetDeathActivity();
	// slot 394 0x10327a90 (walked) `bool CorpseGib()`
	//   layer 14, story 29d
	virtual bool CorpseGib();
	// slot 395 0x10326040 (sdk) `void CorpseFade()`
	//   layer 6, story 29c
	virtual void CorpseFade();
	// slot 396 0x10325f00 (sdk) `bool HasHumanGibs()`
	//   layer 0, story 29c
	virtual bool HasHumanGibs();
	// slot 397 0x10325fa0 (sdk) `bool HasAlienGibs()`
	//   layer 1, story 29c
	virtual bool HasAlienGibs();
	// slot 398 0x10348a60 (walked) `bool HasExplosiveGibs()`
	//   layer 0, story 29c
	virtual bool HasExplosiveGibs();
	// slot 399 0x1014fa30 (walked) `bool vfunc399()`
	//   layer 0, story 29c
	virtual bool Slot399();
	// slot 400 0x1014fa50 (walked) `bool AllowsKnockbackBypass()`
	//   layer 0, story 29c
	virtual bool AllowsKnockbackBypass();
	// slot 401 0x10348b00 (walked) `Activity KnockbackActivity_Default(int)`
	//   layer 0, story 29c
	virtual int32 KnockbackActivity_Default(int32);
	// slot 402 0x1032af40 (walked) `bool Event_Gibbed()`
	//   layer 15, story 29d
	virtual bool Event_Gibbed();
	// slot 403 0x1032bdf0 (sdk) `void Event_Dying()`
	//   layer 0, story 29c
	virtual void Event_Dying();
	// slot 404 0x10333340 (sdk) `Disposition_t IRelationType(CBaseEntity*)`
	//   returns `Disposition_t`
	//   layer 13, story 29d
	virtual int32 IRelationType(FElysiumEntity*);
	// slot 405 0x10333700 (sdk) `int IRelationPriority(CBaseEntity*)`
	//   layer 0, story 29c
	virtual int32 IRelationPriority(FElysiumEntity*);
