// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 20 generated slot rows of `FElysiumAnimatingOverlay` (CBaseAnimatingOverlay): 11 it introduces
// and 9 it overrides with a body of its own.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// This file is included INSIDE `class FElysiumAnimatingOverlay` (`ElysiumPlayer.h`). It is not
// a header: it has no include guard and declares nothing of its own. One declaration per
// slot, in slot order, with the retail declaration in the comment and the port's lowered
// signature in the code.
//
// Each slot is declared by the port class of the retail class that introduces it, with that
// class's own body, and overridden by every port class whose retail table holds another
// body there (story 0019/5 step 6). The stub names the retail class that owns its body.
//
// A body lands on one of these in 29c/29d/29e. Until then the definition in
// `ElysiumAnimatingOverlaySlots.cpp` tallies `elysium.stubs` with the retail address — except
// where the verdict overlay records that retail's whole body is one literal, which the
// generator emits, or that the body is written by hand in the substrate, in which case no
// definition is generated at all and the linker is what checks the claim.

	// slot 5 0x10098a60 (walked) `void* ~CBaseEntity(unsigned int)`
	//   retail `~CBaseEntity` is a lifetime slot; declared by index
	//   returns `void*`
	void* Slot5(uint32) override;
	// slot 31 0x10098a90 (walked) `void Dump(int)`
	//   layer 1, story 29c
	void Dump(int32) override;
	// slot 79 0x10097d70 (walked) `datamap_t* GetPredDescMap()`
	//   returns `datamap_t*`
	void* GetPredDescMap() override;
	// slot 80 0x10098020 (walked) `ServerClass* GetServerClass()`
	//   returns `ServerClass*`
	void* GetServerClass() override;
	// slot 81 0x10098040 (walked) `int YouForgotToImplementOrDeclareServerClass()`
	int32 YouForgotToImplementOrDeclareServerClass() override;
	// slot 82 0x10097ce0 (walked) `datamap_t* GetDataDescMap()`
	//   returns `datamap_t*`
	void* GetDataDescMap() override;
	// slot 250 0x10098bb0 (walked) `float StudioFrameAdvance(float)`
	//   layer 2, story 29c
	float StudioFrameAdvance(float) override;
	// slot 255 0x10098eb0 (walked) `void GetSkeleton(Vector*, Quaternion*, int)`
	//   takes `Quaternion*`
	//   layer 13, story 29d
	void GetSkeleton(FVector*, void*, int32) override;
	// slot 258 0x10098c80 (walked) `void DispatchAnimEvents(float, CBaseAnimating*)`
	//   layer 2, story 29c
	void DispatchAnimEvents(float, FElysiumEntity*) override;
	// slot 265 0x10099690 (walked) `void AddFlinchGesture(Activity, float, float, const char*,
	// float)`
	//   layer 6, story 29c
	virtual void AddFlinchGesture(int32, float, float, const TCHAR*, float);
	// slot 266 0x100997f0 (walked) `void vfunc266()`
	//   layer 0, story 29c
	virtual void Slot266();
	// slot 267 0x10098a40 (walked) `int GetFirstGestureLayer()`
	//   layer 0, story 29c
	virtual int32 GetFirstGestureLayer();
	// slot 268 0x10099020 (walked) `void SetLayer(int, Activity, int, bool)`
	//   layer 1, story 29c
	virtual void SetLayer(int32, int32, int32, bool);
	// slot 269 0x10099660 (walked) `void RemoveLayer(int)`
	//   layer 0, story 29c
	virtual void RemoveLayer(int32);
	// slot 270 0x10099540 (walked) `bool HasLayer(Activity)`
	//   layer 2, story 29c
	virtual bool HasLayer(int32);
	// slot 271 0x100994c0 (walked) `int FindLayerByOwner(Activity)`
	//   layer 1, story 29c
	virtual int32 FindLayerByOwner(int32);
	// slot 272 0x10099470 (walked) `int AllocateLayer()`
	//   layer 1, story 29c
	virtual int32 AllocateLayer();
	// slot 273 0x10099570 (walked) `void RestartGesture(Activity, bool, bool)`
	//   layer 4, story 29c
	virtual void RestartGesture(int32, bool, bool);
	// slot 274 0x100995e0 (walked) `void RemoveLayerByOwner(Activity)`
	//   layer 2, story 29c
	virtual void RemoveLayerByOwner(int32);
	// slot 275 0x10099630 (walked) `void RemoveAllGestures()`
	//   layer 0, story 29c
	virtual void RemoveAllGestures();
