// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FLATBUFFERSSMOKE_ELYSIUM_CAPTURE_SMOKE_H_
#define FLATBUFFERS_GENERATED_FLATBUFFERSSMOKE_ELYSIUM_CAPTURE_SMOKE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Elysium {
namespace Capture {
namespace Smoke {

struct SmokeRecord;
struct SmokeRecordBuilder;

struct SmokeRecord FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SmokeRecordBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQUENCE = 4,
    VT_LABEL = 6,
    VT_VALUES = 8
  };
  uint64_t sequence() const {
    return GetField<uint64_t>(VT_SEQUENCE, 0);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  const ::flatbuffers::Vector<float> *values() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SEQUENCE, 8) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct SmokeRecordBuilder {
  typedef SmokeRecord Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sequence(uint64_t sequence) {
    fbb_.AddElement<uint64_t>(SmokeRecord::VT_SEQUENCE, sequence, 0);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(SmokeRecord::VT_LABEL, label);
  }
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<float>> values) {
    fbb_.AddOffset(SmokeRecord::VT_VALUES, values);
  }
  explicit SmokeRecordBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SmokeRecord> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SmokeRecord>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SmokeRecord> CreateSmokeRecord(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t sequence = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> values = 0) {
  SmokeRecordBuilder builder_(_fbb);
  builder_.add_sequence(sequence);
  builder_.add_values(values);
  builder_.add_label(label);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SmokeRecord> CreateSmokeRecordDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t sequence = 0,
    const char *label = nullptr,
    const std::vector<float> *values = nullptr) {
  auto label__ = label ? _fbb.CreateString(label) : 0;
  auto values__ = values ? _fbb.CreateVector<float>(*values) : 0;
  return Elysium::Capture::Smoke::CreateSmokeRecord(
      _fbb,
      sequence,
      label__,
      values__);
}

inline const Elysium::Capture::Smoke::SmokeRecord *GetSmokeRecord(const void *buf) {
  return ::flatbuffers::GetRoot<Elysium::Capture::Smoke::SmokeRecord>(buf);
}

inline const Elysium::Capture::Smoke::SmokeRecord *GetSizePrefixedSmokeRecord(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Elysium::Capture::Smoke::SmokeRecord>(buf);
}

inline const char *SmokeRecordIdentifier() {
  return "ELFS";
}

inline bool SmokeRecordBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SmokeRecordIdentifier());
}

inline bool SizePrefixedSmokeRecordBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SmokeRecordIdentifier(), true);
}

template <bool B = false>
inline bool VerifySmokeRecordBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Elysium::Capture::Smoke::SmokeRecord>(SmokeRecordIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedSmokeRecordBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Elysium::Capture::Smoke::SmokeRecord>(SmokeRecordIdentifier());
}

inline void FinishSmokeRecordBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Elysium::Capture::Smoke::SmokeRecord> root) {
  fbb.Finish(root, SmokeRecordIdentifier());
}

inline void FinishSizePrefixedSmokeRecordBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Elysium::Capture::Smoke::SmokeRecord> root) {
  fbb.FinishSizePrefixed(root, SmokeRecordIdentifier());
}

}  // namespace Smoke
}  // namespace Capture
}  // namespace Elysium

#endif  // FLATBUFFERS_GENERATED_FLATBUFFERSSMOKE_ELYSIUM_CAPTURE_SMOKE_H_
