// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 21 generated slot bodies of `FElysiumFlex`: 0 carry the retail default story 29c recovered, 1 are
// defined by hand in the substrate, and 9 are still stubs — 3 29c, 6 unassigned. 11 are closed
// (0019/6) and answer the value-initialised default without tallying.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// A stub body says one thing: this slot has no port implementation yet. The tally row
// carries the retail class that owns the body, its address and the story that owns it, so
// `elysium.stubs` joins `docs/vtmb/npc-kernel/functions.md` by address.
//
// A body with a `default:` verdict says something stronger: retail's whole body at that
// slot is `return <literal>;`, so the port answers the same literal and stops tallying.
// The literal is a recovered fact, not a written behaviour, and the slot table at the end
// of this file is what `Elysium.Substrate.NpcKernelSlots.Defaults` calls every one of them
// through, on a receiver typed to this class.

#include "ElysiumFlex.h"

#include "ElysiumStub.h"
#include "Substrate/ElysiumNpcKernelShape.h"

namespace
{
	// One shape for every slot stub: the surface is the retail class and method, which is
	// what the ledger joins on, and never an instance name. Unit-prefixed because the module
	// builds adaptive-unity and this anonymous namespace is regularly merged with others.
	void FireFlexSlot(const TCHAR* Surface, const TCHAR* Address, const TCHAR* Story,
		const FString& Receiver)
	{
		ElysiumStub::FSurface Row;
		Row.Kind = TEXT("slot");
		Row.Surface = Surface;
		Row.Address = Address;
		Row.Story = Story;
		ElysiumStub::Fired(Row, Receiver, FString(), TEXT("the NPC kernel"));
	}
}

// slot 5 0x100b5940 (walked) `void* ~CBaseEntity(unsigned int)`
//   retail `~CBaseEntity` is a lifetime slot; declared by index
//   returns `void*`
void* FElysiumFlex::Slot5(uint32)
{
	FireFlexSlot(TEXT("CBaseFlex::Slot5"), TEXT("0x100b5940"), TEXT(""), DebugString());
	return {};
}

// slot 79 0x100b58b0 (walked) `datamap_t* GetPredDescMap()`
//   returns `datamap_t*`
void* FElysiumFlex::GetPredDescMap()
{
	FireFlexSlot(TEXT("CBaseFlex::GetPredDescMap"), TEXT("0x100b58b0"), TEXT(""), DebugString());
	return {};
}

// slot 80 0x100b5520 (walked) `ServerClass* GetServerClass()`
//   returns `ServerClass*`
void* FElysiumFlex::GetServerClass()
{
	FireFlexSlot(TEXT("CBaseFlex::GetServerClass"), TEXT("0x100b5520"), TEXT(""), DebugString());
	return {};
}

// slot 81 0x100b5540 (walked) `int YouForgotToImplementOrDeclareServerClass()`
int32 FElysiumFlex::YouForgotToImplementOrDeclareServerClass()
{
	FireFlexSlot(TEXT("CBaseFlex::YouForgotToImplementOrDeclareServerClass"), TEXT("0x100b5540"),
		TEXT(""), DebugString());
	return {};
}

// slot 82 0x100b57b0 (walked) `datamap_t* GetDataDescMap()`
//   returns `datamap_t*`
void* FElysiumFlex::GetDataDescMap()
{
	FireFlexSlot(TEXT("CBaseFlex::GetDataDescMap"), TEXT("0x100b57b0"), TEXT(""), DebugString());
	return {};
}

// slot 105 0x100b5ab0 (sdk) `void SetModel(char*)`
//   layer 0, story 29c
void FElysiumFlex::SetModel(TCHAR*)
{
	FireFlexSlot(TEXT("CBaseFlex::SetModel"), TEXT("0x100b5ab0"), TEXT("29c"), DebugString());
}

// slot 276 0x100b5ce0 (sdk) `void Blink()`
//   layer 0, story 29c
void FElysiumFlex::Blink()
{
	FireFlexSlot(TEXT("CBaseFlex::Blink"), TEXT("0x100b5ce0"), TEXT("29c"), DebugString());
}

// slot 277 0x100b5b00 (walked) `void SetViewtarget(const Vector&)`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::SetViewtarget`, written by hand in the substrate.
// Declared here, defined there.

// slot 278 0x100b5b40 (walked) `const Vector& GetViewtarget() const`
//   returns `const Vector&`
//   layer 0, story 29c
void* FElysiumFlex::GetViewtarget() const
{
	FireFlexSlot(TEXT("CBaseFlex::GetViewtarget"), TEXT("0x100b5b40"), TEXT("29c"), DebugString());
	return {};
}

// slot 279 0x100b5ba0 (walked) `void SetFlexWeight(int, float)`
//   layer 1, story 29c
void FElysiumFlex::SetFlexWeight(int32, float)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 280 0x100b5b60 (walked) `void SetFlexWeight(char*, float)`
//   layer 6, story 29c
void FElysiumFlex::SetFlexWeight(TCHAR*, float)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 281 0x100b5c50 (walked) `float GetFlexWeight(int)`
//   layer 1, story 29c
float FElysiumFlex::GetFlexWeight(int32)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
	return {};
}

// slot 283 0x100b6250 (walked) `void ProcessSceneEvents()`
//   layer 9, story 29c
void FElysiumFlex::ProcessSceneEvents()
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 284 0x100b65b0 (walked) `void AddSceneExpressions()`
void FElysiumFlex::AddSceneExpressions()
{
	FireFlexSlot(TEXT("CBaseFlex::AddSceneExpressions"), TEXT("0x100b65b0"), TEXT(""),
		DebugString());
}

// slot 285 0x100b5d80 (walked) `void ClearSceneEvents(CChoreoScene*)`
//   takes `CChoreoScene*`
//   layer 1, story 29c
void FElysiumFlex::ClearSceneEvents(void*)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 286 0x100b5e60 (walked) `void AddSceneEvent(CChoreoScene*, CChoreoEvent*)`
//   takes `CChoreoScene*`
//   takes `CChoreoEvent*`
//   layer 3, story 29c
void FElysiumFlex::AddSceneEvent(void*, void*)
{
	// verdict `mechanism`, closed at `UEContainer` (0019/6): nothing observes this body, but the
	// slot is still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 287 0x100b6180 (walked) `void RemoveSceneEvent(CChoreoEvent*)`
//   takes `CChoreoEvent*`
//   layer 1, story 29c
void FElysiumFlex::RemoveSceneEvent(void*)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 288 0x100b6cf0 (walked) `void AddFlexSetting(const char*, float, const flexsettinghdr_t*,
// const flexsettinghdr_t*, bool)`
//   takes `const flexsettinghdr_t*`
//   takes `const flexsettinghdr_t*`
//   layer 6, story 29c
void FElysiumFlex::AddFlexSetting(const TCHAR*, float, void*, void*, bool)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 289 0x100b6960 (walked) `void AddFlexAnimation(CSceneEventInfo*)`
//   takes `CSceneEventInfo*`
//   layer 7, story 29c
void FElysiumFlex::AddFlexAnimation(void*)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 290 0x100b70e0 (walked) `void ProcessSequenceSceneEvent(CSceneEventInfo*)`
//   takes `CSceneEventInfo*`
//   layer 2, story 29c
void FElysiumFlex::ProcessSequenceSceneEvent(void*)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

// slot 291 0x100b7040 (walked) `void ProcessGestureSceneEvent(CSceneEventInfo*)`
//   takes `CSceneEventInfo*`
//   layer 3, story 29c
void FElysiumFlex::ProcessGestureSceneEvent(void*)
{
	// verdict `mechanism`, closed at `0010` (0019/6): nothing observes this body, but the slot is
	// still reached, so it answers the value-initialised default and tallies nothing.
}

namespace ElysiumNpcKernelShape
{
	namespace
	{
		// Every generated slot row of `FElysiumFlex`, in slot order: the census the class answers
		// for (`Elysium.Substrate.NpcKernelShape.SlotOwners`) and, for each recovered default,
		// the probe `Elysium.Substrate.NpcKernelSlots.Defaults` calls on a receiver of this
		// class. `bDeclaredHere` is decided by the compiler, not written.
		const TElysiumNpcSlotRow<FElysiumFlex> GFlexSlotRows[] =
		{
			{ 5, TEXT("0x100b5940"), TEXT("CBaseFlex"), TEXT("Slot5"), EElysiumNpcSlotBody::Stub,
				TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void*(uint32)>::Test(&FElysiumFlex::Slot5),
				nullptr },
			{ 79, TEXT("0x100b58b0"), TEXT("CBaseFlex"), TEXT("GetPredDescMap"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void*()>::Test(&FElysiumFlex::GetPredDescMap),
				nullptr },
			{ 80, TEXT("0x100b5520"), TEXT("CBaseFlex"), TEXT("GetServerClass"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void*()>::Test(&FElysiumFlex::GetServerClass),
				nullptr },
			{ 81, TEXT("0x100b5540"), TEXT("CBaseFlex"),
				TEXT("YouForgotToImplementOrDeclareServerClass"), EElysiumNpcSlotBody::Stub,
				TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, int32()>::Test(&FElysiumFlex::YouForgotToImplementOrDeclareServerClass),
				nullptr },
			{ 82, TEXT("0x100b57b0"), TEXT("CBaseFlex"), TEXT("GetDataDescMap"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void*()>::Test(&FElysiumFlex::GetDataDescMap),
				nullptr },
			{ 105, TEXT("0x100b5ab0"), TEXT("CBaseFlex"), TEXT("SetModel"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(TCHAR*)>::Test(&FElysiumFlex::SetModel),
				nullptr },
			{ 276, TEXT("0x100b5ce0"), TEXT("CBaseFlex"), TEXT("Blink"), EElysiumNpcSlotBody::Stub,
				TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void()>::Test(&FElysiumFlex::Blink),
				nullptr },
			{ 277, TEXT("0x100b5b00"), TEXT("CBaseFlex"), TEXT("SetViewtarget"),
				EElysiumNpcSlotBody::Hand, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(const FVector&)>::Test(&FElysiumFlex::SetViewtarget),
				nullptr },
			{ 278, TEXT("0x100b5b40"), TEXT("CBaseFlex"), TEXT("GetViewtarget"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void*() const>::Test(&FElysiumFlex::GetViewtarget),
				nullptr },
			{ 279, TEXT("0x100b5ba0"), TEXT("CBaseFlex"), TEXT("SetFlexWeight"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(int32, float)>::Test(&FElysiumFlex::SetFlexWeight),
				nullptr },
			{ 280, TEXT("0x100b5b60"), TEXT("CBaseFlex"), TEXT("SetFlexWeight"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(TCHAR*, float)>::Test(&FElysiumFlex::SetFlexWeight),
				nullptr },
			{ 281, TEXT("0x100b5c50"), TEXT("CBaseFlex"), TEXT("GetFlexWeight"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, float(int32)>::Test(&FElysiumFlex::GetFlexWeight),
				nullptr },
			{ 283, TEXT("0x100b6250"), TEXT("CBaseFlex"), TEXT("ProcessSceneEvents"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void()>::Test(&FElysiumFlex::ProcessSceneEvents),
				nullptr },
			{ 284, TEXT("0x100b65b0"), TEXT("CBaseFlex"), TEXT("AddSceneExpressions"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void()>::Test(&FElysiumFlex::AddSceneExpressions),
				nullptr },
			{ 285, TEXT("0x100b5d80"), TEXT("CBaseFlex"), TEXT("ClearSceneEvents"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(void*)>::Test(&FElysiumFlex::ClearSceneEvents),
				nullptr },
			{ 286, TEXT("0x100b5e60"), TEXT("CBaseFlex"), TEXT("AddSceneEvent"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(void*, void*)>::Test(&FElysiumFlex::AddSceneEvent),
				nullptr },
			{ 287, TEXT("0x100b6180"), TEXT("CBaseFlex"), TEXT("RemoveSceneEvent"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(void*)>::Test(&FElysiumFlex::RemoveSceneEvent),
				nullptr },
			{ 288, TEXT("0x100b6cf0"), TEXT("CBaseFlex"), TEXT("AddFlexSetting"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(const TCHAR*, float, void*, void*, bool)>::Test(&FElysiumFlex::AddFlexSetting),
				nullptr },
			{ 289, TEXT("0x100b6960"), TEXT("CBaseFlex"), TEXT("AddFlexAnimation"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(void*)>::Test(&FElysiumFlex::AddFlexAnimation),
				nullptr },
			{ 290, TEXT("0x100b70e0"), TEXT("CBaseFlex"), TEXT("ProcessSequenceSceneEvent"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(void*)>::Test(&FElysiumFlex::ProcessSequenceSceneEvent),
				nullptr },
			{ 291, TEXT("0x100b7040"), TEXT("CBaseFlex"), TEXT("ProcessGestureSceneEvent"),
				EElysiumNpcSlotBody::Closed, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumFlex, void(void*)>::Test(&FElysiumFlex::ProcessGestureSceneEvent),
				nullptr },
		};
	}

	TArrayView<const TElysiumNpcSlotRow<FElysiumFlex>> FlexSlotRows()
	{
		return MakeArrayView(GFlexSlotRows);
	}
}
