// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 22 generated slot bodies of `FElysiumFlex`: 0 carry the retail default story 29c recovered, 12
// are defined by hand in the substrate, and 10 are still stubs — 4 29c, 6 unassigned.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// A stub body says one thing: this slot has no port implementation yet. The tally row
// carries the retail class that owns the body, its address and the story that owns it, so
// `elysium.stubs` joins `docs/vtmb/npc-kernel/functions.md` by address.
//
// A body with a `default:` verdict says something stronger: retail's whole body at that
// slot is `return <literal>;`, so the port answers the same literal and stops tallying.
// The literal is a recovered fact, not a written behaviour — the same argument the story
// makes for a species override of a constant-returning virtual — and the probe tables in
// `ElysiumNpcSlots.cpp` are what `Elysium.Substrate.NpcKernelSlots.Defaults` and
// `.ShadowedDefaults` call every one of them through.

#include "ElysiumPlayer.h"

#include "ElysiumStub.h"

namespace
{
	// One shape for every slot stub: the surface is the retail class and method, which is
	// what the ledger joins on, and never an instance name. Unit-prefixed because the module
	// builds adaptive-unity and this anonymous namespace is regularly merged with others.
	void FireFlexSlot(const TCHAR* Surface, const TCHAR* Address, const TCHAR* Story,
		const FString& Receiver)
	{
		ElysiumStub::FSurface Row;
		Row.Kind = TEXT("slot");
		Row.Surface = Surface;
		Row.Address = Address;
		Row.Story = Story;
		ElysiumStub::Fired(Row, Receiver, FString(), TEXT("the NPC kernel"));
	}
}

// slot 5 0x100b5940 (walked) `void* ~CBaseEntity(unsigned int)`
//   retail `~CBaseEntity` is a lifetime slot; declared by index
//   returns `void*`
void* FElysiumFlex::Slot5(uint32)
{
	FireFlexSlot(TEXT("CBaseFlex::Slot5"), TEXT("0x100b5940"), TEXT(""), DebugString());
	return {};
}

// slot 79 0x100b58b0 (walked) `datamap_t* GetPredDescMap()`
//   returns `datamap_t*`
void* FElysiumFlex::GetPredDescMap()
{
	FireFlexSlot(TEXT("CBaseFlex::GetPredDescMap"), TEXT("0x100b58b0"), TEXT(""), DebugString());
	return {};
}

// slot 80 0x100b5520 (walked) `ServerClass* GetServerClass()`
//   returns `ServerClass*`
void* FElysiumFlex::GetServerClass()
{
	FireFlexSlot(TEXT("CBaseFlex::GetServerClass"), TEXT("0x100b5520"), TEXT(""), DebugString());
	return {};
}

// slot 81 0x100b5540 (walked) `int YouForgotToImplementOrDeclareServerClass()`
int32 FElysiumFlex::YouForgotToImplementOrDeclareServerClass()
{
	FireFlexSlot(TEXT("CBaseFlex::YouForgotToImplementOrDeclareServerClass"), TEXT("0x100b5540"),
		TEXT(""), DebugString());
	return {};
}

// slot 82 0x100b57b0 (walked) `datamap_t* GetDataDescMap()`
//   returns `datamap_t*`
void* FElysiumFlex::GetDataDescMap()
{
	FireFlexSlot(TEXT("CBaseFlex::GetDataDescMap"), TEXT("0x100b57b0"), TEXT(""), DebugString());
	return {};
}

// slot 105 0x100b5ab0 (sdk) `void SetModel(char*)`
//   layer 0, story 29c
void FElysiumFlex::SetModel(TCHAR*)
{
	FireFlexSlot(TEXT("CBaseFlex::SetModel"), TEXT("0x100b5ab0"), TEXT("29c"), DebugString());
}

// slot 276 0x100b5ce0 (sdk) `void Blink()`
//   layer 0, story 29c
void FElysiumFlex::Blink()
{
	FireFlexSlot(TEXT("CBaseFlex::Blink"), TEXT("0x100b5ce0"), TEXT("29c"), DebugString());
}

// slot 277 0x100b5b00 (walked) `void SetViewtarget(const Vector&)`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::SetViewtarget`, written by hand in the substrate.
// Declared here, defined there.

// slot 278 0x100b5b40 (walked) `const Vector& GetViewtarget() const`
//   returns `const Vector&`
//   layer 0, story 29c
void* FElysiumFlex::GetViewtarget() const
{
	FireFlexSlot(TEXT("CBaseFlex::GetViewtarget"), TEXT("0x100b5b40"), TEXT("29c"), DebugString());
	return {};
}

// slot 279 0x100b5ba0 (walked) `void SetFlexWeight(int, float)`
//   layer 1, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::SetFlexWeight`, written by hand in the substrate.
// Declared here, defined there.

// slot 280 0x100b5b60 (walked) `void SetFlexWeight(char*, float)`
//   layer 6, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::SetFlexWeight`, written by hand in the substrate.
// Declared here, defined there.

// slot 281 0x100b5c50 (walked) `float GetFlexWeight(int)`
//   layer 1, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::GetFlexWeight`, written by hand in the substrate.
// Declared here, defined there.

// slot 282 0x100b5c20 (walked) `float GetFlexWeight(char*)`
//   layer 6, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::GetFlexWeight`, written by hand in the substrate.
// Declared here, defined there.

// slot 283 0x100b6250 (walked) `void ProcessSceneEvents()`
//   layer 9, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::ProcessSceneEvents`, written by hand in the
// substrate. Declared here, defined there.

// slot 284 0x100b65b0 (walked) `void AddSceneExpressions()`
void FElysiumFlex::AddSceneExpressions()
{
	FireFlexSlot(TEXT("CBaseFlex::AddSceneExpressions"), TEXT("0x100b65b0"), TEXT(""),
		DebugString());
}

// slot 285 0x100b5d80 (walked) `void ClearSceneEvents(CChoreoScene*)`
//   takes `CChoreoScene*`
//   layer 1, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::ClearSceneEvents`, written by hand in the
// substrate. Declared here, defined there.

// slot 286 0x100b5e60 (walked) `void AddSceneEvent(CChoreoScene*, CChoreoEvent*)`
//   takes `CChoreoScene*`
//   takes `CChoreoEvent*`
//   layer 3, story 29c
void FElysiumFlex::AddSceneEvent(void*, void*)
{
	FireFlexSlot(TEXT("CBaseFlex::AddSceneEvent"), TEXT("0x100b5e60"), TEXT("29c"), DebugString());
}

// slot 287 0x100b6180 (walked) `void RemoveSceneEvent(CChoreoEvent*)`
//   takes `CChoreoEvent*`
//   layer 1, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::RemoveSceneEvent`, written by hand in the
// substrate. Declared here, defined there.

// slot 288 0x100b6cf0 (walked) `void AddFlexSetting(const char*, float, const flexsettinghdr_t*,
// const flexsettinghdr_t*, bool)`
//   takes `const flexsettinghdr_t*`
//   takes `const flexsettinghdr_t*`
//   layer 6, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::AddFlexSetting`, written by hand in the
// substrate. Declared here, defined there.

// slot 289 0x100b6960 (walked) `void AddFlexAnimation(CSceneEventInfo*)`
//   takes `CSceneEventInfo*`
//   layer 7, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::AddFlexAnimation`, written by hand in the
// substrate. Declared here, defined there.

// slot 290 0x100b70e0 (walked) `void ProcessSequenceSceneEvent(CSceneEventInfo*)`
//   takes `CSceneEventInfo*`
//   layer 2, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::ProcessSequenceSceneEvent`, written by hand in
// the substrate. Declared here, defined there.

// slot 291 0x100b7040 (walked) `void ProcessGestureSceneEvent(CSceneEventInfo*)`
//   takes `CSceneEventInfo*`
//   layer 3, story 29c
// verdict `mechanism`: the body is `FElysiumFlex::ProcessGestureSceneEvent`, written by hand in the
// substrate. Declared here, defined there.
