#include "Substrate/ElysiumScheduleNumbers.h"

namespace
{
	// One row per constant in the header. A constant with no row here is not checked, which is the
	// only way a hand-decoded number gets back into this runtime -- so adding one means adding a
	// row, and the header says so.
	const FElysiumScheduleNumberRow GCheckedRows[] = {
		{ TEXT("cai_basenpc"), TEXT("NONE"), ElysiumSched::NONE },
		{ TEXT("cai_basenpc"), TEXT("IDLE_STAND"), ElysiumSched::IDLE_STAND },
		{ TEXT("cai_basenpc"), TEXT("IDLE_WALK"), ElysiumSched::IDLE_WALK },
		{ TEXT("cai_basenpc"), TEXT("TARGET_FACE"), ElysiumSched::TARGET_FACE },
		{ TEXT("cai_basenpc"), TEXT("TARGET_CHASE"), ElysiumSched::TARGET_CHASE },
		{ TEXT("cai_basenpc"), TEXT("ALERT_SMALL_FLINCH"), ElysiumSched::ALERT_SMALL_FLINCH },
		{ TEXT("cai_basenpc"), TEXT("SMALL_FLINCH"), ElysiumSched::SMALL_FLINCH },
		{ TEXT("cai_basenpc"), TEXT("TAKE_COVER_FROM_ORIGIN"),
			ElysiumSched::TAKE_COVER_FROM_ORIGIN },
		{ TEXT("cai_basenpc"), TEXT("STANDOFF"), ElysiumSched::STANDOFF },
		{ TEXT("cai_basenpc"), TEXT("DIE"), ElysiumSched::DIE },
		{ TEXT("cai_basenpc"), TEXT("SCHED_DIE_RAGDOLL"), ElysiumSched::SCHED_DIE_RAGDOLL },
		{ TEXT("cai_basenpc"), TEXT("WAIT_FOR_SCRIPT"), ElysiumSched::WAIT_FOR_SCRIPT },
		{ TEXT("cai_basenpc"), TEXT("AISCRIPT"), ElysiumSched::AISCRIPT },
		{ TEXT("cai_basenpc"), TEXT("SCRIPTED_WALK"), ElysiumSched::SCRIPTED_WALK },
		{ TEXT("cai_basenpc"), TEXT("SCRIPTED_RUN"), ElysiumSched::SCRIPTED_RUN },
		{ TEXT("cai_basenpc"), TEXT("SCRIPTED_CUSTOM_MOVE"), ElysiumSched::SCRIPTED_CUSTOM_MOVE },
		{ TEXT("cai_basenpc"), TEXT("SCRIPTED_WAIT"), ElysiumSched::SCRIPTED_WAIT },
		{ TEXT("cai_basenpc"), TEXT("SCRIPTED_FACE"), ElysiumSched::SCRIPTED_FACE },
		{ TEXT("cai_basenpc"), TEXT("SCHED_FLINCH_PHYSICS"), ElysiumSched::SCHED_FLINCH_PHYSICS },
		{ TEXT("cai_basenpc"), TEXT("FAIL"), ElysiumSched::FAIL },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_IDLE_STAND"),
			ElysiumSched::SCHED_TROIKA_IDLE_STAND },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_IDLE_DISPOSITION"),
			ElysiumSched::SCHED_TROIKA_IDLE_DISPOSITION },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_CHASE_ENEMY_FAILED"),
			ElysiumSched::SCHED_TROIKA_CHASE_ENEMY_FAILED },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_ALERT_LOOK_AROUND_NI"),
			ElysiumSched::SCHED_TROIKA_ALERT_LOOK_AROUND_NI },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_BACK_AWAY_FROM_DOOR_NE"),
			ElysiumSched::SCHED_TROIKA_BACK_AWAY_FROM_DOOR_NE },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_BACK_AWAY_FROM_DOOR_WAIT_NE"),
			ElysiumSched::SCHED_TROIKA_BACK_AWAY_FROM_DOOR_WAIT_NE },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_TAKE_COVER_HINT_DOOR"),
			ElysiumSched::SCHED_TROIKA_TAKE_COVER_HINT_DOOR },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_ATTACK1_NR"),
			ElysiumSched::SCHED_TROIKA_MELEE_ATTACK1_NR },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_CHASE_ENEMY"),
			ElysiumSched::SCHED_TROIKA_CHASE_ENEMY },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_RUN_AWAY_FROM_ENEMY"),
			ElysiumSched::SCHED_TROIKA_RUN_AWAY_FROM_ENEMY },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_STANDOFF"),
			ElysiumSched::SCHED_TROIKA_STANDOFF },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_IDLE"),
			ElysiumSched::SCHED_TROIKA_MELEE_IDLE },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_ADVANCE"),
			ElysiumSched::SCHED_TROIKA_MELEE_ADVANCE },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_STEPBACK"),
			ElysiumSched::SCHED_TROIKA_MELEE_STEPBACK },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_DODGE"),
			ElysiumSched::SCHED_TROIKA_MELEE_DODGE },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_PREBLOCK"),
			ElysiumSched::SCHED_TROIKA_MELEE_PREBLOCK },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_KICK"),
			ElysiumSched::SCHED_TROIKA_MELEE_KICK },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_ATTACK1"),
			ElysiumSched::SCHED_TROIKA_MELEE_ATTACK1 },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_ATTACK1_SWING"),
			ElysiumSched::SCHED_TROIKA_MELEE_ATTACK1_SWING },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MELEE_CIRCLE_ADVANCE"),
			ElysiumSched::SCHED_TROIKA_MELEE_CIRCLE_ADVANCE },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_RANGE_ATTACK1_SHOOT_AT_HINT"),
			ElysiumSched::SCHED_TROIKA_RANGE_ATTACK1_SHOOT_AT_HINT },
		{ TEXT("cai_basenpctroika"), TEXT("SCHED_TROIKA_MESMERIZED"),
			ElysiumSched::SCHED_TROIKA_MESMERIZED },
		{ TEXT("cai_basenpc"), TEXT("NPC_FREEZE"), ElysiumSched::NPC_FREEZE },
		{ TEXT("cnpc_vvampireboss"), TEXT("SCHED_VVAMPIREBOSS_TRANSFORM"), ElysiumSched::SCHED_VVAMPIREBOSS_TRANSFORM },
		{ TEXT("cnpc_vvampireboss"), TEXT("SCHED_VVAMPIREBOSS_TRANSFORM_TO_BEAST"), ElysiumSched::SCHED_VVAMPIREBOSS_TRANSFORM_TO_BEAST },
		{ TEXT("cnpc_vwerewolf"), TEXT("SCHED_VWEREWOLF_RUN_TO_SPECIAL_MOVEMENT"), ElysiumSched::SCHED_VWEREWOLF_RUN_TO_SPECIAL_MOVEMENT },
		{ TEXT("cnpc_vwerewolf"), TEXT("SCHED_VWEREWOLF_DO_SPECIAL_MOVEMENT"), ElysiumSched::SCHED_VWEREWOLF_DO_SPECIAL_MOVEMENT },
		{ TEXT("cnpc_vwerewolf"), TEXT("SCHED_VWEREWOLF_DO_JUMP_HINT"), ElysiumSched::SCHED_VWEREWOLF_DO_JUMP_HINT },
		{ TEXT("cnpc_vwerewolf"), TEXT("SCHED_VWEREWOLF_DO_DEATH_HINT"), ElysiumSched::SCHED_VWEREWOLF_DO_DEATH_HINT },
		{ TEXT("cnpc_vgargoyle"), TEXT("SCHED_VGARGOYLE_DEATH"), ElysiumSched::SCHED_VGARGOYLE_DEATH },
		{ TEXT("cnpc_vzombie"), TEXT("SCHED_VZOMBIE_ANIMATED_DEATH"), ElysiumSched::SCHED_VZOMBIE_ANIMATED_DEATH },
		{ TEXT("cnpc_vsabbatleader"), TEXT("SCHED_VSABBATLEADER_TRANSFORM_TO_BEAST"), ElysiumSched::SCHED_VSABBATLEADER_TRANSFORM_TO_BEAST },
		{ TEXT("cnpc_vmingxiao"), TEXT("SCHED_VMING_XIAO_HIT_IN_HEAD"), ElysiumSched::SCHED_VMING_XIAO_HIT_IN_HEAD },
		{ TEXT("cnpc_vmingxiao"), TEXT("SCHED_VMING_XIAO_HIT_IN_TENTACLE"), ElysiumSched::SCHED_VMING_XIAO_HIT_IN_TENTACLE },
		{ TEXT("cnpc_vmingxiao"), TEXT("SCHED_VMING_XIAO_DIE"), ElysiumSched::SCHED_VMING_XIAO_DIE },
		{ TEXT("cnpc_vmingxiao"), TEXT("SCHED_VMING_XIAO_DIE_PROXY"), ElysiumSched::SCHED_VMING_XIAO_DIE_PROXY },
		{ TEXT("cnpc_vmingxiaotentacle"), TEXT("SCHED_VMING_XIAO_TENTACLE_DELAYED_DIE"), ElysiumSched::SCHED_VMING_XIAO_TENTACLE_DELAYED_DIE },
		{ TEXT("cnpc_vmingxiaotentacle"), TEXT("SCHED_VMING_XIAO_TENTACLE_EXPLODE_DIE"), ElysiumSched::SCHED_VMING_XIAO_TENTACLE_EXPLODE_DIE },
		{ TEXT("cnpc_vmingxiaotentacle"), TEXT("SCHED_VMING_XIAO_TENTACLE_SIMPLE_DIE"), ElysiumSched::SCHED_VMING_XIAO_TENTACLE_SIMPLE_DIE },
		{ TEXT("cnpc_vhengeyokai"), TEXT("SCHED_VHENGEYOKAI_STUNNED"), ElysiumSched::SCHED_VHENGEYOKAI_STUNNED },
	};
}

TConstArrayView<FElysiumScheduleNumberRow> ElysiumSched::CheckedRows()
{
	return GCheckedRows;
}
