// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 204 generated slot bodies of `FElysiumNpcBase`: 55 carry the retail default story 29c recovered,
// 108 are defined by hand in the substrate, and 41 are still stubs — 27 29c, 2 29d, 12 29e.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// A stub body says one thing: this slot has no port implementation yet. The tally row
// carries the retail class that owns the body, its address and the story that owns it, so
// `elysium.stubs` joins `docs/vtmb/npc-kernel/functions.md` by address.
//
// A body with a `default:` verdict says something stronger: retail's whole body at that
// slot is `return <literal>;`, so the port answers the same literal and stops tallying.
// The literal is a recovered fact, not a written behaviour — the same argument the story
// makes for a species override of a constant-returning virtual — and the probe tables in
// `ElysiumNpcSlots.cpp` are what `Elysium.Substrate.NpcKernelSlots.Defaults` and
// `.ShadowedDefaults` call every one of them through.

#include "Substrate/ElysiumNpcBase.h"

#include "ElysiumStub.h"

namespace
{
	// One shape for every slot stub: the surface is the retail class and method, which is
	// what the ledger joins on, and never an instance name. Unit-prefixed because the module
	// builds adaptive-unity and this anonymous namespace is regularly merged with others.
	void FireKernelBaseSlot(const TCHAR* Surface, const TCHAR* Address, const TCHAR* Story,
		const FString& Receiver)
	{
		ElysiumStub::FSurface Row;
		Row.Kind = TEXT("slot");
		Row.Surface = Surface;
		Row.Address = Address;
		Row.Story = Story;
		ElysiumStub::Fired(Row, Receiver, FString(), TEXT("the NPC kernel"));
	}
}

// slot 5 0x1027c7f0 (walked) `void* ~CBaseEntity(unsigned int)`
//   retail `~CBaseEntity` is a lifetime slot; declared by index
//   returns `void*`
//   layer 7, story 29c
void* FElysiumNpcBase::Slot5(uint32)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::Slot5"), TEXT("0x1027c7f0"), TEXT("29c"), DebugString());
	return {};
}

// slot 76 0x102775e0 (walked) `void DrawDebugStatOverlays()`
//   layer 6, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::DrawDebugStatOverlays`, written by hand in the
// substrate. Declared here, defined there.

// slot 82 0x1027a7c0 (walked) `datamap_t* GetDataDescMap()`
//   returns `datamap_t*`
//   layer 0, story 29c
void* FElysiumNpcBase::GetDataDescMap()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetDataDescMap"), TEXT("0x1027a7c0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 104 0x1027bb50 (sdk) `void Precache()`
//   layer 13, story 29d
// verdict `mechanism`: the body is `FElysiumNpcBase::Precache`, written by hand in the substrate.
// Declared here, defined there.

// slot 106 0x1027bb20 (sdk) `void PostConstructor(char*)`
//   layer 15, story 29d
// verdict `mechanism`: the body is `FElysiumNpcBase::PostConstructor`, written by hand in the
// substrate. Declared here, defined there.

// slot 123 0x10275760 (sdk) `void DrawDebugGeometryOverlays()`
//   layer 8, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::DrawDebugGeometryOverlays`, written by hand in the
// substrate. Declared here, defined there.

// slot 124 0x102767d0 (sdk) `int DrawDebugTextOverlays()`
//   layer 14, story 29d
// verdict `dead`: the body is `FElysiumNpcBase::DrawDebugTextOverlays`, written by hand in the
// substrate. Declared here, defined there.

// slot 126 0x1027bc60 (sdk) `int Save(ISave&)`
//   takes `ISave&`
//   layer 15, story 29d
// verdict `mechanism`: the body is `FElysiumNpcBase::Save`, written by hand in the substrate.
// Declared here, defined there.

// slot 127 0x1027c160 (walked) `int Restore(IRestore&)`
//   takes `IRestore&`
//   layer 9, story 29c
int32 FElysiumNpcBase::Restore(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::Restore"), TEXT("0x1027c160"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 128 0x101a6520 (sdk) `bool ShouldSavePhysics()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
bool FElysiumNpcBase::ShouldSavePhysics()
{
	return false;
}

// slot 130 0x1027bf50 (walked) `void OnRestore(bool)`
//   layer 21, story 29e
// verdict `mechanism`: the body is `FElysiumNpcBase::OnRestore`, written by hand in the substrate.
// Declared here, defined there.

// slot 136 0x101a6860 (walked) `bool vfunc136()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 1;`
bool FElysiumNpcBase::Slot136()
{
	return true;
}

// slot 141 0x10266780 (walked) `void TraceAttack(const CTakeDamageInfo&, const Vector&, trace_t*)`
//   takes `const CTakeDamageInfo&`
//   takes `trace_t*`
//   layer 8, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::TraceAttack`, written by hand in the substrate.
// Declared here, defined there.

// slot 142 0x10265e90 (sdk) `int OnTakeDamage(CTakeDamageInfo&)`
//   takes `CTakeDamageInfo&`
//   layer 24, story 29e
int32 FElysiumNpcBase::OnTakeDamage(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::OnTakeDamage"), TEXT("0x10265e90"), TEXT("29e"),
		DebugString());
	return {};
}

// slot 144 0x10265ad0 (sdk) `void Event_Killed(CTakeDamageInfo&)`
//   takes `CTakeDamageInfo&`
//   layer 20, story 29e
void FElysiumNpcBase::Event_Killed(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::Event_Killed"), TEXT("0x10265ad0"), TEXT("29e"),
		DebugString());
}

// slot 153 0x10280300 (walked) `bool IsMoving()`
//   layer 2, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::IsMoving`, written by hand in the substrate.
// Declared here, defined there.

// slot 167 0x101a67e0 (walked) `CBaseEntity* GetEnemy() const`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::GetEnemy`, written by hand in the substrate.
// Declared here, defined there.

// slot 180 0x1027ca30 (sdk) `void UpdateOnRemove()`
//   layer 6, story 29c
void FElysiumNpcBase::UpdateOnRemove()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::UpdateOnRemove"), TEXT("0x1027ca30"), TEXT("29c"),
		DebugString());
}

// slot 197 0x102789c0 (walked) `Vector BodyTarget(const Vector&, bool, bool)`
//   layer 9, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::BodyTarget`, written by hand in the substrate.
// Declared here, defined there.

// slot 223 0x10273720 (walked) `bool CreateVPhysics()`
//   layer 13, story 29d
// verdict `mechanism`: the body is `FElysiumNpcBase::CreateVPhysics`, written by hand in the
// substrate. Declared here, defined there.

// slot 251 0x10272900 (walked) `bool IsActivityFinished()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::IsActivityFinished`, written by hand in the
// substrate. Declared here, defined there.

// slot 310 0x102725d0 (sdk) `void SetActivity(Activity)`
//   layer 16, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::SetActivity`, written by hand in the substrate.
// Declared here, defined there.

// slot 311 0x10272400 (walked) `void ForcePreTranslatedSequenceAndActivity(Activity, Activity,
// int)`
//   layer 6, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::ForcePreTranslatedSequenceAndActivity`, written by
// hand in the substrate. Declared here, defined there.

// slot 333 0x1026b810 (walked) `void MaintainEyeDirection(float)`
//   layer 4, story 29c
void FElysiumNpcBase::MaintainEyeDirection(float)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::MaintainEyeDirection"), TEXT("0x1026b810"), TEXT("29c"),
		DebugString());
}

// slot 337 0x10270820 (walked) `int GetUsedHullBits()`
//   layer 1, story 29c
int32 FElysiumNpcBase::GetUsedHullBits()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetUsedHullBits"), TEXT("0x10270820"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 354 0x1026cec0 (walked) `void vfunc354()`
//   layer 21, story 29e
void FElysiumNpcBase::Slot354()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::Slot354"), TEXT("0x1026cec0"), TEXT("29e"),
		DebugString());
}

// slot 355 0x1026cf90 (walked) `void vfunc355()`
//   layer 8, story 29c
// verdict `present`: the body is `FElysiumNpcBase::Slot355`, written by hand in the substrate.
// Declared here, defined there.

// slot 372 0x1026b210 (walked) `Vector EyeDirection2D()`
//   layer 5, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::EyeDirection2D`, written by hand in the substrate.
// Declared here, defined there.

// slot 373 0x1026b240 (walked) `Vector EyeDirection3D()`
//   layer 4, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::EyeDirection3D`, written by hand in the substrate.
// Declared here, defined there.

// slot 375 0x10271f50 (walked) `Activity NPC_EarlyTranslateActivity(Activity)`
//   layer 0, story 29c
int32 FElysiumNpcBase::NPC_EarlyTranslateActivity(int32)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::NPC_EarlyTranslateActivity"), TEXT("0x10271f50"),
		TEXT("29c"), DebugString());
	return {};
}

// slot 376 0x10271f70 (sdk) `Activity NPC_TranslateActivity(Activity)`
//   layer 5, story 29c
int32 FElysiumNpcBase::NPC_TranslateActivity(int32)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::NPC_TranslateActivity"), TEXT("0x10271f70"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 390 0x10265ed0 (walked) `int OnTakeDamage_Alive(const CTakeDamageInfo&)`
//   takes `const CTakeDamageInfo&`
//   layer 23, story 29e
int32 FElysiumNpcBase::OnTakeDamage_Alive(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::OnTakeDamage_Alive"), TEXT("0x10265ed0"), TEXT("29e"),
		DebugString());
	return {};
}

// slot 392 0x102664c0 (sdk) `int OnTakeDamage_Dead(CTakeDamageInfo&)`
//   takes `CTakeDamageInfo&`
//   layer 9, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::OnTakeDamage_Dead`, written by hand in the
// substrate. Declared here, defined there.

// slot 402 0x102658f0 (walked) `bool Event_Gibbed()`
//   layer 15, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::Event_Gibbed`, written by hand in the substrate.
// Declared here, defined there.

// slot 406 0x1027e740 (walked) `const char* GetStateName(NPC_STATE)`
//   layer 1, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetStateName`, written by hand in the substrate.
// Declared here, defined there.

// slot 407 0x1027e7d0 (walked) `const char* GetNavTypeName(Navigation_t)`
//   takes `Navigation_t`
//   layer 1, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetNavTypeName`, written by hand in the substrate.
// Declared here, defined there.

// slot 408 0x1027ede0 (walked) `const char* GetShortConditionName(int)`
//   layer 1, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetShortConditionName`, written by hand in the
// substrate. Declared here, defined there.

// slot 409 0x1027ee00 (walked) `int GetLastSharedCondition()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0x77;`
int32 FElysiumNpcBase::GetLastSharedCondition()
{
	return static_cast<int32>(0x77);
}

// slot 410 0x101a6420 (walked) `const Vector* TranslateNavGoalPosition(const Vector*)`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::TranslateNavGoalPosition`, written by hand in the
// substrate. Declared here, defined there.

// slot 411 0x10280fd0 (walked) `void vfunc411()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::Slot411()
{
}

// slot 412 0x101a6440 (walked) `float GetLastUpdateThink()`
//   layer 1, story 29c
float FElysiumNpcBase::GetLastUpdateThink()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetLastUpdateThink"), TEXT("0x101a6440"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 413 0x101a6460 (walked) `float GetLastNormalThink()`
//   layer 1, story 29c
float FElysiumNpcBase::GetLastNormalThink()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetLastNormalThink"), TEXT("0x101a6460"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 414 0x101a6480 (walked) `float GetLastMoveThink()`
//   layer 1, story 29c
float FElysiumNpcBase::GetLastMoveThink()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetLastMoveThink"), TEXT("0x101a6480"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 415 0x101a64a0 (walked) `float GetLastAIThink()`
//   layer 1, story 29c
float FElysiumNpcBase::GetLastAIThink()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetLastAIThink"), TEXT("0x101a64a0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 416 0x101a64c0 (walked) `void SetForceFrequentThink(bool)`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::SetForceFrequentThink(bool)
{
}

// slot 417 0x101a64e0 (walked) `bool GetForceFrequentThink()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
bool FElysiumNpcBase::GetForceFrequentThink()
{
	return false;
}

// slot 418 0x102702d0 (walked) `float ResolveTaskDistance(float)`
//   layer 1, story 29c
float FElysiumNpcBase::ResolveTaskDistance(float)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::ResolveTaskDistance"), TEXT("0x102702d0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 419 0x101a6500 (walked) `void UpdateBurstShootPause()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::UpdateBurstShootPause()
{
}

// slot 420 0x10273390 (sdk) `void NPCInit()`
//   layer 20, story 29e
// verdict `rule`: the body is `FElysiumNpcBase::NPCInit`, written by hand in the substrate.
// Declared here, defined there.

// slot 421 0x101a6540 (sdk) `void PostNPCInit()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::PostNPCInit()
{
}

// slot 422 0x10273ad0 (walked) `void StartNPC()`
//   layer 20, story 29e
// verdict `rule`: the body is `FElysiumNpcBase::StartNPC`, written by hand in the substrate.
// Declared here, defined there.

// slot 423 0x1027e120 (walked) `bool IsTemplate()`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::IsTemplate`, written by hand in the substrate.
// Declared here, defined there.

// slot 424 0x1027cae0 (walked) `bool CreateComponents()`
//   layer 7, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CreateComponents`, written by hand in the
// substrate. Declared here, defined there.

// slot 425 0x1027cc10 (walked) `CAI_Senses* CreateSenses()`
//   returns `CAI_Senses*`
//   layer 5, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CreateSenses`, written by hand in the
// substrate. Declared here, defined there.

// slot 426 0x1027cef0 (walked) `CAI_MoveProbe* CreateMoveProbe()`
//   returns `CAI_MoveProbe*`
//   layer 5, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CreateMoveProbe`, written by hand in the
// substrate. Declared here, defined there.

// slot 427 0x1027cec0 (walked) `CAI_Motor* CreateMotor()`
//   returns `CAI_Motor*`
//   layer 5, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CreateMotor`, written by hand in the
// substrate. Declared here, defined there.

// slot 428 0x1027cf60 (walked) `CAI_LocalNavigator* CreateLocalNavigator()`
//   returns `CAI_LocalNavigator*`
//   layer 5, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CreateLocalNavigator`, written by hand in the
// substrate. Declared here, defined there.

// slot 429 0x1027cf90 (walked) `CAI_Navigator* CreateNavigator()`
//   returns `CAI_Navigator*`
//   layer 6, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CreateNavigator`, written by hand in the
// substrate. Declared here, defined there.

// slot 430 0x1027cfc0 (walked) `CAI_Pathfinder* CreatePathfinder()`
//   returns `CAI_Pathfinder*`
//   layer 5, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CreatePathfinder`, written by hand in the
// substrate. Declared here, defined there.

// slot 431 0x1026ca80 (sdk) `void NPCThink()`
//   layer 25, story 29e
void FElysiumNpcBase::NPCThink()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::NPCThink"), TEXT("0x1026ca80"), TEXT("29e"),
		DebugString());
}

// slot 432 0x1026f110 (walked) `void RunAI(bool)`
//   layer 24, story 29e
void FElysiumNpcBase::RunAI(bool)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::RunAI"), TEXT("0x1026f110"), TEXT("29e"), DebugString());
}

// slot 433 0x1026ec30 (sdk) `void GatherConditions()`
//   layer 23, story 29e
void FElysiumNpcBase::GatherConditions()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GatherConditions"), TEXT("0x1026ec30"), TEXT("29e"),
		DebugString());
}

// slot 434 0x101a6560 (sdk) `void PrescheduleThink()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::PrescheduleThink()
{
}

// slot 436 0x101a6580 (walked) `void OnStartSchedule(int)`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::OnStartSchedule(int32)
{
}

// slot 437 0x1028a2a0 (walked) `int PreSelectSchedule()`
//   layer 2, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::PreSelectSchedule`, written by hand in the
// substrate. Declared here, defined there.

// slot 439 0x1028abe0 (sdk) `int SelectFailSchedule(int, int, AI_TaskFailureCode_t)`
//   takes `AI_TaskFailureCode_t`
//   layer 0, story 29c
// verdict `present`: the body is `FElysiumNpcBase::SelectFailSchedule`, written by hand in the
// substrate. Declared here, defined there.

// slot 441 0x101a65a0 (walked) `int StartTask(Task_t*)`
//   takes `Task_t*`
//   layer 25, story 29e
int32 FElysiumNpcBase::StartTask(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::StartTask"), TEXT("0x101a65a0"), TEXT("29e"),
		DebugString());
	return {};
}

// slot 442 0x102827f0 (sdk) `int StartTask(Task_t*)`
//   slot 441 declares the same method; which body is which is unrecovered
//   takes `Task_t*`
//   layer 24, story 29e
int32 FElysiumNpcBase::StartTaskSlot442(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::StartTaskSlot442"), TEXT("0x102827f0"), TEXT("29e"),
		DebugString());
	return {};
}

// slot 443 0x101a65e0 (walked) `int RunTask(Task_t*)`
//   takes `Task_t*`
//   layer 23, story 29e
int32 FElysiumNpcBase::RunTask(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::RunTask"), TEXT("0x101a65e0"), TEXT("29e"),
		DebugString());
	return {};
}

// slot 444 0x10288780 (sdk) `int RunTask(Task_t*)`
//   slot 443 declares the same method; which body is which is unrecovered
//   takes `Task_t*`
//   layer 22, story 29e
int32 FElysiumNpcBase::RunTaskSlot444(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::RunTaskSlot444"), TEXT("0x10288780"), TEXT("29e"),
		DebugString());
	return {};
}

// slot 445 0x10288710 (walked) `void StartTaskOverlay()`
//   layer 10, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::StartTaskOverlay`, written by hand in the
// substrate. Declared here, defined there.

// slot 446 0x102cc260 (sdk) `CAI_Schedule* GetScheduleOfType(int)`
//   returns `CAI_Schedule*`
//   layer 4, story 29c
// verdict `present`: the body is `FElysiumNpcBase::GetScheduleOfType`, written by hand in the
// substrate. Declared here, defined there.

// slot 447 0x101a6620 (walked) `int GetLocalScheduleId(int)`
//   layer 1, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::GetLocalScheduleId`, written by hand in the
// substrate. Declared here, defined there.

// slot 449 0x102cc350 (sdk) `char* TaskName(int)`
//   layer 3, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::TaskName`, written by hand in the substrate.
// Declared here, defined there.

// slot 450 0x101a6640 (walked) `int GetLocalTaskId(int)`
//   layer 1, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetLocalTaskId`, written by hand in the substrate.
// Declared here, defined there.

// slot 451 0x101a6660 (sdk) `char* GetSchedulingErrorName()`
//   layer 0, story 29c
TCHAR* FElysiumNpcBase::GetSchedulingErrorName()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetSchedulingErrorName"), TEXT("0x101a6660"),
		TEXT("29c"), DebugString());
	return {};
}

// slot 452 0x1027c2e0 (sdk) `bool LoadedSchedules()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 1;`
bool FElysiumNpcBase::LoadedSchedules()
{
	return true;
}

// slot 454 0x101a6680 (walked) `CAI_BehaviorBase* GetRunningBehavior()`
//   returns `CAI_BehaviorBase*`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
void* FElysiumNpcBase::GetRunningBehavior()
{
	return nullptr;
}

// slot 455 0x101a66a0 (walked) `bool OnBehaviorChangeStatus(CAI_BehaviorBase*, bool)`
//   takes `CAI_BehaviorBase*`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
bool FElysiumNpcBase::OnBehaviorChangeStatus(void*, bool)
{
	return false;
}

// slot 456 0x101a66c0 (walked) `CAI_BehaviorBase** AccessBehaviors()`
//   returns `CAI_BehaviorBase**`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
void* FElysiumNpcBase::AccessBehaviors()
{
	return nullptr;
}

// slot 457 0x101a66e0 (walked) `int NumBehaviors()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
int32 FElysiumNpcBase::NumBehaviors()
{
	return static_cast<int32>(0);
}

// slot 458 0x102cc300 (walked) `const char* ConditionName(int)`
//   layer 3, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::ConditionName`, written by hand in the substrate.
// Declared here, defined there.

// slot 459 0x1026d7f0 (walked) `void RemoveIgnoredConditions()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::RemoveIgnoredConditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 460 0x1026f590 (walked) `NPC_STATE PreSelectIdealState()`
//   layer 21, story 29e
// verdict `rule`: the body is `FElysiumNpcBase::PreSelectIdealState`, written by hand in the
// substrate. Declared here, defined there.

// slot 461 0x1026f660 (walked) `NPC_STATE SelectIdealState()`
//   layer 21, story 29e
// verdict `rule`: the body is `FElysiumNpcBase::SelectIdealState`, written by hand in the
// substrate. Declared here, defined there.

// slot 462 0x101a6700 (sdk) `bool ShouldGoToIdleState()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 0;`
bool FElysiumNpcBase::ShouldGoToIdleState()
{
	return false;
}

// slot 463 0x1026e3e0 (sdk) `void OnStateChange(NPC_STATE, NPC_STATE)`
//   layer 0, story 29c
void FElysiumNpcBase::OnStateChange(EElysiumNpcState, EElysiumNpcState)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::OnStateChange"), TEXT("0x1026e3e0"), TEXT("29c"),
		DebugString());
}

// slot 464 0x101a6720 (walked) `NPC_STATE GetState()`
//   layer 0, story 29c
// verdict `present`: the body is `FElysiumNpcBase::GetState`, written by hand in the substrate.
// Declared here, defined there.

// slot 465 0x101a6740 (sdk) `void OnChangeActivity(Activity)`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::OnChangeActivity(int32)
{
}

// slot 466 0x10272790 (walked) `bool ShouldMaintainActivity()`
//   layer 1, story 29c
bool FElysiumNpcBase::ShouldMaintainActivity()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::ShouldMaintainActivity"), TEXT("0x10272790"),
		TEXT("29c"), DebugString());
	return {};
}

// slot 467 0x101a6760 (sdk) `bool QueryHearSound(CSound*)`
//   takes `CSound*`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 1;`
bool FElysiumNpcBase::QueryHearSound(void*)
{
	return true;
}

// slot 468 0x101a6780 (walked) `bool QuerySeeEntity(CBaseEntity*)`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 1;`
bool FElysiumNpcBase::QuerySeeEntity(FElysiumEntity*)
{
	return true;
}

// slot 469 0x1026a2c0 (sdk) `void OnLooked(int)`
//   layer 14, story 29d
void FElysiumNpcBase::OnLooked(int32)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::OnLooked"), TEXT("0x1026a2c0"), TEXT("29d"),
		DebugString());
}

// slot 470 0x1026a5e0 (sdk) `void OnListened()`
//   layer 8, story 29c
void FElysiumNpcBase::OnListened()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::OnListened"), TEXT("0x1026a5e0"), TEXT("29c"),
		DebugString());
}

// slot 471 0x1026a8a0 (walked) `float GetReactionDelay()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::GetReactionDelay`, written by hand in the
// substrate. Declared here, defined there.

// slot 472 0x101a67a0 (walked) `void OnSeeEntity(CBaseEntity*)`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::OnSeeEntity(FElysiumEntity*)
{
}

// slot 473 0x1026ae90 (walked) `int GetSoundInterests()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 7;`
int32 FElysiumNpcBase::GetSoundInterests()
{
	return static_cast<int32>(7);
}

// slot 474 0x1026aef0 (walked) `CSound* GetBestSound()`
//   returns `CSound*`
//   layer 3, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::GetBestSound`, written by hand in the substrate.
// Declared here, defined there.

// slot 475 0x1026af30 (walked) `CSound* GetBestScent()`
//   returns `CSound*`
//   layer 3, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::GetBestScent`, written by hand in the substrate.
// Declared here, defined there.

// slot 476 0x101a67c0 (walked) `float HearingSensitivity()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::HearingSensitivity`, written by hand in the
// substrate. Declared here, defined there.

// slot 477 0x1026e5c0 (sdk) `void ClearSenseConditions()`
//   layer 2, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::ClearSenseConditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 478 0x102743c0 (sdk) `CBaseEntity* BestEnemy()`
//   layer 14, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::BestEnemy`, written by hand in the substrate.
// Declared here, defined there.

// slot 479 0x101a6820 (walked) `bool IsValidEnemy(CBaseEntity*)`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 1;`
bool FElysiumNpcBase::IsValidEnemy(FElysiumEntity*)
{
	return true;
}

// slot 480 0x10279d00 (sdk) `bool ShouldChooseNewEnemy()`
//   layer 2, story 29c
// verdict `present`: the body is `FElysiumNpcBase::ShouldChooseNewEnemy`, written by hand in the
// substrate. Declared here, defined there.

// slot 481 0x10270b20 (sdk) `void GatherEnemyConditions(CBaseEntity*)`
//   layer 22, story 29e
void FElysiumNpcBase::GatherEnemyConditions(FElysiumEntity*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GatherEnemyConditions"), TEXT("0x10270b20"), TEXT("29e"),
		DebugString());
}

// slot 482 0x10278090 (walked) `CanPlaySequence_t CanPlaySequence(bool, int)`
//   returns `CanPlaySequence_t`
//   layer 2, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::CanPlaySequence`, written by hand in the substrate.
// Declared here, defined there.

// slot 483 0x101a6840 (walked) `bool CanPlaySentence(bool)`
//   layer 1, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::CanPlaySentence`, written by hand in the substrate.
// Declared here, defined there.

// slot 484 0x10278e30 (walked) `int PlaySentence(const char*, float, float, soundlevel_t,
// CBaseEntity*)`
//   takes `soundlevel_t`
//   layer 5, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::PlaySentence`, written by hand in the substrate.
// Declared here, defined there.

// slot 485 0x10279000 (walked) `int PlayScriptedSentence(const char*, float, float, soundlevel_t,
// bool, CBaseEntity*)`
//   takes `soundlevel_t`
//   layer 6, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::PlayScriptedSentence`, written by hand in the
// substrate. Declared here, defined there.

// slot 486 0x1027a5c0 (walked) `bool FOkToMakeSound()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::FOkToMakeSound`, written by hand in the substrate.
// Declared here, defined there.

// slot 487 0x1027a640 (walked) `void JustMadeSound()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::JustMadeSound`, written by hand in the substrate.
// Declared here, defined there.

// slot 488 0x101a6880 (walked) `void DeathSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::DeathSound()
{
}

// slot 489 0x101a68a0 (walked) `void AlertSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::AlertSound()
{
}

// slot 490 0x101a68c0 (walked) `void IdleSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::IdleSound()
{
}

// slot 491 0x101a68e0 (walked) `void PainSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::PainSound()
{
}

// slot 492 0x101a6900 (walked) `void FearSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::FearSound()
{
}

// slot 493 0x101a6920 (walked) `void LostEnemySound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::LostEnemySound()
{
}

// slot 494 0x101a6940 (walked) `void FoundEnemySound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::FoundEnemySound()
{
}

// slot 495 0x101a6960 (walked) `void SurprisedSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::SurprisedSound()
{
}

// slot 496 0x101a6980 (walked) `void TargetAcquiredSound()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::TargetAcquiredSound()
{
}

// slot 497 0x101a69a0 (walked) `void vfunc497()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::Slot497()
{
}

// slot 498 0x101a69c0 (walked) `void FleeSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::FleeSound()
{
}

// slot 499 0x101a69e0 (walked) `void IdleAgitatedSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::IdleAgitatedSound()
{
}

// slot 500 0x101a6a00 (walked) `void ExertHvySound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::ExertHvySound()
{
}

// slot 501 0x101a6a20 (walked) `void ExertLightSound()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::ExertLightSound()
{
}

// slot 502 0x101a6a40 (walked) `void RiledSound()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::RiledSound()
{
}

// slot 503 0x101a6a60 (walked) `void ComfortSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::ComfortSound()
{
}

// slot 504 0x101a6a80 (walked) `void UpsetSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::UpsetSound()
{
}

// slot 505 0x101a6aa0 (walked) `void TargetGiveUpSound()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::TargetGiveUpSound()
{
}

// slot 506 0x101a6ac0 (walked) `void vfunc506()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::Slot506()
{
}

// slot 507 0x101a6ae0 (walked) `void FloatSound()`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return;`
void FElysiumNpcBase::FloatSound()
{
}

// slot 508 0x101a6b00 (walked) `void SpeakSentence(int)`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::SpeakSentence(int32)
{
}

// slot 509 0x1027a420 (walked) `bool ShouldPlayIdleSound()`
//   layer 2, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::ShouldPlayIdleSound`, written by hand in the
// substrate. Declared here, defined there.

// slot 510 0x1027a530 (walked) `bool ShouldPlayFloatSound()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::ShouldPlayFloatSound`, written by hand in the
// substrate. Declared here, defined there.

// slot 511 0x1027caa0 (walked) `void StopLoopingSounds()`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::StopLoopingSounds`, written by hand in the
// substrate. Declared here, defined there.

// slot 512 0x101a6b20 (walked) `CAI_Expresser* GetExpresser()`
//   returns `CAI_Expresser*`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
void* FElysiumNpcBase::GetExpresser()
{
	return nullptr;
}

// slot 513 0x1026db30 (sdk) `int CapabilitiesGet() const`
//   layer 1, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::CapabilitiesGet`, written by hand in the substrate.
// Declared here, defined there.

// slot 514 0x1027d9d0 (walked) `bool MovementCost(int, const Vector&, const Vector&, float*)`
//   takes `float*`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 0;`
bool FElysiumNpcBase::MovementCost(int32, const FVector&, const FVector&, void*)
{
	return false;
}

// slot 515 0x10274b30 (walked) `float CalcIdealYaw(const Vector&)`
//   layer 1, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::CalcIdealYaw`, written by hand in the
// substrate. Declared here, defined there.

// slot 516 0x10280bb0 (sdk) `float MaxYawSpeed()`
//   layer 0, story 29c
float FElysiumNpcBase::MaxYawSpeed()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::MaxYawSpeed"), TEXT("0x10280bb0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 517 0x10278d90 (walked) `void AddFacingTarget(CBaseEntity*, const Vector&, float, float,
// float)`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::AddFacingTarget`, written by hand in the
// substrate. Declared here, defined there.

// slot 518 0x10278d20 (walked) `void AddFacingTarget(const Vector&, float, float, float)`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::AddFacingTarget`, written by hand in the
// substrate. Declared here, defined there.

// slot 519 0x10278cb0 (walked) `void AddFacingTarget(CBaseEntity*, float, float, float)`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::AddFacingTarget`, written by hand in the substrate.
// Declared here, defined there.

// slot 520 0x10278e00 (sdk) `float GetFacingDirection(Vector&)`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetFacingDirection`, written by hand in the
// substrate. Declared here, defined there.

// slot 521 0x10280880 (sdk) `bool IsJumpLegal(Vector&, Vector&, Vector&) const`
//   layer 2, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::IsJumpLegal`, written by hand in the
// substrate. Declared here, defined there.

// slot 522 0x101a6b40 (sdk) `float StepHeight() const`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::StepHeight`, written by hand in the substrate.
// Declared here, defined there.

// slot 523 0x101a6b60 (sdk) `float GetMaxJumpSpeed() const`
//   layer 0, story 29c
float FElysiumNpcBase::GetMaxJumpSpeed() const
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetMaxJumpSpeed"), TEXT("0x101a6b60"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 524 0x101a6b80 (sdk) `float GetJumpGravity() const`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetJumpGravity`, written by hand in the substrate.
// Declared here, defined there.

// slot 525 0x1027da90 (sdk) `bool OverrideMove(float)`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::OverrideMove`, written by hand in the
// substrate. Declared here, defined there.

// slot 526 0x1027d9f0 (sdk) `bool OverrideMoveFacing(AILocalMoveGoal_t&, float)`
//   takes `AILocalMoveGoal_t&`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::OverrideMoveFacing`, written by hand in the
// substrate. Declared here, defined there.

// slot 527 0x101a6ba0 (walked) `bool IsUnusableNode(CAI_Node*)`
//   takes `CAI_Node*`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 0;`
bool FElysiumNpcBase::IsUnusableNode(void*)
{
	return false;
}

// slot 528 0x10280360 (walked) `bool ValidateNavGoal()`
//   layer 6, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::ValidateNavGoal`, written by hand in the substrate.
// Declared here, defined there.

// slot 529 0x10280330 (walked) `bool IsCurTaskContinuousMove()`
//   layer 1, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::IsCurTaskContinuousMove`, written by hand in the
// substrate. Declared here, defined there.

// slot 530 0x102741e0 (sdk) `bool IsUnreachable(CBaseEntity*)`
//   layer 1, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::IsUnreachable`, written by hand in the substrate.
// Declared here, defined there.

// slot 531 0x1027dc80 (walked) `bool OnObstructingDoor(AILocalMoveGoal_t*, CBaseDoor*, float,
// AIMoveResult_t*)`
//   takes `AILocalMoveGoal_t*`
//   takes `AIMoveResult_t*`
//   layer 0, story 29c
bool FElysiumNpcBase::OnObstructingDoor(void*, FElysiumEntity*, float, void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::OnObstructingDoor"), TEXT("0x1027dc80"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 532 0x1027e0f0 (walked) `void vfunc532(int)`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::Slot532`, written by hand in the substrate.
// Declared here, defined there.

// slot 533 0x10274db0 (walked) `Vector EyeOffset(Activity, Activity)`
//   layer 2, story 29c
FVector FElysiumNpcBase::EyeOffset(int32, int32)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::EyeOffset"), TEXT("0x10274db0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 535 0x101a6be0 (walked) `void AddLookTarget(const Vector&, float, float, float)`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::AddLookTarget(const FVector&, float, float, float)
{
}

// slot 536 0x101a6bc0 (walked) `void AddLookTarget(CBaseEntity*, float, float, float)`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::AddLookTarget(FElysiumEntity*, float, float, float)
{
}

// slot 537 0x1026af70 (sdk) `void SetHeadDirection(Vector&, float)`
//   layer 3, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::SetHeadDirection`, written by hand in the
// substrate. Declared here, defined there.

// slot 538 0x1026b4f0 (walked) `void AimGun()`
//   layer 13, story 29d
// verdict `mechanism`: the body is `FElysiumNpcBase::AimGun`, written by hand in the substrate.
// Declared here, defined there.

// slot 539 0x1026b480 (walked) `void SetAim(const Vector&)`
//   layer 2, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::SetAim`, written by hand in the substrate.
// Declared here, defined there.

// slot 540 0x10279060 (walked) `float PlayScene(const char*)`
//   layer 4, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::PlayScene`, written by hand in the substrate.
// Declared here, defined there.

// slot 541 0x10273e10 (walked) `CAI_Enemies* GetEnemies()`
//   returns `CAI_Enemies*`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::GetEnemies`, written by hand in the substrate.
// Declared here, defined there.

// slot 542 0x10273dd0 (walked) `void vfunc542()`
//   layer 5, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::Slot542`, written by hand in the substrate.
// Declared here, defined there.

// slot 543 0x10273e40 (walked) `void RemoveMemory()`
//   layer 5, story 29c
// verdict `mechanism`: the body is `FElysiumNpcBase::RemoveMemory`, written by hand in the
// substrate. Declared here, defined there.

// slot 544 0x102709c0 (walked) `bool UpdateEnemyMemory(CBaseEntity*, const Vector&, CBaseEntity*)`
//   layer 10, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::UpdateEnemyMemory`, written by hand in the
// substrate. Declared here, defined there.

// slot 545 0x10273d30 (sdk) `bool InitSquad()`
//   layer 8, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::InitSquad`, written by hand in the substrate.
// Declared here, defined there.

// slot 546 0x101a6c00 (walked) `const char* SquadSlotName(int)`
//   layer 3, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::SquadSlotName`, written by hand in the substrate.
// Declared here, defined there.

// slot 547 0x1028b0f0 (walked) `int GetSlotSchedule(int)`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetSlotSchedule`, written by hand in the substrate.
// Declared here, defined there.

// slot 548 0x1028af20 (walked) `bool IsValidCover(const Vector&, const CAI_Hint*)`
//   takes `const CAI_Hint*`
//   layer 4, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::IsValidCover`, written by hand in the substrate.
// Declared here, defined there.

// slot 549 0x1028b0b0 (walked) `bool IsValidShootPosition(const Vector&, const CAI_Hint*)`
//   takes `const CAI_Hint*`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::IsValidShootPosition`, written by hand in the
// substrate. Declared here, defined there.

// slot 550 0x101a6c20 (walked) `float CoverRadius()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::CoverRadius`, written by hand in the substrate.
// Declared here, defined there.

// slot 551 0x101a6c40 (walked) `void OnChangeHintGroup(string_t, string_t)`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::OnChangeHintGroup(FName, FName)
{
}

// slot 552 0x1027a400 (walked) `bool ShouldFadeOnDeath()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::ShouldFadeOnDeath`, written by hand in the
// substrate. Declared here, defined there.

// slot 553 0x1026d890 (walked) `int RangeAttack1Conditions(float, float)`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::RangeAttack1Conditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 554 0x1026d920 (walked) `int RangeAttack2Conditions(float, float)`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::RangeAttack2Conditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 555 0x1026d9a0 (walked) `int MeleeAttack1Conditions(float, float)`
//   layer 1, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::MeleeAttack1Conditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 556 0x1026da90 (walked) `int MeleeAttack2Conditions(float, float)`
//   layer 1, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::MeleeAttack2Conditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 557 0x101a6c60 (walked) `bool OnBeginMoveAndShoot()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return 1;`
bool FElysiumNpcBase::OnBeginMoveAndShoot()
{
	return true;
}

// slot 558 0x101a6c80 (walked) `void OnEndMoveAndShoot()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::OnEndMoveAndShoot()
{
}

// slot 559 0x10279090 (walked) `CBaseEntity* FindNamedEntity(const char*)`
//   layer 9, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::FindNamedEntity`, written by hand in the substrate.
// Declared here, defined there.

// slot 560 0x1026dc80 (sdk) `void ClearAttackConditions()`
//   layer 2, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::ClearAttackConditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 561 0x1026dd10 (sdk) `void GatherAttackConditions(CBaseEntity*, float)`
//   layer 4, story 29c
// verdict `present`: the body is `FElysiumNpcBase::GatherAttackConditions`, written by hand in the
// substrate. Declared here, defined there.

// slot 562 0x1026fbe0 (walked) `bool WeaponLOSCondition(const Vector&, const Vector&, bool)`
//   layer 15, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::WeaponLOSCondition`, written by hand in the
// substrate. Declared here, defined there.

// slot 563 0x10289f20 (walked) `void TranslateEnemyChasePosition(CBaseEntity*, Vector&, float&,
// float*)`
//   takes `float&`
//   takes `float*`
//   layer 1, story 29c
void FElysiumNpcBase::TranslateEnemyChasePosition(FElysiumEntity*, FVector&, void*, void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::TranslateEnemyChasePosition"), TEXT("0x10289f20"),
		TEXT("29c"), DebugString());
}

// slot 564 0x10270840 (walked) `bool FCanCheckAttacks()`
//   layer 2, story 29c
bool FElysiumNpcBase::FCanCheckAttacks()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::FCanCheckAttacks"), TEXT("0x10270840"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 565 0x101a6ca0 (walked) `void CheckAmmo()`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::CheckAmmo()
{
}

// slot 566 0x1026a8d0 (sdk) `bool FValidateHintType(CAI_Hint*)`
//   takes `CAI_Hint*`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 0;`
bool FElysiumNpcBase::FValidateHintType(void*)
{
	return false;
}

// slot 567 0x1026a8f0 (walked) `Activity GetHintActivity(short)`
//   layer 0, story 29c
// verdict `rule`: retail's whole body is `return 1;`
int32 FElysiumNpcBase::GetHintActivity(int16)
{
	return static_cast<int32>(1);
}

// slot 568 0x1026a910 (walked) `float GetHintDelay(short)`
//   layer 0, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::GetHintDelay`, written by hand in the substrate.
// Declared here, defined there.

// slot 569 0x10274aa0 (walked) `Activity GetCoverActivity(CAI_Hint*)`
//   takes `CAI_Hint*`
//   layer 1, story 29c
int32 FElysiumNpcBase::GetCoverActivity(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetCoverActivity"), TEXT("0x10274aa0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 570 0x10274820 (walked) `Activity GetReloadActivity(CAI_Hint*)`
//   takes `CAI_Hint*`
//   layer 4, story 29c
int32 FElysiumNpcBase::GetReloadActivity(void*)
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetReloadActivity"), TEXT("0x10274820"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 571 0x10289ce0 (walked) `Activity vfunc571(float)`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::Slot571`, written by hand in the substrate.
// Declared here, defined there.

// slot 572 0x10289d10 (walked) `void SetTurnActivity()`
//   layer 18, story 29d
void FElysiumNpcBase::SetTurnActivity()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::SetTurnActivity"), TEXT("0x10289d10"), TEXT("29d"),
		DebugString());
}

// slot 573 0x1026fcf0 (walked) `bool InnateWeaponLOSCondition(const Vector&, const Vector&, bool)`
//   layer 14, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::InnateWeaponLOSCondition`, written by hand in the
// substrate. Declared here, defined there.

// slot 574 0x10278900 (walked) `Vector GetShootEnemyDir(const Vector&, int, int)`
//   layer 12, story 29d
// verdict `rule`: the body is `FElysiumNpcBase::GetShootEnemyDir`, written by hand in the
// substrate. Declared here, defined there.

// slot 575 0x10278c60 (walked) `bool ShouldMoveAndShoot()`
//   layer 2, story 29c
bool FElysiumNpcBase::ShouldMoveAndShoot()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::ShouldMoveAndShoot"), TEXT("0x10278c60"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 576 0x10266630 (walked) `bool IsLightDamage(float, int)`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::IsLightDamage`, written by hand in the substrate.
// Declared here, defined there.

// slot 577 0x10266660 (walked) `bool IsHeavyDamage(float, int)`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumNpcBase::IsHeavyDamage`, written by hand in the substrate.
// Declared here, defined there.

// slot 578 0x101a6cc0 (walked) `void NotifyDeadFriend(CBaseEntity*)`
//   layer 0, story 29c
// verdict `dead`: retail's whole body is `return;`
void FElysiumNpcBase::NotifyDeadFriend(FElysiumEntity*)
{
}

// slot 579 0x101a6ce0 (walked) `bool vfunc579(int)`
//   layer 1, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::Slot579`, written by hand in the substrate.
// Declared here, defined there.

// slot 580 0x101a6d00 (walked) `CAI_ClassScheduleIdSpace* GetClassScheduleIdSpace()`
//   returns `CAI_ClassScheduleIdSpace*`
//   layer 0, story 29c
void* FElysiumNpcBase::GetClassScheduleIdSpace()
{
	FireKernelBaseSlot(TEXT("CAI_BaseNPC::GetClassScheduleIdSpace"), TEXT("0x101a6d00"),
		TEXT("29c"), DebugString());
	return {};
}

// slot 581 0x102779a0 (walked) `void ReportAIState()`
//   layer 4, story 29c
// verdict `dead`: the body is `FElysiumNpcBase::ReportAIState`, written by hand in the substrate.
// Declared here, defined there.
