// Generated by `uv run elysium research gen_kernel_bindings`. Do not hand-edit.
//
// The datamap-backed field/input bindings of the port's NPC-family classes, transcribed from the
// datamap replay (`research/ghidra/types/datamap_records-vampire.dll.json`; CBaseEntity 0x10552e18,
// CBaseToggle 0x1059b6f0, CBaseAnimating 0x1054cd70, CBaseCombatCharacter 0x1061664c, CAI_BaseNPC
// 0x105c9814, CAI_BaseNPCTroika 0x105ce470, CNPCMaker 0x10624718, CAI_InterestingPlace 0x1060bdd8,
// CAI_Hint 0x106099f0, CAI_InterestingPlaceConverstation 0x1060c2c0, CNPCMaker_Zombie 0x106253e8).
// The replay carries no module hash line, so the datamap addresses are the provenance this file
// holds.

#pragma once

#include "Containers/ArrayView.h"

struct FElysiumClassDesc;

namespace ElysiumNpcKernelBindings
{
	enum class EClass : uint8 { BaseEntity, Toggle, Animating, CombatCharacter, Npc, NpcMaker,
		InterestingPlace, Hint, ConversationPlace, NpcMakerZombie };

	void AddBaseEntityFields(FElysiumClassDesc& D);
	void AddToggleFields(FElysiumClassDesc& D);
	void AddAnimatingFields(FElysiumClassDesc& D);
	void AddCombatCharacterFields(FElysiumClassDesc& D);
	void AddNpcFields(FElysiumClassDesc& D);
	void AddNpcMakerFields(FElysiumClassDesc& D);
	void AddInterestingPlaceFields(FElysiumClassDesc& D);
	void AddHintFields(FElysiumClassDesc& D);
	void AddConversationPlaceFields(FElysiumClassDesc& D);
	void AddNpcMakerZombieFields(FElysiumClassDesc& D);
	void AddNpcSaveFields(FElysiumClassDesc& D);
	TConstArrayView<const TCHAR*> Outputs(EClass Class = EClass::Npc);
	TConstArrayView<const TCHAR*> InputFuncs(EClass Class = EClass::Npc);
	struct FCounts
	{
		int32 Bound;
		int32 Unbound;
		int32 Outputs;
		int32 InputFuncs;
		int32 Saved;
	};
	FCounts Counts(EClass Class = EClass::Npc);
}
