// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 182 generated slot rows of `FElysiumNpcBase` (CAI_BaseNPC): 157 it introduces and 25 it overrides
// with a body of its own.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// This file is included INSIDE `class FElysiumNpcBase` (`Substrate/ElysiumNpcBase.h`). It is not
// a header: it has no include guard and declares nothing of its own. One declaration per
// slot, in slot order, with the retail declaration in the comment and the port's lowered
// signature in the code.
//
// Each slot is declared by the port class of the retail class that introduces it, with that
// class's own body, and overridden by every port class whose retail table holds another
// body there (story 0019/5 step 6). The stub names the retail class that owns its body.
//
// A body lands on one of these in 29c/29d/29e. Until then the definition in
// `ElysiumNpcBaseSlots.cpp` tallies `elysium.stubs` with the retail address — except
// where the verdict overlay records that retail's whole body is one literal, which the
// generator emits, or that the body is written by hand in the substrate, in which case no
// definition is generated at all and the linker is what checks the claim.

	// slot 126 0x1027bc60 (sdk) `int Save(ISave&)`
	//   takes `ISave&`
	//   layer 15, story 29d
	int32 Save(void*) override;
	// slot 128 0x101a6520 (sdk) `bool ShouldSavePhysics()`
	//   layer 0, story 29c
	bool ShouldSavePhysics() override;
	// slot 130 0x1027bf50 (walked) `void OnRestore(bool)`
	//   layer 21, story 29e
	void OnRestore(bool) override;
	// slot 136 0x101a6860 (walked) `bool vfunc136()`
	//   layer 0, story 29c
	bool Slot136() override;
	// slot 141 0x10266780 (walked) `void TraceAttack(const CTakeDamageInfo&, const Vector&,
	// trace_t*)`
	//   takes `const CTakeDamageInfo&`
	//   takes `trace_t*`
	//   layer 8, story 29c
	void TraceAttack(void*, const FVector&, void*) override;
	// slot 142 0x10265e90 (sdk) `int OnTakeDamage(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 24, story 29e
	int32 OnTakeDamage(void*) override;
	// slot 144 0x10265ad0 (sdk) `void Event_Killed(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 20, story 29e
	void Event_Killed(void*) override;
	// slot 153 0x10280300 (walked) `bool IsMoving()`
	//   layer 2, story 29c
	bool IsMoving() override;
	// slot 167 0x101a67e0 (walked) `CBaseEntity* GetEnemy() const`
	//   layer 0, story 29c
	FElysiumEntity* GetEnemy() const override;
	// slot 180 0x1027ca30 (sdk) `void UpdateOnRemove()`
	//   layer 6, story 29c
	void UpdateOnRemove() override;
	// slot 197 0x102789c0 (walked) `Vector BodyTarget(const Vector&, bool, bool)`
	//   layer 9, story 29c
	FVector BodyTarget(const FVector&, bool, bool) override;
	// slot 223 0x10273720 (walked) `bool CreateVPhysics()`
	//   layer 13, story 29d
	bool CreateVPhysics() override;
	// slot 251 0x10272900 (walked) `bool IsActivityFinished()`
	//   layer 0, story 29c
	bool IsActivityFinished() override;
	// slot 310 0x102725d0 (sdk) `void SetActivity(Activity)`
	//   layer 16, story 29d
	void SetActivity(int32) override;
	// slot 311 0x10272400 (walked) `void ForcePreTranslatedSequenceAndActivity(Activity, Activity,
	// int)`
	//   layer 6, story 29c
	void ForcePreTranslatedSequenceAndActivity(int32, int32, int32) override;
	// slot 333 0x1026b810 (walked) `void MaintainEyeDirection(float)`
	//   layer 4, story 29c
	void MaintainEyeDirection(float) override;
	// slot 354 0x1026cec0 (walked) `void vfunc354()`
	//   layer 21, story 29e
	void Slot354() override;
	// slot 355 0x1026cf90 (walked) `void vfunc355()`
	//   layer 8, story 29c
	void Slot355() override;
	// slot 372 0x1026b210 (walked) `Vector EyeDirection2D()`
	//   layer 5, story 29c
	FVector EyeDirection2D() override;
	// slot 373 0x1026b240 (walked) `Vector EyeDirection3D()`
	//   layer 4, story 29c
	FVector EyeDirection3D() override;
	// slot 375 0x10271f50 (walked) `Activity NPC_EarlyTranslateActivity(Activity)`
	//   layer 0, story 29c
	int32 NPC_EarlyTranslateActivity(int32) override;
	// slot 376 0x10271f70 (sdk) `Activity NPC_TranslateActivity(Activity)`
	//   layer 5, story 29c
	int32 NPC_TranslateActivity(int32) override;
	// slot 390 0x10265ed0 (walked) `int OnTakeDamage_Alive(const CTakeDamageInfo&)`
	//   takes `const CTakeDamageInfo&`
	//   layer 23, story 29e
	int32 OnTakeDamage_Alive(void*) override;
	// slot 392 0x102664c0 (sdk) `int OnTakeDamage_Dead(CTakeDamageInfo&)`
	//   takes `CTakeDamageInfo&`
	//   layer 9, story 29c
	int32 OnTakeDamage_Dead(void*) override;
	// slot 402 0x102658f0 (walked) `bool Event_Gibbed()`
	//   layer 15, story 29d
	bool Event_Gibbed() override;
	// slot 406 0x1027e740 (walked) `const char* GetStateName(NPC_STATE)`
	//   layer 1, story 29c
	virtual const TCHAR* GetStateName(EElysiumNpcState);
	// slot 407 0x1027e7d0 (walked) `const char* GetNavTypeName(Navigation_t)`
	//   takes `Navigation_t`
	//   layer 1, story 29c
	virtual const TCHAR* GetNavTypeName(int32);
	// slot 408 0x1027ede0 (walked) `const char* GetShortConditionName(int)`
	//   layer 1, story 29c
	virtual const TCHAR* GetShortConditionName(int32);
	// slot 409 0x1027ee00 (walked) `int GetLastSharedCondition()`
	//   layer 0, story 29c
	virtual int32 GetLastSharedCondition();
	// slot 410 0x101a6420 (walked) `const Vector* TranslateNavGoalPosition(const Vector*)`
	//   layer 0, story 29c
	virtual const FVector* TranslateNavGoalPosition(const FVector*);
	// slot 411 0x10280fd0 (walked) `void vfunc411()`
	//   layer 0, story 29c
	virtual void Slot411();
	// slot 412 0x101a6440 (walked) `float GetLastUpdateThink()`
	//   layer 1, story 29c
	virtual float GetLastUpdateThink();
	// slot 413 0x101a6460 (walked) `float GetLastNormalThink()`
	//   layer 1, story 29c
	virtual float GetLastNormalThink();
	// slot 414 0x101a6480 (walked) `float GetLastMoveThink()`
	//   layer 1, story 29c
	virtual float GetLastMoveThink();
	// slot 415 0x101a64a0 (walked) `float GetLastAIThink()`
	//   layer 1, story 29c
	virtual float GetLastAIThink();
	// slot 416 0x101a64c0 (walked) `void SetForceFrequentThink(bool)`
	//   layer 0, story 29c
	virtual void SetForceFrequentThink(bool);
	// slot 417 0x101a64e0 (walked) `bool GetForceFrequentThink()`
	//   layer 0, story 29c
	virtual bool GetForceFrequentThink();
	// slot 418 0x102702d0 (walked) `float ResolveTaskDistance(float)`
	//   layer 1, story 29c
	virtual float ResolveTaskDistance(float);
	// slot 419 0x101a6500 (walked) `void UpdateBurstShootPause()`
	//   layer 0, story 29c
	virtual void UpdateBurstShootPause();
	// slot 420 0x10273390 (sdk) `void NPCInit()`
	//   layer 20, story 29e
	virtual void NPCInit();
	// slot 421 0x101a6540 (sdk) `void PostNPCInit()`
	//   layer 0, story 29c
	virtual void PostNPCInit();
	// slot 422 0x10273ad0 (walked) `void StartNPC()`
	//   layer 20, story 29e
	virtual void StartNPC();
	// slot 423 0x1027e120 (walked) `bool IsTemplate()`
	//   layer 0, story 29c
	virtual bool IsTemplate();
	// slot 424 0x1027cae0 (walked) `bool CreateComponents()`
	//   layer 7, story 29c
	virtual bool CreateComponents();
	// slot 425 0x1027cc10 (walked) `CAI_Senses* CreateSenses()`
	//   returns `CAI_Senses*`
	//   layer 5, story 29c
	virtual void* CreateSenses();
	// slot 426 0x1027cef0 (walked) `CAI_MoveProbe* CreateMoveProbe()`
	//   returns `CAI_MoveProbe*`
	//   layer 5, story 29c
	virtual void* CreateMoveProbe();
	// slot 427 0x1027cec0 (walked) `CAI_Motor* CreateMotor()`
	//   returns `CAI_Motor*`
	//   layer 5, story 29c
	virtual void* CreateMotor();
	// slot 428 0x1027cf60 (walked) `CAI_LocalNavigator* CreateLocalNavigator()`
	//   returns `CAI_LocalNavigator*`
	//   layer 5, story 29c
	virtual void* CreateLocalNavigator();
	// slot 429 0x1027cf90 (walked) `CAI_Navigator* CreateNavigator()`
	//   returns `CAI_Navigator*`
	//   layer 6, story 29c
	virtual void* CreateNavigator();
	// slot 430 0x1027cfc0 (walked) `CAI_Pathfinder* CreatePathfinder()`
	//   returns `CAI_Pathfinder*`
	//   layer 5, story 29c
	virtual void* CreatePathfinder();
	// slot 431 0x1026ca80 (sdk) `void NPCThink()`
	//   layer 25, story 29e
	virtual void NPCThink();
	// slot 432 0x1026f110 (walked) `void RunAI(bool)`
	//   layer 24, story 29e
	virtual void RunAI(bool);
	// slot 433 0x1026ec30 (sdk) `void GatherConditions()`
	//   layer 23, story 29e
	virtual void GatherConditions();
	// slot 434 0x101a6560 (sdk) `void PrescheduleThink()`
	//   layer 0, story 29c
	virtual void PrescheduleThink();
	// slot 436 0x101a6580 (walked) `void OnStartSchedule(int)`
	//   layer 0, story 29c
	virtual void OnStartSchedule(int32);
	// slot 437 0x1028a2a0 (walked) `int PreSelectSchedule()`
	//   layer 2, story 29c
	virtual int32 PreSelectSchedule();
	// slot 439 0x1028abe0 (sdk) `int SelectFailSchedule(int, int, AI_TaskFailureCode_t)`
	//   takes `AI_TaskFailureCode_t`
	//   layer 0, story 29c
	virtual int32 SelectFailSchedule(int32, int32, int32);
	// slot 441 0x101a65a0 (walked) `int StartTask(Task_t*)`
	//   takes `Task_t*`
	//   layer 25, story 29e
	virtual int32 StartTask(void*);
	// slot 442 0x102827f0 (sdk) `int StartTask(Task_t*)`
	//   slot 441 declares the same method; which body is which is unrecovered
	//   takes `Task_t*`
	//   layer 24, story 29e
	virtual int32 StartTaskSlot442(void*);
	// slot 443 0x101a65e0 (walked) `int RunTask(Task_t*)`
	//   takes `Task_t*`
	//   layer 23, story 29e
	virtual int32 RunTask(void*);
	// slot 444 0x10288780 (sdk) `int RunTask(Task_t*)`
	//   slot 443 declares the same method; which body is which is unrecovered
	//   takes `Task_t*`
	//   layer 22, story 29e
	virtual int32 RunTaskSlot444(void*);
	// slot 445 0x10288710 (walked) `void StartTaskOverlay()`
	//   layer 10, story 29d
	virtual void StartTaskOverlay();
	// slot 446 0x102cc260 (sdk) `CAI_Schedule* GetScheduleOfType(int)`
	//   returns `CAI_Schedule*`
	//   layer 4, story 29c
	virtual void* GetScheduleOfType(int32);
	// slot 447 0x101a6620 (walked) `int GetLocalScheduleId(int)`
	//   layer 1, story 29c
	virtual int32 GetLocalScheduleId(int32);
	// slot 449 0x102cc350 (sdk) `char* TaskName(int)`
	//   layer 3, story 29c
	virtual TCHAR* TaskName(int32);
	// slot 450 0x101a6640 (walked) `int GetLocalTaskId(int)`
	//   layer 1, story 29c
	virtual int32 GetLocalTaskId(int32);
	// slot 451 0x101a6660 (sdk) `char* GetSchedulingErrorName()`
	//   layer 0, story 29c
	virtual TCHAR* GetSchedulingErrorName();
	// slot 452 0x1027c2e0 (sdk) `bool LoadedSchedules()`
	//   layer 0, story 29c
	virtual bool LoadedSchedules();
	// slot 454 0x101a6680 (walked) `CAI_BehaviorBase* GetRunningBehavior()`
	//   returns `CAI_BehaviorBase*`
	//   layer 0, story 29c
	virtual void* GetRunningBehavior();
	// slot 455 0x101a66a0 (walked) `bool OnBehaviorChangeStatus(CAI_BehaviorBase*, bool)`
	//   takes `CAI_BehaviorBase*`
	//   layer 0, story 29c
	virtual bool OnBehaviorChangeStatus(void*, bool);
	// slot 456 0x101a66c0 (walked) `CAI_BehaviorBase** AccessBehaviors()`
	//   returns `CAI_BehaviorBase**`
	//   layer 0, story 29c
	virtual void* AccessBehaviors();
	// slot 457 0x101a66e0 (walked) `int NumBehaviors()`
	//   layer 0, story 29c
	virtual int32 NumBehaviors();
	// slot 458 0x102cc300 (walked) `const char* ConditionName(int)`
	//   layer 3, story 29c
	virtual const TCHAR* ConditionName(int32);
	// slot 459 0x1026d7f0 (walked) `void RemoveIgnoredConditions()`
	//   layer 0, story 29c
	virtual void RemoveIgnoredConditions();
	// slot 462 0x101a6700 (sdk) `bool ShouldGoToIdleState()`
	//   layer 0, story 29c
	virtual bool ShouldGoToIdleState();
	// slot 463 0x1026e3e0 (sdk) `void OnStateChange(NPC_STATE, NPC_STATE)`
	//   layer 0, story 29c
	virtual void OnStateChange(EElysiumNpcState, EElysiumNpcState);
	// slot 464 0x101a6720 (walked) `NPC_STATE GetState()`
	//   layer 0, story 29c
	virtual EElysiumNpcState GetState();
	// slot 465 0x101a6740 (sdk) `void OnChangeActivity(Activity)`
	//   layer 0, story 29c
	virtual void OnChangeActivity(int32);
	// slot 466 0x10272790 (walked) `bool ShouldMaintainActivity()`
	//   layer 1, story 29c
	virtual bool ShouldMaintainActivity();
	// slot 467 0x101a6760 (sdk) `bool QueryHearSound(CSound*)`
	//   takes `CSound*`
	//   layer 0, story 29c
	virtual bool QueryHearSound(void*);
	// slot 468 0x101a6780 (walked) `bool QuerySeeEntity(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool QuerySeeEntity(FElysiumEntity*);
	// slot 469 0x1026a2c0 (sdk) `void OnLooked(int)`
	//   layer 14, story 29d
	virtual void OnLooked(int32);
	// slot 470 0x1026a5e0 (sdk) `void OnListened()`
	//   layer 8, story 29c
	virtual void OnListened();
	// slot 471 0x1026a8a0 (walked) `float GetReactionDelay()`
	//   layer 0, story 29c
	virtual float GetReactionDelay();
	// slot 472 0x101a67a0 (walked) `void OnSeeEntity(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void OnSeeEntity(FElysiumEntity*);
	// slot 473 0x1026ae90 (walked) `int GetSoundInterests()`
	//   layer 0, story 29c
	virtual int32 GetSoundInterests();
	// slot 474 0x1026aef0 (walked) `CSound* GetBestSound()`
	//   returns `CSound*`
	//   layer 3, story 29c
	virtual void* GetBestSound();
	// slot 475 0x1026af30 (walked) `CSound* GetBestScent()`
	//   returns `CSound*`
	//   layer 3, story 29c
	virtual void* GetBestScent();
	// slot 476 0x101a67c0 (walked) `float HearingSensitivity()`
	//   layer 0, story 29c
	virtual float HearingSensitivity();
	// slot 477 0x1026e5c0 (sdk) `void ClearSenseConditions()`
	//   layer 2, story 29c
	virtual void ClearSenseConditions();
	// slot 478 0x102743c0 (sdk) `CBaseEntity* BestEnemy()`
	//   layer 14, story 29d
	virtual FElysiumEntity* BestEnemy();
	// slot 479 0x101a6820 (walked) `bool IsValidEnemy(CBaseEntity*)`
	//   layer 0, story 29c
	virtual bool IsValidEnemy(FElysiumEntity*);
	// slot 480 0x10279d00 (sdk) `bool ShouldChooseNewEnemy()`
	//   layer 2, story 29c
	virtual bool ShouldChooseNewEnemy();
	// slot 481 0x10270b20 (sdk) `void GatherEnemyConditions(CBaseEntity*)`
	//   layer 22, story 29e
	virtual void GatherEnemyConditions(FElysiumEntity*);
	// slot 482 0x10278090 (walked) `CanPlaySequence_t CanPlaySequence(bool, int)`
	//   returns `CanPlaySequence_t`
	//   layer 2, story 29c
	virtual int32 CanPlaySequence(bool, int32);
	// slot 483 0x101a6840 (walked) `bool CanPlaySentence(bool)`
	//   layer 1, story 29c
	virtual bool CanPlaySentence(bool);
	// slot 484 0x10278e30 (walked) `int PlaySentence(const char*, float, float, soundlevel_t,
	// CBaseEntity*)`
	//   takes `soundlevel_t`
	//   layer 5, story 29c
	virtual int32 PlaySentence(const TCHAR*, float, float, int32, FElysiumEntity*);
	// slot 485 0x10279000 (walked) `int PlayScriptedSentence(const char*, float, float,
	// soundlevel_t, bool, CBaseEntity*)`
	//   takes `soundlevel_t`
	//   layer 6, story 29c
	virtual int32 PlayScriptedSentence(const TCHAR*, float, float, int32, bool, FElysiumEntity*);
	// slot 486 0x1027a5c0 (walked) `bool FOkToMakeSound()`
	//   layer 0, story 29c
	virtual bool FOkToMakeSound();
	// slot 487 0x1027a640 (walked) `void JustMadeSound()`
	//   layer 0, story 29c
	virtual void JustMadeSound();
	// slot 488 0x101a6880 (walked) `void DeathSound()`
	//   layer 0, story 29c
	virtual void DeathSound();
	// slot 489 0x101a68a0 (walked) `void AlertSound()`
	//   layer 0, story 29c
	virtual void AlertSound();
	// slot 490 0x101a68c0 (walked) `void IdleSound()`
	//   layer 0, story 29c
	virtual void IdleSound();
	// slot 491 0x101a68e0 (walked) `void PainSound()`
	//   layer 0, story 29c
	virtual void PainSound();
	// slot 492 0x101a6900 (walked) `void FearSound()`
	//   layer 0, story 29c
	virtual void FearSound();
	// slot 493 0x101a6920 (walked) `void LostEnemySound()`
	//   layer 0, story 29c
	virtual void LostEnemySound();
	// slot 494 0x101a6940 (walked) `void FoundEnemySound()`
	//   layer 0, story 29c
	virtual void FoundEnemySound();
	// slot 495 0x101a6960 (walked) `void SurprisedSound()`
	//   layer 0, story 29c
	virtual void SurprisedSound();
	// slot 496 0x101a6980 (walked) `void TargetAcquiredSound()`
	//   layer 0, story 29c
	virtual void TargetAcquiredSound();
	// slot 497 0x101a69a0 (walked) `void vfunc497()`
	//   layer 0, story 29c
	virtual void Slot497();
	// slot 498 0x101a69c0 (walked) `void FleeSound()`
	//   layer 0, story 29c
	virtual void FleeSound();
	// slot 499 0x101a69e0 (walked) `void IdleAgitatedSound()`
	//   layer 0, story 29c
	virtual void IdleAgitatedSound();
	// slot 500 0x101a6a00 (walked) `void ExertHvySound()`
	//   layer 0, story 29c
	virtual void ExertHvySound();
	// slot 501 0x101a6a20 (walked) `void ExertLightSound()`
	//   layer 0, story 29c
	virtual void ExertLightSound();
	// slot 502 0x101a6a40 (walked) `void RiledSound()`
	//   layer 0, story 29c
	virtual void RiledSound();
	// slot 503 0x101a6a60 (walked) `void ComfortSound()`
	//   layer 0, story 29c
	virtual void ComfortSound();
	// slot 504 0x101a6a80 (walked) `void UpsetSound()`
	//   layer 0, story 29c
	virtual void UpsetSound();
	// slot 505 0x101a6aa0 (walked) `void TargetGiveUpSound()`
	//   layer 0, story 29c
	virtual void TargetGiveUpSound();
	// slot 506 0x101a6ac0 (walked) `void vfunc506()`
	//   layer 0, story 29c
	virtual void Slot506();
	// slot 507 0x101a6ae0 (walked) `void FloatSound()`
	//   layer 0, story 29c
	virtual void FloatSound();
	// slot 508 0x101a6b00 (walked) `void SpeakSentence(int)`
	//   layer 0, story 29c
	virtual void SpeakSentence(int32);
	// slot 509 0x1027a420 (walked) `bool ShouldPlayIdleSound()`
	//   layer 2, story 29c
	virtual bool ShouldPlayIdleSound();
	// slot 510 0x1027a530 (walked) `bool ShouldPlayFloatSound()`
	//   layer 0, story 29c
	virtual bool ShouldPlayFloatSound();
	// slot 511 0x1027caa0 (walked) `void StopLoopingSounds()`
	//   layer 0, story 29c
	virtual void StopLoopingSounds();
	// slot 512 0x101a6b20 (walked) `CAI_Expresser* GetExpresser()`
	//   returns `CAI_Expresser*`
	//   layer 0, story 29c
	virtual void* GetExpresser();
	// slot 513 0x1026db30 (sdk) `int CapabilitiesGet() const`
	//   layer 1, story 29c
	virtual int32 CapabilitiesGet() const;
	// slot 514 0x1027d9d0 (walked) `bool MovementCost(int, const Vector&, const Vector&, float*)`
	//   takes `float*`
	//   layer 0, story 29c
	virtual bool MovementCost(int32, const FVector&, const FVector&, void*);
	// slot 515 0x10274b30 (walked) `float CalcIdealYaw(const Vector&)`
	//   layer 1, story 29c
	virtual float CalcIdealYaw(const FVector&);
	// slot 516 0x10280bb0 (sdk) `float MaxYawSpeed()`
	//   layer 0, story 29c
	virtual float MaxYawSpeed();
	// slot 517 0x10278d90 (walked) `void AddFacingTarget(CBaseEntity*, const Vector&, float, float,
	// float)`
	//   layer 0, story 29c
	virtual void AddFacingTarget(FElysiumEntity*, const FVector&, float, float, float);
	// slot 518 0x10278d20 (walked) `void AddFacingTarget(const Vector&, float, float, float)`
	//   layer 0, story 29c
	virtual void AddFacingTarget(const FVector&, float, float, float);
	// slot 521 0x10280880 (sdk) `bool IsJumpLegal(Vector&, Vector&, Vector&) const`
	//   layer 2, story 29c
	virtual bool IsJumpLegal(FVector&, FVector&, FVector&) const;
	// slot 522 0x101a6b40 (sdk) `float StepHeight() const`
	//   layer 0, story 29c
	virtual float StepHeight() const;
	// slot 523 0x101a6b60 (walked) `float GetStepDownHeight() const`
	//   layer 0, story 29c
	virtual float GetStepDownHeight() const;
	// slot 525 0x1027da90 (sdk) `bool OverrideMove(float)`
	//   layer 0, story 29c
	virtual bool OverrideMove(float);
	// slot 526 0x1027d9f0 (sdk) `bool OverrideMoveFacing(AILocalMoveGoal_t&, float)`
	//   takes `AILocalMoveGoal_t&`
	//   layer 0, story 29c
	virtual bool OverrideMoveFacing(void*, float);
	// slot 527 0x101a6ba0 (walked) `bool IsUnusableNode(CAI_Node*)`
	//   takes `CAI_Node*`
	//   layer 0, story 29c
	virtual bool IsUnusableNode(void*);
	// slot 528 0x10280360 (walked) `bool ValidateNavGoal()`
	//   layer 6, story 29c
	virtual bool ValidateNavGoal();
	// slot 529 0x10280330 (walked) `bool IsCurTaskContinuousMove()`
	//   layer 1, story 29c
	virtual bool IsCurTaskContinuousMove();
	// slot 530 0x102741e0 (sdk) `bool IsUnreachable(CBaseEntity*)`
	//   layer 1, story 29c
	virtual bool IsUnreachable(FElysiumEntity*);
	// slot 531 0x1027dc80 (walked) `bool OnObstructingDoor(AILocalMoveGoal_t*, CBaseDoor*, float,
	// AIMoveResult_t*)`
	//   takes `AILocalMoveGoal_t*`
	//   takes `AIMoveResult_t*`
	//   layer 0, story 29c
	virtual bool OnObstructingDoor(void*, FElysiumEntity*, float, void*);
	// slot 532 0x1027e0f0 (walked) `void vfunc532(int)`
	//   layer 0, story 29c
	virtual void Slot532(int32);
	// slot 533 0x10274db0 (walked) `Vector EyeOffset(Activity, Activity)`
	//   layer 2, story 29c
	virtual FVector EyeOffset(int32, int32);
	// slot 535 0x101a6be0 (walked) `void AddLookTarget(const Vector&, float, float, float)`
	//   layer 0, story 29c
	virtual void AddLookTarget(const FVector&, float, float, float);
	// slot 536 0x101a6bc0 (walked) `void AddLookTarget(CBaseEntity*, float, float, float)`
	//   layer 0, story 29c
	virtual void AddLookTarget(FElysiumEntity*, float, float, float);
	// slot 537 0x1026af70 (sdk) `void SetHeadDirection(Vector&, float)`
	//   layer 3, story 29c
	virtual void SetHeadDirection(FVector&, float);
	// slot 538 0x1026b4f0 (walked) `void AimGun()`
	//   layer 13, story 29d
	virtual void AimGun();
	// slot 539 0x1026b480 (walked) `void SetAim(const Vector&)`
	//   layer 2, story 29c
	virtual void SetAim(const FVector&);
	// slot 541 0x10273e10 (walked) `CAI_Enemies* GetEnemies()`
	//   returns `CAI_Enemies*`
	//   layer 0, story 29c
	virtual void* GetEnemies();
	// slot 542 0x10273dd0 (walked) `void vfunc542()`
	//   layer 5, story 29c
	virtual void Slot542();
	// slot 543 0x10273e40 (walked) `void RemoveMemory()`
	//   layer 5, story 29c
	virtual void RemoveMemory();
	// slot 544 0x102709c0 (walked) `bool UpdateEnemyMemory(CBaseEntity*, const Vector&,
	// CBaseEntity*)`
	//   layer 10, story 29d
	virtual bool UpdateEnemyMemory(FElysiumEntity*, const FVector&, FElysiumEntity*);
	// slot 545 0x10273d30 (sdk) `bool InitSquad()`
	//   layer 8, story 29c
	virtual bool InitSquad();
	// slot 546 0x101a6c00 (walked) `const char* SquadSlotName(int)`
	//   layer 3, story 29c
	virtual const TCHAR* SquadSlotName(int32);
	// slot 548 0x1028af20 (walked) `bool IsValidCover(const Vector&, const CAI_Hint*)`
	//   takes `const CAI_Hint*`
	//   layer 4, story 29c
	virtual bool IsValidCover(const FVector&, void*);
	// slot 550 0x101a6c20 (walked) `float CoverRadius()`
	//   layer 0, story 29c
	virtual float CoverRadius();
	// slot 551 0x101a6c40 (walked) `void OnChangeHintGroup(string_t, string_t)`
	//   layer 0, story 29c
	virtual void OnChangeHintGroup(FName, FName);
	// slot 552 0x1027a400 (walked) `bool ShouldFadeOnDeath()`
	//   layer 0, story 29c
	virtual bool ShouldFadeOnDeath();
	// slot 553 0x1026d890 (walked) `int RangeAttack1Conditions(float, float)`
	//   layer 0, story 29c
	virtual int32 RangeAttack1Conditions(float, float);
	// slot 555 0x1026d9a0 (walked) `int MeleeAttack1Conditions(float, float)`
	//   layer 1, story 29c
	virtual int32 MeleeAttack1Conditions(float, float);
	// slot 557 0x101a6c60 (walked) `bool OnBeginMoveAndShoot()`
	//   layer 0, story 29c
	virtual bool OnBeginMoveAndShoot();
	// slot 558 0x101a6c80 (walked) `void OnEndMoveAndShoot()`
	//   layer 0, story 29c
	virtual void OnEndMoveAndShoot();
	// slot 559 0x10279090 (walked) `CBaseEntity* FindNamedEntity(const char*)`
	//   layer 9, story 29c
	virtual FElysiumEntity* FindNamedEntity(const TCHAR*);
	// slot 560 0x1026dc80 (sdk) `void ClearAttackConditions()`
	//   layer 2, story 29c
	virtual void ClearAttackConditions();
	// slot 561 0x1026dd10 (sdk) `void GatherAttackConditions(CBaseEntity*, float)`
	//   layer 4, story 29c
	virtual void GatherAttackConditions(FElysiumEntity*, float);
	// slot 562 0x1026fbe0 (walked) `bool WeaponLOSCondition(const Vector&, const Vector&, bool)`
	//   layer 15, story 29d
	virtual bool WeaponLOSCondition(const FVector&, const FVector&, bool);
	// slot 563 0x10289f20 (walked) `void TranslateEnemyChasePosition(CBaseEntity*, Vector&, float&,
	// float*)`
	//   takes `float&`
	//   takes `float*`
	//   layer 1, story 29c
	virtual void TranslateEnemyChasePosition(FElysiumEntity*, FVector&, void*, void*);
	// slot 564 0x10270840 (walked) `bool FCanCheckAttacks()`
	//   layer 2, story 29c
	virtual bool FCanCheckAttacks();
	// slot 565 0x101a6ca0 (walked) `void CheckAmmo()`
	//   layer 0, story 29c
	virtual void CheckAmmo();
	// slot 566 0x1026a8d0 (sdk) `bool FValidateHintType(CAI_Hint*)`
	//   takes `CAI_Hint*`
	//   layer 0, story 29c
	virtual bool FValidateHintType(void*);
	// slot 567 0x1026a8f0 (walked) `Activity GetHintActivity(short)`
	//   layer 0, story 29c
	virtual int32 GetHintActivity(int16);
	// slot 569 0x10274aa0 (walked) `Activity GetCoverActivity(CAI_Hint*)`
	//   takes `CAI_Hint*`
	//   layer 1, story 29c
	virtual int32 GetCoverActivity(void*);
	// slot 570 0x10274820 (walked) `Activity GetReloadActivity(CAI_Hint*)`
	//   takes `CAI_Hint*`
	//   layer 4, story 29c
	virtual int32 GetReloadActivity(void*);
	// slot 571 0x10289ce0 (walked) `Activity vfunc571(float)`
	//   layer 0, story 29c
	virtual int32 Slot571(float);
	// slot 572 0x10289d10 (walked) `void SetTurnActivity()`
	//   layer 18, story 29d
	virtual void SetTurnActivity();
	// slot 573 0x1026fcf0 (walked) `bool InnateWeaponLOSCondition(const Vector&, const Vector&,
	// bool)`
	//   layer 14, story 29d
	virtual bool InnateWeaponLOSCondition(const FVector&, const FVector&, bool);
	// slot 574 0x10278900 (walked) `Vector GetShootEnemyDir(const Vector&, int, int)`
	//   layer 12, story 29d
	virtual FVector GetShootEnemyDir(const FVector&, int32, int32);
	// slot 575 0x10278c60 (walked) `bool ShouldMoveAndShoot()`
	//   layer 2, story 29c
	virtual bool ShouldMoveAndShoot();
	// slot 576 0x10266630 (walked) `bool IsLightDamage(float, int)`
	//   layer 0, story 29c
	virtual bool IsLightDamage(float, int32);
	// slot 577 0x10266660 (walked) `bool IsHeavyDamage(float, int)`
	//   layer 0, story 29c
	virtual bool IsHeavyDamage(float, int32);
	// slot 578 0x101a6cc0 (walked) `void NotifyDeadFriend(CBaseEntity*)`
	//   layer 0, story 29c
	virtual void NotifyDeadFriend(FElysiumEntity*);
	// slot 581 0x102779a0 (walked) `void ReportAIState()`
	//   layer 4, story 29c
	virtual void ReportAIState();

	// The inherited overloads of an overridden name stay visible.
	using FElysiumScriptedCharacter::GetEnemy;
