// Generated by `uv run elysium research gen_kernel_bindings`. Do not hand-edit.
//
// The datamap-backed field/input bindings of the port's NPC-family classes, transcribed from the
// datamap replay (`research/ghidra/types/datamap_records-vampire.dll.json`; CAI_BaseNPC 0x105c9814,
// CAI_BaseNPCTroika 0x105ce470, CNPCMaker 0x10624718, CAI_InterestingPlace 0x1060bdd8, CAI_Hint
// 0x106099f0, CAI_InterestingPlaceConverstation 0x1060c2c0, CNPCMaker_Zombie 0x106253e8).
// The replay carries no module hash line, so the datamap addresses are the provenance this file
// holds.

#include "Substrate/ElysiumNpcKernelBindings.h"

#include "Substrate/ElysiumClassFields.h"
#include "Substrate/ElysiumConversationPlace.h"
#include "Substrate/ElysiumHint.h"
#include "Substrate/ElysiumInterestingPlace.h"
#include "Substrate/ElysiumNpc.h"
#include "Substrate/ElysiumNpcMaker.h"

namespace ElysiumNpcKernelBindings
{
	void AddNpcFields(FElysiumClassDesc& D)
	{
		// One row per replay field row the class's member map binds, sorted by external.
		// Flags: SAVE -> EElysiumField::Save, INPUT -> EElysiumField::Key, neither ->
		// EElysiumField::None; KEY alone adds no flag, because the registry applies spawn
		// keyvalues regardless of Key.
		ElysiumAddClassField(D, TEXT("additionalequipment"), &FElysiumNpc::AdditionalEquipment,
			EElysiumField::Save);  // +0x5dec m_spawnEquipment
		ElysiumAddClassField(D, TEXT("allow_alert_lookaround"),
			&FElysiumNpc::bAllowAlertLookaround, EElysiumField::Save);  // +0x6434 m_bAllowAlertLookaround
		ElysiumAddClassField(D, TEXT("alternateequipment"), &FElysiumNpc::AlternateEquipment,
			EElysiumField::Save);  // +0x1a98 m_altEquipment
		ElysiumAddClassField(D, TEXT("bright_route_penalty"), &FElysiumNpc::BrightRoutePenalty,
			EElysiumField::Save);  // +0x6344 m_iBrightRoutePenalty
		ElysiumAddClassField(D, TEXT("combat_start_activity"), &FElysiumNpc::CombatStartActivity,
			EElysiumField::Save);  // +0x65e0 m_sCombatStartActivity
		ElysiumAddClassField(D, TEXT("default_camera"), &FElysiumNpc::DefaultCamera,
			EElysiumField::Save);  // +0x64c4 m_sDefaultCamera
		ElysiumAddClassField(D, TEXT("follower_boss"), &FElysiumNpc::FollowerBossName,
			EElysiumField::Save);  // +0x6478 m_sFollowerBoss
		ElysiumAddClassField(D, TEXT("follower_type"), &FElysiumNpc::FollowerType,
			EElysiumField::Save);  // +0x6480 m_sFollowerType
		ElysiumAddClassField(D, TEXT("full_investigate"), &FElysiumNpc::FullInvestigate,
			EElysiumField::Save);  // +0x6340 m_bFullInvestigate
		ElysiumAddClassField(D, TEXT("hearing"), &FElysiumNpc::AuthoredHearing,
			EElysiumField::Save);  // +0x63bc m_flHearingScalarBase
		ElysiumAddClassField(D, TEXT("ignore_detected_attack"),
			&FElysiumNpc::bIgnoreDetectedAttack, EElysiumField::Save);  // +0x65f5 m_bIgnoreDetectedAttack
		ElysiumAddClassField(D, TEXT("interesting_place_groups"),
			&FElysiumNpc::InterestingPlaceGroups, EElysiumField::Save);  // +0x62d8 m_sInterestingPlaceGroups
		ElysiumAddClassField(D, TEXT("investigate_mode"), &FElysiumNpc::InvestigateMode,
			EElysiumField::Save);  // +0x6338 m_eInvestigateMode
		ElysiumAddClassField(D, TEXT("investigate_mode_combat"),
			&FElysiumNpc::InvestigateModeCombat, EElysiumField::Save);  // +0x633c m_eInvestigateModeCombat
		ElysiumAddClassField(D, TEXT("invincible"), &FElysiumNpc::bInvincible, EElysiumField::Save);  // +0x63d8 m_bInvincible
		ElysiumAddClassField(D, TEXT("is_bossmonster"), &FElysiumNpc::bIsBossMonster,
			EElysiumField::Save);  // +0x6496 m_bIsBossMonster
		ElysiumAddClassField(D, TEXT("nav_ignore_physics_props"),
			&FElysiumNpc::bNavIgnorePhysicsProps, EElysiumField::Save);  // +0x65f7 m_bNavIgnorePhysicsProps
		ElysiumAddClassField(D, TEXT("no_alert_state"), &FElysiumNpc::bNoAlertState,
			EElysiumField::Save);  // +0x65f6 m_bNoAlertState
		ElysiumAddClassField(D, TEXT("npc_perception"), &FElysiumNpc::AuthoredPerception,
			EElysiumField::Save);  // +0x63b0 m_iNPCPerception
		ElysiumAddClassField(D, TEXT("percent_occluded_chase"), &FElysiumNpc::PercentOccludedChase,
			EElysiumField::Save);  // +0x6430 m_iPercentOccludedChase
		ElysiumAddClassField(D, TEXT("percent_occluded_cover"), &FElysiumNpc::PercentOccludedCover,
			EElysiumField::Save);  // +0x6424 m_iPercentOccludedCover
		ElysiumAddClassField(D, TEXT("percent_occluded_flank"), &FElysiumNpc::PercentOccludedFlank,
			EElysiumField::Save);  // +0x642c m_iPercentOccludedFlank
		ElysiumAddClassField(D, TEXT("percent_occluded_wait"), &FElysiumNpc::PercentOccludedWait,
			EElysiumField::Save);  // +0x6420 m_iPercentOccludedWait
		ElysiumAddClassField(D, TEXT("percent_occluded_walk"), &FElysiumNpc::PercentOccludedWalk,
			EElysiumField::Save);  // +0x6428 m_iPercentOccludedWalk
		ElysiumAddClassField(D, TEXT("pl_criminal_attack"), &FElysiumNpc::PlCriminalAttack,
			EElysiumField::Save | EElysiumField::Key);  // +0x6350 m_iPLCriminalAttackLevel
		ElysiumAddClassField(D, TEXT("pl_criminal_flee"), &FElysiumNpc::PlCriminalFlee,
			EElysiumField::Save | EElysiumField::Key);  // +0x634c m_iPLCriminalFleeLevel
		ElysiumAddClassField(D, TEXT("pl_investigate"), &FElysiumNpc::PlInvestigate,
			EElysiumField::Save | EElysiumField::Key);  // +0x6348 m_iPLInvestigateLevel
		ElysiumAddClassField(D, TEXT("pl_supernatural_attack"), &FElysiumNpc::PlSupernaturalAttack,
			EElysiumField::Save | EElysiumField::Key);  // +0x6358 m_iPLSupernaturalAttackLevel
		ElysiumAddClassField(D, TEXT("pl_supernatural_flee"), &FElysiumNpc::PlSupernaturalFlee,
			EElysiumField::Save | EElysiumField::Key);  // +0x6354 m_iPLSupernaturalFleeLevel
		ElysiumAddClassField(D, TEXT("player_reaction"), &FElysiumNpc::PlayerReaction,
			EElysiumField::Save);  // +0x63ac m_sPlayerReaction
		ElysiumAddClassField(D, TEXT("squadname"), &FElysiumNpc::SquadName, EElysiumField::Save);  // +0x5da8 m_SquadName
		ElysiumAddClassField(D, TEXT("stay_entrenched"), &FElysiumNpc::bStayEntrenched,
			EElysiumField::Save);  // +0x6435 m_bStayEntrenched
		ElysiumAddClassField(D, TEXT("teleport_move_timer"), &FElysiumNpc::TeleportMoveTimer,
			EElysiumField::Save);  // +0x65dc m_flTeleportMoveTimer
		ElysiumAddClassField(D, TEXT("times_talked"), &FElysiumNpc::TimesTalked,
			EElysiumField::Save);  // +0x64bc m_nTimesTalked
		ElysiumAddClassField(D, TEXT("use_interesting"), &FElysiumNpc::bUseInteresting,
			EElysiumField::Save);  // +0x63d9 m_bUseInteresting
		ElysiumAddClassField(D, TEXT("vision"), &FElysiumNpc::AuthoredVision, EElysiumField::Save);  // +0x63b4 m_flSeekDistBase
		// UNBOUND +0x6436 m_bAllowKickHintUse "allow_kick_hint_use" — member type FElysiumNpcScheduleHost
		// UNBOUND +0x6558 m_sDefaultDisposition "default_disposition" — no shape-map member (CHAIN)
		// UNBOUND +0x62e0 m_sHintGroups "hint_groups" — member type FElysiumNpcScheduleHost
		// UNBOUND +0x5db0 m_strHintGroup "hintgroup" — member type FElysiumNpcScheduleHost
	}

	void AddNpcMakerFields(FElysiumClassDesc& D)
	{
		// One row per replay field row the class's member map binds, sorted by external.
		// Flags: SAVE -> EElysiumField::Save, INPUT -> EElysiumField::Key, neither ->
		// EElysiumField::None; KEY alone adds no flag, because the registry applies spawn
		// keyvalues regardless of Key.
		ElysiumAddClassField(D, TEXT("Flag_Fade"), &FElysiumNpcMaker::bFade, EElysiumField::Save);  // +0x66c2 m_bFade
		ElysiumAddClassField(D, TEXT("Flag_InfChild"), &FElysiumNpcMaker::bInfinite,
			EElysiumField::Save);  // +0x66c3 m_bInfChild
		ElysiumAddClassField(D, TEXT("Flag_NPCClip"), &FElysiumNpcMaker::bNpcClip,
			EElysiumField::Save);  // +0x66c1 m_bNPCClip
		ElysiumAddClassField(D, TEXT("Flag_NoDrop"), &FElysiumNpcMaker::bNoDrop,
			EElysiumField::Save);  // +0x66c4 m_bNoDrop
		ElysiumAddClassField(D, TEXT("Flag_StartDisabled"), &FElysiumNpcMaker::bDisabled,
			EElysiumField::Save);  // +0x66c0 m_bDisabled
		ElysiumAddClassField(D, TEXT("Flag_ViewCone"), &FElysiumNpcMaker::bViewCone,
			EElysiumField::Save);  // +0x66c5 m_bViewCone
		ElysiumAddClassField(D, TEXT("MaxLiveChildren"), &FElysiumNpcMaker::MaxLiveChildren,
			EElysiumField::Save);  // +0x66b4 m_iMaxLiveChildren
		ElysiumAddClassField(D, TEXT("MaxNPCCount"), &FElysiumNpcMaker::RemainingTotal,
			EElysiumField::Save);  // +0x6660 m_iMaxNumNPCs
		ElysiumAddClassField(D, TEXT("MinPCDistance"), &FElysiumNpcMaker::MinPcDistance,
			EElysiumField::Save);  // +0x66c8 m_iMinPCDistance
		ElysiumAddClassField(D, TEXT("NPCTargetname"), &FElysiumNpcMaker::ChildTargetName,
			EElysiumField::Save);  // +0x66bc m_ChildTargetName
		ElysiumAddClassField(D, TEXT("NPCType"), &FElysiumNpcMaker::NpcType, EElysiumField::Save);  // +0x665c m_iszNPCClassname
		ElysiumAddClassField(D, TEXT("SpawnFrequency"), &FElysiumNpcMaker::SpawnFrequency,
			EElysiumField::Save);  // +0x6664 m_flSpawnFrequency
	}

	void AddInterestingPlaceFields(FElysiumClassDesc& D)
	{
		// One row per replay field row the class's member map binds, sorted by external.
		// Flags: SAVE -> EElysiumField::Save, INPUT -> EElysiumField::Key, neither ->
		// EElysiumField::None; KEY alone adds no flag, because the registry applies spawn
		// keyvalues regardless of Key.
		ElysiumAddClassField(D, TEXT("enabled"), &FElysiumInterestingPlace::bEnabled,
			EElysiumField::Save);  // +0x57c m_bEnabled
		ElysiumAddClassField(D, TEXT("group_id"), &FElysiumInterestingPlace::GroupId,
			EElysiumField::Save);  // +0x574 m_iGroupID
		ElysiumAddClassField(D, TEXT("match_orientation"),
			&FElysiumInterestingPlace::bMatchOrientation, EElysiumField::Save);  // +0x570 m_bMatchOrientation
		ElysiumAddClassField(D, TEXT("max_npcs"), &FElysiumInterestingPlace::MaxNpcs,
			EElysiumField::Save);  // +0x584 m_iMarkersAllocated
		ElysiumAddClassField(D, TEXT("max_time"), &FElysiumInterestingPlace::MaxTime,
			EElysiumField::Save);  // +0x56c m_fMaxStayTime
		ElysiumAddClassField(D, TEXT("min_time"), &FElysiumInterestingPlace::MinTime,
			EElysiumField::Save);  // +0x568 m_fMinStayTime
		ElysiumAddClassField(D, TEXT("rating"), &FElysiumInterestingPlace::Rating,
			EElysiumField::Save);  // +0x578 m_iRating
		ElysiumAddClassField(D, TEXT("type"), &FElysiumInterestingPlace::Type, EElysiumField::Save);  // +0x544 m_sType
		// UNBOUND +0x571 m_bHolsterWeapon "holster_weapon" — no port member
		// UNBOUND +0x558 m_vecMaxBounds "max_bounds" — no port member
		// UNBOUND +0x54c m_vecMinBounds "min_bounds" — no port member
	}

	void AddHintFields(FElysiumClassDesc& D)
	{
		// One row per replay field row the class's member map binds, sorted by external.
		// Flags: SAVE -> EElysiumField::Save, INPUT -> EElysiumField::Key, neither ->
		// EElysiumField::None; KEY alone adds no flag, because the registry applies spawn
		// keyvalues regardless of Key.
		ElysiumAddClassField(D, TEXT("Group"), &FElysiumHint::Group, EElysiumField::Save);  // +0x5f0 m_strGroup
		ElysiumAddClassField(D, TEXT("HintType"), &FElysiumHint::HintType, EElysiumField::Save);  // +0x5dc m_nHintType
		ElysiumAddClassField(D, TEXT("StartHintDisabled"), &FElysiumHint::Disabled,
			EElysiumField::Save);  // +0x5e8 m_iDisabled
		ElysiumAddClassField(D, TEXT("UserData"), &FElysiumHint::UserData, EElysiumField::Save);  // +0x5d4 m_iszUserData
		ElysiumAddClassField(D, TEXT("group_id"), &FElysiumHint::GroupId, EElysiumField::Save);  // +0x470 m_iGroupID
		ElysiumAddClassField(D, TEXT("hint_rating"), &FElysiumHint::HintRating,
			EElysiumField::Save);  // +0x464 m_flHintRating
		ElysiumAddClassField(D, TEXT("ip_percent"), &FElysiumHint::IpPercent, EElysiumField::Save);  // +0x46c m_iIPPercent
		ElysiumAddClassField(D, TEXT("target_angle_range"), &FElysiumHint::TargetAngleRange,
			EElysiumField::Save);  // +0x454 m_flTargetAngleRange
		ElysiumAddClassField(D, TEXT("target_dist_max"), &FElysiumHint::TargetDistMax,
			EElysiumField::Save);  // +0x460 m_flTargetDistMax
		ElysiumAddClassField(D, TEXT("target_dist_min"), &FElysiumHint::TargetDistMin,
			EElysiumField::Save);  // +0x45c m_flTargetDistMin
		ElysiumAddClassField(D, TEXT("target_name"), &FElysiumHint::InterestTargetName,
			EElysiumField::Save);  // +0x468 m_strTargetName
	}

	void AddConversationPlaceFields(FElysiumClassDesc& D)
	{
		// One row per replay field row the class's member map binds, sorted by external.
		// Flags: SAVE -> EElysiumField::Save, INPUT -> EElysiumField::Key, neither ->
		// EElysiumField::None; KEY alone adds no flag, because the registry applies spawn
		// keyvalues regardless of Key.
		ElysiumAddClassField(D, TEXT("audible_dist"), &FElysiumConversationPlace::AudibleDist,
			EElysiumField::Save);  // +0x468 m_flAudibleDist
		ElysiumAddClassField(D, TEXT("enabled"), &FElysiumConversationPlace::bEnabled,
			EElysiumField::Save);  // +0x45c m_bEnabled
		ElysiumAddClassField(D, TEXT("interesting_places"),
			&FElysiumConversationPlace::InterestingPlaces, EElysiumField::Save);  // +0x450 m_iszInterestingPlaces
		ElysiumAddClassField(D, TEXT("max_time"), &FElysiumConversationPlace::MaxTime,
			EElysiumField::Save);  // +0x510 m_flMaxTime
		ElysiumAddClassField(D, TEXT("min_time"), &FElysiumConversationPlace::MinTime,
			EElysiumField::Save);  // +0x50c m_flMinTime
		ElysiumAddClassField(D, TEXT("player_dist"), &FElysiumConversationPlace::PlayerDist,
			EElysiumField::Save);  // +0x464 m_flPlayerDist
		ElysiumAddClassField(D, TEXT("sound_loop"), &FElysiumConversationPlace::SoundLoop,
			EElysiumField::Save);  // +0x454 m_iszSoundLoop
		ElysiumAddClassField(D, TEXT("sound_occluded"), &FElysiumConversationPlace::bSoundOccluded,
			EElysiumField::Save);  // +0x515 m_bSoundOccluded
		ElysiumAddClassField(D, TEXT("sound_once"), &FElysiumConversationPlace::SoundOnce,
			EElysiumField::Save);  // +0x458 m_iszSoundOnce
		ElysiumAddClassField(D, TEXT("turn_towards_talker"),
			&FElysiumConversationPlace::bTurnTowardsTalker, EElysiumField::Save);  // +0x514 m_bTurnTowardsTalker
	}

	void AddNpcMakerZombieFields(FElysiumClassDesc& D)
	{
		// One row per replay field row the class's member map binds, sorted by external.
		// Flags: SAVE -> EElysiumField::Save, INPUT -> EElysiumField::Key, neither ->
		// EElysiumField::None; KEY alone adds no flag, because the registry applies spawn
		// keyvalues regardless of Key.
		ElysiumAddClassField(D, TEXT("Flag_ZombieAIType"), &FElysiumNpcMaker::ZombieAiType,
			EElysiumField::Save);  // +0x76d0 m_iZombieAISpawnType
		ElysiumAddClassField(D, TEXT("remove_distance"), &FElysiumNpcMaker::RemoveDistance,
			EElysiumField::Save);  // +0x76d8 m_flRemoveDist
		ElysiumAddClassField(D, TEXT("should_ragdoll"), &FElysiumNpcMaker::bShouldRagdoll,
			EElysiumField::Save);  // +0x76d4 m_bShouldRagdoll
	}

	namespace
	{
	const TCHAR* const GNpcOutputs[] =
	{
		TEXT("OnDamaged"),
		TEXT("OnDeath"),
		TEXT("OnDialogBegin"),
		TEXT("OnDialogEnd"),
		TEXT("OnFedUponBegin"),
		TEXT("OnFedUponEnd"),
		TEXT("OnFoundEnemy"),
		TEXT("OnFoundPlayer"),
		TEXT("OnGrappleBegin"),
		TEXT("OnGrappleEnd"),
		TEXT("OnHalfHealth"),
		TEXT("OnHearCombat"),
		TEXT("OnHearPlayer"),
		TEXT("OnHearWorld"),
		TEXT("OnIncapacitatedEnd"),
		TEXT("OnIncapacitatedStart"),
		TEXT("OnInterestingPlaceArrived"),
		TEXT("OnInterestingPlaceLeft"),
		TEXT("OnLostEnemy"),
		TEXT("OnLostEnemyLOS"),
		TEXT("OnLostPlayer"),
		TEXT("OnLostPlayerLOS"),
		TEXT("OnStateFleeing"),
		TEXT("OnUnknownVisionPlayer"),
	};

	const TCHAR* const GNpcInputFuncs[] =
	{
		TEXT("AllowAlertLookaround"),
		TEXT("AllowKickHintUse"),
		TEXT("AllowOpenDoors"),
		TEXT("ChangeSchedule"),
		TEXT("ClearPatrolPath"),
		TEXT("DisableThink"),
		TEXT("Faint"),
		TEXT("FleeAndDie"),
		TEXT("FollowPatrolPath"),
		TEXT("MakeInvincible"),
		TEXT("PlayDialogFile"),
		TEXT("SetBloodShieldDiscipline"),
		TEXT("SetBossMonster"),
		TEXT("SetDefaultDialogCamera"),
		TEXT("SetDontFacePlayerInDialog"),
		TEXT("SetFallToGround"),
		TEXT("SetFollowerBoss"),
		TEXT("SetFollowerType"),
		TEXT("SetInvestigateMode"),
		TEXT("SetInvestigateModeCombat"),
		TEXT("SetMovementMultiplier"),
		TEXT("SetRelationship"),
		TEXT("SetScriptedDiscipline"),
		TEXT("SetSpeechVolume"),
		TEXT("SetupPatrolType"),
		TEXT("StartPlayerDialog"),
		TEXT("StartPlayerDialogRemote"),
		TEXT("StartPlayerDialogUnforced"),
		TEXT("StayEntrenched"),
		TEXT("TakeDamage"),
		TEXT("TeleportToEntity"),
		TEXT("TweakParam"),
		TEXT("UseInteresting"),
		TEXT("WalkToNode"),
	};

	const TCHAR* const GNpcMakerOutputs[] =
	{
		TEXT("OnLastNPCDied"),
		TEXT("OnNPCDied"),
		TEXT("OnSpawnNPC"),
	};

	const TCHAR* const GNpcMakerInputFuncs[] =
	{
		TEXT("Disable"),
		TEXT("Enable"),
		TEXT("Spawn"),
		TEXT("Toggle"),
	};

	const TCHAR* const GInterestingPlaceOutputs[] =
	{
		TEXT("OnAnimEvent1"),
		TEXT("OnAnimEvent2"),
		TEXT("OnAnimEvent3"),
		TEXT("OnAnimEvent4"),
		TEXT("OnAnimEvent5"),
		TEXT("OnAnimEvent6"),
		TEXT("OnAnimEvent7"),
		TEXT("OnAnimEvent8"),
		TEXT("OnNPCArrived"),
		TEXT("OnNPCLeft"),
	};

	const TCHAR* const GInterestingPlaceInputFuncs[] =
	{
		TEXT("Disable"),
		TEXT("Enable"),
	};

	const TCHAR* const GHintOutputs[] =
	{
		TEXT("OnAnimEvent1"),
		TEXT("OnAnimEvent2"),
		TEXT("OnAnimEvent3"),
		TEXT("OnAnimEvent4"),
		TEXT("OnAnimEvent5"),
		TEXT("OnAnimEvent6"),
		TEXT("OnAnimEvent7"),
		TEXT("OnAnimEvent8"),
		TEXT("OnNPCArrival"),
		TEXT("OnNPCKicked"),
	};

	const TCHAR* const GHintInputFuncs[] =
	{
		TEXT("DisableHint"),
		TEXT("DontWalk"),
		TEXT("EnableHint"),
		TEXT("SetUserData"),
		TEXT("Walk"),
	};

	const TCHAR* const GConversationPlaceOutputs[] =
	{
		TEXT("OnConversationEnd"),
		TEXT("OnConversationStart"),
		TEXT("OnNewTalker"),
		TEXT("OnOneOffSoundComplete"),
		TEXT("OnPlayerLeftRadius"),
		TEXT("OnPlayerTooClose"),
	};

	const TCHAR* const GConversationPlaceInputFuncs[] =
	{
		TEXT("Disable"),
		TEXT("Enable"),
		TEXT("PlayOneOffSound"),
	};

	}

	TConstArrayView<const TCHAR*> Outputs(EClass Class)
	{
		switch (Class)
		{
			case EClass::NpcMaker:
				return MakeArrayView(GNpcMakerOutputs);
			case EClass::InterestingPlace:
				return MakeArrayView(GInterestingPlaceOutputs);
			case EClass::Hint:
				return MakeArrayView(GHintOutputs);
			case EClass::ConversationPlace:
				return MakeArrayView(GConversationPlaceOutputs);
			case EClass::NpcMakerZombie:
				return TConstArrayView<const TCHAR*>();
			default:
				return MakeArrayView(GNpcOutputs);
		}
	}

	TConstArrayView<const TCHAR*> InputFuncs(EClass Class)
	{
		switch (Class)
		{
			case EClass::NpcMaker:
				return MakeArrayView(GNpcMakerInputFuncs);
			case EClass::InterestingPlace:
				return MakeArrayView(GInterestingPlaceInputFuncs);
			case EClass::Hint:
				return MakeArrayView(GHintInputFuncs);
			case EClass::ConversationPlace:
				return MakeArrayView(GConversationPlaceInputFuncs);
			case EClass::NpcMakerZombie:
				return TConstArrayView<const TCHAR*>();
			default:
				return MakeArrayView(GNpcInputFuncs);
		}
	}

	FCounts Counts(EClass Class)
	{
		switch (Class)
		{
			case EClass::NpcMaker:
				return {12, 0, 3, 4};
			case EClass::InterestingPlace:
				return {8, 3, 10, 2};
			case EClass::Hint:
				return {11, 0, 10, 5};
			case EClass::ConversationPlace:
				return {10, 0, 6, 3};
			case EClass::NpcMakerZombie:
				return {3, 0, 0, 0};
			default:
				return {36, 4, 24, 34};
		}
	}
}
