// Generated by `uv run elysium research gen_kernel_shape`. Do not hand-edit.
//
// The NPC kernel's shape, transcribed from `docs/vtmb/npc-kernel/` — `layout.md` (every
// word of the flattened `CAI_BaseNPCTroika` layout, typed), `signatures.md` (every
// primary-vtable slot's declaration), `classes.md` (the family tree and the entity
// classnames each class claims) and `slots.md` (the bodies per class). It is the census
// the port's own shape is asserted against; it carries no behaviour and no rule.
//
// 38 generated slot bodies of `FElysiumAnimating`: 0 carry retail's one-constant default (story
// 29c's verdicts, the L0 re-check's `RETAIL_DEFAULTS`), 5 are defined by hand in the substrate, and
// 33 are still stubs — 21 29c, 12 unassigned.
//
// vampire.dll sha256 `c546f4de2003624d…`; the ledger's own provenance line is in every table under
// `docs/vtmb/npc-kernel/`.
//
// A stub body says one thing: this slot has no port implementation yet. The tally row
// carries the retail class that owns the body, its address and the story that owns it, so
// `elysium.stubs` joins `docs/vtmb/npc-kernel/functions.md` by address.
//
// A body with a `default:` verdict says something stronger: retail's whole body at that
// slot is `return <literal>;`, so the port answers the same literal and stops tallying.
// The literal is a recovered fact, not a written behaviour, and the slot table at the end
// of this file is what `Elysium.Substrate.NpcKernelSlots.Defaults` calls every one of them
// through, on a receiver typed to this class.

#include "ElysiumAnimating.h"

#include "ElysiumStub.h"
#include "Substrate/ElysiumNpcKernelShape.h"

namespace
{
	// One shape for every slot stub: the surface is the retail class and method, which is
	// what the ledger joins on, and never an instance name. Unit-prefixed because the module
	// builds adaptive-unity and this anonymous namespace is regularly merged with others.
	void FireAnimatingSlot(const TCHAR* Surface, const TCHAR* Address, const TCHAR* Story,
		const FString& Receiver)
	{
		ElysiumStub::FSurface Row;
		Row.Kind = TEXT("slot");
		Row.Surface = Surface;
		Row.Address = Address;
		Row.Story = Story;
		ElysiumStub::Fired(Row, Receiver, FString(), TEXT("the NPC kernel"));
	}
}

// slot 5 0x1008b390 (walked) `void* ~CBaseEntity(unsigned int)`
//   retail `~CBaseEntity` is a lifetime slot; declared by index
//   returns `void*`
void* FElysiumAnimating::Slot5(uint32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::Slot5"), TEXT("0x1008b390"), TEXT(""), DebugString());
	return {};
}

// slot 31 0x1008b530 (walked) `void Dump(int)`
//   layer 0, story 29c
void FElysiumAnimating::Dump(int32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::Dump"), TEXT("0x1008b530"), TEXT("29c"), DebugString());
}

// slot 68 0x1008bfe0 (walked) `bool ShouldIgnoreCollision(CBaseEntity*)`
//   layer 0, story 29c
bool FElysiumAnimating::ShouldIgnoreCollision(FElysiumEntity*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::ShouldIgnoreCollision"), TEXT("0x1008bfe0"),
		TEXT("29c"), DebugString());
	return {};
}

// slot 79 0x10097ae0 (walked) `datamap_t* GetPredDescMap()`
//   returns `datamap_t*`
void* FElysiumAnimating::GetPredDescMap()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetPredDescMap"), TEXT("0x10097ae0"), TEXT(""),
		DebugString());
	return {};
}

// slot 80 0x1008a9f0 (walked) `ServerClass* GetServerClass()`
//   returns `ServerClass*`
void* FElysiumAnimating::GetServerClass()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetServerClass"), TEXT("0x1008a9f0"), TEXT(""),
		DebugString());
	return {};
}

// slot 81 0x1008aa10 (walked) `int YouForgotToImplementOrDeclareServerClass()`
int32 FElysiumAnimating::YouForgotToImplementOrDeclareServerClass()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::YouForgotToImplementOrDeclareServerClass"),
		TEXT("0x1008aa10"), TEXT(""), DebugString());
	return {};
}

// slot 82 0x1008a760 (walked) `datamap_t* GetDataDescMap()`
//   returns `datamap_t*`
void* FElysiumAnimating::GetDataDescMap()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetDataDescMap"), TEXT("0x1008a760"), TEXT(""),
		DebugString());
	return {};
}

// slot 99 0x100956e0 (sdk) `bool TestCollision(Ray_t&, unsignedint, trace_t&)`
//   takes `Ray_t&`
//   takes `unsignedint`
//   takes `trace_t&`
//   layer 0, story 29c
bool FElysiumAnimating::TestCollision(void*, int32, void*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::TestCollision"), TEXT("0x100956e0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 100 0x10095a20 (sdk) `bool TestHitboxes(Ray_t&, unsignedint, trace_t&)`
//   takes `Ray_t&`
//   takes `unsignedint`
//   takes `trace_t&`
//   layer 0, story 29c
bool FElysiumAnimating::TestHitboxes(void*, int32, void*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::TestHitboxes"), TEXT("0x10095a20"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 105 0x10095030 (sdk) `void SetModel(char*)`
//   layer 0, story 29c
void FElysiumAnimating::SetModel(TCHAR*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::SetModel"), TEXT("0x10095030"), TEXT("29c"),
		DebugString());
}

// slot 110 0x101c1480 (walked) `bool KeyValue(const char*, const char*)`
//   layer 10, story 29d
// verdict `rule`: the body is `FElysiumAnimating::KeyValue`, written by hand in the substrate.
// Declared here, defined there.

// slot 124 0x10096100 (sdk) `int DrawDebugTextOverlays()`
int32 FElysiumAnimating::DrawDebugTextOverlays()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::DrawDebugTextOverlays"), TEXT("0x10096100"), TEXT(""),
		DebugString());
	return {};
}

// slot 130 0x1008df10 (walked) `void OnRestore(bool)`
//   layer 0, story 29c
void FElysiumAnimating::OnRestore(bool)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::OnRestore"), TEXT("0x1008df10"), TEXT("29c"),
		DebugString());
}

// slot 137 0x1004fc50 (walked) `CBaseAnimating* GetBaseAnimating()`
//   layer 0, story 29c
// verdict `mechanism`: the body is `FElysiumAnimating::GetBaseAnimating`, written by hand in the
// substrate. Declared here, defined there.

// slot 199 0x10095e50 (sdk) `void GetVelocity(Vector*, AngularImpulse*)`
//   takes `AngularImpulse*`
//   layer 0, story 29c
void FElysiumAnimating::GetVelocity(FVector*, void*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetVelocity"), TEXT("0x10095e50"), TEXT("29c"),
		DebugString());
}

// slot 241 0x1008c170 (walked) `void GetEventName(char*, animevent_t*)`
//   takes `animevent_t*`
//   layer 0, story 29c
void FElysiumAnimating::GetEventName(TCHAR*, void*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetEventName"), TEXT("0x1008c170"), TEXT("29c"),
		DebugString());
}

// slot 242 0x100916a0 (walked) `float GetIdealYawSpeed()`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumAnimating::GetIdealYawSpeed`, written by hand in the
// substrate. Declared here, defined there.

// slot 243 0x10090580 (walked) `void BurnModel(const char*, bool)`
//   layer 0, story 29c
void FElysiumAnimating::BurnModel(const TCHAR*, bool)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::BurnModel"), TEXT("0x10090580"), TEXT("29c"),
		DebugString());
}

// slot 244 0x1004fc30 (walked) `const char* GetSkeletonModelName()`
const TCHAR* FElysiumAnimating::GetSkeletonModelName()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetSkeletonModelName"), TEXT("0x1004fc30"), TEXT(""),
		DebugString());
	return {};
}

// slot 245 0x1008e0a0 (walked) `void AddExtraAnimationModels(CBaseEntity*, const char*, const
// char*, int, int)`
//   layer 0, story 29c
void FElysiumAnimating::AddExtraAnimationModels(FElysiumEntity*, const TCHAR*, const TCHAR*, int32,
	int32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::AddExtraAnimationModels"), TEXT("0x1008e0a0"),
		TEXT("29c"), DebugString());
}

// slot 246 0x1008e310 (walked) `void RemoveExtraAnimationModels()`
//   layer 0, story 29c
void FElysiumAnimating::RemoveExtraAnimationModels()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::RemoveExtraAnimationModels"), TEXT("0x1008e310"),
		TEXT("29c"), DebugString());
}

// slot 247 0x10090c80 (walked) `void SetAttackExtentsForSequence(int)`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumAnimating::SetAttackExtentsForSequence`, written by hand in
// the substrate. Declared here, defined there.

// slot 248 0x10091740 (sdk) `float GetIdealSpeed() const`
//   layer 0, story 29c
// verdict `rule`: the body is `FElysiumAnimating::GetIdealSpeed`, written by hand in the substrate.
// Declared here, defined there.

// slot 249 0x100917e0 (sdk) `float GetIdealAccel() const`
//   layer 0, story 29c
float FElysiumAnimating::GetIdealAccel() const
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetIdealAccel"), TEXT("0x100917e0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 250 0x1008f120 (walked) `float StudioFrameAdvance(float)`
//   layer 0, story 29c
float FElysiumAnimating::StudioFrameAdvance(float)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::StudioFrameAdvance"), TEXT("0x1008f120"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 251 0x1004fc70 (walked) `bool IsActivityFinished()`
bool FElysiumAnimating::IsActivityFinished()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::IsActivityFinished"), TEXT("0x1004fc70"), TEXT(""),
		DebugString());
	return {};
}

// slot 252 0x1008f3c0 (walked) `int SelectWeightedSequenceForStat(Activity, int, int)`
int32 FElysiumAnimating::SelectWeightedSequenceForStat(int32, int32, int32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::SelectWeightedSequenceForStat"), TEXT("0x1008f3c0"),
		TEXT(""), DebugString());
	return {};
}

// slot 253 0x1008f600 (walked) `int SelectHeaviestSequenceForStat(Activity, int, int)`
int32 FElysiumAnimating::SelectHeaviestSequenceForStat(int32, int32, int32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::SelectHeaviestSequenceForStat"), TEXT("0x1008f600"),
		TEXT(""), DebugString());
	return {};
}

// slot 254 0x1008f480 (walked) `int SelectSameSequenceForStat(Activity, int, int)`
int32 FElysiumAnimating::SelectSameSequenceForStat(int32, int32, int32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::SelectSameSequenceForStat"), TEXT("0x1008f480"),
		TEXT(""), DebugString());
	return {};
}

// slot 255 0x10095fe0 (walked) `void GetSkeleton(Vector*, Quaternion*, int)`
//   takes `Quaternion*`
void FElysiumAnimating::GetSkeleton(FVector*, void*, int32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetSkeleton"), TEXT("0x10095fe0"), TEXT(""),
		DebugString());
}

// slot 256 0x100927f0 (sdk) `void GetBoneTransform(int, matrix3x4_t&)`
//   takes `matrix3x4_t&`
//   layer 0, story 29c
void FElysiumAnimating::GetBoneTransform(int32, void*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetBoneTransform"), TEXT("0x100927f0"), TEXT("29c"),
		DebugString());
}

// slot 257 0x10092b50 (sdk) `void SetupBones(matrix3x4_t*, int)`
//   takes `matrix3x4_t*`
//   layer 0, story 29c
void FElysiumAnimating::SetupBones(void*, int32)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::SetupBones"), TEXT("0x10092b50"), TEXT("29c"),
		DebugString());
}

// slot 258 0x10091880 (walked) `void DispatchAnimEvents(float, CBaseAnimating*)`
//   layer 0, story 29c
void FElysiumAnimating::DispatchAnimEvents(float, FElysiumEntity*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::DispatchAnimEvents"), TEXT("0x10091880"), TEXT("29c"),
		DebugString());
}

// slot 260 0x10091fe0 (walked) `float SetPoseParameter02(int, float)`
//   layer 0, story 29c
float FElysiumAnimating::SetPoseParameter02(int32, float)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::SetPoseParameter02"), TEXT("0x10091fe0"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 261 0x10091f10 (walked) `float SetPoseParameter01(const char*, float)`
//   layer 0, story 29c
float FElysiumAnimating::SetPoseParameter01(const TCHAR*, float)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::SetPoseParameter01"), TEXT("0x10091f10"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 262 0x10093000 (walked) `bool GetAttachment03(int, matrix3x4_t&)`
//   takes `matrix3x4_t&`
//   layer 0, story 29c
bool FElysiumAnimating::GetAttachment03(int32, void*)
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetAttachment03"), TEXT("0x10093000"), TEXT("29c"),
		DebugString());
	return {};
}

// slot 263 0x10094870 (sdk) `Vector GetGroundSpeedVelocity()`
//   layer 0, story 29c
FVector FElysiumAnimating::GetGroundSpeedVelocity()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::GetGroundSpeedVelocity"), TEXT("0x10094870"),
		TEXT("29c"), DebugString());
	return {};
}

// slot 264 0x10096980 (walked) `void DrawServerHitboxes()`
//   layer 0, story 29c
void FElysiumAnimating::DrawServerHitboxes()
{
	FireAnimatingSlot(TEXT("CBaseAnimating::DrawServerHitboxes"), TEXT("0x10096980"), TEXT("29c"),
		DebugString());
}

namespace ElysiumNpcKernelShape
{
	namespace
	{
		// Every generated slot row of `FElysiumAnimating`, in slot order: the census the class answers
		// for (`Elysium.Substrate.NpcKernelShape.SlotOwners`) and, for each recovered default,
		// the probe `Elysium.Substrate.NpcKernelSlots.Defaults` calls on a receiver of this
		// class. `bDeclaredHere` is decided by the compiler, not written.
		const TElysiumNpcSlotRow<FElysiumAnimating> GAnimatingSlotRows[] =
		{
			{ 5, TEXT("0x1008b390"), TEXT("CBaseAnimating"), TEXT("Slot5"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void*(uint32)>::Test(&FElysiumAnimating::Slot5),
				nullptr },
			{ 31, TEXT("0x1008b530"), TEXT("CBaseAnimating"), TEXT("Dump"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(int32)>::Test(&FElysiumAnimating::Dump),
				nullptr },
			{ 68, TEXT("0x1008bfe0"), TEXT("CBaseAnimating"), TEXT("ShouldIgnoreCollision"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, bool(FElysiumEntity*)>::Test(&FElysiumAnimating::ShouldIgnoreCollision),
				nullptr },
			{ 79, TEXT("0x10097ae0"), TEXT("CBaseAnimating"), TEXT("GetPredDescMap"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void*()>::Test(&FElysiumAnimating::GetPredDescMap),
				nullptr },
			{ 80, TEXT("0x1008a9f0"), TEXT("CBaseAnimating"), TEXT("GetServerClass"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void*()>::Test(&FElysiumAnimating::GetServerClass),
				nullptr },
			{ 81, TEXT("0x1008aa10"), TEXT("CBaseAnimating"),
				TEXT("YouForgotToImplementOrDeclareServerClass"), EElysiumNpcSlotBody::Stub,
				TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, int32()>::Test(&FElysiumAnimating::YouForgotToImplementOrDeclareServerClass),
				nullptr },
			{ 82, TEXT("0x1008a760"), TEXT("CBaseAnimating"), TEXT("GetDataDescMap"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void*()>::Test(&FElysiumAnimating::GetDataDescMap),
				nullptr },
			{ 99, TEXT("0x100956e0"), TEXT("CBaseAnimating"), TEXT("TestCollision"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, bool(void*, int32, void*)>::Test(&FElysiumAnimating::TestCollision),
				nullptr },
			{ 100, TEXT("0x10095a20"), TEXT("CBaseAnimating"), TEXT("TestHitboxes"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, bool(void*, int32, void*)>::Test(&FElysiumAnimating::TestHitboxes),
				nullptr },
			{ 105, TEXT("0x10095030"), TEXT("CBaseAnimating"), TEXT("SetModel"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(TCHAR*)>::Test(&FElysiumAnimating::SetModel),
				nullptr },
			{ 110, TEXT("0x101c1480"), TEXT("CBaseToggle"), TEXT("KeyValue"),
				EElysiumNpcSlotBody::Hand, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, bool(const TCHAR*, const TCHAR*)>::Test(&FElysiumAnimating::KeyValue),
				nullptr },
			{ 124, TEXT("0x10096100"), TEXT("CBaseAnimating"), TEXT("DrawDebugTextOverlays"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, int32()>::Test(&FElysiumAnimating::DrawDebugTextOverlays),
				nullptr },
			{ 130, TEXT("0x1008df10"), TEXT("CBaseAnimating"), TEXT("OnRestore"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(bool)>::Test(&FElysiumAnimating::OnRestore),
				nullptr },
			{ 137, TEXT("0x1004fc50"), TEXT("CBaseAnimating"), TEXT("GetBaseAnimating"),
				EElysiumNpcSlotBody::Hand, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, FElysiumEntity*()>::Test(&FElysiumAnimating::GetBaseAnimating),
				nullptr },
			{ 199, TEXT("0x10095e50"), TEXT("CBaseAnimating"), TEXT("GetVelocity"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, true,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(FVector*, void*)>::Test(&FElysiumAnimating::GetVelocity),
				nullptr },
			{ 241, TEXT("0x1008c170"), TEXT("CBaseAnimating"), TEXT("GetEventName"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(TCHAR*, void*)>::Test(&FElysiumAnimating::GetEventName),
				nullptr },
			{ 242, TEXT("0x100916a0"), TEXT("CBaseAnimating"), TEXT("GetIdealYawSpeed"),
				EElysiumNpcSlotBody::Hand, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, float()>::Test(&FElysiumAnimating::GetIdealYawSpeed),
				nullptr },
			{ 243, TEXT("0x10090580"), TEXT("CBaseAnimating"), TEXT("BurnModel"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(const TCHAR*, bool)>::Test(&FElysiumAnimating::BurnModel),
				nullptr },
			{ 244, TEXT("0x1004fc30"), TEXT("CBaseAnimating"), TEXT("GetSkeletonModelName"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, const TCHAR*()>::Test(&FElysiumAnimating::GetSkeletonModelName),
				nullptr },
			{ 245, TEXT("0x1008e0a0"), TEXT("CBaseAnimating"), TEXT("AddExtraAnimationModels"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(FElysiumEntity*, const TCHAR*, const TCHAR*, int32, int32)>::Test(&FElysiumAnimating::AddExtraAnimationModels),
				nullptr },
			{ 246, TEXT("0x1008e310"), TEXT("CBaseAnimating"), TEXT("RemoveExtraAnimationModels"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void()>::Test(&FElysiumAnimating::RemoveExtraAnimationModels),
				nullptr },
			{ 247, TEXT("0x10090c80"), TEXT("CBaseAnimating"), TEXT("SetAttackExtentsForSequence"),
				EElysiumNpcSlotBody::Hand, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(int32)>::Test(&FElysiumAnimating::SetAttackExtentsForSequence),
				nullptr },
			{ 248, TEXT("0x10091740"), TEXT("CBaseAnimating"), TEXT("GetIdealSpeed"),
				EElysiumNpcSlotBody::Hand, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, float() const>::Test(&FElysiumAnimating::GetIdealSpeed),
				nullptr },
			{ 249, TEXT("0x100917e0"), TEXT("CBaseAnimating"), TEXT("GetIdealAccel"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, float() const>::Test(&FElysiumAnimating::GetIdealAccel),
				nullptr },
			{ 250, TEXT("0x1008f120"), TEXT("CBaseAnimating"), TEXT("StudioFrameAdvance"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, float(float)>::Test(&FElysiumAnimating::StudioFrameAdvance),
				nullptr },
			{ 251, TEXT("0x1004fc70"), TEXT("CBaseAnimating"), TEXT("IsActivityFinished"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, bool()>::Test(&FElysiumAnimating::IsActivityFinished),
				nullptr },
			{ 252, TEXT("0x1008f3c0"), TEXT("CBaseAnimating"),
				TEXT("SelectWeightedSequenceForStat"), EElysiumNpcSlotBody::Stub, TEXT(""), 0,
				false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, int32(int32, int32, int32)>::Test(&FElysiumAnimating::SelectWeightedSequenceForStat),
				nullptr },
			{ 253, TEXT("0x1008f600"), TEXT("CBaseAnimating"),
				TEXT("SelectHeaviestSequenceForStat"), EElysiumNpcSlotBody::Stub, TEXT(""), 0,
				false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, int32(int32, int32, int32)>::Test(&FElysiumAnimating::SelectHeaviestSequenceForStat),
				nullptr },
			{ 254, TEXT("0x1008f480"), TEXT("CBaseAnimating"), TEXT("SelectSameSequenceForStat"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, int32(int32, int32, int32)>::Test(&FElysiumAnimating::SelectSameSequenceForStat),
				nullptr },
			{ 255, TEXT("0x10095fe0"), TEXT("CBaseAnimating"), TEXT("GetSkeleton"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(FVector*, void*, int32)>::Test(&FElysiumAnimating::GetSkeleton),
				nullptr },
			{ 256, TEXT("0x100927f0"), TEXT("CBaseAnimating"), TEXT("GetBoneTransform"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(int32, void*)>::Test(&FElysiumAnimating::GetBoneTransform),
				nullptr },
			{ 257, TEXT("0x10092b50"), TEXT("CBaseAnimating"), TEXT("SetupBones"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(void*, int32)>::Test(&FElysiumAnimating::SetupBones),
				nullptr },
			{ 258, TEXT("0x10091880"), TEXT("CBaseAnimating"), TEXT("DispatchAnimEvents"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void(float, FElysiumEntity*)>::Test(&FElysiumAnimating::DispatchAnimEvents),
				nullptr },
			{ 260, TEXT("0x10091fe0"), TEXT("CBaseAnimating"), TEXT("SetPoseParameter02"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, float(int32, float)>::Test(&FElysiumAnimating::SetPoseParameter02),
				nullptr },
			{ 261, TEXT("0x10091f10"), TEXT("CBaseAnimating"), TEXT("SetPoseParameter01"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, float(const TCHAR*, float)>::Test(&FElysiumAnimating::SetPoseParameter01),
				nullptr },
			{ 262, TEXT("0x10093000"), TEXT("CBaseAnimating"), TEXT("GetAttachment03"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, bool(int32, void*)>::Test(&FElysiumAnimating::GetAttachment03),
				nullptr },
			{ 263, TEXT("0x10094870"), TEXT("CBaseAnimating"), TEXT("GetGroundSpeedVelocity"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, FVector()>::Test(&FElysiumAnimating::GetGroundSpeedVelocity),
				nullptr },
			{ 264, TEXT("0x10096980"), TEXT("CBaseAnimating"), TEXT("DrawServerHitboxes"),
				EElysiumNpcSlotBody::Stub, TEXT(""), 0, false, false,
				ElysiumNpcKernelShape::TDeclaredOn<FElysiumAnimating, void()>::Test(&FElysiumAnimating::DrawServerHitboxes),
				nullptr },
		};
	}

	TArrayView<const TElysiumNpcSlotRow<FElysiumAnimating>> AnimatingSlotRows()
	{
		return MakeArrayView(GAnimatingSlotRows);
	}
}
