#include "Substrate/ElysiumNpcKernelShapeMap.h"

#include "Substrate/ElysiumDamage.h"
#include "Substrate/ElysiumNpc.h"
#include "Substrate/ElysiumNpcConditions.h"
#include "Substrate/ElysiumNpcDialogue.h"
#include "Substrate/ElysiumNpcEnemyMemory.h"
#include "Substrate/ElysiumNpcFlags.h"
#include "Substrate/ElysiumNpcMind.h"
#include "Substrate/ElysiumNpcScheduleHost.h"
#include "Substrate/ElysiumNpcSenses.h"
#include "Substrate/ElysiumNpcWitness.h"
#include "Substrate/ElysiumSchedule.h"

// One row per word of `CAI_BaseNPC` and `CAI_BaseNPCTroika` — the 388 the NPC itself carries, in
// offset order, exactly as `docs/vtmb/npc-kernel/layout.md` lists them. The census
// (`ElysiumNpcKernelShape.cpp`) is generated from the ledger and says what each word IS; this file
// is written by hand and says what this runtime made of it, and the test joins the two.
//
// Reading a row: `ELYSIUM_NPC_WORD` compiles the member's type and name, so it cannot go stale.
// `_PRIVATE` is a member its owner keeps private, named as a string because `sizeof` cannot reach
// it. `_CHAIN` is a concern the port carries below the NPC. `_IMPLICIT` and `_ABSENT` have no
// member and say why — an `_ABSENT` row is a recorded gap, never an oversight.

namespace
{
	constexpr FElysiumNpcWordBinding GBindings[] =
	{
	ELYSIUM_NPC_WORD_IMPLICIT(0x0000, "the C++ vtable"),
	ELYSIUM_NPC_WORD_CHAIN(0x0004, "FElysiumEntity::TargetName",
		"retail's fixed-buffer debug copy of the entity name; the chain carries the name itself"),
	ELYSIUM_NPC_WORD_CHAIN(0x0024, "FElysiumEntity::Class",
		"retail's debug copy of the classname; the registry descriptor carries it"),
	ELYSIUM_NPC_WORD_CHAIN(0x0224, "FElysiumEntity::DebugOverlays",
		"m_debugOverlays, the ent_text bit set every slot-123/124/620 body gates on; family Debug "
		"(29c-1) declared it on the chain because it is a CBaseEntity word, not an NPC one"),
	ELYSIUM_NPC_WORD(0x1a40, FElysiumNpcScheduleHost, bShouldMove),
	ELYSIUM_NPC_WORD(0x1a44, FElysiumNpc, CollisionMask),
	ELYSIUM_NPC_WORD_NOTED(0x1a48, FElysiumNpc, DeferredDeathInfo,
		"CTakeDamageInfo is this port's typed damage packet"),
	ELYSIUM_NPC_WORD(0x1a94, FElysiumNpcMemory, LastEnemy),
	ELYSIUM_NPC_WORD(0x1a98, FElysiumNpc, AlternateEquipment),
	ELYSIUM_NPC_WORD_NOTED(0x1a9c, FElysiumNpcCognition, DelayedConditions,
		"retail's eight-slot CAI_DelayedConditionList: a condition number and its promote stamp"),
	ELYSIUM_NPC_WORD_PRIVATE(0x1ae0, "FElysiumNpcSenses::PendingSounds",
		"the delayed sound-condition list, condition plus promote time"),
	ELYSIUM_NPC_WORD(0x1b24, FElysiumNpcScheduleHost, InterruptTime),
	ELYSIUM_NPC_WORD_PRIVATE(0x1b28, "FElysiumNpcMind::bForceStateChange",
		"private to its owner: m_bForceStateChange"),
	ELYSIUM_NPC_WORD_ABSENT(0x1b2c,
		"retail's file/line selector trace; this runtime records selections in the mind's "
			"transition trace"),
	ELYSIUM_NPC_WORD_ABSENT(0x1b38,
		"retail's file/line ideal-state trace; the mind's transition trace carries the same "
			"account"),
	ELYSIUM_NPC_WORD_ABSENT(0x1b44,
		"retail's file/line task-failure trace; the named failure reason and the schedule trace "
			"rows carry it"),
	ELYSIUM_NPC_WORD(0x1b4c, FElysiumNpcScheduleHost, bRanAi),
	ELYSIUM_NPC_WORD_NOTED(0x1b4d, FElysiumNpc, bUnknown1b4d,
		"unsettled in 29b-0; carried by offset name with its recorded type"),
	ELYSIUM_NPC_WORD_ABSENT(0x1b4e,
		"retail's 16 KB in-memory AI debug ring; this runtime logs through its own channels"),
	ELYSIUM_NPC_WORD_ABSENT(0x5b50, "the write cursor of that debug ring"),
	ELYSIUM_NPC_WORD_ABSENT(0x5b54, "the wrap latch of that debug ring"),
	ELYSIUM_NPC_WORD_ABSENT(0x5b55, "the dump request for that debug ring"),
	ELYSIUM_NPC_WORD_NOTED(0x5b58, FElysiumNpc, Unknown5b58,
		"unsettled in 29b-0; carried by offset name with its recorded type"),
	ELYSIUM_NPC_WORD_NOTED(0x5b5c, FElysiumNpc, NpcInitTime,
		"an absolute curtime stamp, carried as double like every other stamp here"),
	ELYSIUM_NPC_WORD_NOTED(0x5b60, FElysiumNpc, NextDoorUseTime,
		"an absolute curtime stamp, carried as double"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5b64,
		"the per-state capability byte is a pure function of the state here "
			"(FElysiumNpc::NpcStateFlags)"),
	ELYSIUM_NPC_WORD_NOTED(0x5b68, FElysiumNpcMemory, LastSeen,
		"the HATE element of the seen-by-disposition array"),
	ELYSIUM_NPC_WORD_NOTED(0x5b6c, FElysiumNpcMemory, LastSeen, "the FEAR element"),
	ELYSIUM_NPC_WORD_NOTED(0x5b70, FElysiumNpcMemory, LastSeen, "the DISLIKE element"),
	ELYSIUM_NPC_WORD_NOTED(0x5b74, FElysiumNpcMemory, LastSeen, "the NEMESIS element"),
	ELYSIUM_NPC_WORD_NOTED(0x5b78, FElysiumNpcMemory, BestSoundSource,
		"the port cites +0x5b78 here; LastHeardSource beside it is the raw stimulus record"),
	ELYSIUM_NPC_WORD(0x5b7c, FElysiumNpcMemory, LastDamageAttacker),
	ELYSIUM_NPC_WORD(0x5b80, FElysiumNpcCognition, bCondTookDamage),
	ELYSIUM_NPC_WORD_PRIVATE(0x5b84, "FElysiumNpcFlags::FrenziedWord",
		"private to its owner: m_bfNPCFrenziedFlags"),
	ELYSIUM_NPC_WORD_NOTED(0x5b88, FElysiumNpc, WeaponBlockedByFriendTimer,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD_NOTED(0x5b8c, FElysiumNpc, ExtendedBlockedByFriendTimer,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD_ABSENT(0x5b90,
		"retail's cached surfacedata_t*; this runtime resolves the step surface per footfall and "
			"records only the null case"),
	ELYSIUM_NPC_WORD(0x5b94, FElysiumNpc, RelativeEyeTarget),
	ELYSIUM_NPC_WORD(0x5b98, FElysiumNpcMemory, EnemyOccludedCheck),
	ELYSIUM_NPC_WORD(0x5b9c, FElysiumNpcMemory, LastDamageAttackPosition),
	ELYSIUM_NPC_WORD(0x5ba8, FElysiumNpc, ShootTargetOverride),
	ELYSIUM_NPC_WORD(0x5bac, FElysiumNpc, SpecialDistanceAccum),
	ELYSIUM_NPC_WORD(0x5bb0, FElysiumNpcScheduleHost, SquadDisconnected),
	ELYSIUM_NPC_WORD_PRIVATE(0x5bb4, "FElysiumNpcFlags::ObliviousCount",
		"private to its owner: m_iIsOblivious"),
	ELYSIUM_NPC_WORD(0x5bb8, FElysiumScheduleState, bDidMaintainSchedule),
	ELYSIUM_NPC_WORD(0x5bbc, FElysiumNpc, BurstShootPauseMin),
	ELYSIUM_NPC_WORD(0x5bc0, FElysiumNpc, BurstShootPauseMax),
	ELYSIUM_NPC_WORD(0x5bc4, FElysiumNpc, bInChoreoScene),
	ELYSIUM_NPC_WORD_NOTED(0x5bc5, FElysiumNpcMemory, bEnemyWentOccluded,
		"the occlusion edge, distinct from bEnemyOccluded which is the ten-failure debounce"),
	ELYSIUM_NPC_WORD(0x5bc8, FElysiumNpcMemory, EnemyWentOccludedPosition),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5bd8,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5bf0,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5c08,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5c20,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD(0x5c38, FElysiumScheduleState, Current),
	ELYSIUM_NPC_WORD_NOTED(0x5c3c, FElysiumNpcScheduleHost, IdealSchedule,
		"the port's schedule id is a uint8 enum carrying retail's registered number, so it is "
			"narrower than the retail word"),
	ELYSIUM_NPC_WORD_NOTED(0x5c40, FElysiumNpc, Schedule,
		"the task index, status and stamps of the running program"),
	ELYSIUM_NPC_WORD_NOTED(0x5c54, FElysiumScheduleState, FailScheduleOverride,
		"the port's schedule id is a uint8 enum carrying retail's registered number, so it is "
			"narrower than the retail word"),
	ELYSIUM_NPC_WORD(0x5c58, FElysiumNpcScheduleHost, bDoPostRestoreRefindPath),
	ELYSIUM_NPC_WORD(0x5c5c, FElysiumNpcCognition, Conditions),
	ELYSIUM_NPC_WORD_NOTED(0x5c74, FElysiumNpcCognition, CustomInterruptConditions,
		"retail's cached mask; today recomputed each think by ElysiumSchedule::EffectiveInterrupts"),
	ELYSIUM_NPC_WORD_NOTED(0x5c8c, FElysiumNpcCognition, InverseInterruptConditions,
		"the inverted !COND mask retail keeps as a second word"),
	ELYSIUM_NPC_WORD_NOTED(0x5ca4, FElysiumNpcCognition, GatheredAt,
		"the gathered marker, carried as the pass stamp"),
	ELYSIUM_NPC_WORD(0x5ca8, FElysiumNpcSenses, HeardConditions),
	ELYSIUM_NPC_WORD_PRIVATE(0x5cc0, "FElysiumNpcMind::CurrentState",
		"private to its owner: m_NPCState"),
	ELYSIUM_NPC_WORD_PRIVATE(0x5cc4, "FElysiumNpcMind::DesiredState",
		"private to its owner: m_IdealNPCState"),
	ELYSIUM_NPC_WORD_PRIVATE(0x5cc8, "FElysiumNpcMind::LastStateChangeTime",
		"an absolute curtime stamp, carried as double"),
	ELYSIUM_NPC_WORD_NOTED(0x5ccc, FElysiumNpc, IdealSequence,
		"retail's resolved sequence index; this runtime's ideal is the clip identity beside it"),
	ELYSIUM_NPC_WORD_NOTED(0x5cd0, FElysiumNpc, IdealTranslatedActivity,
		"an activity enum with no port counterpart, so the registered number"),
	ELYSIUM_NPC_WORD_NOTED(0x5cd4, FElysiumNpc, IdealWeaponActivity,
		"an activity enum with no port counterpart, so the registered number"),
	ELYSIUM_NPC_WORD(0x5cd8, FElysiumNpcSenses, bKeepSound),
	ELYSIUM_NPC_WORD(0x5cdc, FElysiumNpc, Senses),
	ELYSIUM_NPC_WORD(0x5ce0, FElysiumNpcMemory, Enemy),
	ELYSIUM_NPC_WORD_PRIVATE(0x5ce4, "FElysiumNpc::TargetEnt",
		"private to its owner: m_hTargetEnt"),
	ELYSIUM_NPC_WORD_NOTED(0x5ce8, FElysiumNpcMemory, SoundWaitTime,
		"an absolute curtime deadline, beside the other two sound clocks"),
	ELYSIUM_NPC_WORD_NOTED(0x5cec, FElysiumNpc, CapabilityWord,
		"the whole capability word; ElysiumNpcCond::ECapability is only the two bits combat "
			"selection reads"),
	ELYSIUM_NPC_WORD(0x5cf0, FElysiumNpcScheduleHost, MoveWaitFinished),
	ELYSIUM_NPC_WORD_ABSENT(0x5cf4,
		"CAI_MoveAndShootOverlay has no counterpart; this runtime's motor carries no "
			"move-and-shoot overlay"),
	ELYSIUM_NPC_WORD(0x5d24, FElysiumNpc, OpeningDoor),
	ELYSIUM_NPC_WORD(0x5d28, FElysiumNpc, BlockedDoor),
	ELYSIUM_NPC_WORD(0x5d2c, FElysiumNpc, CondHitByDoor),
	ELYSIUM_NPC_WORD(0x5d30, FElysiumNpc, bOpeningDoorWait),
	ELYSIUM_NPC_WORD_CHAIN(0x5d34, "FElysiumScriptedCharacter::Motor",
		"the navigator is the one motor seam this chain stands beside the body"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d38, "FElysiumScriptedCharacter::Motor",
		"the local navigator is folded into the same motor seam"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d3c, "FElysiumScriptedCharacter::Motor",
		"the motor owns path generation"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d40, "FElysiumScriptedCharacter::Motor",
		"the motor answers the move probe's world queries"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d44, "FElysiumScriptedCharacter::Motor",
		"the motor's own steering state"),
	ELYSIUM_NPC_WORD_ABSENT(0x5d48,
		"UnreachableEnt_t has no port counterpart and this motor seam answers no reachability "
			"query"),
	ELYSIUM_NPC_WORD_NOTED(0x5d5c, FElysiumNpc, CheckOnGroundTime,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d60, "FElysiumEntity",
		"no stored view offset; the eye point is the chain's virtual EyePosition()"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d6c, "FElysiumCombatCharacter::NextEyeLookTime",
		"the port keeps the gaze scan clock on the combat character"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d70, "FElysiumScriptedCharacter::ScriptPhase",
		"the port spells retail's script state as the phase plus the entity's script owner"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d74, "FElysiumEntity::ScriptOwner", "m_hCine, on the entity chain"),
	ELYSIUM_NPC_WORD_CHAIN(0x5d78, "FElysiumEntity::bHidden",
		"script-hide is the chain's ScriptHide/ScriptUnhide pair, which keeps no separate cine "
			"latch"),
	ELYSIUM_NPC_WORD_NOTED(0x5d7c, FElysiumNpc, ScriptArrivalActivity,
		"an activity enum with no port counterpart, so the registered number"),
	ELYSIUM_NPC_WORD(0x5d80, FElysiumNpc, ScriptArrivalSequence),
	ELYSIUM_NPC_WORD_NOTED(0x5d88, FElysiumNpc, EnemyMemory,
		"the CAI_Memory store; squad redirection replaces the ownership, not the object"),
	ELYSIUM_NPC_WORD(0x5d8c, FElysiumNpcScheduleHost, MemoryBits),
	ELYSIUM_NPC_WORD(0x5d90, FElysiumNpcMemory, EnemyOccluder),
	ELYSIUM_NPC_WORD(0x5d94, FElysiumNpcMemory, RepeatedDamageAccumulated),
	ELYSIUM_NPC_WORD_NOTED(0x5d98, FElysiumNpcMemory, RepeatedDamageWindowStart,
		"the port cites +0x5d98 here; LastDamageTime beside it is the typed commit's own stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x5d9c, FElysiumNpc, LastAttackTime,
		"an absolute curtime stamp, carried as double"),
	ELYSIUM_NPC_WORD_NOTED(0x5da0, FElysiumNpc, NextWeaponSearchTime,
		"an absolute curtime stamp, carried as double"),
	ELYSIUM_NPC_WORD_ABSENT(0x5da4,
		"this substrate has no squad object, which is why ConnectedSquad() answers nothing"),
	ELYSIUM_NPC_WORD(0x5da8, FElysiumNpc, SquadName),
	ELYSIUM_NPC_WORD(0x5dac, FElysiumNpc, MySquadSlot),
	ELYSIUM_NPC_WORD(0x5db0, FElysiumNpcScheduleHost, HintGroup),
	ELYSIUM_NPC_WORD_NOTED(0x5db4, FElysiumNpcScheduleHost, WaitFinished,
		"an absolute curtime deadline, beside its existing bWaitFinishedSet"),
	ELYSIUM_NPC_WORD(0x5db8, FElysiumNpc, LastPosition),
	ELYSIUM_NPC_WORD_NOTED(0x5dc4, FElysiumNpc, LastFacing,
		"retail types it Vector though it holds angles, as the chain stores Angles as FVector"),
	ELYSIUM_NPC_WORD(0x5dd0, FElysiumNpc, SavePosition),
	ELYSIUM_NPC_WORD_NOTED(0x5ddc, FElysiumNpcScheduleHost, HintNode,
		"the claimed hint is carried as a node index, not an entity handle"),
	ELYSIUM_NPC_WORD_CHAIN(0x5de0, "FElysiumCombatCharacter::Inventory",
		"the loaded magazine lives on the held item's record, not on the NPC"),
	ELYSIUM_NPC_WORD(0x5de4, FElysiumNpc, DistTooFar),
	ELYSIUM_NPC_WORD(0x5de8, FElysiumNpcScheduleHost, GoalEnt),
	ELYSIUM_NPC_WORD(0x5dec, FElysiumNpc, AdditionalEquipment),
	ELYSIUM_NPC_WORD(0x5df0, FElysiumNpc, bNoDamageDecal),
	ELYSIUM_NPC_WORD(0x5df4, FElysiumNpcScheduleHost, StoredPathTarget),
	ELYSIUM_NPC_WORD(0x5df8, FElysiumNpcScheduleHost, StoredPathGoal),
	ELYSIUM_NPC_WORD_NOTED(0x5e04, FElysiumNpcScheduleHost, StoredPathType,
		"GoalType_t has no port enum"),
	ELYSIUM_NPC_WORD(0x5e08, FElysiumNpcScheduleHost, StoredPathFlags),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5e0c,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5e24,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5e3c,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5e54,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5e6c,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5e84,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5e9c,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5eb4,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5ecc,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5ee4,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5efc,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5f14,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD(0x5f2c, FElysiumNpc, bWantsLargeHull),
	ELYSIUM_NPC_WORD(0x5f2d, FElysiumNpc, bIsUsingSmallHull),
	ELYSIUM_NPC_WORD(0x5f30, FElysiumNpcScheduleHost, FailText),
	ELYSIUM_NPC_WORD(0x5f34, FElysiumNpcScheduleHost, InterruptText),
	ELYSIUM_NPC_WORD(0x5f38, FElysiumNpcScheduleHost, FailedSchedule),
	ELYSIUM_NPC_WORD(0x5f3c, FElysiumNpcScheduleHost, InterruptSchedule),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5f44,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5f5c,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5f74,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5f8c,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5fa4,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5fbc,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5fd4,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x5fec,
		"outputs are fired by name through FElysiumEntity::FireOutput"),
	ELYSIUM_NPC_WORD(0x6004, FElysiumNpc, KnockbackVelocity),
	ELYSIUM_NPC_WORD(0x6010, FElysiumNpc, KnockbackHitEntity),
	ELYSIUM_NPC_WORD_NOTED(0x6014, FElysiumNpc, KnockbackWallHitFallTime,
		"an absolute curtime stamp, carried as double"),
	ELYSIUM_NPC_WORD_NOTED(0x6018, FElysiumNpc, FinishingMoveBoneTrackLastTime,
		"an absolute curtime stamp, carried as double"),
	ELYSIUM_NPC_WORD(0x601c, FElysiumNpc, FinishingMoveBoneTrackLastPos),
	ELYSIUM_NPC_WORD_ABSENT(0x6028,
		"MeleeMoveRecord_t has no port counterpart; the melee selector keeps its own retained draw"),
	ELYSIUM_NPC_WORD_CHAIN(0x6064, "FElysiumCombatCharacter::HitBuildupCount",
		"the port cites +0x6064 there"),
	ELYSIUM_NPC_WORD_NOTED(0x6068, FElysiumNpc, KnockbackType,
		"retail's raw type word; the port's classification is ElysiumReactions' "
			"size/height/direction triple"),
	ELYSIUM_NPC_WORD_NOTED(0x606c, FElysiumNpc, LastMeleeStepbackTime,
		"an absolute curtime stamp, carried as double"),
	ELYSIUM_NPC_WORD_NOTED(0x6070, FElysiumNpc, MeleeCanEnterTimer,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD_NOTED(0x6074, FElysiumNpc, MeleeMustLeaveTimer,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD(0x6078, FElysiumNpc, bInMelee),
	ELYSIUM_NPC_WORD_NOTED(0x607c, FElysiumNpc, CanSeekCoverTimer,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD_PRIVATE(0x6080, "FElysiumNpc::bDisableAi",
		"private to its owner: m_bDisableAI"),
	ELYSIUM_NPC_WORD_NOTED(0x6081, FElysiumNpcMemory, bPlayerInOuterBand,
		"the outer-band sighting the see-unknown path reads"),
	ELYSIUM_NPC_WORD(0x6084, FElysiumNpcMemory, SeeUnknownGraceUntil),
	ELYSIUM_NPC_WORD(0x6088, FElysiumNpcMemory, BestSeeUnknown),
	ELYSIUM_NPC_WORD(0x608c, FElysiumNpcMemory, LastSeeUnknown),
	ELYSIUM_NPC_WORD(0x6090, FElysiumNpcMemory, LastSeeUnknownPosition),
	ELYSIUM_NPC_WORD(0x609c, FElysiumNpcMemory, SeeUnknownRunTimer),
	ELYSIUM_NPC_WORD(0x60a0, FElysiumNpcMemory, SeeUnknownStartTimer),
	ELYSIUM_NPC_WORD(0x60a4, FElysiumNpcMemory, SeeUnknownRepeatSightings),
	ELYSIUM_NPC_WORD(0x60a8, FElysiumNpc, EnemySightings),
	ELYSIUM_NPC_WORD(0x60ac, FElysiumNpc, FriendPlayer),
	ELYSIUM_NPC_WORD(0x60b0, FElysiumNpcMemory, BestSound),
	ELYSIUM_NPC_WORD(0x60dc, FElysiumNpcMemory, InvestigateSound),
	ELYSIUM_NPC_WORD(0x6108, FElysiumNpcMemory, LastSoundDanger),
	ELYSIUM_NPC_WORD(0x6134, FElysiumNpcMemory, LastSoundPhysicsDanger),
	ELYSIUM_NPC_WORD(0x6160, FElysiumNpcMemory, LastSoundCombat),
	ELYSIUM_NPC_WORD(0x618c, FElysiumNpcMemory, LastSoundBulletImpact),
	ELYSIUM_NPC_WORD(0x61b8, FElysiumNpcMemory, LastSoundPlayer),
	ELYSIUM_NPC_WORD(0x61e4, FElysiumNpcMemory, LastSoundWorld),
	ELYSIUM_NPC_WORD(0x6210, FElysiumNpcMemory, LastSoundFlinch),
	ELYSIUM_NPC_WORD(0x623c, FElysiumNpcMemory, NextInvestigateSoundTime),
	ELYSIUM_NPC_WORD(0x6240, FElysiumNpcScheduleHost, MoveTarget),
	ELYSIUM_NPC_WORD(0x6244, FElysiumNpcScheduleHost, NextUpdate),
	ELYSIUM_NPC_WORD(0x6248, FElysiumNpcScheduleHost, NextNormal),
	ELYSIUM_NPC_WORD(0x624c, FElysiumNpcScheduleHost, NextMove),
	ELYSIUM_NPC_WORD(0x6250, FElysiumNpcScheduleHost, NextAI),
	ELYSIUM_NPC_WORD(0x6254, FElysiumNpcScheduleHost, LastUpdate),
	ELYSIUM_NPC_WORD(0x6258, FElysiumNpcScheduleHost, LastNormal),
	ELYSIUM_NPC_WORD(0x625c, FElysiumNpcScheduleHost, LastMove),
	ELYSIUM_NPC_WORD(0x6260, FElysiumNpcScheduleHost, LastAI),
	ELYSIUM_NPC_WORD_NOTED(0x6264, FElysiumNpcMemory, ClosestPlayerDistanceCm,
		"the port carries this distance in centimetres"),
	ELYSIUM_NPC_WORD(0x6268, FElysiumNpcScheduleHost, EnemyDistUnits),
	ELYSIUM_NPC_WORD(0x626c, FElysiumNpcScheduleHost, EnemyHeightDiffUnits),
	ELYSIUM_NPC_WORD(0x6270, FElysiumNpcScheduleHost, EnemyLastKnownDistUnits),
	ELYSIUM_NPC_WORD_NOTED(0x6274, FElysiumNpc, MeleeHeightDiffTimer,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD(0x6278, FElysiumNpcMemory, bPlayerInPvs),
	ELYSIUM_NPC_WORD(0x6279, FElysiumNpcMemory, bPlayerLos),
	ELYSIUM_NPC_WORD(0x627c, FElysiumNpcMemory, PlayerPvsLastClearTime),
	ELYSIUM_NPC_WORD(0x6280, FElysiumNpcMemory, PlayerLosLastClearTime),
	ELYSIUM_NPC_WORD(0x6284, FElysiumNpcMemory, PlayerLosNextUpdateTime),
	ELYSIUM_NPC_WORD_NOTED(0x6288, FElysiumNpcMemory, NextCheckEnterPvsTime,
		"an absolute curtime deadline, carried as double"),
	ELYSIUM_NPC_WORD_NOTED(0x628c, FElysiumNpcMemory, ClosestPlayer,
		"the closest-player cache the sense pass fills"),
	ELYSIUM_NPC_WORD_NOTED(0x6290, FElysiumNpc, Forward,
		"retail's cached facing basis; this runtime recomputes it per query"),
	ELYSIUM_NPC_WORD(0x629c, FElysiumNpc, Right),
	ELYSIUM_NPC_WORD(0x62a8, FElysiumNpc, InitialPosition),
	ELYSIUM_NPC_WORD_NOTED(0x62b4, FElysiumNpc, InitialAngles,
		"angles carried as FVector, as FElysiumEntity::Angles already is"),
	ELYSIUM_NPC_WORD(0x62c0, FElysiumNpc, OccludedDelayNormal),
	ELYSIUM_NPC_WORD(0x62c4, FElysiumNpc, OccludedDelayCover),
	ELYSIUM_NPC_WORD(0x62c8, FElysiumNpc, OccludedDelay),
	ELYSIUM_NPC_WORD_NOTED(0x62cc, FElysiumNpc, OccludedReportTimeE,
		"FIELD_TIME; an absolute stamp, carried as double like every other stamp here"),
	ELYSIUM_NPC_WORD_NOTED(0x62d0, FElysiumNpc, OccludedReportTimeT,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x62d4, FElysiumNpc, OccludedReportTimeW,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x62d8, FElysiumNpc, InterestingPlaceGroups, "the authored allowlist"),
	ELYSIUM_NPC_WORD_NOTED(0x62dc, FElysiumNpc, InterestingPlaceGroupMask,
		"retail's own shape: a 32-bit set, one bit per group id, parsed by `0x10298910`"),
	ELYSIUM_NPC_WORD_NOTED(0x62e0, FElysiumNpcScheduleHost, HintGroups,
		"the authored hint-group allowlist"),
	ELYSIUM_NPC_WORD_NOTED(0x62e4, FElysiumNpcScheduleHost, HintGroupMask,
		"retail's own shape: a 32-bit set, one bit per group id, parsed by `0x102989e0`"),
	ELYSIUM_NPC_WORD_PRIVATE(0x62e8, "FElysiumNpc::bAmbientArrived",
		"private to its owner: m_bInterestingPlaceArrived"),
	ELYSIUM_NPC_WORD_CHAIN(0x62e9, "FElysiumEntity::bSpawnCalled",
		"the entity base already latches 'Spawn has run'; retail's byte has no reader either"),
	ELYSIUM_NPC_WORD_PRIVATE(0x62ec, "FElysiumNpc::CurrentSpotIndex",
		"the port addresses a place by index rather than by pointer"),
	ELYSIUM_NPC_WORD(0x62f0, FElysiumNpc, InterestingPlacePosition),
	ELYSIUM_NPC_WORD_NOTED(0x62fc, FElysiumNpc, LastSpotIndex,
		"a place index; there is no interesting-place pointer in this runtime"),
	ELYSIUM_NPC_WORD_NOTED(0x6300, FElysiumNpcScheduleHost, Unknown6300,
		"the placeholder already reserved for +0x6300, cleared by both teardown virtuals"),
	ELYSIUM_NPC_WORD_PRIVATE(0x6304, "FElysiumNpc::AmbientPhase",
		"retail 1 is the INTO arm and 2 the idle dwell"),
	ELYSIUM_NPC_WORD(0x6308, FElysiumNpc, InterestingDeathActivity),
	ELYSIUM_NPC_WORD_ABSENT(0x630c,
		"no navigation-link object exists in this runtime's motor seam; the two restore node ids "
			"below carry the whole link"),
	ELYSIUM_NPC_WORD(0x6310, FElysiumNpc, RestorePedLinkNode),
	ELYSIUM_NPC_WORD(0x6314, FElysiumNpc, RestorePedLinkDestNode),
	ELYSIUM_NPC_WORD_NOTED(0x6318, FElysiumNpc, NextCrosswalkUpdateTime,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x631c, FElysiumNpc, NextPedInteractTime,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD(0x6320, FElysiumNpcScheduleHost, GoalToleranceCm),
	ELYSIUM_NPC_WORD(0x6324, FElysiumNpcScheduleHost, InsideInterruptDistanceSqr),
	ELYSIUM_NPC_WORD(0x6328, FElysiumNpcScheduleHost, OutsideInterruptDistanceSqr),
	ELYSIUM_NPC_WORD(0x632c, FElysiumNpcScheduleHost, InterruptTime),
	ELYSIUM_NPC_WORD_NOTED(0x6330, FElysiumNpcScheduleHost, WaitFinishedDelta,
		"FIELD_FLOAT in retail: a delta added to the wait deadline, not a stamp"),
	ELYSIUM_NPC_WORD(0x6334, FElysiumNpcScheduleHost, bWaitFinishedSet),
	ELYSIUM_NPC_WORD(0x6338, FElysiumNpc, InvestigateMode),
	ELYSIUM_NPC_WORD(0x633c, FElysiumNpc, InvestigateModeCombat),
	ELYSIUM_NPC_WORD_NOTED(0x6340, FElysiumNpc, FullInvestigate,
		"carried as the authored integer, not a bool"),
	ELYSIUM_NPC_WORD(0x6344, FElysiumNpc, BrightRoutePenalty),
	ELYSIUM_NPC_WORD(0x6348, FElysiumNpc, PlInvestigate),
	ELYSIUM_NPC_WORD(0x634c, FElysiumNpc, PlCriminalFlee),
	ELYSIUM_NPC_WORD(0x6350, FElysiumNpc, PlCriminalAttack),
	ELYSIUM_NPC_WORD(0x6354, FElysiumNpc, PlSupernaturalFlee),
	ELYSIUM_NPC_WORD(0x6358, FElysiumNpc, PlSupernaturalAttack),
	ELYSIUM_NPC_WORD_NOTED(0x635c, FElysiumNpcWitness, Channels,
		"the criminal channel's witnessed level; retail obfuscates the word through CSecureType"),
	ELYSIUM_NPC_WORD_NOTED(0x6368, FElysiumNpcWitness, Channels,
		"the supernatural channel's witnessed level"),
	ELYSIUM_NPC_WORD_NOTED(0x636c, FElysiumNpcWitness, Channels,
		"the criminal channel's processed count"),
	ELYSIUM_NPC_WORD_NOTED(0x6370, FElysiumNpcWitness, Channels,
		"the supernatural channel's processed count"),
	ELYSIUM_NPC_WORD_NOTED(0x6374, FElysiumNpcWitness, Channels,
		"the supernatural channel's witnessed location"),
	ELYSIUM_NPC_WORD_NOTED(0x6380, FElysiumNpcWitness, Channels,
		"the criminal channel's witnessed location"),
	ELYSIUM_NPC_WORD_NOTED(0x638c, FElysiumNpcWitness, Channels, "the criminal channel's offender"),
	ELYSIUM_NPC_WORD_NOTED(0x6390, FElysiumNpcWitness, Channels,
		"the supernatural channel's offender"),
	ELYSIUM_NPC_WORD(0x6394, FElysiumNpcWitness, bSupernaturalFleeOnly),
	ELYSIUM_NPC_WORD_NOTED(0x6398, FElysiumNpcWitness, Channels,
		"the criminal channel's ignore deadline"),
	ELYSIUM_NPC_WORD_NOTED(0x639c, FElysiumNpcWitness, Channels,
		"the supernatural channel's ignore deadline"),
	ELYSIUM_NPC_WORD(0x63a0, FElysiumNpcWitness, NosferatuIgnoreUntil),
	ELYSIUM_NPC_WORD_NOTED(0x63a4, FElysiumNpcWitness, CriminalWitnessedTime,
		"FIELD_TIME; the stamp beside the retained criminal record"),
	ELYSIUM_NPC_WORD_NOTED(0x63a8, FElysiumNpcWitness, SupernaturalWitnessedTime,
		"FIELD_TIME; the stamp beside the retained supernatural record"),
	ELYSIUM_NPC_WORD(0x63ac, FElysiumNpc, PlayerReaction),
	ELYSIUM_NPC_WORD_NOTED(0x63b0, FElysiumNpc, AuthoredPerception,
		"the npc_perception key as authored"),
	ELYSIUM_NPC_WORD_NOTED(0x63b4, FElysiumNpc, AuthoredVision,
		"the vision key as authored, sentinel included"),
	ELYSIUM_NPC_WORD_NOTED(0x63b8, FElysiumNpcPerception, VisionDistanceCm,
		"the resolved channel; the port converts to centimetres once"),
	ELYSIUM_NPC_WORD_NOTED(0x63bc, FElysiumNpc, AuthoredHearing,
		"the hearing key as authored, sentinel included"),
	ELYSIUM_NPC_WORD_NOTED(0x63c0, FElysiumNpcPerception, HearingScalar, "the resolved channel"),
	ELYSIUM_NPC_WORD_NOTED(0x63c4, FElysiumNpcSenses, StealthVisionScalar,
		"this body's own stealth surface, which an observer's cone test multiplies in"),
	ELYSIUM_NPC_WORD_NOTED(0x63c8, FElysiumNpcSenses, StealthVisionCone,
		"the target cone scalar of the same surface"),
	ELYSIUM_NPC_WORD(0x63cc, FElysiumNpcSenses, StealthHearingDist),
	ELYSIUM_NPC_WORD_PRIVATE(0x63d0, "FElysiumNpcSenses::LastListenTime",
		"the port stamps the last listen and adds the cadence rather than storing the next"),
	ELYSIUM_NPC_WORD_PRIVATE(0x63d4, "FElysiumNpc::AmbientNextActivityAt",
		"the interesting-place activity clock"),
	ELYSIUM_NPC_WORD(0x63d8, FElysiumNpc, bInvincible),
	ELYSIUM_NPC_WORD(0x63d9, FElysiumNpc, bUseInteresting),
	ELYSIUM_NPC_WORD(0x63da, FElysiumNpc, bForceNpcCheck),
	ELYSIUM_NPC_WORD_NOTED(0x63dc, FElysiumNpc, WeaponScareTime, "FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD(0x63e0, FElysiumNpcScheduleHost, bSavePositionWalk),
	ELYSIUM_NPC_WORD(0x63e4, FElysiumNpc, FaceAnim),
	ELYSIUM_NPC_WORD(0x63e8, FElysiumNpc, FaceYawDiff),
	ELYSIUM_NPC_WORD(0x63ec, FElysiumNpcScheduleHost, DesiredMoveYaw),
	ELYSIUM_NPC_WORD(0x63f0, FElysiumNpc, bForceFrequentThink),
	ELYSIUM_NPC_WORD(0x63f4, FElysiumNpc, AlertLevel),
	ELYSIUM_NPC_WORD(0x63f8, FElysiumNpc, SubState),
	ELYSIUM_NPC_WORD(0x63fc, FElysiumNpc, bGoToIdleState),
	ELYSIUM_NPC_WORD(0x63fd, FElysiumNpc, bLeaningLeft),
	ELYSIUM_NPC_WORD_NOTED(0x6400, FElysiumNpcScheduleHost, NextCoverLosCheck,
		"FIELD_TIME; declared beside the existing FailedCoverLosChecks"),
	ELYSIUM_NPC_WORD(0x6404, FElysiumNpcScheduleHost, FailedCoverLosChecks),
	ELYSIUM_NPC_WORD(0x6408, FElysiumNpcScheduleHost, bForceCoverLosCheck),
	ELYSIUM_NPC_WORD(0x640c, FElysiumNpc, PeekOutCount),
	ELYSIUM_NPC_WORD(0x6410, FElysiumNpc, bAggressiveAnims),
	ELYSIUM_NPC_WORD(0x6414, FElysiumNpc, CowerAnimOffset),
	ELYSIUM_NPC_WORD(0x6418, FElysiumNpcMemory, NextSeeSoundSourceTime),
	ELYSIUM_NPC_WORD_NOTED(0x641c, FElysiumNpcMemory, NextFleeSoundTime,
		"FIELD_TIME; the third sound clock beside the two already carried"),
	ELYSIUM_NPC_WORD(0x6420, FElysiumNpc, PercentOccludedWait),
	ELYSIUM_NPC_WORD(0x6424, FElysiumNpc, PercentOccludedCover),
	ELYSIUM_NPC_WORD(0x6428, FElysiumNpc, PercentOccludedWalk),
	ELYSIUM_NPC_WORD(0x642c, FElysiumNpc, PercentOccludedFlank),
	ELYSIUM_NPC_WORD(0x6430, FElysiumNpc, PercentOccludedChase),
	ELYSIUM_NPC_WORD(0x6434, FElysiumNpc, bAllowAlertLookaround),
	ELYSIUM_NPC_WORD_NOTED(0x6435, FElysiumNpc, bStayEntrenched,
		"step 2 of the interest predicate, whose keyfield is not parsed yet"),
	ELYSIUM_NPC_WORD(0x6436, FElysiumNpcScheduleHost, bAllowKickHintUse),
	ELYSIUM_NPC_WORD_NOTED(0x6438, FElysiumNpcScheduleHost, KickPropSearchTimer,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD(0x643c, FElysiumNpcScheduleHost, KickProp),
	ELYSIUM_NPC_WORD_NOTED(0x6440, FElysiumNpcScheduleHost, NextShootAtHintSearchTime,
		"an absolute curtime deadline"),
	ELYSIUM_NPC_WORD_NOTED(0x6444, FElysiumNpcScheduleHost, ShootAtHintNode,
		"hints are node indices here, as HintNode is; NOT the shoot-target override at +0x5ba8"),
	ELYSIUM_NPC_WORD(0x6448, FElysiumNpcScheduleHost, HintCoverObject),
	ELYSIUM_NPC_WORD_NOTED(0x644c, FElysiumNpc, AlternateAi,
		"RunAlternateAi has no stored mode yet"),
	ELYSIUM_NPC_WORD_NOTED(0x6450, FElysiumNpc, AlternateAiExpireTime,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD(0x6454, FElysiumNpc, PreOpenDoorActivity),
	ELYSIUM_NPC_WORD_NOTED(0x6458, FElysiumNpc, IgnoreCollisionUntil,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD(0x645c, FElysiumNpc, HuntPatrolTarget),
	ELYSIUM_NPC_WORD(0x6468, FElysiumNpc, HeldPosition),
	ELYSIUM_NPC_WORD_NOTED(0x6474, FElysiumNpc, HuntExpireTime, "FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x6478, FElysiumNpc, FollowerBossName, "the authored follower-boss key"),
	ELYSIUM_NPC_WORD_NOTED(0x647c, FElysiumNpc, FollowerBoss,
		"the interest predicate's step 4 reads it; no follower subsystem writes it yet"),
	ELYSIUM_NPC_WORD(0x6480, FElysiumNpc, FollowerType),
	ELYSIUM_NPC_WORD_NOTED(0x6484, FElysiumNpc, FollowerDistanceBackAway,
		"resolved from the rulebook's follower row"),
	ELYSIUM_NPC_WORD(0x6488, FElysiumNpc, FollowerDistanceWalkTo),
	ELYSIUM_NPC_WORD(0x648c, FElysiumNpc, FollowerDistanceRunTo),
	ELYSIUM_NPC_WORD(0x6490, FElysiumNpc, BurstFireCount),
	ELYSIUM_NPC_WORD(0x6494, FElysiumNpc, bReturnToInitialPos),
	ELYSIUM_NPC_WORD(0x6495, FElysiumNpcDialogue, bForceDialogStart),
	ELYSIUM_NPC_WORD(0x6496, FElysiumNpc, bIsBossMonster),
	ELYSIUM_NPC_WORD(0x6497, FElysiumNpc, bInBossRegistry),
	ELYSIUM_NPC_WORD_NOTED(0x6498, FElysiumNpc, bJumping,
		"the cadence tail's hard-deadline clamp already names this word"),
	ELYSIUM_NPC_WORD(0x649c, FElysiumNpc, JumpOrigin),
	ELYSIUM_NPC_WORD(0x64a8, FElysiumNpc, JumpTarget),
	ELYSIUM_NPC_WORD(0x64b4, FElysiumNpc, JumpHeight),
	ELYSIUM_NPC_WORD(0x64b8, FElysiumNpc, JumpGravity),
	ELYSIUM_NPC_WORD(0x64bc, FElysiumNpc, TimesTalked),
	ELYSIUM_NPC_WORD_NOTED(0x64c0, FElysiumNpc, TalkingUntil,
		"the flag and its end time are one stamp in this port"),
	ELYSIUM_NPC_WORD(0x64c4, FElysiumNpc, DefaultCamera),
	ELYSIUM_NPC_WORD_NOTED(0x64c8, FElysiumNpc, Stance, "the stance index, retail's m_CurrStance"),
	ELYSIUM_NPC_WORD_NOTED(0x64cc, FElysiumNpc, TalkingUntil,
		"the same stamp m_bIsTalking maps to"),
	ELYSIUM_NPC_WORD_NOTED(0x64d0, FElysiumNpc, NoDeformExpression,
		"the port names expressions rather than indexing the disposition table"),
	ELYSIUM_NPC_WORD_CHAIN(0x64d4, "FElysiumAnimating::Disposition",
		"the port keys the row by name and level, not by a table row index"),
	ELYSIUM_NPC_WORD_NOTED(0x64d8, FElysiumNpc, StanceTuning,
		"the disposition row's blink floor, on the resolved tuning"),
	ELYSIUM_NPC_WORD_NOTED(0x64dc, FElysiumNpc, StanceTuning, "its blink ceiling"),
	ELYSIUM_NPC_WORD_NOTED(0x64e0, FElysiumNpc, Stance, "the fidget latch"),
	ELYSIUM_NPC_WORD_NOTED(0x64e1, FElysiumNpc, Stance, "the transition latch"),
	ELYSIUM_NPC_WORD_NOTED(0x64e4, FElysiumNpc, Stance, "the stance change stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x64e8, FElysiumNpc, StanceResolvedFor,
		"the (model, disposition) key the stance table was resolved for"),
	ELYSIUM_NPC_WORD_NOTED(0x64ec, FElysiumNpcDialogue, DialogQue,
		"char[96] used as a queued line name"),
	ELYSIUM_NPC_WORD(0x654c, FElysiumNpcDialogue, bDialogQueIsFinal),
	ELYSIUM_NPC_WORD(0x6550, FElysiumNpcDialogue, SpeechVolume),
	ELYSIUM_NPC_WORD_NOTED(0x6554, FElysiumNpcDialogue, DialogScene,
		"the speech scene this NPC is bound to"),
	ELYSIUM_NPC_WORD_CHAIN(0x6558, "FElysiumAnimating::Disposition",
		"the authored default_disposition key seeds the chain's live disposition"),
	ELYSIUM_NPC_WORD(0x655c, FElysiumNpc, TargetLeadMin),
	ELYSIUM_NPC_WORD(0x6560, FElysiumNpc, TargetLeadMax),
	ELYSIUM_NPC_WORD(0x6564, FElysiumNpc, TargetLeadCurrentWeight),
	ELYSIUM_NPC_WORD(0x6568, FElysiumNpc, TargetLeadPredictedWeight),
	ELYSIUM_NPC_WORD(0x656c, FElysiumNpc, TargetLeadWeightScale),
	ELYSIUM_NPC_WORD_CHAIN(0x6570, "FElysiumBlinkSchedule::Timer",
		"the eye pass carries retail's blink countdown per body"),
	ELYSIUM_NPC_WORD_NOTED(0x6574, FElysiumNpc, LoudExpressionTime,
		"FIELD_TIME; the loud-line expression cooldown"),
	ELYSIUM_NPC_WORD_CHAIN(0x6578, "FElysiumCombatCharacter::FidgetStep",
		"m_nEyeFidgetStep, on the entity chain"),
	ELYSIUM_NPC_WORD_CHAIN(0x657c, "FElysiumCombatCharacter::NextFidgetTime",
		"the between-sequence arm of the fidget clock"),
	ELYSIUM_NPC_WORD_CHAIN(0x6580, "FElysiumCombatCharacter::NextFidgetTime",
		"the per-cell arm of the same clock"),
	ELYSIUM_NPC_WORD_CHAIN(0x6584, "FElysiumEyeTargetTuning::MinInterval",
		"the disposition row's fidget floor, on the resolved tuning"),
	ELYSIUM_NPC_WORD_CHAIN(0x6588, "FElysiumEyeTargetTuning::MaxInterval", "its fidget ceiling"),
	ELYSIUM_NPC_WORD_PRIVATE(0x658c, "FElysiumNpc::PatrolPoints",
		"the named route resolved to its points; no patrol-path object exists here"),
	ELYSIUM_NPC_WORD_NOTED(0x6594, FElysiumNpc, HuntPatrolPoints,
		"the hunt sibling of the patrol route, in the same resolved-points form"),
	ELYSIUM_NPC_WORD_NOTED(0x659c, FElysiumNpcScheduleHost, Unknown659c,
		"the placeholder already reserved for +0x659c, cleared by both teardown virtuals"),
	ELYSIUM_NPC_WORD(0x65a0, FElysiumNpcScheduleHost, bPatrolPathUseHint),
	ELYSIUM_NPC_WORD_NOTED(0x65a4, FElysiumNpc, NextDodgeTime, "FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x65a8, FElysiumNpc, QueuedBurnDamage,
		"CTakeDamageInfo maps to this port's damage packet"),
	ELYSIUM_NPC_WORD_NOTED(0x65bc, FElysiumNpc, NextBurnTime, "FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD(0x65c0, FElysiumNpcMemory, DetectedAttackAttacker),
	ELYSIUM_NPC_WORD_NOTED(0x65c4, FElysiumNpcMemory, DetectedAttackTime,
		"the port stamps the notice and derives the five-second expiry from it"),
	ELYSIUM_NPC_WORD_NOTED(0x65c8, FElysiumNpcScheduleHost, ForcedSchedule,
		"a registered schedule id, as every other schedule word here is"),
	ELYSIUM_NPC_WORD_NOTED(0x65cc, FElysiumNpc, ScriptedScheduleOrder,
		"the forced state travels with the pushed order"),
	ELYSIUM_NPC_WORD_NOTED(0x65d0, FElysiumNpcScheduleHost, SavedSleepExtents,
		"the saved attack-partition margin SetAttackExtents restores from"),
	ELYSIUM_NPC_WORD_NOTED(0x65dc, FElysiumNpc, TeleportMoveTimer,
		"kept float as declared, though it is read as an absolute curtime"),
	ELYSIUM_NPC_WORD_NOTED(0x65e0, FElysiumNpc, CombatStartActivity,
		"the authored combat-start activity key"),
	ELYSIUM_NPC_WORD_NOTED(0x65e4, FElysiumNpc, CombatStartActivityId, "the resolved activity id"),
	ELYSIUM_NPC_WORD_NOTED(0x65e8, FElysiumNpc, AttackCoordinator,
		"the index of the three global coordinators; this runtime has no coordinator object to "
			"point at"),
	ELYSIUM_NPC_WORD(0x65ec, FElysiumNpc, AttackCoordinatorName),
	ELYSIUM_NPC_WORD(0x65f0, FElysiumNpc, FakeReloadCount),
	ELYSIUM_NPC_WORD(0x65f4, FElysiumNpc, bCameFromSpawner),
	ELYSIUM_NPC_WORD(0x65f5, FElysiumNpc, bIgnoreDetectedAttack),
	ELYSIUM_NPC_WORD(0x65f6, FElysiumNpc, bNoAlertState),
	ELYSIUM_NPC_WORD(0x65f7, FElysiumNpc, bNavIgnorePhysicsProps),
	ELYSIUM_NPC_WORD_NOTED(0x65f8, FElysiumNpcWitness, bAllowCriminalSuspicion,
		"the criminal lane's own admission gate"),
	ELYSIUM_NPC_WORD(0x65f9, FElysiumNpc, bAllowTurningAnims),
	ELYSIUM_NPC_WORD(0x65fa, FElysiumNpc, bForceMaintainActivity),
	ELYSIUM_NPC_WORD_NOTED(0x65fc, FElysiumNpc, StandingOnHeadTimer,
		"FIELD_FLOAT in retail's datamap, so a duration rather than a stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x6600, FElysiumNpc, WeaponThroughWallTime,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD(0x6604, FElysiumNpcMemory, StealthVisionOverrideUntil),
	ELYSIUM_NPC_WORD_NOTED(0x6608, FElysiumNpc, CorpseConditionTime,
		"FIELD_TIME; an absolute stamp"),
	ELYSIUM_NPC_WORD_NOTED(0x660c, FElysiumNpcMemory, LastDamageAttacker,
		"the retail packet is kept as the LastDamage attacker/time/amount triple"),
	ELYSIUM_NPC_WORD_NOTED(0x6658, FElysiumNpc, bUnread6658,
		"unsettled in 29b-0: a constructor-zeroed byte with no reader; declared so the census "
			"stays whole"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x6659,
		"retail's empty CScheduleLoader exists only to run LoadSchedules from the constructor; "
			"this port registers its programs in a static table"),
	ELYSIUM_NPC_WORD_IMPLICIT(0x665a,
		"alignment tail; the C++ compiler lays out the port's own members"),
	};
}

TArrayView<const FElysiumNpcWordBinding> ElysiumNpcKernelShapeMap::Bindings()
{
	return MakeArrayView(GBindings);
}
