// Generated by `uv run elysium research gen_kernel_tunables`. Do not hand-edit.
//
// The NPC kernel's tunables: every retail number a kernel body reads, from
// `research/tooling/ghidra/driver/kernel_tunables.tsv` (spec 0019 story 4). Each row was read out
// of the pinned `Vampire/dlls/vampire.dll` (image base `0x10000000`) at the width its type states,
// and `--check` reads it again. A body reads the NAME; the address and its evidence are here, once.
//
// 51 cells and immediates, 48 ConVars; image sha256 `c546f4de2003624d…`.

#include "Substrate/ElysiumNpcKernelTunables.h"

namespace ElysiumNpcTunables
{
namespace
{
	constexpr FConVarRow GConVarRows[] =
	{
		{ TEXT("manbat_delta"), 0x1093b7c8u, TEXT("600.0"), 600.0f, 600 },
		{ TEXT("debug_allow_fake_reload"), 0x10923d38u, TEXT("1"), 1.0f, 1 },
		{ TEXT("debug_melee_advance_combatmove_dist"), 0x10924a18u, TEXT("100"), 100.0f, 100 },
		{ TEXT("debug_allow_dodge"), 0x109248f0u, TEXT("0"), 0.0f, 0 },
		{ TEXT("werewolf_draw_hints"), 0x1093f958u, TEXT("0"), 0.0f, 0 },
		{ TEXT("werewolf_show_debug"), 0x1093f738u, TEXT("0"), 0.0f, 0 },
		{ TEXT("sk_basenpctroika_health"), 0x10923f10u, TEXT("10"), 10.0f, 10 },
		{ TEXT("andrei_force_awaken"), 0x1093c348u, TEXT("0"), 0.0f, 0 },
		{ TEXT("debug_viewcone_back_dist"), 0x10937a88u, TEXT("40"), 40.0f, 40 },
		{ TEXT("werewolf_pursuit_unseen_time"), 0x1093f8e8u, TEXT("3.0"), 3.0f, 3 },
		{ TEXT("werewolf_pursuit_distance"), 0x1093d570u, TEXT("800"), 800.0f, 800 },
		{ TEXT("debug_view_cone_2d3d"), 0x10936f70u, TEXT("3"), 3.0f, 3 },
		{ TEXT("tzimisce_voice_pitch"), 0x1093cf90u, TEXT("100"), 100.0f, 100 },
		{ TEXT("tzimisce_voice_attn"), 0x1093cfd8u, TEXT("65"), 65.0f, 65 },
		{ TEXT("tzimisce_voice_volume"), 0x1093ceb8u, TEXT("1"), 1.0f, 1 },
		{ TEXT("debug_allow_move_facing"), 0x10924f70u, TEXT("1"), 1.0f, 1 },
		{ TEXT("debug_turning"), 0x109247e8u, TEXT("0"), 0.0f, 0 },
		{ TEXT("sabbat_gunman_speed_threshold"), 0x1093c100u, TEXT("0.1"), 0.1f, 0 },
		{ TEXT("sabbat_gunman_speed_trails"), 0x1093c148u, TEXT("3"), 3.0f, 3 },
		{ TEXT("sabbat_gunman_speed_scalar"), 0x1093c1f0u, TEXT("3.0"), 3.0f, 3 },
		{ TEXT("werewolf_fastbreak_chance"), 0x1093f858u, TEXT("40"), 40.0f, 40 },
		{ TEXT("debug_turn_scalar"), 0x10924c90u, TEXT(".15"), 0.15f, 0 },
		{ TEXT("debug_dog_turn_scalar"), 0x1093ad20u, TEXT(".15"), 0.15f, 0 },
		{ TEXT("tzimisce_turn_scalar"), 0x1093c9f8u, TEXT(".15"), 0.15f, 0 },
		{ TEXT("debug_turning_speed"), 0x10923e80u, TEXT("90"), 90.0f, 90 },
		{ TEXT("werewolf_disregard_player_vision"), 0x1093d690u, TEXT("0"), 0.0f, 0 },
		{ TEXT("werewolf_translated_enemy_position_tolerance"), 0x1093d528u, TEXT("0"), 0.0f, 0 },
		{ TEXT("werewolf_teleport_out_time"), 0x1093d410u, TEXT("4.0"), 4.0f, 4 },
		{ TEXT("tzimisce_claw_left_x"), 0x1093cc38u, TEXT("0"), 0.0f, 0 },
		{ TEXT("tzimisce_claw_left_y"), 0x1093cbf0u, TEXT("25"), 25.0f, 25 },
		{ TEXT("tzimisce_claw_left_z"), 0x1093cba8u, TEXT("40"), 40.0f, 40 },
		{ TEXT("ming_xiao_pickup"), 0x1093ba88u, TEXT("1"), 1.0f, 1 },
		{ TEXT("debug_tentacle_mask"), 0x1093bb10u, TEXT("-1"), -1.0f, -1 },
		{ TEXT("dialog_facial_debug"), 0x109241f8u, TEXT("0"), 0.0f, 0 },
		{ TEXT("tzimisce_throw_power"), 0x1093ca88u, TEXT(".007"), 0.007f, 0 },
		{ TEXT("tzimisce_throw_hds"), 0x1093ca40u, TEXT(".0008"), 0.0008f, 0 },
		{ TEXT("debug_force_anim"), 0x10924d68u, TEXT("0"), 0.0f, 0 },
		{ TEXT("debug_alert_aggressive"), 0x10923f58u, TEXT("0"), 0.0f, 0 },
		{ TEXT("debug_hunting_aggressive"), 0x10924030u, TEXT("1"), 1.0f, 1 },
		{ TEXT("npc_hit_buildup_amount"), 0x109245e0u, TEXT("2"), 2.0f, 2 },
		{ TEXT("flex_minplayertime"), 0x1090fc08u, TEXT("5"), 5.0f, 5 },
		{ TEXT("flex_maxplayertime"), 0x1090fc98u, TEXT("7"), 7.0f, 7 },
		{ TEXT("ent_trace_doors"), 0x10924298u, TEXT("0"), 0.0f, 0 },
		{ TEXT("debug_vision_line"), 0x10924798u, TEXT("0"), 0.0f, 0 },
		{ TEXT("debug_weapon_shoot_pos"), 0x109244c0u, TEXT("0"), 0.0f, 0 },
		{ TEXT("debug_show_npc_skeletons"), 0x10924358u, TEXT("0"), 0.0f, 0 },
		{ TEXT("debug_show_body_targets"), 0x10924f20u, TEXT("0"), 0.0f, 0 },
		{ TEXT("ent_trace_conditions"), 0x10924a68u, TEXT("1"), 1.0f, 1 },
	};
	static_assert(UE_ARRAY_COUNT(GConVarRows) == static_cast<int32>(EConVar::Count),
		"one row per EConVar enumerator");

	// The live values. Game-thread only, like the rest of the substrate; a slot that was never
	// set answers the row's default.
	struct FConVarLive
	{
		float Float = 0.f;
		int32 Int = 0;
		bool bSet = false;
	};
	FConVarLive GConVarLive[static_cast<int32>(EConVar::Count)];
}

const FConVarRow& ConVarRow(EConVar ConVar)
{
	check(ConVar < EConVar::Count);
	return GConVarRows[static_cast<int32>(ConVar)];
}

float ConVarFloat(EConVar ConVar)
{
	const FConVarLive& Live = GConVarLive[static_cast<int32>(ConVar)];
	return Live.bSet ? Live.Float : ConVarRow(ConVar).Float;
}

int32 ConVarInt(EConVar ConVar)
{
	const FConVarLive& Live = GConVarLive[static_cast<int32>(ConVar)];
	return Live.bSet ? Live.Int : ConVarRow(ConVar).Int;
}

void SetConVar(EConVar ConVar, float Value)
{
	// `ConVar::SetValue(float)`: `m_fValue = value; m_nValue = (int)value`.
	check(ConVar < EConVar::Count);
	GConVarLive[static_cast<int32>(ConVar)] = { Value, static_cast<int32>(Value), true };
}

void ResetConVars()
{
	for (FConVarLive& Live : GConVarLive)
	{
		Live = FConVarLive();
	}
}
}
