"""The shader-program seam: VtMB's readable ps.1.x assembly and its compiled combo bundles.

Two unit kinds share one package because they share one corpus. `vtmb:shader-source:<stem>` is
one `materials/dxshaders/<stem>.psh` parsed into its version line, `def` declarations,
instructions and comments; `vtmb:shader-program:<subdir>/<stem>` is one
`shaders/{psh,vsh,fxc}/<stem>.vcs` header, combo table and Direct3D token streams, disassembled
into instruction tables that reassemble byte for byte. Both are scene-less and carry no BIN chunk.
"""

from elysium_pipeline.formats.shader_program_glb.coverage import (
    build_ledger,
    shader_program_coverage,
    shader_source_coverage,
)
from elysium_pipeline.formats.shader_program_glb.decode import (
    HEADER_BYTES,
    ShaderProgramDecodeError,
    ShaderSourceDecodeError,
    decode_shader_program,
    decode_shader_source,
    shader_program_coverage_for,
    shader_source_coverage_for,
    source_resolution_for,
)
from elysium_pipeline.formats.shader_program_glb.model import (
    PROGRAM_DIR,
    PROGRAM_GENERATOR_TITLE,
    PROGRAM_SUBDIRS,
    PROGRAM_SUFFIX,
    SCHEMA_VERSION,
    SHADER_PROGRAM_ASSET_PREFIX,
    SHADER_PROGRAM_EXTENSION,
    SHADER_PROGRAM_KIND,
    SHADER_SOURCE_ASSET_PREFIX,
    SHADER_SOURCE_EXTENSION,
    SHADER_SOURCE_KIND,
    SOURCE_DIR,
    SOURCE_FAMILY_DIR,
    SOURCE_GENERATOR_TITLE,
    SOURCE_SUFFIX,
    ShaderKeyError,
    ShaderProgramModel,
    ShaderSourceModel,
    normalize_program_key,
    normalize_source_key,
    program_asset_id,
    program_member_path,
    program_output_relative_path,
    source_asset_id,
    source_member_path,
    source_output_relative_path,
)
from elysium_pipeline.formats.shader_program_glb.source import (
    ShaderProgramClosure,
    ShaderSourceClosure,
    ShaderSourceError,
    load_shader_source_closure,
    load_source_closure,
    program_keys,
    shader_source_keys,
)

__all__ = [
    "HEADER_BYTES",
    "PROGRAM_DIR",
    "PROGRAM_GENERATOR_TITLE",
    "PROGRAM_SUBDIRS",
    "PROGRAM_SUFFIX",
    "SCHEMA_VERSION",
    "SHADER_PROGRAM_ASSET_PREFIX",
    "SHADER_PROGRAM_EXTENSION",
    "SHADER_PROGRAM_KIND",
    "SHADER_SOURCE_ASSET_PREFIX",
    "SHADER_SOURCE_EXTENSION",
    "SHADER_SOURCE_KIND",
    "SOURCE_DIR",
    "SOURCE_FAMILY_DIR",
    "SOURCE_GENERATOR_TITLE",
    "SOURCE_SUFFIX",
    "ShaderKeyError",
    "ShaderProgramClosure",
    "ShaderProgramDecodeError",
    "ShaderProgramModel",
    "ShaderSourceClosure",
    "ShaderSourceDecodeError",
    "ShaderSourceError",
    "ShaderSourceModel",
    "build_ledger",
    "decode_shader_program",
    "decode_shader_source",
    "load_shader_source_closure",
    "load_source_closure",
    "normalize_program_key",
    "normalize_source_key",
    "program_asset_id",
    "program_keys",
    "program_member_path",
    "program_output_relative_path",
    "shader_program_coverage",
    "shader_program_coverage_for",
    "shader_source_coverage",
    "shader_source_coverage_for",
    "shader_source_keys",
    "source_asset_id",
    "source_member_path",
    "source_output_relative_path",
    "source_resolution_for",
]
