"""Isolated lossless Script GLB format aggregation."""

from elysium_pipeline.formats.script_glb.decode import (
    ENTITY_LOOKUPS,
    SOUND_CALLS,
    ScriptDecodeError,
    classify_literal,
    collect_entity_names,
    collect_references,
    decode_script,
    derive_structure,
    describe_source,
    indent_anomaly,
    statement_start_lines,
    verify_token_partition,
)
from elysium_pipeline.formats.script_glb.model import (
    ANOMALY_ROLES,
    COMPILED_EXTENSION,
    DEPENDENCY_ROLES,
    KIND,
    KIND_TITLE,
    SCHEMA_VERSION,
    SCRIPT_EXTENSION,
    SCRIPT_ROOT,
    SOURCE_EXTENSION,
    SOURCE_KINDS,
    ScriptIdentityError,
    ScriptModel,
    asset_id,
    compiled_path,
    normalize_script_key,
    output_relative_path,
    source_path,
)
from elysium_pipeline.formats.script_glb.opcodes import (
    HAVE_ARGUMENT,
    OPNAME,
    PYTHON_21_MAGIC,
    PYTHON_21_MAGIC_BYTES,
)
from elysium_pipeline.formats.script_glb.pyc import PycDecodeError, decode_pyc, walk_codes
from elysium_pipeline.formats.script_glb.source import (
    EXTRA_DIRS,
    ScriptSourceClosure,
    ScriptSourceError,
    load_source_closure,
    script_dirs,
    source_keys,
)

__all__ = [
    "ANOMALY_ROLES",
    "COMPILED_EXTENSION",
    "DEPENDENCY_ROLES",
    "ENTITY_LOOKUPS",
    "EXTRA_DIRS",
    "HAVE_ARGUMENT",
    "KIND",
    "KIND_TITLE",
    "OPNAME",
    "PYTHON_21_MAGIC",
    "PYTHON_21_MAGIC_BYTES",
    "SCHEMA_VERSION",
    "SCRIPT_EXTENSION",
    "SCRIPT_ROOT",
    "SOUND_CALLS",
    "SOURCE_EXTENSION",
    "SOURCE_KINDS",
    "PycDecodeError",
    "ScriptDecodeError",
    "ScriptIdentityError",
    "ScriptModel",
    "ScriptSourceClosure",
    "ScriptSourceError",
    "asset_id",
    "classify_literal",
    "collect_entity_names",
    "collect_references",
    "compiled_path",
    "decode_pyc",
    "decode_script",
    "derive_structure",
    "describe_source",
    "indent_anomaly",
    "load_source_closure",
    "normalize_script_key",
    "output_relative_path",
    "script_dirs",
    "source_keys",
    "source_path",
    "statement_start_lines",
    "verify_token_partition",
    "walk_codes",
]
