"""Isolated lossless Sound GLB format aggregation."""

from elysium_pipeline.formats.sound_glb.coverage import (
    MAPPED_KEYS,
    build as build_coverage,
    mapped_keys,
)
from elysium_pipeline.formats.sound_glb.decode import SoundDecodeError, decode_sound
from elysium_pipeline.formats.sound_glb.model import (
    ANOMALY_ROLES,
    AUDIO_EXTENSIONS,
    CONTAINERS,
    DECODED_CHUNKS,
    DEPENDENCY_ROLES,
    KIND,
    MEMBER_ROLES,
    OMISSION_ROLES,
    SAMPLE_FORMATS,
    SCHEMA_VERSION,
    SOUND_EXTENSION,
    SOUND_ROOT,
    UNIDENTIFIED_CHUNKS,
    LipDocument,
    LipPhoneme,
    LipPhrase,
    LipWord,
    MpegFrame,
    RiffChunk,
    SoundKeyError,
    SoundModel,
    asset_id,
    companion_path,
    counterpart_key,
    key_extension,
    key_stem,
    normalize_key,
    output_relative_path,
    source_path,
)
from elysium_pipeline.formats.sound_glb.source import (
    SoundSourceClosure,
    SoundSourceError,
    load_source_closure,
    source_keys,
)

__all__ = [
    "ANOMALY_ROLES",
    "AUDIO_EXTENSIONS",
    "CONTAINERS",
    "DECODED_CHUNKS",
    "DEPENDENCY_ROLES",
    "KIND",
    "MAPPED_KEYS",
    "MEMBER_ROLES",
    "OMISSION_ROLES",
    "SAMPLE_FORMATS",
    "SCHEMA_VERSION",
    "SOUND_EXTENSION",
    "SOUND_ROOT",
    "UNIDENTIFIED_CHUNKS",
    "LipDocument",
    "LipPhoneme",
    "LipPhrase",
    "LipWord",
    "MpegFrame",
    "RiffChunk",
    "SoundDecodeError",
    "SoundKeyError",
    "SoundModel",
    "SoundSourceClosure",
    "SoundSourceError",
    "asset_id",
    "build_coverage",
    "companion_path",
    "counterpart_key",
    "decode_sound",
    "key_extension",
    "key_stem",
    "load_source_closure",
    "mapped_keys",
    "normalize_key",
    "output_relative_path",
    "source_keys",
    "source_path",
]
